### ISSUE TITLE
EPSON TM-T81 printer won't print from live server.

### ISSUE THREAD

**Issue by rajjagani** [mike42/escpos-php#100]
I have connected EPSON TM-T81 thermal printer to router through Ethernet cable and given a one ip address i.e. 192.168.1.12.

Now I have a live website and I am using this library to make a print call using below code. 

```
$connector = new NetworkPrintConnector($ip, $port); // here $ip is printer ip and port is 9100
$printer = new Escpos($connector);

```

but from live website it won't make call but if I do this from my localhost than printing is working. Is there something I missing for configuration to print it from server. Do i need to install driver for this in PC or any configuration.

**Note : Remember I am making call from window OS and all device are connected to same network. Even when I do from my android app printing than it working fine.**

below is the error message.

```
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
```
Please help me out as soon as possible.

**Comment by rajjagani** [comment]
I have more debug on that to find the value of connector object but when i testing on my live server it show me the below error

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```
but when I test it from local server it shows me below error.
```
Type: Exception

Message: Cannot initialise NetworkPrintConnector: A connection attempt failed because the connected party did not properly respond after a period of time or established connection failed because connected host has failed to respond.
```
In a case when printer is not connected the above exception is right but when i test in on live server it will throw me a internal server error. looks like it will never go to the file code.

please help me out.

**Comment by mike42** [comment]
No local driver install is needed for Ethernet printers, PHP just needs to be able to talk to your printer on port 9100 (ie, firewall, permissions, correct network setup). It's seems from what you've posted that the connection simply isn't going through.

Some questions to get you looking at the details of why this may be:

- What OS, PHP version and webserver are you on?
- Can you ping your printer and connect on port 9100 from the command-line on this server? (eg, telnet, powershell)
- Can you print from the command line on this server? Eg. C:\php\php.exe hello-world.php (where hello-world.php uses a NetworkPrintConnector and tries to print)
- What user is the webserver running as?
- Do you have a firewall preventing connections out from the webserver process? (Eg. Turn off firewall, see if error changes, maybe you need a rule)

**Comment by rajjagani** [comment]
I have tried everything but nothing working I am not good at networking part but some of my server details are below If you can help me out on amazon server.

1. I have setup website on amazon server. which us working on Linux OS.

**Comment by mike42** [comment]
Hey, assumed earlier that your live server was on the same network and running Windows as well, but if your server is on Amazon, then it would seem that you are printing from the public Internet on Linux OS.

This is what I'm hearing-

![image](https://cloud.githubusercontent.com/assets/2080552/14037259/b4a4f42e-f295-11e5-9ee0-5b782f1be818.png)

--
Updated tips-

- Use the standard solutions to allow your server to see the printer securely over the Internet (VPN or SSH tunnel in to a box on your networ; a Raspberry Pi has enough power if you just need to drop in a device to host OpenVPN internally).
 - Disclaimer: This is not a networking forum! You will need to source your own information on setting up these applications. Once you have a working command to connect to the printer over the network, please post it here along with the extra info requested in the last question for any extra driver help.
- Your setup is working when you can send text to the printer from the webserver with something like `nc`:

````
$ echo "Hi Hi hi!!" | nc 192.x.x.x 9100
````

**Comment by rajjagani** [comment]
yes you are getting correct. The diagram you show me exactly same way I am trying for priting directly form net through local computer. well I will follow your tips don't know much about Raspberry Pi but if you have any solutions using any library change than please give me. If I will get any thing I'll update you.

can we install Epson-TM-T81 driver to Linux server ?

Thanks

**Comment by mike42** [comment]
Closing this off as there's no more `escpos-php` questions in the thread.

**Comment by mutiemule** [comment]
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
