### ISSUE TITLE
Printing from web-based app

### ISSUE THREAD

**Issue by c-myers1** [mike42/escpos-php#1000]
It's not clear to me how to send to a usb printer when the php app runs from a hosting server. The server is Linux, the browser is running on windows and the receipt printer is connected to the local windows machine via usb.

Would the WindowsPrintConnector still work? Automatically or is there any further config to do? I am assuming escpos-php can do this based on "... including web-based point-of-sale (POS) applications."

**Comment by c-myers1** [comment]
Ok I see there are existing discussions on this. I change the question to this: in what way can esc-pos be used with web-based pos applications?

**Comment by freemartian** [comment]
Hi, How did you manage to work it out, I am still struggling. 
When I try to connect to my web app from a Linux server, it says the port is not available. 
When I run ls -l /dev/tty* I am getting this list. 

![image](https://user-images.githubusercontent.com/54478679/149649464-eec123fc-2d8a-4a5a-b105-d51fb2422e30.png)

When I try to run stty -F /dev/ttyS0 its showing the  result

![image](https://user-images.githubusercontent.com/54478679/149649495-4a380d97-ca60-4b94-bdeb-a05155e44fee.png)

but when I run stty -F /dev/ttyUSB0 I am getting 
![image](https://user-images.githubusercontent.com/54478679/149649526-d6cc21bb-22b9-4275-83a5-adcf88ef5353.png)

Does anyone knows how to solve this, I am trying this for the last 5 days.

**Comment by c-myers1** [comment]
Is your case also to print from USB? I read somewhere escpos doesn't directly address this, I cannot recall where. Ended up using this:https://www.neodynamic.com/products/printing/js-print-manager/download/  there's a free executable that allows printing LAN/USB.
