### ISSUE TITLE
Class 'IntBreakIterator' not found 

### ISSUE THREAD

**Issue by JacksonSamuel42** [mike42/escpos-php#1044]
Class 'IntBreakIterator' not found  not found MIke42/Escpos/CodePage.php line118

**Comment by MasterStomp** [comment]
in php.ini enabled intl

![image](https://user-images.githubusercontent.com/41119244/110741437-39ece180-8267-11eb-825c-334b9b04fa5a.png)

remove semicolon

**Comment by JacksonSamuel42** [comment]
thanks it working
