### ISSUE TITLE
EPSON TM U220 How to print thai language 

### ISSUE THREAD

**Issue by MasterStomp** [mike42/escpos-php#1045]
Hello @Mike42  

I tried to find the problem but was unsuccessful. (#51)
https://github.com/mike42/escpos-php/issues/701#issuecomment-468989275

while a "South Asia" variant of the Epson printers will correctly compose the Thai characters.

`<img src=""/>`
![S__1957892](https://user-images.githubusercontent.com/41119244/110735651-cba32180-825c-11eb-9f08-25f9ebe2471d.jpg)

**Comment by MasterStomp** [comment]
Maybe is TM-U220 is not support Codepage874

**Comment by shinnlu** [comment]
> Hello @mike42
> 
> I tried to find the problem but was unsuccessful. (#51) [#701 (comment)](https://github.com/mike42/escpos-php/issues/701#issuecomment-468989275)
> 
> while a "South Asia" variant of the Epson printers will correctly compose the Thai characters.
> 
> `<img src=""/>` ![S__1957892](https://user-images.githubusercontent.com/41119244/110735651-cba32180-825c-11eb-9f08-25f9ebe2471d.jpg)

how do you print image on TM U220, I tried a lot in issues, but not working.
