### ISSUE TITLE
Print conflicts and android!

### ISSUE THREAD

**Issue by lovetoast** [mike42/escpos-php#109]
Hi!

2 questions here!

1) Is there any way to print from android, to a USB printer connected to a windows device.
2) As this won't be using windows printing services, via the ethernet print I mean, are there are issues when 2 devices print at the same time? might it create conflicts?

**Comment by lovetoast** [comment]
Also, is there any way to print Chinese characters? And to print an image, do we need Mike's image converter?

**Comment by mike42** [comment]
Hi, there is a real mix of questions here.

Can you clarify whether your printer is Ethernet or USB, which machine is running PHP, and the which model/vendor printer you have?

For example, I have a Zijang ZJ-5890T, which is a USB printer. If I wanted to print from a web page (say Android), and had a Windows box which was running PHP, then the compatibility table in README.md suggests that I use a WindowsPrintConnector. This print connector uses system printing to get the blob of ESC/POS from server to printer.

That same printer supports bitImage() for graphics. Chinese text is not part of the ESC/POS protoccol, but in this case textChinese() will work.

**Comment by lovetoast** [comment]
Hi Mike,

Sorry, my original psot was not particularly clear!

Let me just rephrase:

1) Can I install a local server on an Android system, and use it to connect to a shared printer on a Windows device?

2) When I try to print via USB using Windows 8.1 (and the correct IP address as I have tested it using a simple fsock open script) using your script, I can't print, it says:

Couldn't print to this printer: Cannot initialise NetworkPrintConnector: Unable to find the socket transport "http" - did you forget to enable it when you configured PHP? 

Any idea?

Thanks very much in advance?

**Comment by lovetoast** [comment]
In fact, 2) is resolved, I was just being a bit dim, so:

3) If two devices try to print to the same ethernet printer at the same time, will it create conflicts?

**Comment by mike42** [comment]
Hi. Please take a moment just to identify your setup so that you can get better answers-

> Can you clarify whether your printer is Ethernet or USB, which machine is running PHP, and which model/vendor printer you have?

But very specifically-

1) Not tested.
3) Depends on the printer

**Comment by lovetoast** [comment]
Thanks Mike!

But have you encountered any issues, the reason I ask is if we directly open port 9100, we aren't using any Windows printer spooling services?

**Comment by mike42** [comment]
As above, this is going to depend on your printer.

Please take a moment to identify your setup if you have further queries.

**Comment by mike42** [comment]
Closing as there is no specific question about the driver here.
