### ISSUE TITLE
It is possible to print chinese character my epson TM 20II or any type of TM series?

### ISSUE THREAD

**Issue by zjj87** [mike42/escpos-php#110]
Hi i have tried with chinese.php code inside specific folder to print chinese character with my TM20II printer but it doesn't work. can you tell me if is possible to printi chinese characters with espon printer or do i have to change it???

**Comment by mike42** [comment]
I don't know of a TM-T20 variabt that supports Chinese text.

Are you on Windows or Linux, and have you been able to use image printing? Your options will be to change printers, or depending on the platform, use one of the slower i18n work-arounds, which will involve either rendering HTML, using an `ImagePrintBuffer`.
