### ISSUE TITLE
Unable to Strike a text

### ISSUE THREAD

**Issue by deep97** [mike42/escpos-php#112]
Hi, I was trying to use setDoubleStrike. To strike a text. But it is not working for me.
Any Idea

Regards

**Comment by deep97** [comment]
actually like <strike> function in html

**Comment by mike42** [comment]
`setDoubleStrike` instructs an impact printer to strike the paper twice, causing **stronger** text. It is not related to strikeout, which is is not an ESC/POS feature AFAIK.

Printing <s>strike-out</s> would require you to render text to an image on the PC, and send raster graphics to the printer.

**Comment by mike42** [comment]
Closing this as it is not known to be an ESC/POS feature, so is out of scope for the library.

As with #117, consider rendering text into an image (or via HTML) if this is a critical part of your use case.
