### ISSUE TITLE
Print PDF file

### ISSUE THREAD

**Issue by mekniamir** [mike42/escpos-php#115]
Call to undefined method Mike42\Escpos\EscposImage::loadPdf()

**Comment by mike42** [comment]
Hi,

That example was not up to date, please pull in the latest code from master, which has a fix for this.

Due to the way this feature is implemented, it is _very very_ slow. You will get much faster prints if you can pre-process your doc to say a 550px wide PNG first.

**Comment by haithem-rihane** [comment]
Hi,

I can't get waht you mean by **You will get much faster prints if you can pre-process your doc to say a 550px wide PNG first.**

**Comment by mike42** [comment]
Hi,

Maybe some code snippets will clarify. Printing a PDF file directly will work, but takes a very long time.

```php
escpos-php/example$ cat test1.php 
<?php
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\ImagickEscposImage;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$pdf = 'resources/document.pdf';
$connector = new FilePrintConnector("php://stdout");
$printer = new Printer($connector);
$pages = ImagickEscposImage::loadPdf($pdf);
foreach ($pages as $page) {
    $printer -> graphics($page);
}
$printer -> cut();
$printer -> close();
```

```
escpos-php/example$ time (php test1.php > /dev/null)

real	0m8.446s
user	0m8.508s
sys	0m0.044s
```

I think that this is too slow to handle, and suggest that you pre-process your PDF document by converting them into a series of PNG images first. This lets you ask `escpos-php` to print a PNG, which is much faster. Raster images need it to be about 550px wide (depends on your printer).

```php
escpos-php/example$ cat test2.php 
<?php
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$page1 = 'resources/document-0.png';
$page2 = 'resources/document-1.png';
$connector = new FilePrintConnector("php://stdout");
$printer = new Printer($connector);
$pages = array(EscposImage::load($page1), EscposImage::load($page2));
foreach ($pages as $page) {
    $printer -> graphics($page);
}
$printer -> cut();
$printer -> close();
```

```
$ time (convert -density 133 resources/document.pdf resources/document.png; php test2.php > /dev/null)

real	0m0.773s
user	0m0.656s
sys	0m0.216s
```

**Comment by albert47** [comment]
Hi,
I tried printing pdf to printer using the following codes, but it prints out gibberish.  My printer model is POS-8220.  I am able to print normal text, but not graphics.  I have installed Imagick on my system and it's working on command line to convert file.

Can anyone help?


public function printPdfFile($pdf) {
        $connector = new NetworkPrintConnector("192.168.1.222", 9100);
        $printer = new Printer($connector);

        try {
            $pages = ImagickEscposImage::loadPdf($pdf);
            // Log::info($pages);

            foreach ($pages as $page) {
                $printer -> graphics($page);
                // $printer -> graphics($page, Printer::IMG_DOUBLE_HEIGHT | Printer::IMG_DOUBLE_WIDTH);
            }
            $printer->feed(2);
            $printer -> cut();
        } catch (Exception $e) {
            echo $e -> getMessage() . "\n";
        } finally {
            $printer -> close();
        }
    }

**Comment by mike42** [comment]
@albert47 - One topic per issue please, I'll lock this thread, please file a new issue if the two alternatives to `graphics()` that are listed in the README also generate garbage.
