### ISSUE TITLE
Sending Custom Commands (Italic text on TM-T20)

### ISSUE THREAD

**Issue by haithem-rihane** [mike42/escpos-php#117]
Hi all,

I have a question, I hope that you can help me. I read in EPSON Manuel that i can send custom HEX commands. I'm trying to write **_italic_** text :

`$connector -> write("\x1b". "!" . chr(1));`
`$printer -> text("Hello World!\n");`

But i'm not getting the right result

Thank you for your time in responding.

**Comment by mike42** [comment]
This is the correct way to send custom binary directly to your printer. Of course, this bypasses the code which generates ESC/POS commands, so your mileage may vary.

The command you are sending is equivalent to:

```php
$printer -> selectPrintMode(Printer::MODE_FONT_B)
```

On my Epson TM-T20, this simply prints in a slightly smaller font.

Can you share the make, model, and a link to the vendor docs? I'm yet to see an ESC/POS printer that supports italics natively, so I'd like to check whether italics are a documented feature on the printer.

**Comment by haithem-rihane** [comment]
Thx Mike for the replay actually i'm having also TM-T20 Printer also and that's why the italic font dosent work. it work on différent Epson model. This [Link](http://www.piclist.com/techref/language/ESC/commands.htm) where i found the doc about the italic font

thx for the great job ur doing !!!

**Comment by mike42** [comment]
Ah, different protocol. Similar names and commands, but ESC/POS has different features to ESC/P or ESC/P2 protocols, which are not used on receipt printers. This puts it out of scope for this driver, so I'll close this issue off. 

Same as #112, if you really needed italic text, you would need to generate images of and then send the images to the printer.
- There is an example in the repo which uses `whhtmltoimage` to tranform HTML to PNG, then PNG to ESC/POS, which is a useful catch-all solution  for all kinds of advanced formatting (Linux only).
- If you can format your receipt using the available features instead (bold, underline, and font changes), the output is faster, more readable, cross platform, and you can even [parse the binary to recover the text](https://github.com/mike42/escpos-snippets/tree/master/parser) if needed.
