### ISSUE TITLE
problem  border

### ISSUE THREAD

**Issue by shahoit** [mike42/escpos-php#1171]
i have problem i want to show text in box like border for text how i can do this ss

**Comment by gogl92** [comment]
I've been trying to solve this problem too, if I found a way to do it I'll post the solution here.

**Comment by test-account-mr-blackhole** [comment]
<svg>### ### [
![sd](https://github.com/mike42/escpos-php/assets/82785681/b501ecab-3aad-43be-9e86-fc2fa6b00d08)
](url)

**Comment by shahoit** [comment]
[shopify-2023-11-15T12_19_22Z.json](https://github.com/mike42/escpos-php/files/13400973/shopify-2023-11-15T12_19_22Z.json)
