### ISSUE TITLE
Print multiple copies

### ISSUE THREAD

**Issue by haithem-rihane** [mike42/escpos-php#118]
Hi,

Is there any solution to send number of coipes to printer ?

I even tried  to put my code inside foreach loop but it only print 1 copy 

Thx in advance

**Comment by mike42** [comment]
There is currently no example for how to do this, see #101.

Can you share a minimal code snippet which demonstrates the issue you're seeing?

**Comment by mike42** [comment]
Closing, see #101 for request for an example of printing multiple copies.
