### ISSUE TITLE
Is it possible to print on a bluetooth thermal printer under android os?

### ISSUE THREAD

**Issue by frank012** [mike42/escpos-php#119]
I was wondering if it's possible and what kind of configuration need to be used for that purpose. I think that it should be like the serial one, but I don't know how it should be and where to get port information if needed
Thanks, Regards

**Comment by mike42** [comment]
Android/bluetooth has not been explored (see [compatibility table in README.md](https://github.com/mike42/escpos-php/blob/cfea4c4fc95516ac953e1e5b623f854632afa2ee/README.md#interfaces-and-operating-systems)).

In general, before you can use this driver in your PHP application, you are going to need to check that you are using PHP 5.3+, and that you have working command that can send text to your printer (from the machine that PHP is running on).

So please provide some more information-

- What PHP binaries are you running?
 - What happened when you executed the ['Hello world'](https://github.com/mike42/escpos-php#the-hello-world-receipt) receipt script on the command line?
- What make/model printer do you have?
 - Does the vendor have programmer documentation?
  - How is it the printer exposed to the programmer? (Serial printers pop up as a device file, for example)
 - Do you have a working command that will get the data from the 'Hello World' receipt to your printer?

**Comment by mike42** [comment]
Closing, not enough info to answer
