### ISSUE TITLE
Excelvan HOP-80 (connect through powered hub) works!

### ISSUE THREAD

**Issue by mattiamanzati** [mike42/escpos-php#120]
Just to let you all know :)

**Comment by haithem-rihane** [comment]
Can you explain **Excelvan HOP-80 (connect through powered hub)** ?

**Comment by mattiamanzati** [comment]
It's a esc/pos printer model, I bought one and tested all the features connecting via usb cable on Windows and works as a charm, so you could add this model to the homepage readme :)

**Comment by haithem-rihane** [comment]
Nice

**Comment by mike42** [comment]
Thank you!
