### ISSUE TITLE
Table-formatted text

### ISSUE THREAD

**Issue by skyvory** [mike42/escpos-php#123]
Is it possible to format the text as if it's printed on a table?
I'd like to print multiple column of text where each of them is right aligned.

For example, a line consist of "item name", "quantity", "price per item", and "total price" would all be printed right aligned in their own column except for "item name" which is left aligned.

FYI, I use Epson LX-310 on Windows.

**Comment by skyvory** [comment]
Never mind. I achieved the desired result by using sprintf() to arrange the spacing/padding of the text.

**Comment by haithem-rihane** [comment]
Can u share us ur code how u used sprintf() to arrange the spacing/padding of the text.

Thanks

**Comment by skyvory** [comment]
Sure do.
```
$connector = new FilePrintConnector("php://stdout");
$printer = new Printer($connector);
// loop
$line = sprintf('%-40.40s %5.0f %13.2f %13.2f', $item_name, $quantity, $price, $total);
$printer->text($line);
$printer->text("\n"); 
// end loop
$printer -> close();
```
Sorry that I couldn't explain it in detail because I haven't fully grasped how sprintf() works. 
Basically 40 characters for item name, 5 for quantity, and 13 with 2 decimal digits for price and total.
It was trial and error until I found the perfect fit of the spacing.

**Comment by haithem-rihane** [comment]
Nice , and thanks for sharing ;)

**Comment by Leonardus-dot** [comment]
I was trial and error , and i use and I use thermal paper with a size of 80 * 80 , and i try format number with my functions:
<?php
function rupiah($angka){
	
	$hasil_rupiah = number_format($angka,2,',','.');
	return $hasil_rupiah;
 
}

require __DIR__ . '/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
$connector = new WindowsPrintConnector("POS80");

$n1="".retnumformt($row['item_price']).",00";
$n2="".retnumformt($row['sub_total']).",00";

$line = sprintf('%-13.40s %3.0f %-3.40s %9.40s %-2.40s %13.40s','ITEM NAME'  , 3, 'x', $n1,'=', $n2);
$printer -> text("$line\n");

?>
Result images : 

![IMG_20190409_193520](https://user-images.githubusercontent.com/7751523/55849173-dd17b680-5b79-11e9-8b9a-99343552b589.jpg)

**Comment by Leonardus-dot** [comment]
looping the data  from databases:

$line = sprintf('%-13.40s %3.0f %-3.40s %9.40s %-2.40s %13.40s',$row['item_code']  , $row['item_qty'], $row['kali'], $n1,$row['hasil'], $n2);
$printer -> text("$line\n");

And transactions info : 

$lineTotal      = sprintf('%-5.40s  %-1.05s  %13.40s','Total Belanja.','=', $tot1);
$printer -> text("$lineTotal\n");
$lineTunai      = sprintf('%-5.40s  %-1.05s  %13.40s','Uang Tunai.','=', $tot2);
$printer -> text("$lineTunai\n");
$lineDisc       = sprintf('%-5.40s  %-1.05s  %13.40s','Disc.','=', $tot3);
$printer -> text("$lineDisc\n");
$lineKembalian  = sprintf('%-5.40s  %-1.05s  %13.40s','Kembalian.','=', $tot4);
$printer -> text("$lineKembalian\n");

**Comment by mountainclimbing** [comment]
@Leonardus-dot Please attach full code. Preferably even Sample .SQL database and full php code.

**Comment by Leonardus-dot** [comment]
Hey @mountainclimbing  , this is sample for php code : 
`<?php
require_once "header.php";  
require_once "menu.php"; 
/* Change to the correct path if you copy this example! */
require __DIR__ . '/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

/**
 * Install the printer using USB printing support, and the "Generic / Text Only" driver,
 * then share it (you can use a firewall so that it can only be seen locally).
 *
 * Use a WindowsPrintConnector with the share name to print.
 *
 * Troubleshooting: Fire up a command prompt, and ensure that (if your printer is shared as
 * "Receipt Printer), the following commands work:
 *
 *  echo "Hello World" > testfile
 *  copy testfile "\\%COMPUTERNAME%\Receipt Printer"
 *  del testfile
 */
try {
	
    // Enter the share name for your USB printer here
    //$connector = null;
    $connector = new WindowsPrintConnector("POS80");
	$receipt   = $_GET['nomorOrder']; 
  
    $printer = new Printer($connector);
	$printer -> setJustification(Printer::JUSTIFY_CENTER);
    $printer -> text("CV. LEONARDUS EMAN ROHAEMAN\n");
	$printer -> text("JLN. PASIR KIDUL NO. 28\n");
	$printer -> text("CIGUGUR - KUNINGAN , JAWA BARAT\n");
	$printer -> text("\n");
	$printer -> setJustification(Printer::JUSTIFY_LEFT); 

	$sqlOrder = "SELECT customer.customer_name FROM order_master INNER JOIN customer ON order_master.customer_id = customer.customer_id where order_master.order_number='$receipt'";
	$resultOrder = $con->query($sqlOrder);
	
	$rowOrder = $resultOrder->fetch_assoc();

	$printer -> text("No. Transaksi : $receipt\n");
	$printer -> text("Pelanggan     : $rowOrder[customer_name]\n");
	$printer -> text("Kasir         : $_SESSION[username]\n");
	$printer -> text("================================================\n");

	$printer -> setJustification(Printer::JUSTIFY_RIGHT);
	
	$sql = "SELECT o.item_code,o.item_qty,o.item_price,(o.item_qty*o.item_price) as tot,(select item_name from item_master where item_code=o.item_code) as itemname,'X' as kali,'=' as hasil from order_item o where o.order_number='$receipt'";
	$result = $con->query($sql);
	
	while($row = $result->fetch_assoc()) {
		$printer -> setJustification(Printer::JUSTIFY_LEFT); 
		$printer -> text("$row[itemname]\n");
		$printer -> setJustification(Printer::JUSTIFY_RIGHT); 
		$n1="".retnumformt($row['item_price']).",00";
		$n2="".retnumformt($row['tot']).",00";

		$line = sprintf('%-13.40s %3.0f %-3.40s %9.40s %-2.40s %13.40s',$row['item_code']  , $row['item_qty'], $row['kali'], $n1,$row['hasil'], $n2);
		$printer -> text("$line\n");
		
	}
	
	$sqlTotal = "SELECT * from order_master where order_number='$receipt'";
	$resultTotal = $con->query($sqlTotal);
	$rowTotal = $resultTotal->fetch_assoc();

	$tot1= "".retnumformt($rowTotal['order_tot']).",00";
	$tot2= "".retnumformt($rowTotal['order_pay']).",00";
	$tot3= "".retnumformt($rowTotal['order_discount']).",00";
	$tot4= "".retnumformt($rowTotal['order_cash_back']).",00";
	$tot5= "".retnumformt($rowTotal['order_remaining']).",00";

	$printer -> text("------------------------------------------------\n");

	$lineTotal      = sprintf('%-5.40s  %-1.05s  %13.40s','Total Belanja.','=', $tot1);
	$printer -> text("$lineTotal\n");
	$lineTunai      = sprintf('%-5.40s  %-1.05s  %13.40s','Uang Tunai.','=', $tot2);
	$printer -> text("$lineTunai\n");
	$lineDisc       = sprintf('%-5.40s  %-1.05s  %13.40s','Disc.','=', $tot3);
	$printer -> text("$lineDisc\n");
	$lineKembalian  = sprintf('%-5.40s  %-1.05s  %13.40s','Kembalian.','=', $tot4);
	$printer -> text("$lineKembalian\n");

	if ($rowTotal['order_remaining'] > 0){
		$lineHutang     = sprintf('%-5.40s  %-1.05s  %13.40s','Hutang.','=', $tot5);
		$printer -> text("$lineHutang\n");
	}
			
	$printer -> setJustification(Printer::JUSTIFY_CENTER);
	$printer -> text("------------------------------------------------\n");
	$printer -> text("CV. LEONARDUS EMAN ROHAEMAN\n");
	$printer -> text("*** Thank You ***\n");
	$printer->text(date("Y-m-d H:i:s") . "\n");
  
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();
	echo "<script>;document.location.href = 'http://localhost/salesapp/applications/nomor-order';</script>";
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
	
}
`

**Comment by mountainclimbing** [comment]
@Leonardus-dot Thanks!

**Comment by ahsanAsif26** [comment]
can i have the code please ??? just for design purpose.
Not the sql data.
Thanks

**Comment by ahsanAsif26** [comment]
@Leonardus-dot  @mountainclimbing  can i have the code please ??? just for design purpose.
Not the sql data.
Thanks

**Comment by Leonardus-dot** [comment]
> @Leonardus-dot @mountainclimbing can i have the code please ??? just for design purpose.
> Not the sql data.
> Thanks

ya, you can get the code , just pm me on gmail , leonardus25@gmail.com

**Comment by duvan177** [comment]
gracias amigo, esto es lo que necesitaba! toma tu like!

**Comment by rimbawansr** [comment]
@Leonardus-dot Please attach full code. Preferably even Sample .SQL database and full php code.
