### ISSUE TITLE
No imprime correctamente caracteres latinos (ñ, Ñ, á, é, í, ó, ú...)

### ISSUE THREAD

**Issue by InternetFacilito** [mike42/escpos-php#1238]
Estoy utilizando Laravel 9x con PHP 8x y una impresora térmica EPSON TM-T20II.
El problema se presenta cuando imprimo caracteres acentuados o por ejemplo la letra ñ.

He estado haciendo pruebas utilizando funciones y no he logrado resolver el problema. Anteriormente utilizaba sin problemas la función utf8_decode pero ahora no funciona pues me salta un error que dice que la cadena a decodificar debe ser utf8. El editor me muestra que es una función obsoleta pero no creo que ese sea el error. ¿Alguien podrá aclararlo?
He probado otras funciones incluso algunas propuestas por Mike pero no, sigue sin funcionar como se espera...

Después de probar y probas cosas raras me di cuenta de que cuando imprimo alguna palabra o caracter distinto al latino el texto en adelante imprime correctamente las ñ y acentos... por el momento así lo hago para poder imprimir acentos y ñ... En la primera línea imprimo un caracter del alfabeto Turkish y ya con eso lo que sigue lo imprime sin problemas. jajaja hay que ingeniárselas para solucionar XD.

Aquí mi principal pregunta es saber si alguien ha tenido el mismo problema y si encontró otra solución.

Imprimiendo caracteres extraños:
![IMG_20230126_123413](https://user-images.githubusercontent.com/123510787/214922044-ad48dd18-3268-49ac-97a8-0c62a7bfb86e.jpg)

Imprimiendo caracter turco en primera línea:
![IMG_20230126_123645](https://user-images.githubusercontent.com/123510787/214922217-6bcf8173-9765-444b-b47f-1b855b3beff5.jpg)

Código:
![imprimirTicket](https://user-images.githubusercontent.com/123510787/214922284-d411d121-4484-43fb-85b9-40c079046b8e.PNG)

**Comment by parallels999** [comment]
Cual seria el caracter turco?? la **i**?

OK si es la **i** sin punto
```
ıııııııııııııııı
```

**Comment by parallels999** [comment]
> El editor me muestra que es una función obsoleta pero no creo que ese sea el error.

https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated
