### ISSUE TITLE
Need help to make xprinter xp-360b work

### ISSUE THREAD

**Issue by candrairawan78** [mike42/escpos-php#127]
Dear mike, 

I see there is some chinese printer that work with escpos-php like:
Xprinter XP-Q800
Zijang NT-58H
Zijang ZJ-5870
Zijang ZJ-5890T (Marketed as POS 5890T)
Zijang ZJ-5890K

I have XPrinter xp-360B, i wish i can use it on my web application on linux.
My pc can detect this printer use usblp but i can not print use echo "test" >> /dev/usb/lp0

I have succeeded to test echo "test" >> /dev/usb/lp0 on my epson tmu-220

Could you help me to make this printer work?

Regards,
Candra

**Comment by mike42** [comment]
Are you sure this is an ESC/POS printer? (eg, [this person](http://stackoverflow.com/questions/36962056/how-to-use-tspl-language-in-php) is asking about [TSPL](http://www.tscprinters.com/cms/upload/download_en/TSPL_TSPL2_Programming.pdf))

`echo "test"` happens to output valid ESC/POS, but it may not be valid for any other page description languages. Some printers have an ESC/POS emulation mode which can be activated to speak with standard POS software, may be best to consult the manual.

**Comment by candrairawan78** [comment]
Dear mike,
I just realized that this is not an esc printer. I think every thermal printer support esc pos command.

Thank you for helping. I close this issue

Regards,
Candra

**Comment by krixnaas** [comment]
i just got the Xprinter-xp 350 BM, and this library doesn't support the printer.

**Comment by candrairawan78** [comment]
Thank you for your response.I have solve my problem. I use ZPL language to print

Sent from Yahoo Mail on Android 
 
  On Tue, 16 Jan 2018 at 0:40, krixnaas<notifications@github.com> wrote:   
i just got the Xprinter-xp 350 BM, and this library doesn't support the printer.
