### ISSUE TITLE
Can i control the content's padding/margin in print paper.

### ISSUE THREAD

**Issue by aisuhua** [mike42/escpos-php#130]
By default, the padding of the paper is too large, I want to reduce it. By I don't know how to do it.
Thinks!

**Comment by mike42** [comment]
- What make/model of printer do you have?
- Can you share a code snippet that shows the issue and a picture of what it prints?

This driver does not pad or wrap text, but these may help narrow down the source of your unwanted margin.

**Comment by aisuhua** [comment]
That is not an error. And the margin is normal. But i want to reduce the default margin.
I use the Star TSP700II printer. I print the example/demo.php. Like this

![20160609184249](https://cloud.githubusercontent.com/assets/11390617/15927167/78936e84-2e72-11e6-942a-1c564558e77e.jpg)

I want to reduce the margin (red line)

**Comment by mike42** [comment]
It is not currently possible to adjust the left margin via this driver. On my TM-T20, the margin is much smaller, around the width of a single character.

Googling this model turns up this [data sheet](http://www.starmicronics.com/printer/thermal_printers/tsp700ii) which suggest that it treats the first column differently intentionally for 'lottery printing'. To adjust it, you would need to reach out to the vendor to determine whether this can be configured a DIP switch, some configuration tool, or via commands (and if so what commands could be sent to control it from ESC/POS emulation mode).

**Comment by aisuhua** [comment]
I can switch the DIP mode. And that turn on/off print two different left magin.

![img_20160609_212102](https://cloud.githubusercontent.com/assets/11390617/15931134/f29ef340-2e88-11e6-8469-b42a9e70479e.jpg)

The first one is when i turn off DIP, the left margin is smaller than when i turn on DIP.

But, If i turn off DIP, that will  be not printing properly. At here, I want to only show the different  results.

**Comment by aisuhua** [comment]
To adjust the left margin, I use this command:

```php
<?php

require __DIR__ . '/../autoload.php';

use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfiles\StarCapabilityProfile;

$connector = new WindowsPrintConnector("device");

$profile = StarCapabilityProfile::getInstance();

$printer = new Printer($connector, $profile);

$printer -> text("This is normal left margin.\n");
$printer -> text("PHP receipt printer library for use with ESC/POS-compatible thermal and impact printers.\n");

$printer -> text("   \n");


//To reduce the left margin
$connector->write(Printer::GS.'L'.chr(0).chr(0));

$printer -> text("After reducing the left margin.\n");
$printer -> text("PHP receipt printer library for use with ESC/POS-compatible thermal and impact printers.\n");

$printer -> text("   \n");


$printer->setEmphasis(true);
$printer -> text("It's seen that the width of each line is fixed.\n");
$printer -> text("But I want the right margin is as same as the left margin.\n");

$printer -> cut();
$printer -> close();

```

![20160611210108](https://cloud.githubusercontent.com/assets/11390617/15985197/37b7daa6-3018-11e6-828c-455118ca0173.jpg)


That works! But now, I have another difficult, because I can not adjust the right margin as the same as left margin. It's seen that the width of each line is fixed. It is a way to do this ?  I am not familiar with this. Thinks!

**Comment by mike42** [comment]
Good result.

`GS L`, which you're using here, is not implemented in the library, nor is `GS W` (set print area width). Do you have a programming guide that suggests whether your printer will accept `GS W`, and if so, what values it will take?

**Comment by mike42** [comment]
The snippet below based on your code shows how `GS L` & `GS W` work for me. Hopefully you can use it to expand the page width and remove the right marign.

```php
<?php
/* Left margin & page width experiment on TM-T20 */

require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;

function intLowHigh($input, $length)
{
    // Function to encode a number as two bytes. This is straight out of Mike42\Escpos\Printer
    $outp = "";
    for ($i = 0; $i < $length; $i++) {
        $outp .= chr($input % 256);
        $input = (int)($input / 256);
    }
    return $outp;
}

// Printer initialisation
$connector = new FilePrintConnector("/dev/usb/lp0");
$printer = new Printer($connector);

// Stuff around with left margin
$printer -> text("Default left\n");
foreach(array(1, 2, 4, 8, 16, 32, 64, 128, 256, 512) as $margin) {
    $connector->write(Printer::GS.'L'.intLowHigh($margin, 2));
    $printer -> text("left margin $margin\n");
}
// Reset left
$connector->write(Printer::GS.'L'.intLowHigh(0, 2));

// Stuff around with page width
$printer -> setJustification(Printer::JUSTIFY_RIGHT);
$printer -> text("Default width\n");
foreach(array(512, 256, 128, 64) as $width) {
    $connector->write(Printer::GS.'W'.intLowHigh($width, 2));
    $printer -> text("page width $width\n");
}

// Printer shutdown
$printer -> cut();
$printer -> close();
```

![2016-06-margins](https://cloud.githubusercontent.com/assets/2080552/15985359/c4ca7b8c-302d-11e6-98e6-69435165ad65.jpg)

Also marking this as a feature request, as this would be pretty straightforward to add to the driver.

**Comment by aisuhua** [comment]
Oh, thank you very much ! `GS L` work with `GS W` can satisfy it. And that is a good features. 

It work for me . 

```php

function intLowHigh($input, $length)
{
    // Function to encode a number as two bytes. This is straight out of Mike42\Escpos\Printer
    $outp = "";
    for ($i = 0; $i < $length; $i++) {
        $outp .= chr($input % 256);
        $input = (int)($input / 256);
    }
    return $outp;
}


//To reduce the left margin
$connector->write(Printer::GS.'L'.intLowHigh(0, 2));

//Set the print with
$connector->write(Printer::GS.'W'.intLowHigh(512, 2));

```

PS: I use Star TSP 700II, the manual is here [HSP7_ESCPOS_Command.pdf](http://www.aures-support.fr/DATA/install/HSP7_ESCPOS_Command.pdf)

Thanks!
