### ISSUE TITLE
Implement pdf417 2D code printing

### ISSUE THREAD

**Issue by aisuhua** [mike42/escpos-php#132]
The document about pdf417 barcode is very complicated for me now. I will try it latter. 

The pdf417 barcode look like:

![barcode sample copy](https://cloud.githubusercontent.com/assets/11390617/15989576/8dd60252-30ac-11e6-973a-00fd926466d2.jpg)

Have some suggestion about it ? Thanks !

**Comment by mike42** [comment]
QR codes are the only 2D code currently supported. The PDF417 code is a very similar command, so I'll label this as a possible enhancement.

Can you give some sample data that you might print in one of these codes?

**Comment by aisuhua** [comment]
Like the unique code:

    $code = unique❨'id', true❩;  
    // id4b340550242239.64159797

**Comment by mike42** [comment]
I've got PDF417 codes working on an Epson TM-T20II, and plan to add support in the next minor release.

Can you confirm-

- Which make/model printer do you have?
- Have native QR codes and barcodes worked reliably on your printer? (ie, `$printer -> qrCode()`)
