### ISSUE TITLE
WindowsPrintConnector not found on CodeIgniter

### ISSUE THREAD

**Issue by Rachmannh** [mike42/escpos-php#1326]
Hello @mike42, i have a problem with WindowsPrintConnector on CodeIgniter 3, it's say like this : 

message: Class 'Mike42\Escpos\PrintConnectors\WindowsPrintConnector' not found

i already loaded (require) a path for autoload.php :

`
require_once 'vendor\autoload.php';

use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\Printer;
`

but still error. can anyboady help me?

thank you :)
![Capture](https://github.com/mike42/escpos-php/assets/69642186/7f5c5664-a2a8-4e8d-94d5-0d7b842b5df5)

**Comment by parallels999** [comment]
https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php

**Comment by Rachmannh** [comment]
> https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php

Thank you for your help.
