### ISSUE TITLE
Tested -- Rongta RP326US

### ISSUE THREAD

**Issue by digipifini** [mike42/escpos-php#133]
Testing out your awesome PHP driver for ESC/POS on a Chinese Manufactured low-cost thermal direct printer from Rongta.  The specific model is the RP326US, plugged in to an ASUS RT-56U via the USB port using the built-in printserver.  Most commands appear to work without issue, just trying to find the exact command for the internal beep command.  Works great for a customer accessible print solution for a pizza place, great job guys!

**Comment by bobbyhsu** [comment]
Hi  digipifini,

Did you figure out how to send a beep?

Thanks

Bobby

**Comment by digipifini** [comment]
Guess I responded to your question previously.

https://github.com/mike42/escpos-php/issues/142

**Comment by mike42** [comment]
Thanks for reporting, glad you have found the driver useful!

I've added this to the list of printers in the README for future users.
