### ISSUE TITLE
ImagePrintBuffer attempts to instantiate abstract class Mike42\Escpos\EscposImage

### ISSUE THREAD

**Issue by blady911** [mike42/escpos-php#134]
Hi

I am trying to print Arabic by your example in 6-arabic-epos-tep-220m.php from a web server .
However, I am getting this error: 
Fatal error: Cannot instantiate abstract class Mike42\Escpos\EscposImage

The code works fine when I print regular text (english) without using the ImagePrintBuffer.php

**Comment by mike42** [comment]
This is probably a bug, the example you're referring to looks like it needs to be updated.
