### ISSUE TITLE
Printing image from url

### ISSUE THREAD

**Issue by celinekoe** [mike42/escpos-php#135]
Hi Mike,

Thanks for your help previously! I just have another question. I tried printing an image from a url:
https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png
but it doesn't work. Is it possible to print from a url without first storing the file in my server? I've looked at bitImageColumnFormat, but it doesn't seem obvious to me how to do it.

**Comment by mike42** [comment]
The simplest work-around would involve just saving the image to a temp file, but it may also be possible via [imagick.readimagefile](http://php.net/manual/en/imagick.readimagefile.php).
