### ISSUE TITLE
Characters per line per font

### ISSUE THREAD

**Issue by oth** [mike42/escpos-php#136]
Hi,
Is there a way to read the num of chars per line from the printer ?
Actually I'm testing with three printers ( SAMSUNG SRP-350G, CITIZEN S310II and Oxhoo TP35D ) and they all have different chars per line, 48, 50, 42 for font A

**Comment by mike42** [comment]
There is no simple way to query the info from the printer, and the driver does not currently track this. I'll take this as a feature request to track printer characteristics in the `CapabilityProfile`.

Given that you know the widths, you could still store information in the `CapabilityProfile` for a particular type of printer like this:

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\CapabilityProfiles\DefaultCapabilityProfile;

// Store a custom characteristic for this model of printer in its CapabilityProfile.
$profile = DefaultCapabilityProfile::getInstance();
$profile -> lineWidth = 50; 

// Printer initialisation
$connector = new FilePrintConnector("/dev/usb/lp0");
$printer = new Printer($connector, $profile);
printReceipt($printer);

function printReceipt(Printer $printer) {
    // Get the width from the printer, with only the printer in scope.
    // Retrieve width
    $i = $printer -> getPrinterCapabilityProfile() -> lineWidth;
    $printer -> text("Hello world: $i\n");

    // Printer shutdown
    $printer -> cut();
    $printer -> close();
}
```

**Comment by oth** [comment]
Thanks, I just added a setting to the software to accommodate with that. I first thought it was standard in all printers, but unfortunately it's not
