### ISSUE TITLE
Qrcode side by side

### ISSUE THREAD

**Issue by raindy29** [mike42/escpos-php#137]
Thanks for mke42/escpos easy print qrcode
I can't print in the same column in two qrcode ?

https://drive.google.com/file/d/0B_BlNnqmXZ7-VUtVa0ZydFBKbm8/view?usp=sharing

**Comment by mike42** [comment]
Unfortunately there is no way to create this sort of layout without ESC/POS Page Mode, which is not currently supported in this driver.

Your options are probably to adjust the layout, render the codes to an image and print that instead, use a driver that supports page mode, or to implement page mode.
