### ISSUE TITLE
Epson TM-T88V

### ISSUE THREAD

**Issue by robpowers** [mike42/escpos-php#139]
We are using this library successfully with the following printer:

Epson TM-T88V
Model M244A

**Comment by nitinsbuzz** [comment]
Did you make additional changes or did you face any hair-pulling issues?

**Comment by robpowers** [comment]
No changes needed.  Everything worked fine with little effort on the features we needed:

Line feed, cutting, text output, image printing, pulse generation for a cash drawer, text justification, font manipulation.

**Comment by mike42** [comment]
Thanks for reporting!

**Comment by ninsky** [comment]
@robpowers , did you also try to print a 4-bit grayscale image? See my ticket [https://github.com/mike42/escpos-php/issues/154](url)

**Comment by robpowers** [comment]
@mike42 We only used 1-bit black and white BMP images.  I have not attempted to print a 4-bit grayscale image.
