### ISSUE TITLE
I got an issue with Vietnamese

### ISSUE THREAD

**Issue by hoaianit** [mike42/escpos-php#140]
Hi Mike42,
I have an issue with escpos, it does not support Vietnamese.
text string ex:  "Tiếng Việt, còn gọi tiếng Việt Nam hay Việt ngữ, là ngôn ngữ của người Việt (người Kinh) và là ngôn ngữ chính thức tại Việt Nam."
Could you please help me to solve it.
Thanks!

**Comment by mike42** [comment]
Hi,

Which make/model printer do you have? Does it support Vietnamese?

The Epson TM-T20 seems two code pages containing Vietnamese characters, so it might be as simple as typing these out if you have a similar printer: [tm-t20ii_trg_en_revc.pdf](https://files.support.epson.com/pdf/pos/bulk/tm-t20ii_trg_en_revc.pdf) (page 137/8).

**Comment by hoaianit** [comment]
The printer I am testing is Epson TM-20,
I will try your suggestion.
Thanks!

**Comment by hoaianit** [comment]
Hi Mike,
In the codepage.php, I changed:
const CP1258 = "CP1258";
const TCVN_3 = "TCVN-3";
I would like to print Unicode UTF8 font(not TCVN font, it is too old and not a default font on web), but some texts are correct, some are not.
Please see the picture.
![vietnamese_issue_escpos](https://cloud.githubusercontent.com/assets/9885836/16571616/9da36cbe-422d-11e6-9220-e322cf608f71.jpg)

Please help!
Thanks!

**Comment by hoaianit** [comment]
Hi Mike,
Is there any luck on this?
Do you need any more info from me?
Thanks!

**Comment by mike42** [comment]
Hey, some background for future readers,

The driver will attempt to convert from UTF-8 to the target code pages. In this case we need to add the content of the code pages as UTF-8 strings in the DefaultCapabilityProfile. We added Latvian support the same way (this snippet from [StarCapabilityProfile](https://github.com/mike42/escpos-php/blob/v1.2.1/src/Mike42/Escpos/CapabilityProfiles/StarCapabilityProfile.php))

```php
    public function getCustomCodePages()
    {
        return array(
            'CP3011' => "ÇüéâäàåçêëèïîìÄÅ" .
                        "ÉæÆôöòûùÿÖÜ¢£¥₧ƒ" .
                        "áíóúñÑªº¿⌐¬½¼¡«»" .
                        "░▒▓│┤Ā╢ņ╕╣║╗╝╜╛┐" .
                        "└┴┬├─┼ā╟╚╔╩╦╠═╬╧" .
                        "Š╤čČ╘╒ģĪī┘┌█▄ūŪ▀" .
                        "αßΓπΣσµτΦΘΩδ∞φε∩" .
                        "ĒēĢķĶļĻžŽ∙·√Ņš■ "
        );
    }
    public function getSupportedCodePages()
    {
        return array(
                76 => 'custom:CP3011');
    }
```

The content of the two TCVN-3 code pages on TM-T20 are: (images are from PDF linked above)

- 30 / [TCVN-3](https://cloud.githubusercontent.com/assets/2080552/16894482/cc81caaa-4b9a-11e6-9304-b455c54f958e.png)
- 31 / [TCVN-3](https://cloud.githubusercontent.com/assets/2080552/16894481/cae87a2c-4b9a-11e6-8d54-c0f998fb4f17.png)

So I've typed these out in DefaultCapabilityProfile (code change is in [this commit](https://github.com/mike42/escpos-php/commit/8b143ee99287bd8b16b9714c31195c07906e2724)) and attempted to print your example string-

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\CapabilityProfiles\DefaultCapabilityProfile;

// Printer initialisation
$connector = new FilePrintConnector("/dev/usb/lp1");
$printer = new Printer($connector, $profile);
$printer -> text("Tiếng Việt, còn gọi tiếng Việt Nam hay Việt ngữ, là ngôn ngữ của người Việt (người Kinh) và là ngôn ngữ chính thức tại Việt Nam.\n");

// Printer shutdown
$printer -> cut();
$printer -> close();
```

![escpos-140-test](https://cloud.githubusercontent.com/assets/2080552/16894785/56a810ae-4ba5-11e6-9562-1627b8388b2c.png)

Can you check this output for correctness and/or try to replicate?

**Comment by hoaianit** [comment]
Awesome, it works like a charm,
Thank you so much!
