### ISSUE TITLE
How to send a beep to the printer

### ISSUE THREAD

**Issue by bobbyhsu** [mike42/escpos-php#142]

**Comment by bobbyhsu** [comment]
Hi Mike,

I tried to send BEL or BEEP command by using connector->write with some raw characters but printer won't beep. Any thoughts? Thanks

**Comment by digipifini** [comment]
Depending on the make of printer and model, some of these commands will differ.  After some searching on Rongta for their command set I found the right command:

$printer -> getPrintConnector() -> write(PRINTER::ESC . "B" . chr(4) . chr(1));

The B is for the bell chime, the second digit for the number of requested beeps, and the third for the time between beeps.  Some other manufacturers use BEL or BEEP or even BEP for the chime.

However, as other users have noted, not all printers allow use of the beep, which Epson regards only as a warning of something wrong (ex. paper jam, out of paper).

**Comment by bobbyhsu** [comment]
Much appreciated.

**Comment by mike42** [comment]
I'm consolidating a few similar issues into #174, to track progress adding a beep command to the driver.

Sounds like the original question was answered here, so I'll close this.

**Comment by Wilgust** [comment]
Hola mike42, tengo un modelo de impresora POS-D 230 y estoy intentando hacer que emita un BEEP cuando esta imprima pero no lo hace, por favor tu ayuda.

**Comment by alejoni0** [comment]
I confirm that it worked just by putting this line   
 $printer -> getPrintConnector() -> write(PRINTER::ESC . "B" . chr(4) . chr(1));
