### ISSUE TITLE
Printer cut() cuts paper and sometimes it doesn't

### ISSUE THREAD

**Issue by oth** [mike42/escpos-php#144]
Hello, 
On some printers, I'm seeing a weird behaviour where a call to $printer -> cut(); cuts the paper sometimes, and sometimes it doesn't depending on the content of the receipt 
Any one experienced this behavior before ?

**Comment by mike42** [comment]
Do you have any examples you could post?

This driver wont currently stop you from using `cut()` if the print buffer hasn't been cleared, but most printers would just ignore it, so first make sure you issue a newline before you cut.

```php
// Prints "Hello World" and fails to cut
$printer -> text("Hello world\n");
$printer -> text("An incomplete line");
$printer -> cut();
// Prints "Hello World", "Demo", and cuts
$printer -> text("Hello world\n");
$printer -> text("Demo\n");
$printer -> cut();
```

**Comment by oth** [comment]
This is the code I use:
```
		$printer -> text("$footer\n");
		$printer->selectPrintMode();
		$printer->setBarcodeTextPosition(Printer::BARCODE_TEXT_BELOW);
		$printer->setBarcodeHeight(64);
		$printer->barcode($mvt[$m]['id'].'-'.time(), Printer::BARCODE_CODE39);
		$printer->feed();
		$printer -> cut();
		if(!$is_restaurant) {
			$printer -> pulse();
		}
		$printer -> close();
```
Btw, the barcode doesn't show on some printers I tested

**Comment by oth** [comment]
Hello @mike42 
This issue is driving me nuts. it only happens in serial port print, in network printing it works fine. And apparently it's random or I'm missing something.
Apparently it stops before the cut and sometimes it prints weird characters
Is there something I should be aware of concerning serial ports ?

**Comment by oth** [comment]
Update:
It's not related to escpos-php
I'm using the output of php and sending it to a c++ Qt wrapper to send it to a serial port.
The problem is that, the Qt program doesn't change the data bits to 8 ( by default 7 ) ( altho I specify it using QSerialPort )
windows 7 device manager shows the wrong value. I had to use cmd line *mode* to change the serial port settings ( still don't know why it doesn't work otherwise )

**Comment by mike42** [comment]
Hey, glad you have been able to find some more info this. I will assume that this is not a bug.

I don't have a serial printer, but if I did-
- In Windows, I would have installed the printer with the generic/text only driver, mapped it to COM1, and used a `WindowsPrintConnector` to pass data to it.
- In Linux, I would have used a USB/serial adapter, and rigged up a `FilePrintConnector` to `/dev/ttyS0`.
