### ISSUE TITLE
support for Datamax O´neil thermal printers

### ISSUE THREAD

**Issue by coyarzun2013** [mike42/escpos-php#149]
just add support for datamax Thermal printers

M-class Mark II

thanks in advance

**Comment by mike42** [comment]
Hi, this project implements a subset of Epson's ESC/POS protocol for thermal receipt printers.

I believe Datamax O'Neil printers speak [DPL](https://www.datamax-oneil.com/do/sp/en-us/file.cfm/CL2_88-2341-01_L.pdf?contentID=7616&ext=.pdf) only, so you probably need to locate or write a DPL driver.
