### ISSUE TITLE
Aures ODP500

### ISSUE THREAD

**Issue by mszajner** [mike42/escpos-php#153]
I'm using this driver with AURES ODP500 and it works well (add this printer to list, please). I've some issue with printing. ODP500 prints very slow some texts. When line has 42 bytes (chars) then printer prints this line about 0.6 sec. Have anyone same issue with Aures ODP500?

**Comment by mike42** [comment]
I get slowness on the Epson TM-T20 when I print images that are too wide.

Is your paper width 42 characters, so that the driver could fix this through word-wrapping?

**Comment by mszajner** [comment]
I'm cutting to wide lines (more than 42 characters) but printer still slows down. I found that sometimes fwrite in Connector returns false so in my opinion printer is unable to buffer more bytes. I've added usleep ~5ms and retries to send this byte (10 attempts) and I think problem dissapears :-) I'm testing my patch for over 2 days.

**Comment by mike42** [comment]
Assuming this is solved.

If there's any modifications that you think we should incorporate into the main library as a more permanent fix, then please suggest them as a new issue or pull request.
