### ISSUE TITLE
TM-T88V 4-bit grayscale image printing

### ISSUE THREAD

**Issue by ninsky** [mike42/escpos-php#154]
Hi Mike

I'm using Epson's TM-T88v direct print feature to print receipts with images. The Epson Print XML document expects a base64 encoded PNG image.

If I encode the following 128x128px image with Epson's [ePOS-Print XML generator tool](http://www.i-pos.nl/epson/) and copy the produced base64 encoded image to the XML document manually, the image gets printed correctly.
![3x](https://cloud.githubusercontent.com/assets/1623045/17603926/9ea1321e-6013-11e6-9a82-d9af788325f2.png)

Now, I'm trying to create the same base64 encoded raster code with following commands which works for a 1bit PNG (monochrome) but doesn't work for the picture above which is a 4bit (grayscale):

```
$imagick = new Imagick('3x.png'); 
$iEscposImage = new ImagickEscposImage();
$iEscposImage->readImageFromImagick($imagick);
$rasterFormat = $iEscposImage->toRasterFormat();
return base64_encode($rasterFormat);
```

I've noticed that the base64 code out of Epson's tool looks different than the code produced by toRasterFormat(). 

Epson's ePos Print-XML documentation tells us:

> Data is generated based on 1 bit per pixel for two-tone images, and 4 bits per pixel for 16-tone images, starting with the upper bits of byte data. And zero-padding is performed so that scan data per line can be treated on a byte basis. To create raster graphic bit-images, use the ePOS-Print XML generator tool or your own application. Note the following when creating raster graphic images using your own application. Two-tone image: Specify a multiple of 8 for the image width or fill the missing bits with zeros. 16-tone image: Specify a multiple of 2 for the image width or fill the missing bits with zeros.

Any advice would be highly appreciated! 

Thanks in advance  
ninsky

**Comment by mike42** [comment]
Hey,

I can confirm that this driver currently going to help much with your use case. It operates with 1-bit images only, and produces binary output in the ESC/POS protocol, rather than this ePos XML.

Perhaps you would be able to re-post this as two feature requests? (4-bit greyscale and alternate XML-based output can be discussed and worked on separately). As I don't currently have printers which support these, I'm not likely to implement them myself, but I'd be happy for possible future improvements such as these to be tracked here.

**Comment by ninsky** [comment]
Hi Mike

Thanks for your reply. Would be happy to test 4bit grayscale rastercode on my Epson TM-T88V as soon as we have a PHP function producing such code.

(Meanwhile I've created a bit clumsy workaround by using Epson's JS library to create the code client side, posting it afterwards to MySQL.)

Will post a new issue which can be marked as feature request (as proposed).

Best regards
ninsky

**Comment by mike42** [comment]
Closing off. I think this is answered. #158 tracks feature request for 4-bit images.
