### ISSUE TITLE
How to print from a server

### ISSUE THREAD

**Issue by lkcodk** [mike42/escpos-php#155]
Hi mike
I just uploaded the epson-script to my PHP server, but i dont know how to print to a shared printer on my computer from the server? Btw. It works fine on localhost.

Here is the code:

<?php

	require("autoload.php");
	use Mike42\Escpos\Printer;
	use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
	
		
		try {
	
		$connector = null;
		$connector = new WindowsPrintConnector("smb://KASPERPC/kasperbon");

		
		$printer = new Printer($connector);
		$printer -> text("Hello World!\n");
		$printer -> cut();
		
	
		$printer -> close();
	} catch (Exception $e) {
		echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
	}
	
?>

Here is the error on the server side:

Couldn't print to this printer: Failed to print. Command "smbclient '//KASPERPC/kasperbon' -c 'print -' -N" failed with exit code 127:

I hope you can help me.

Thank you
Kasper

**Comment by mike42** [comment]
In short, it looks like you are moving your script from Windows to a Linux server that  [doesn't have smbclient](https://www.google.com/search?q=exit+code+127). I've filed the low-quality output as bug #156 to make sure that's improved, as this has previously affected users who are missing the package.

Your best sanity check for this setup is to print "hello world" from the server, on the command-line, exactly as the driver does (copy-pasted the command from your error message):

```
echo "hello world" | smbclient '//KASPERPC/kasperbon' -c 'print -' -N
```

Some other users with this setup have been attempting to print from servers on the Internet. I have some remarks at #121 which you may be interested to read if this applies to you.

**Comment by mike42** [comment]
I'm assuming this has been answered.

More background on the issue of printing across networks is now listed in the [FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md).

**Comment by iimnd** [comment]
hi @mike42 , i have succes print using this command : 
`echo "hello world" | smbclient '//KASPERPC/kasperbon' -c 'print -' -N`

but, when i print using my web app, i get this error 

> "printer_status":"Failed to print. Command \"smbclient '\/\/T410\/debian_printer'
 -c 'print -' -N\" failed with exit code 1: Domain=[T410] OS=[Windows 8 Pro 9200] Server=[Windows 8 Pro
 6.2]tree connect failed: NT_STATUS_BAD_NETWORK_NAME"

**Comment by erakashpatel** [comment]
Hello @mike42 

Same issue i got . is there any way so fixed that error.?

Couldn't print to this printer: Failed to print. Command "smbclient '//woodbox.site/POS-58' -c 'print -' -N -m SMB2" failed with exit code 127: sh: smbclient: command not found

i hope you give me some positive reply regrading it.

Thanks
akash
