### ISSUE TITLE
4-bit grayscale raster code

### ISSUE THREAD

**Issue by ninsky** [mike42/escpos-php#158]
Hi

Epson's TM-T88V series features printing 16 color grayscale images. With this issue I would like to propose an enhancement to create a PHP function which produces 4-bit grayscale raster code which is needed print such grayscale images (also see #154 ).

**Enhancement**
Currently escpos-php supports a PHP function called [**toRasterFormat()**](escpos-php/src/Mike42/Escpos/EscposImage.php) which produces 1-bit raster code for two color monochrome images. It would be great to enhance this PHP function or to create a new one to produce 4-bit raster code.

**How to produce such raster code?**
Epson provides some information which could help to create the needed function:

_1. Epson Print-XML documentation_

> Data is generated based on 1 bit per pixel for two-tone images, and 4 bits per pixel for 16-tone images, starting with the upper bits of byte data. And zero-padding is performed so that scan data per line can be treated on a byte basis. To create raster graphic bit-images, use the ePOS-Print XML generator tool or your own application. Note the following when creating raster graphic images using your own application. Two-tone image: Specify a multiple of 8 for the image width or fill the missing bits with zeros. 16-tone image: Specify a multiple of 2 for the image width or fill the missing bits with zeros.

_2. Epson ePOS-Print Editor_
The [ePOS-Print Editor](http://www.i-pos.nl/epson/) is part of Epson's ePOS-Print JS SDK which is available [here](https://c4b.epson-biz.com/modules/community/index.php?content_id=70). The JS SDK provides a JS library containing a function called `toGrayImage(imgdata, g)`. A possible solution could be to translate this JS function to PHP. 

I think this enhancement would be a great addition to an already great library :) Would be happy to test any code as I'm owning a TM-T88V. Just let me know.

Best regards
ninsky

**Comment by mike42** [comment]
This issue has been open for approximately 2 years, and there does not appear to be any interest in implementing it. Also, as mentioned in #154, we have no existing XML output, so it's not clear to me how this would fit in with the existing code.

I'm closing it off now to keep bug tracker focused. Future readers, please make some noise if you are interested in implementing 4 bit grayscale output in this. You will need to be able to test it on real hardware using only a publicly available manual (original implementations only please), and it must not change the output for existing printers which do not support this feature.
