### ISSUE TITLE
Adjust the text

### ISSUE THREAD

**Issue by lkcodk** [mike42/escpos-php#159]
Hi mike

How do i make the printed content centered?

And how can i make some parts of the text "float right"

loot at the example
![ex](https://cloud.githubusercontent.com/assets/17985956/17966256/f1c283a0-6ac0-11e6-92ee-ec829be3cc10.gif)

kasper

**Comment by Stenerson** [comment]
@lkcodk You can change the text justification with the [`setJustification()`](https://github.com/mike42/escpos-php#setjustificationjustification) method. There are examples of this in many of the examples (like [`receipt-with-logo`](https://github.com/mike42/escpos-php/blob/master/example/receipt-with-logo.php)) 
`$printer -> setJustification(Printer::JUSTIFY_CENTER);`

I don't think there's a way to float text right or left. You could slice your text up to present the illusion of floated text. Something like:

```
This is something   This is another
that I want on the  thing that I 
left                want on the right
```

**Comment by mike42** [comment]
This is all correct. Text 'floating' can only be achieved in HTML or PDF input at the moment, since page mode is not implemented in this driver.

Laying out the text in columns would be very effective though. The print driver does not know how wide the page is, so you could tweak this example and send it via `text()` function. See how you go, anyway (example ASCII only, just for illustration).

```
$ php columnify.php 
Lorem ipsum dolor sit     Ut enim ad minim      
amet, consectetur         veniam, quis nostrud  
adipiscing elit, sed      exercitation ullamco  
do eiusmod tempor         laboris nisi ut       
incididunt ut labore      aliquip ex ea commodo 
et dolore magna           consequat.            
aliqua.                                         
```

```php
<?php
/**
 * Multi-column text printing example.
 */

$leftCol = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";
$rightCol = "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";

echo columnify($leftCol, $rightCol, 22, 22, 4);

/**
 * Arrange ASCII text into columns
 * 
 * @param string $leftCol
 *            Text in left column
 * @param string $rightCol
 *            Text in right column
 * @param number $leftWidth
 *            Width of left column
 * @param number $rightWidth
 *            Width of right column
 * @param number $space
 *            Gap between columns
 * @return string Text in columns
 */
function columnify($leftCol, $rightCol, $leftWidth, $rightWidth, $space = 4)
{
    $leftWrapped = wordwrap($leftCol, $leftWidth, "\n", true);
    $rightWrapped = wordwrap($rightCol, $rightWidth, "\n", true);
    
    $leftLines = explode("\n", $leftWrapped);
    $rightLines = explode("\n", $rightWrapped);
    $allLines = array();
    for ($i = 0; $i < max(count($leftLines), count($rightLines)); $i ++) {
        $leftPart = str_pad(isset($leftLines[$i]) ? $leftLines[$i] : "", $leftWidth, " ");
        $rightPart = str_pad(isset($rightLines[$i]) ? $rightLines[$i] : "", $rightWidth, " ");
        $allLines[] = $leftPart . str_repeat(" ", $space) . $rightPart;
    }
    return implode($allLines, "\n") . "\n";
}
```

**Comment by umardevid** [comment]
this code is wrong params position mike
return implode($allLines, "\n") . "\n";

the true is
return implode("\n", $allLines) . "\n";
