### ISSUE TITLE
Import printer capabilities profiles from JSON

### ISSUE THREAD

**Issue by miracle2k** [mike42/escpos-php#160]
I'm using python-escpos. It seems that you, Mike, or involved over there as well.

I'd like to see the Python version support capability profiles; more than what we have here right now, I'd also like to collect the column count infos for different models.

My suggestion would be building a YAML document containing all the information; this can then be loaded both in Python and PHP, or, from it we can generate the PHP classes.

Thoughts?

**Comment by miracle2k** [comment]
I'm thinking something like this: https://github.com/miracle2k/python-escpos/commit/246f7ad1ceefb22dcf21da468f86e888d2e94506

**Comment by mike42** [comment]
Commented in more detail at https://github.com/python-escpos/python-escpos/pull/149

YAML can't be used directly in this project for compatibility reasons, but its the best source format for the data, and I can do the conversion automatically to something like JSON.

For this project, implementing this change would involve porting the existing data to YAML, committing   a JSON export of the data here, then refactoring the `CapabilityProfile` and `CodePage` classes to read data from these files.
