### ISSUE TITLE
how to let printer alarm before print?

### ISSUE THREAD

**Issue by wesleyxiao** [mike42/escpos-php#173]
i am using pbm 822d printer with escpos php, which everthing working great.

i using ethernet 192.168.1.199  9100, which working good , i can print everything i need.

i make a lot of research try to add some code to printer.php files to let print beep before print. but it's not end up will, all i try is fail. no sound.

if i click on my computer -> device and printer-> which i setup manually on printer properties alarm before printing, when i click test page , this will beep(alarm) before printing.

but if i using escpos php, to print something, beep(alarm) is fail to call before printing.

anyone have idea to let printer beep(alarm) before print?

**Comment by wesleyxiao** [comment]
https://github.com/mike42/escpos-php/issues/142

just found the answer here, +1:

**Comment by mike42** [comment]
Thanks for the update.

This command has been mentioned a few times on the bug tracker. I've opened a new issue #174, tagged "enhancement", to track progress adding this to the driver.

**Comment by wesleyxiao** [comment]
open phppos/src/Mike42/Escpos/printer.php

add following code

public function beep($beep, $duration){ 

//$beep = how many time you want to beep, $duration = how many second.
	
$this -> -> getPrintConnector() -> write(PRINTER::ESC . "B" . chr($beep) . chr($duration));
}

when using function 

$printer -> beep(4,1);  //this mean beep 4 time in 1 second

**Comment by javitzso** [comment]
Can confirm this worked for Scangle SGT-88IV.
