### ISSUE TITLE
Venus V248T

### ISSUE THREAD

**Issue by wonk4rol** [mike42/escpos-php#176]
New support printer Venus V248T

**Comment by mike42** [comment]
Thanks for reporting!

If you notice any commands that don't work correctly on your printer, then please post a code snippet and a picture of the output. Compatibility information that you post from using the Venus V248T escpos-php could be loaded into the [ESC/POS printer database](https://github.com/receipt-print-hq/escpos-printer-db), which will help other users who have the same printer.
