### ISSUE TITLE
Server-client question 

### ISSUE THREAD

**Issue by CJAlder** [mike42/escpos-php#183]
Hi mike i have an application in a server and all the request come from a client and i need to print tickets for a sale and i want to know if with your driver it is possible, the principal question is about the printer if the driver recognizes the printer even the printer if in the client , i will hope for a answer.

**Comment by mike42** [comment]
Hey, can you please provide some more information about the setup?

- What printer model do you have, and how is it connected to the client?
- What platforms are the client and server?
- Are the client and server on the same network?

**Comment by CJAlder** [comment]
1- the printer is a TMU220 but this is only for test's
2-the server is a linux(debian) server and the cliente is windows 7
3-No the cliente and the server will be in a different network

**Comment by mike42** [comment]
The information that I've just added about printing from the Internet will apply to your setup.

- [doc/FAQ.md](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md)

**Comment by mike42** [comment]
Assuming this is answered, closing this issue.
