### ISSUE TITLE
ESC/POS printer feeds lines after cutting

### ISSUE THREAD

**Issue by jankal** [mike42/escpos-php#187]
Using `Printer::cut()` our ESC/POS printer cuts the paper but then feeds like 4 lines so the next print always has like 4 lines space from the top to the text.

How to fix this?
Using Excelvan ZJ-8220 (fully ESC/POS compatible said manual)

**Comment by mike42** [comment]
Hey, the command should be called "cut and feed", 3 lines by default ([README section](https://github.com/mike42/escpos-php/tree/2b9a2bf043942de40626674335a5e597895fcdc8#cutmode-lines))

What happens if you change it to:

```php
$printer -> feed(Printer::CUT_FULL, 0)
```

If this helps, I'll adjust the default to 0.

**Comment by mike42** [comment]
If you're still interested in solving this, please do test the suggestion above.

I'll assume this can be closed if I haven't heard back in a few days.

**Comment by jankal** [comment]
As I remember I'v already tried `$printer -> feed(Printer::CUT_FULL, 0)` when I had the printer available. But I think this didn't work. When I have the printer available again, I'll try these suggestions. Thanks.

**Comment by mike42** [comment]
Closing this off as inactive, please file a new issue with the extra info if you think this is a bug which can be fixed in the library.
