### ISSUE TITLE
Print QRCode

### ISSUE THREAD

**Issue by dexmendonca** [mike42/escpos-php#19]
Can I print QRCode

**Comment by mike42** [comment]
This was not previously implemented, but I've added it to the driver today. Resources on how to use the feature are:
- [README.md entry](https://github.com/mike42/escpos-php#qrcodecontent-ec-size-model)
- [example script](https://github.com/mike42/escpos-php/blob/master/example/qr-code.php)
- [Detailed howto, including alternatives if your printer cannot generate QR codes](http://mike.bitrevision.com/blog/2015-04-howto-qrcodes-on-receipts-with-escpos-php)

**Comment by dexmendonca** [comment]
thank you
