### ISSUE TITLE
I would add 2 more columns in items

### ISSUE THREAD

**Issue by dumorim** [mike42/escpos-php#190]
$items = array(
    new item("Example item #1", "qtd", "sub",  "4.00"),
    new item("Another thing", "qtd", "sub",  "3.50"),
    new item("Something else",  "qtd", "sub",  "1.00"),
    new item("A final item",  "qtd", "sub",  "4.45"),
);

https://github.com/mike42/escpos-php/blob/master/example/receipt-with-logo.php

**Comment by mike42** [comment]
The examples are intended to show how to interact with the library. They are not templates- you do need to write your own PHP code to produce receipts that work for you.

The `item()` class uses `sprintf()` to space the strings, and this would also work in 4 columns.

Best of luck!

**Comment by mike42** [comment]
Assuming this is answered, closing this issue off.
