### ISSUE TITLE
Print character set

### ISSUE THREAD

**Issue by haintiris** [mike42/escpos-php#194]
Hello, I am using P-822D Thermal printer but can not print full characters of VietNamese.
P-822D capability profile code page: 27 => false , // VietNam

Is there any settings i can do?

Thank you

**Comment by mike42** [comment]
On Epson printers, I was able to identify two code pages that contain "TCVN-3", and Vietnamese text support is pretty good.

To get that for the P-822D, we need to find out what's in that code page, and type it out in the profile. Do you have a test print that shows supported code pages, or a link to vendor documentation which displays the characters available at each point?

As a side note, there are some changes coming to printer profiles, so the fixes will go upstream to [receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db), which will store profile information from release 1.4 onward.

**Comment by mike42** [comment]
Closing this off as answered, see also #254, which has a work-around for printing vietnamese on printers which we can't encode for.
