### ISSUE TITLE
error in EscposImage.php

### ISSUE THREAD

**Issue by ckrempe** [mike42/escpos-php#196]
Calling class EscposImage.php :
 $img = new EscposImage($dest);

as mentioned in the examples, I get the error
"PHP Fatal error:  Cannot instantiate abstract class Mike42\Escpos\EscposImage

The image file $dest exists in /tmp.
Is there something missing?

Christoph

**Comment by mike42** [comment]
Yep, this usage is not correct. Where in the examples did you find it?

See also [the README, under graphics()](https://github.com/mike42/escpos-php/blob/4b855426b48d7b26b99e7fc997189e6562f06558/README.md#graphicsescposimage-image-size).

**Comment by ckrempe** [comment]
I use https://github.com/mike42/escpos-php/blob/development/example/print-from-html.php, line 69
With
        $img = EscposImage::load($dest);
        $printer->graphics($img);

it works!

Thank you!
