### ISSUE TITLE
Open cash drawer

### ISSUE THREAD

**Issue by sysxlabs** [mike42/escpos-php#2]
i would like to thank you for this project, it makes my life a lot easy... i would like to request a new feature in this project. besides thermal printers can you enhance this to support cash drawers also?

**Comment by mike42** [comment]
Hello,

I've added a new method, and my TM T82II is now able to output a pulse on its RJ9 port. This is supposedly how most drawers are opened.

https://github.com/mike42/escpos-php#pulsepin-on_mm-off_ms

Unfortunately I can't test this change with an actual cash drawer (I don't have one!). Can you please try out the new function with a few different parameters and let me know if it works?

Examples you could try-

    $escpos -> pulse();
    $escpos -> pulse(1);
    $escpos -> pulse(0, 100, 100);
    $escpos -> pulse(0, 300, 300);
    $escpos -> pulse(1, 100, 100);
    $escpos -> pulse(1, 300, 300);

If you can't get the drawer to open, then I'll need to know more about the setup, such as the models of the components involved, and how they are interfaced.

Cheers,

-Michael

**Comment by sysxlabs** [comment]
Michael, I will try it on a cash drawer and will share the result with you... thanks
Cheers, Sam

**Comment by dudwig** [comment]
Hi, i am afraid its not working. The variable names are wrong. The line:
```
function pulse($pin = 0, $on_ms = 120, $off_ms = 240) {
		fwrite($this -> fp, self::ESC . "p" . chr($m + 48) . chr($t1 / 2) . chr($t2 / 2));
	}
```
Has to be changed to
```
function pulse($pin = 0, $on_ms = 120, $off_ms = 240) {
		fwrite($this -> fp, self::ESC . "p" . chr($pin + 48) . chr($on_ms / 2) . chr($off_ms / 2));
	}
```

Also, i think $on_ms and $off_ms should be in hexadecimal format, e.g. 1ms =x01 but i am not sure about that.

Thanks for the nice Library
Dudwig

**Comment by mike42** [comment]
This could have to do with the pin being sent as character 48/49 in my output, not 0/1 as some printers expect. There's a new attempt in the testing branch based on a retailer's guide for entering the command.

Please test ('git checkout testing') and let me know.

**Comment by dudwig** [comment]
On my Epson TM-T70II, the original method is working now  with pin 48. I am going to try the new method soon.

**Comment by steeledward** [comment]
In mi case for the EPSON_TM_T20II printer on Windows only with the 
$printer->pulse();
works correctly, thanks a lot

**Comment by ankit007etsofficial** [comment]
Thank you mike42  its working
