### ISSUE TITLE
how do I download drivers that are listed in your posts

### ISSUE THREAD

**Issue by danielcintaa** [mike42/escpos-php#205]
how do I download drivers that are listed in your posts

I beg to send a link to my email
jackdaniel.jd151@gmail.com

**Comment by mike42** [comment]
You can download the latest release directly from [mike42/escpos-php/releases/latest](https://github.com/mike42/escpos-php/releases/latest), for inclusion in your PHP project.

The suggested first steps are [in the README here](https://github.com/mike42/escpos-php#basic-usage). They mention that you can also download the code through `git`, or via [composer](https://packagist.org/packages/mike42/escpos-php).
