### ISSUE TITLE
Multi Line Text with New Lines print question marks

### ISSUE THREAD

**Issue by Reflic** [mike42/escpos-php#209]
I have the following problem, while using the libary. Maybe i have missed a bit of important information than please just give me a hint.

I use a Serial Connected Printer and have a Webseite where you can enter some text in a textbox. If I am putting some text there and press enter and then start writing some more text. 
Alle New Lines are printed as question marks...

Have i missed a setting for encoding or something like that?

Input:

```
test1


test2
```

Print:

```
test1?
?
?
test2
```

**Comment by mike42** [comment]
Hi Kevin,

You may have found a bug. Are you by any chance sending Windows line endings?

**Comment by Reflic** [comment]
I thought this also, do you have any idea how i can test this?

The printer is connected to a Linux System, the problem occurs on the 
Website aswell on Mac as on Ubuntu.

Thanks for your help!

Am 30.10.2016 um 23:31 schrieb Mike:

**Comment by mike42** [comment]
See if you can use a FilePrintConnector to write to a file, then use hexdump, I would say.

**Comment by Reflic** [comment]
Ok, will test that as soon as i have the time to :)

**Comment by mike42** [comment]
I've just made a point release (v1.4.1) which allows Windows line endings to be used without triggering question marks. I suspect this will fix the issue you're seeing.

Can you update and re-test?

**Comment by mike42** [comment]
The fix in #210 works for me, closing this off.

Thanks for reporting.

**Comment by Reflic** [comment]
Sorry for my late answer had a lot of work todo. Your Release fixed the problem and it were the wrong line endings. Thanks for you fast response!
