### ISSUE TITLE
Bixolon printer

### ISSUE THREAD

**Issue by JrHasanBUDAK** [mike42/escpos-php#219]
What about bixolon's printer devices. for example "**Bixolon srp 270**"

**Comment by mike42** [comment]
Hello, please see the FAQ entry: [Can you add support for Printer X?](https://github.com/mike42/escpos-php/blob/4d2db9cdc7cd9b35fbbc62390516a20e4d5f55f2/doc/FAQ.md#can-you-add-support-for-printer-x).

I think in your case, since the Bixolon SRP-350III is already known to work, so the SRP 270 has a good chance of working as well. Please report back with how it goes!

**Comment by JrHasanBUDAK** [comment]
Hi, it's working as well. Thanks.

**Comment by mike42** [comment]
Ok, there's a few things here. I'll address them separately-

### Images

You appear to have printed a representation of the `GdEscposImage` object as text. Can you try sending the same object via `bitImage()`?:

```php
// Load image
$footer = EscposImage::load(public_path('assets\img\footer.png'));
// Print a dummy receipt
$connector = new FilePrintConnector("/dev/whatever");
$printer = new Printer($connector);
$printer -> text("The quick brown fox jumps over the lazy dog");
$printer -> bitImage($footer);
$printer -> cut();
$printer -> close();
```

If this doesn't work, send through a full code snippet.

As an aside, images will print much faster if you install the `Imagick` php extension, and load the image as above (`allowOptimisations=true`)

### Barcodes

A quick read of the [Boxolon command manual](http://www.bixolon.com/upload/download/unified%20command%20manual_rev_1_01.pdf) suggests that the barcode command is not available on your printer.

> Print bar code
> **Code:**
> ASCII GS k m d1...dk NUL
> ASCII GS k m n d1...dn
> ...
> **Printers:**
> All printer models except for SRP-270, SRP-275, SRP-280, SRP-500 

There is not much we can do about this, but if you know of a good PHP library to render barcodes as images, you may wish to suggest that we add this as a feature in future.

### QR codes
As above. `GS ( k` is not supported on your printer according to the manual. We do have an open feature request to render them with `phpqrcode` as a fallback though: #208

### Other

I've filed an issue for your printer at our upstream compatibility project: receipt-print-hq/escpos-printer-db#19, which will help to improve support for your printer in open source drivers.

**Comment by JrHasanBUDAK** [comment]
Thank you for your interest in 👍 
I had tried with bitImage too not worked. The printer result like [**that**](https://drive.google.com/file/d/0B8XvWmab8wi_UHEtSkRWSmFhSkU/view?usp=sharing)
This is full code snippet;
```
namespace App\Http\Controllers\Escpos;

use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use App\Http\Controllers\Controller;

class bixolonController extends Controller
{    
    private $connector;
    private $imgPath;
    private $sampleText;
    public function __construct(){
        $this->connector = new WindowsPrintConnector("BIXOLON");
        $this->image = EscposImage::load(public_path('assets\img\footer.png')); 
        $this->sampleText = "Bixolon SRP270 test text\n";
    }
    public function bitImage(){      
        try{            
            $printer = new Printer($this->connector); 
            $this->title($printer, "bitImage Test\n");
            $printer->text($this->sampleText);
            $printer->bitImage($this->image);
        }catch(\Exception $e){
            return $e->getMessage();
        }finally{
            $printer->cut();
            $printer->close();
        }
    }
    private function title(Printer $printer, $str)
    {
        $printer->selectPrintMode(Printer::MODE_DOUBLE_HEIGHT | Printer::MODE_DOUBLE_WIDTH);
        $printer->text($str);
        $printer->selectPrintMode();
    }
}
```

**Comment by mike42** [comment]
The plot thickens. Have you noticed that `\n` is being ignored? `\n` will usually clear the print buffer, which must be empty before images can be printed.

Your printer should also accept `\n`, and I notice you are on Windows. So the first thing to do is to ensure that the print system is not modifying the output before the printer gets it. On Windows, this means that the printer must be installed with a "Generic / Text Only driver", so remove any vendor drivers and re-install the printer to be sure. [This post about USB printers](https://mike42.me/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows) is basically what you need.

Next up, repeat your tests, maybe the output will change.

If not, try avoiding `\n`, and print images with an empty print buffer. You could, eg, reboot the printer and run just the `bitImage()` part-

```php
<?php
namespace App\Http\Controllers\Escpos;

use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use App\Http\Controllers\Controller;

class bixolonController extends Controller
{    
    private $connector;
    private $imgPath;
    private $sampleText;
    public function __construct(){
        $this->connector = new WindowsPrintConnector("BIXOLON");
        $this->image = EscposImage::load(public_path('assets\img\footer.png')); 
//        $this->sampleText = "Bixolon SRP270 test text\n";
    }
    public function bitImage(){      
        try{            
            $printer = new Printer($this->connector); 
//            $this->title($printer, "bitImage Test\n");
//            $printer->text($this->sampleText);
            $printer->bitImage($this->image);
        }catch(\Exception $e){
            return $e->getMessage();
        }finally{
            $printer->cut();
            $printer->close();
        }
    }
    private function title(Printer $printer, $str)
    {
        $printer->selectPrintMode(Printer::MODE_DOUBLE_HEIGHT | Printer::MODE_DOUBLE_WIDTH);
        $printer->text($str);
        $printer->selectPrintMode();
    }
}
```

If that works, you could add `feed(2)` to see if you can feed lines with an ESC/POS command-

```php
<?php
namespace App\Http\Controllers\Escpos;

use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use App\Http\Controllers\Controller;

class bixolonController extends Controller
{    
    private $connector;
    private $imgPath;
    private $sampleText;
    public function __construct(){
        $this->connector = new WindowsPrintConnector("BIXOLON");
        $this->image = EscposImage::load(public_path('assets\img\footer.png')); 
        $this->sampleText = "Bixolon SRP270 test text\n";
    }
    public function bitImage(){      
        try{            
            $printer = new Printer($this->connector); 
            $this->title($printer, "bitImage Test\n");
            $printer->text($this->sampleText);
            $printer->feed(2);
            $printer->bitImage($this->image);
        }catch(\Exception $e){
            return $e->getMessage();
        }finally{
            $printer->cut();
            $printer->close();
        }
    }
    private function title(Printer $printer, $str)
    {
        $printer->selectPrintMode(Printer::MODE_DOUBLE_HEIGHT | Printer::MODE_DOUBLE_WIDTH);
        $printer->text($str);
        $printer->feed(2);
        $printer->selectPrintMode();
    }
}
```

Best of luck.

**Comment by JrHasanBUDAK** [comment]
Hi @mike42 ,
There is no luck for me :) I tried bitImage() code (as you see at below) with orginal SRP 270 it didn't work after i tried like you said "Generic/Text only" driver but result didn't change. 
```
$printer = new Printer($this->connector); 
//$this->title($printer, "bitImage Test\n");
//$printer->text($this->sampleText);
$printer->bitImage($this->image);
```
I think there is no more we can do?
And the printer's result you can see with this [link](https://drive.google.com/file/d/0B8XvWmab8wi_VTlLa0JWeWktaWs/view)

**Comment by mike42** [comment]
Yep. The driver is outputting commands that appear in your printer documentation, so for it to be garbled this way (line endings and all), something is either wrong with your printer, or your print setup.

Installing as a "Generic/Text only" printer and sharing it locally is pretty much the standard way to achieve raw printing from PHP on Windows.

Knowing this has worked for other users, I'd be setting this up again on a fresh system with no vendor drivers, to be sure.
