### ISSUE TITLE
Select a shared printer 

### ISSUE THREAD

**Issue by abouhanna** [mike42/escpos-php#221]
Hi, firstly thanks for this nice work,
 
I have installed the escpos library on my server and I also installed my idipos T80 printer on a client PC (PC-01) my problem is when I test the script on a local printer is works fine; and after sharing the printer the script told me that it can not access to the printer (the server can not communicate with the printer).

Err msg : **_Couldn't print to this printer: Failed to copy file to printer_**

image bellow shows my config and I am using the current example : 

```
<?php 

require '../escpos-php-development/autoload.php';

use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

try {
    // Enter the share name for your USB printer here
	$connector = null;
	$connector = new WindowsPrintConnector("\\\PC-01\Printer");


	/* Print a "Hello world" receipt" */
	$printer = new Printer($connector);
	$printer -> text("Hello World!\n");
	$printer -> cut();

	/* Close printer */
	$printer -> close();
} catch (Exception $e) {
	echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

?>
```

![printerarch](https://cloud.githubusercontent.com/assets/11266838/20198700/64daf058-a7a6-11e6-8fd9-76848a449572.PNG)

OS : windows 7 
PHP v : 5.5.12
Thns for your help.

**Comment by mike42** [comment]
Hello,

Please start by verifying your print sharing setup outside of PHP.

I'll quote the FAQ, which offers some general advice under the heading ["Why do I get this error when I try to print?"](https://github.com/mike42/escpos-php/blob/4d2db9cdc7cd9b35fbbc62390516a20e4d5f55f2/doc/FAQ.md)

> Start by testing that you can send text to your printer outside of escpos-php. The examples linked to in the README are commented with some commands to get you started.

> Generally, initial setup problems seem to have one of these causes:

> 1. You are writing to the wrong place. Writing to LPT1 does not output to parallel port on Linux, and /dev/ttyS0 is not a serial printer on Windows.
> 2. The printer has not been set up to accept printing the way you expect. This means permissions on Linux, network printers being configured, and shared printers having user accounts and firewalls set up correctly on the print server.
> 3. Your printer actually doesn't work (rare but possible).

In your case, some `net use` and `copy` commands in [example/interface/smb.php](https://github.com/mike42/escpos-php/blob/70bd5a877312f51912718538eecbd38a0f1f7ec8/example/interface/smb.php) should show you the problem to you started:

```
copy test.txt \\PC-01\foo
```

I wont attempt to solve your printer sharing setup, but you basically just keep working on it until you can send text on the command line, then move on to sending it from PHP instead. The `WindowsPrintConnector` with a URL to a shared printer is correct for Windows-to-Windows setups like this.

As a minor point, I'm surprised that this snippet passed without throwing a different error- `WindowsPrintConnector` expects the printer to be specified in a URL-format, as in `smb://PC-01/Printer`.
