### ISSUE TITLE
Using google cloud print

### ISSUE THREAD

**Issue by ahmedmrj** [mike42/escpos-php#224]
Hi, many thanks for this great work,

Is it possible to use this library for printing receipt using a printer connected to google cloud print?

**Comment by mike42** [comment]
I haven't heard of anybody using this setup. If you can get raw data to the printer from the server that runs PHP, then yes.

Could you give an example of a working command to do a raw print from the command-line on your setup? There may be an existing `PrintConnector` that applies.

**Comment by tomyue** [comment]
In China, There are many cloud printer . ESC/POS Printer just connect to the Internet,The printer will be  Request print data automaticly from the internet server. Now ,The question is How to connect print service between Printer(Client) and PHP SERVER in Internet ..

**Comment by mike42** [comment]
@tomyue This question is specific to Google Cloud print- one topic per issue please. You can check [the FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md), and create a [new issue](https://github.com/mike42/escpos-php/issues/new) if the existing answers do not cover your use case.

**Comment by mike42** [comment]
Closing this off, I think the original question is answered.

If anybody uses the driver in such a setup, I'm open to reviewing pull requests for either a Google Cloud print connector, or for extra Google Cloud print documentation.

**Comment by spucheta** [comment]
i send escpos to cloud print via cups
Status: Sorry, CUPS Cloud Print no longer supports printing

cups logs
Sorry, CUPS Cloud Print no longer supports printing                          files directly for security reasons

**Comment by buckneri** [comment]
I see that this was closed off, however, did anyone find an actual solution?

I can print a file to google cloud print using an oAuth connector found here:
[https://github.com/yasirsiddiqui/php-google-cloud-print](https://github.com/yasirsiddiqui/php-google-cloud-print)
however this setup only allows printing from an already existing file and im having a hell of a time tweaking the escpos code and that to submit all the data without actually creating a file.

any direction would be awesome. Thanks.

**Comment by mike42** [comment]
@buckneri - This is closed because the question is answered, not because it works! :)

I actually think that you can trivially modify the `php-google-cloud-print` code to accept data instead of a file.

```diff
diff --git a/GoogleCloudPrint.php b/GoogleCloudPrint.php
index b7652e4..0877577 100644
--- a/GoogleCloudPrint.php
+++ b/GoogleCloudPrint.php
@@ -153,11 +153,11 @@ class GoogleCloudPrint {
         * 
         * @param Job Title $printjobtitle // Title of the print Job e.g. Fincial reports 2012
         * 
-        * @param File Path $filepath      // Path to the file to be send to Google Cloud Print
+        * @param File Content $contents      // Path to the file to be send to Google Cloud Print
         * 
         * @param Content Type $contenttype // File content type e.g. application/pdf, image/png for pdf and images
         */
-       public function sendPrintToPrinter($printerid,$printjobtitle,$filepath,$contenttype) {
+       public function sendPrintToPrinter($printerid,$printjobtitle,$contents,$contenttype) {
                
        // Check if we have auth token
                if(empty($this->authtoken)) {
@@ -169,16 +169,7 @@ class GoogleCloudPrint {
                        // Printer id is not there so throw exception
                        throw new Exception("Please provide printer ID");       
                }
-               // Open the file which needs to be print
-               $handle = fopen($filepath, "rb");
-               if(!$handle)
-               {
-                       // Can't locate file so throw exception
-                       throw new Exception("Could not read the file. Please check file path.");
-               }
-               // Read file content
-               $contents = file_get_contents($filepath);
-               
+
                // Prepare post fields for sending print
                $post_fields = array(
```

And for this library, use a `DummyPrintConnector`, and call `getData` at the end. [Here is an example](https://github.com/mike42/escpos-php/blob/9d4da6a1e3bcbf2428ad70eb772e9ab0dfb22210/example/specific/235-get-data.php).

If you can get this working, then please consider posting a new issue describing the process, and we can add this to the repo as an `example/` script. I would be hesitant to add dependencies on OAuth/HTTP only for this, so a hyptothetical `GoogleCloudPrintConnector` implementation would go in its own repo.
