### ISSUE TITLE
€ Symbol on TM-T88V

### ISSUE THREAD

**Issue by devgiu** [mike42/escpos-php#225]
Maybe this is not related with the lib, but I'm going crazy. Normally I work with General TExt printer, but with this Epson TM-T88V I had to install the drivers. Now, my ticket is printing strange characters and not the € symbol in all places, only in one. I use the same to print this char,  
chr(constant("EUR") where EUR constant is defined:
define("EUR", 0xD5);

But is shown correctly only in orders detail, but not in other places. In header of the ticket I get a ? char too, I don't know here this come from.

Some idea?

In printer configuration I have it as Spanish with several character codifications, with the same result always.

![image](https://cloud.githubusercontent.com/assets/20609976/20345133/059a6f0c-abf6-11e6-886a-d237d9299985.jpeg)

**Comment by mike42** [comment]
Can you share a code snippet so that I can see together how you're setting up the printer, what method you're using to send the Euro character, and what you're sending when the "?" appears at the end?

I'll be more specific if I can see what you're sending, but you'll need to load the correct `CapabilityProfile` for the TM-T88V, send your input as UTF-8, and check that you're not running an older version affected by #209 if that question mark is a "\r" character..

**Comment by devgiu** [comment]
I don't have the printer with me right now, but I will test. about relation with 209 bug,  I think it's this the problem. I will update the library and test all later. 

about capability I will check it too.  But what I don't understand is why euro symbol is OK in detail of the ticket, but not in the footer showing and F instead. And I send it in the same way,  as plain text using the constant explained in my first post.

**Comment by mike42** [comment]
Without the full picture, any attempt to fix this is going to be a stab in the dark.

I'll come back to this once you've posted a code snippet.

**Comment by devgiu** [comment]
Yes, I will come back when I can update library, and do more tests with the printer, but in code, basically this is what I do in ticket detail right now.

`$printer -> text(str_pad ( $ticketjson[$i]->totalLinea .' '. chr(constant("EUR")) , 9 , " " , STR_PAD_LEFT ));`

And this is what I do on footer for "Total" line where a F is shown instead EUR
`$printer -> text("Total: " . $datosTicket['total'] .' '. chr(constant("EUR")));`

**Comment by donsingh** [comment]
Not sure if this helps but I also had similar issue. Problem is with str_pad. Special characters are multibyte so str_pad doesnt count them as 1 byte. (Test by removing str pad and see if it prints ok)

Read more here:
http://stackoverflow.com/questions/11871811/special-characters-throwing-off-str-pad-in-php

**Comment by mike42** [comment]
Closing this off as inactive. If you are interested in improving support for your printer, you may like to consider contributing to our upstream [receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db) (a printer self-test or vendor documentation showing supported code pages for the TM-T88V would be a good start).
