### ISSUE TITLE
unexpected 'use' (T_USE) in file.

### ISSUE THREAD

**Issue by archit0311** [mike42/escpos-php#226]
Maybe this is not related to Library because you have written a complete code. But I am out of help with this. I am using composer and want to use Receipt printer from USB on windows.

Below is the code. Please help me with this. I am trying to run the demo file from the example directory.

```php
try{

require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
// use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\EscposImage;

// $connector = new FilePrintConnector("php://stdout");
$connector = null;
$printer = new Printer($connector);

/* Initialize */
// $printer -> initialize();

/* Text */
$printer -> text("Hello world\n");
$printer -> cut();

/* Line feeds */
$printer -> text("ABC");
$printer -> feed(7);
$printer -> text("DEF");
$printer -> feedReverse(3);
$printer -> text("GHI");
$printer -> feed();
$printer -> cut();
}
catch (exception $e){
  echo $e->getMessage();
}
```

**Comment by mike42** [comment]
This is not the driver, the error message reports that your code is not syntactically correct.

Please do a web search for the error message, which should give you some information about where the `use` statement is valid. A good editor could also draw attention to syntax issues as you write.
