### ISSUE TITLE
Including location to epson driver repo

### ISSUE THREAD

**Issue by donsingh** [mike42/escpos-php#227]
Continuously encountering driver issue and missing COM1/2 connection on Windows 7.

Maybe we can add in the FAQ:

Installation Guide for Windows:
1. ) Identify printer and download drivers at: [Epson-Biz Driver Page](https://download.epson-biz.com/modules/pos/index.php?page=genre&pcat=3)

2. ) If printer is not listed in COM1 or COM2, download and setup the **Virtual Port Driver**.

3. ) Install, Share and Name printer via the "**Devices and Printers**"

4.) Use the ff connector:
```
$printerName = "myprintersnewname";
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
$connector = new WindowsPrintConnector($printerName);
```

**Comment by mike42** [comment]
Great suggestion.

I've got the documentation in the Git repo. Would you be able to submit this as a pull request?

**Comment by donsingh** [comment]
Made pull request.
