### ISSUE TITLE
Unable to "inject" numbers into barcode from PHP

### ISSUE THREAD

**Issue by bryanlurring** [mike42/escpos-php#231]
I'm not sure if I'm doing something wrong but I can't seem to be able to "inject" numbers into a barcode from a PHP variable.

I have this line in my code:
$printer -> barcode($customernumber);

$customernumber is a variable retrieved from the URL using GET. The code prints a receipt but it stops at the barcode and will nut cut (because the cut is after the barcode).

How do I inject a variable number into the barcode?

**Comment by donsingh** [comment]
According to printer.php:
```
/**
     * Print a barcode.
     *
     * @param string $content The information to encode.
     * @param int $type The barcode standard to output. Supported values are
     * `Printer::BARCODE_UPCA`, `Printer::BARCODE_UPCE`, `Printer::BARCODE_JAN13`,
     * `Printer::BARCODE_JAN8`, `Printer::BARCODE_CODE39`, `Printer::BARCODE_ITF`,
     * `Printer::BARCODE_CODABAR`, `Printer::BARCODE_CODE93`, and `Printer::BARCODE_CODE128`.
     * If not specified, `Printer::BARCODE_CODE39` will be used. Note that some
     * barcode formats only support specific lengths or sets of characters, and that
     * available barcode types vary between printers.
     * @throws InvalidArgumentException Where the length or characters used in $content is invalid for the requested barcode format.
     */
    public function barcode($content, $type = Printer::BARCODE_CODE39)
```
Are you sure the value inside $customernumber is valid? Can you show the code involving that variable?

**Comment by bryanlurring** [comment]
$customernumber = $_GET['cn'];

For testing I am using a 4 digit numeric number but this could be any length up to 13 digits when I'm finished but it will always be numeric. Even if I declare the $customernumber = '1234' it still fails to print.

**Comment by bryanlurring** [comment]
Just got it working.

If I declare $content = $customernumber; and then if I change the parameters to this:
$printer -> barcode($content);
It works. So is the only variable name we can put in that field "$content"?

**Comment by donsingh** [comment]
On my end it accepts any kind of variable name as it should. Very odd indeed.
It could be many things like:

-$_GET['cn'] is not passing a number or technically "not a number" until passed to another variable.
-$customernumber is predefined elsewhere

Have you tried type-casting it?

**Comment by mike42** [comment]
The driver doesn't mind what the variables are called, only what their values are.

You said that printing "stopped". I would be checking where errors are being logged- you might have an uncaught `InvalidArgumentException` exception.

PHP has some settings to print errors out directly, which is recommended for development.

For checking the barcodes, I use [zxing/zxing](https://github.com/zxing/zxing) for Android, works a charm

**Comment by mike42** [comment]
Closing this off as OP has solved the problem.

If you think some behaviour may be a bug, please post a self-contained example that shows the issue. Any stack trace (apache error log) an/or binary output (use FilePrintConnector to write to a file) should also be included.
