### ISSUE TITLE
Problem printing QrCode

### ISSUE THREAD

**Issue by stccorp** [mike42/escpos-php#232]
Hello,  While waiting on my Star Micronics TSP100 to arrive, I am using my networked laser printer brother HL2270DW.  I was able to print the first hello world example. But when I tried the qr-code.php , I get the following(please see attached image).  I am not sure how to go about figuring our the problem.  Is it that the printers does not support those codes? will the tsp100 support them?
![opera_2016-11-23_09-54-02](https://cloud.githubusercontent.com/assets/8180135/20566367/d04e7592-b162-11e6-861b-a625f7fcb32e.png)

**Comment by mike42** [comment]
This driver creates binary ESC/POS code, which is understood by many thermal receipt printers. The Brother HL2270DW does only understands conventional page description languages (I use a [PCL 5E driver](https://mike42.me/blog/2014-01-23_brother_hl-2270dw_on_linux) for mine), so the garbage is expected.

A printer similar to yours is known to work with this driver, so you might like to search the bug tracker for experience (see b28a2123025e822216eb034b2434af40c7b463ff).

Generally, there are a few things you will need to know for Star printers.

- Check that ESC/POS emulation is enabled
- You may need to use something like phpqrcode if QR codes don't work out of the box (#208) -- there's a good chance the command is different to the one implemented here.
- Be sure to load the "SP2000" [CapabilityProfile](https://github.com/mike42/escpos-php/tree/b28a2123025e822216eb034b2434af40c7b463ff#using-a-capabilityprofile). If you ever get garbage printed, file bugs back here and we'll make you a profile that's specific to the TSP100.
