### ISSUE TITLE
Simulate POS Printing

### ISSUE THREAD

**Issue by sequeiradenzil** [mike42/escpos-php#233]
Is there are way to simulate the working of a POS printer without owning a physical device.. Please help..

**Comment by mike42** [comment]
Having access to the hardware is still the best way to go. There aren't any simulators that I can suggest.

In the context of this driver, you can can print the binary data to a file (`FilePrintConnector`), which can be inspected with [this parser](https://github.com/mike42/escpos-snippets/tree/master/parser). I find this useful for development.

Outside of that, there are some commercial products that claim to be able to parse ESC/POS and produce graphical output, but I don't know how good they are.
