### ISSUE TITLE
Help needed for database values to print

### ISSUE THREAD

**Issue by Serteralp** [mike42/escpos-php#234]
/* Information for the receipt */
$fatura_cek = mysql_query("SELECT * FROM stok_hareketleri INNER JOIN stoklar ON stok_hareketleri.sth_stok_kod = stoklar.sto_RECno WHERE stok_hareketleri.sth_fatura_no = '".$_REQUEST['sth_fatura_no']."'");
$satir_sayisi = mysql_num_rows($fatura_cek);
while ($fatura_al = mysql_fetch_array($fatura_cek)){
	$sth_stok_kod = $fatura_al['sth_stok_kod'];
	$sth_adet = $fatura_al['sth_adet'];
	$sth_tutar = $fatura_al['sth_tutar'];
	$sto_isim = $fatura_al['sto_isim'];
	
	$items = array(
    new item("Example item #1", "4.00"),
	);
}

At this part how can i retrieve every rows as an item  which i inserted into mysql table?

**Comment by Serteralp** [comment]
$items = array(
    new item("$sto_isim", "$sth_adet", "$sth_tutar"),
	);

that should be like this but for every row which i inserted into database. So i can print more than one lines of products which is sold.

**Comment by mike42** [comment]
`$items` is an array, so you can [add to it](http://stackoverflow.com/questions/676677/how-to-add-elements-to-an-empty-array-in-php).

**Comment by Serteralp** [comment]
$fatura_cek = mysql_query("SELECT * FROM stok_hareketleri INNER JOIN stoklar ON stok_hareketleri.sth_stok_kod = stoklar.sto_RECno WHERE stok_hareketleri.sth_fatura_no = '".$_REQUEST['sth_fatura_no']."'");
$satir_sayisi = mysql_num_rows($fatura_cek);
while ($fatura_al = mysql_fetch_array($fatura_cek)){
	$sth_stok_kod = $fatura_al['sth_stok_kod'];
	$sth_adet = $fatura_al['sth_adet'];
	$sth_tutar = $fatura_al['sth_tutar'];
	$sto_isim = $fatura_al['sto_isim'];}
	
$items =  array();
$items[] = $sto_isim;
$items[] = $sth_adet;
$items[] = $sth_tutar;

Like this retrieving the last inserted row again. Can you helpl about the right way?

**Comment by Serteralp** [comment]
$fatura_cek = mysql_query("SELECT * FROM stok_hareketleri INNER JOIN stoklar ON stok_hareketleri.sth_stok_kod = stoklar.sto_RECno WHERE stok_hareketleri.sth_fatura_no = '".$_REQUEST['sth_fatura_no']."'");
$satir_sayisi = mysql_num_rows($fatura_cek);
while ($fatura_al = mysql_fetch_array($fatura_cek)){
$sth_stok_kod = $fatura_al['sth_stok_kod'];
$sth_adet = $fatura_al['sth_adet'];
$sth_tutar = $fatura_al['sth_tutar'];
$sto_isim = $fatura_al['sto_isim'];}

$items = array();
$items[] = $sto_isim;
$items[] = $sth_adet;
$items[] = $sth_tutar;

Like this retrieving the last inserted row again. Can you help about the right way?

**Comment by Serteralp** [comment]
$fatura_cek = mysql_query("SELECT * FROM stok_hareketleri INNER JOIN stoklar ON stok_hareketleri.sth_stok_kod = stoklar.sto_RECno WHERE stok_hareketleri.sth_fatura_no = '".$_REQUEST['sth_fatura_no']."'");
$satir_sayisi = mysql_num_rows($fatura_cek);
while ($fatura_al = mysql_fetch_array($fatura_cek)){
	$items[] = $fatura_al['sto_isim'];
	$items[] = $fatura_al['sth_adet'];
	$items[] = $fatura_al['sth_tutar'];
	$items[] = "\n";
	}

I can retrieve all rows from database now in this way. But in this style all values are sticked to each other.
Printing like this for example:

"Coca Cola 330 ml14.00"         in stead of      "Coca Cola 330 ml            1       4.00"

Anything i can do for giving spaces between product name, number of pieces and price ?

**Comment by Serteralp** [comment]
As a last question is it possible to print from it by webpage?

**Comment by Serteralp** [comment]
I set up my printer ip and configured a port to the printer. So how can i communicate to the printer? 
i tried this way : require __DIR__ . '/pos/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
/* Fill in your own connector here */
$connector = new NetworkPrintConnector("212.252.100.74", 9100);

But got error. Any help abou this you can do?

Thanks.

**Comment by mike42** [comment]
It looks like you are working with the [receipt-with-logo.php](https://github.com/mike42/escpos-php/blob/6da47bf3320134432940f2f5f0a6edfb175b85b9/example/receipt-with-logo.php) example. If you follow the code, you will find that this just prints text in the end, ie. `$printer -> text("Words words words\n");`. You can assemble your own string an print it in the same way.

For the second query, please see the FAQ entry "[Why do I get this error when I try to print?](https://github.com/mike42/escpos-php/blob/6da47bf3320134432940f2f5f0a6edfb175b85b9/doc/FAQ.md#why-do-i-get-this-error-when-i-try-to-print)" for some debugging tips.

I wont address the parts of this question which do not relate to the `espos-php` API. You will need to seek your own resources for writing your application code.

**Comment by hendryres** [comment]
sorry i tried to answer @Serteralp question, the meaning might be like this:

$items[] = new item($fatura_al['sto_isim'], $fatura_al['sth_adet'], $fatura_al['sth_tutar']);

it works..
