### ISSUE TITLE
New Star Cloud Printer

### ISSUE THREAD

**Issue by stccorp** [mike42/escpos-php#235]
Hello,  I just bought a Star TSP650IIcloudPRNT(hasnt arrived yet). Although It could be use as a normal printer, I want to use the cloud functionality.  Basically I  created a php file to handle 3 methods, POST, GET and DELETE. Basically the printer ask, is there a job, I return true or false, then if there is a job, the printer does a GET.  For example, if I am going to return a png file, I will do something like as part of my GET:
  http_response_code(200);
  header("Content-type: image/png");
  $im = imagecreatefrompng("assets/ttemplate.png");
  etc,etc,etc
  imagepng($im);
 imagedestroy($im);

I think this will work except for the fact  that just generating a png will not work for me. I need to generate multiple sections(cut between them)  in just one print.  So my question is, how can I use the library to instead of writing to a printer directly allow me to get all the commands(esc/p) into a variable or a stream, so I can return all the  ESC/P commands as part of the GET?

maybe something like:

$buffer = '';
$connector = new BufferConnector($buffer);
$printer = new Printer($connector);
/* Initialize */
$printer -> initialize();
etc,etc
$printer->cut();
$printer->close();

  http_response_code(200);
  header("Content-type: text/plain");
  echo $buffer or printer->stream();//something that gets me all the commands?????

Thank you

**Comment by mike42** [comment]
Sure.

You can use the `FilePrintConnector` with a temp file, then [fpassthru](http://php.net/manual/en/function.fpassthru.php), or you can use the `DummyPrintConnector` from the unit tests as below.-

```php
<?php
/*
 * Example showing how to return binary data back to the user.
 * 
 * This is intended for the "Star TSP650IIcloudPRNT" printer.
 */
require __DIR__ . '/../../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\DummyPrintConnector;
use Mike42\Escpos\CapabilityProfile;

// Make sure you load a Star print connector or you may get gibberish.
$connector = new DummyPrintConnector();
$profile = CapabilityProfile::load("TSP600");
$printer = new Printer($connector);
$printer -> text("Hello world!\n");
$printer -> cut();

// Get the data out as a string
$data = $connector -> getData();

// Return it, check the manual for specifics.
header('Content-type: application/octet-stream');
header('Content-Length: '.strlen($data));
echo $data;

// Close the printer when done.
$printer -> close();
```

**Comment by stccorp** [comment]
Thank you.  I will try it as soon I get my printer

**Comment by mike42** [comment]
Closing off, assuming this is solved.

Please open a new issue if you find any bugs!
