### ISSUE TITLE
Load image from variable and not from file

### ISSUE THREAD

**Issue by stccorp** [mike42/escpos-php#237]
How can I load a dynamically generated image from a variable and not from a file? Thank you
Ex:

my_img1 = imagecreate( 576, 200 ); 
$my_img2 = imagecreate( 576, 300 ); 

 
$ticket = EscposImage::load( $my_img1);//How??
$coupon = EscposImage::load( $my_img2);//How??

$printer = new Printer($connector);
$printer -> graphics($ticket);
$printer -> cut();
$printer -> graphics($coupon);
$printer -> cut();
$printer -> close();

**Comment by mike42** [comment]
Great question. Hopefully this fills you in.

`EscposImage` is library-agnostic, so it never deals with Imagick or GD objects directly.

In your case, it looks like you are using GD, so you would have to directly instantiate a `GdEscposImage` to work with.

I think it's something like:

```php
$foo = new GdEscposImage();
$foo -> readImageFromGdResource($im);
```

Or for Imagick users:

```php
$foo = new ImagickEscposImage();
$foo -> readImageFromImagick($im);
```

I recommend using Imagick if you can get it installed, I've used some tricks to make the conversion to ESC/POS many times faster than the Gd implementation ([FAQ](https://github.com/mike42/escpos-php/blob/b79a8050cdb0a0314e7d87253b62ca39eb4a4be6/doc/FAQ.md#why-is-image-printing-slow)).

**Comment by stccorp** [comment]
Well, It did not work for me.  But I think it has to do with compatibility., Any ideas?  I am calling the printer directly for now just to test the image part.

`require 'autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\GdEscposImage;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\CapabilityProfile;

$connector = new NetworkPrintConnector("192.168.0.24", 9100);
$profile = CapabilityProfile::load("TSP600");
$printer = new Printer($connector);

$ticketim = imagecreatefrompng("assets/ticket.png");

$ticketEscPosIm = new GdEscposImage();
$ticketEscPosIm -> readImageFromGdResource($ticketim);

$printer = new Printer($connector);
$printer -> graphics($ticketEscPosIm);
$printer -> cut();
$printer -> close();
`

![badpicture](https://cloud.githubusercontent.com/assets/8180135/20823707/a85352b0-b824-11e6-8424-024eb2a8cb9b.jpg)

**Comment by stccorp** [comment]
I am not able to print a single image, with or without the profile. Even using the standard load functionality

$connector = new NetworkPrintConnector("192.168.0.24", 9100);
//$profile = CapabilityProfile::load("TSP600");
$printer = new Printer($connector);

$tux = EscposImage::load("output.png", false);
$printer -> graphics($tux);

**Comment by mike42** [comment]
Hmm could be compatibility.

Could you try dropping `graphics()` from the mix? (Only works on Epson).

Ie, try-

```php
$tux = EscposImage::load("output.png", false);
$printer -> bitImageColumnFormat($tux);
```

Or-

```php
$tux = EscposImage::load("output.png", false);
$printer -> bitImage($tux);
```

**Comment by stccorp** [comment]
No, it did not. Just so you know this works perfect but has nothing to do with this library. This is communicating by the web service.

                http_response_code(200);
                header("Content-type: image/png");
                $im = imagecreatefrompng("assets/coupon.png");
                imagepng($im);
                imagedestroy($im);

I will think this tsp650 should be compatible with tsp100 which is pretty standard. Any ideas?

**Comment by mike42** [comment]
Yep, one more thing to check.

This driver speaks ESC/POS, while Star printers listen for a different protocol by default. Can you confirm that your printer has been set to [ESC/POS mode](http://www.starmicronics.com/absolutefm/absolutefm/afmviewfaq.aspx?faqid=72)?

**Comment by stccorp** [comment]
Just my luck.  The printer only has a web configuration tool.  At the device information screen I get MANUFACTURER: B
COMMAND SET: STAR
MODEL: TSP654 (STR_T-001)
CLASS: PRINTER

There is not much you can configure. Only network stuff.

**Comment by stccorp** [comment]
http://www.starmicronics.com/support/download.aspx?type=5&tabText=StarESC/POS®%20Mode%20Command%20Specifications&path=../support/Mannualfolder/escpos_cm_en.pdf&referrer=http://www.starmicronics.com/support/default.aspx?printerCode=TSP650&id=0

I found that document here:
http://www.starmicronics.com/support/sdkdocumentation.aspx

It says that esc/p works woth my printer tsp650II

**Comment by stccorp** [comment]
Can you suggest a LAN printer that I can go out and buy today that will work with the library? I loved the idea of the cloud printer, but if I have to configure the firewall to pass connect the web server with the printer, I will do that.

**Comment by mike42** [comment]
I wrote this driver originally for the Epson TM-T82II ethernet variant, so you would get the best compatibility with the Epson TM-series.

Failing that, anything that understands ESC/POS is fine (huge list in the README, or ask your retailer), and if you have a spare raspberry pi, any printer can be a network printer ;)
