### ISSUE TITLE
Hyphens not appearing in CODE93 barcode

### ISSUE THREAD

**Issue by ckrempe** [mike42/escpos-php#248]
I try to create a barcode with a string containing a hyphen:

$printer->barcode("RS-20160000927", Printer::BARCODE_CODE93);

The printer doesn't print it with hypen, only alpha an numeric signs.

Any idea?

**Comment by mike42** [comment]
- Which make and model of printer do you have?
- Can you share a picture of the output? (I'll compare to my TM-T20II.)

Wikipedia suggests that [CODDE93](https://en.wikipedia.org/wiki/Code_93) supports hyphens, so it may be a bug in either the driver or the printer.

**Comment by ckrempe** [comment]
I use an Epson TM-J7500-P.
There is no output of the barcode "RS-20160000927" at all.

**Comment by ckrempe** [comment]
It't not a problem of the hypen, but of the length of the barcode that should be generated.
Thanks for support!
