### ISSUE TITLE
Change private to protected property of misc functions

### ISSUE THREAD

**Issue by manitu-opensource** [mike42/escpos-php#249]
Can you please change the "private" property of the following functions to "protected" in order to allow derived classes to call them?

```
 class Printer

     // ...
     private static function dataHeader(array $inputs, $long = true)

     // ...
     private static function intLowHigh($input, $length)
```

**Comment by mike42** [comment]
Thanks for the suggestion. I've made this change, and it will be available in the next minor release.

If you're working on new extensions to the code, then I'm open to reviewing any of your changes as pull requests, please see the [contributing guide](https://github.com/mike42/escpos-php/blob/development/CONTRIBUTING.md) if this interests you.
