### ISSUE TITLE
Printing From a Shared windows printed

### ISSUE THREAD

**Issue by ahmedali5530** [mike42/escpos-php#25]
Hi @mike42 , my question is that if i want to use a shared printer from within the network, then which connector should i use?

**Comment by ahmedali5530** [comment]
OK i used the FilePrintConnector, and resolved.

**Comment by mike42** [comment]
Sure, glad this worked.

In case anybody else ends up here from Google, using the FilePrintConnector method to hook up to a shared printer is specific to windows-to-windows setups

First you map it:

    # Check net use command for extra authentication options
    net use LPT1 \\computer\printer

Then in escpos-php, use the `FilePrintConnector` to hook up to the mapped printer, or connect directly using the share name as a path:

```php
$connector = new FilePrintConnector("LPT1");
$connector = new FilePrintConnector("\\\\computer\\printer");
```

----

The `WindowsPrintConnector` is the suggested option, though, as it hooks into system printing for you in a system-agnostic way, and gives much better errors when things don't work.

This lets you hook up to a windows-shared printer from Linux servers also:

```php
$connector = new WindowsPrintConnector("smb://computer/printer");
```

The `smb://` format takes many options, such as `smb://user:password@name/workgroup/printer`.
