### ISSUE TITLE
Printer does not close if there are only a few lines or characters 

### ISSUE THREAD

**Issue by nitinsbuzz** [mike42/escpos-php#251]
I am printing using Ubuntu 14.04, CUPS connector and EPSON TM-T20 thermal printer. When I try to print less than 12 lines (with characters), printer is not closed (pulse is not sent and no receipt is printed). 
Even though the close command does not work, the text and feed commands are sent successfully which turn up on the next successful print (with more characters and lines). There are no errors or warnings in the logs.

Is there a minimum number of lines or characters required for printing to work?

**Comment by mike42** [comment]
Could you post a minimal code sample that demonstrates the issue? I have similar enough hardware that I can try to replicate.

**Comment by nitinsbuzz** [comment]
Hi Mike,

Everything works as expected. I created a method to print receipts and it works on two different printers (with a few small adjustments even works on almost all desktop printers without drivers).

There are is one bug which i encountered several times but i cannot solve it. 

There are two parts to the bug.

The first bug comes up when previous print fails, some characters are missing on the 2nd print. Sometimes the positioning of the text is incorrect (after presumably 3rd consecutive fail). You get a very long print with each seperate character of a string under each other.
A good addition would be a Full reset function before every new print. Else an extra check if close function is called successfully. Maybe possible to use a callback to confirm if close is called but not executed.

The second part of the bug can be related to the first. When i try to print the following, print fails. When I uncomment the last two lines from "Bedankt voor uw bezoek..." The print works perfectly on the second time (after 1st print is missing some characters).

`
    use Mike42\Escpos\PrintConnectors\CupsPrintConnector;
    use \Mike42\Escpos\Printer;

    $connector = new CupsPrintConnector($printerName);
    $this->printer = new Printer($connector);
    //$printer -> initialize();

    $printer -> text(
	'Name of shop' .  "\n"
        . 'Street name and number 66'
        . "\n"
        . 'Postode City Mallname Leidschendam'
        . "\n"
        . 'Tel.: 050 44444 44'
        . "\n"
        //. 'BEDANKT VOOR UW BEZOEK EN GRAAG TOT ZIENS!'
        //. "\n"
    );
    // One final feed before printing
    $printer->feed();
            
    $printer -> cut();
            
    //Open Cashbox
    $printer -> pulse(
           0,
           120,
           240
     );
     $printer -> close();`

Tried single and double quotes around string, trim(), printer -> initialize(), in try and catch, hiding first part of string, and trying to print 2nd sentence

**Comment by nitinsbuzz** [comment]
Would it be faster to translate all input into one feasible low kb image internally for the printer to print as an image? Store it in a buffer, instead of allowing the user to send each input text directly to the printer. Could be less prone to user errors. Just an idea.

**Comment by nitinsbuzz** [comment]
How about moving the printing to the background option: for linux:

http://stackoverflow.com/questions/45953/php-execute-a-background-process

**Comment by mike42** [comment]
Image printing may change the output.

I've attempted this on a TM-T20II and cannot replicate. I'm on Debian / CUPS, and the USB printer is installed using the "Generic - Text Only" driver.

```
<?php
require __DIR__ . '/autoload.php';
use Mike42\Escpos\PrintConnectors\CupsPrintConnector;
use Mike42\Escpos\Printer;

$printerName = "EPSON_TM-T20";

$connector = new CupsPrintConnector($printerName);
$printer = new Printer($connector);

$printer -> text(
    'Name of shop' .  "\n"
    . 'Street name and number 66'
    . "\n"
    . 'Postode City Mallname Leidschendam'
    . "\n"
    . 'Tel.: 050 44444 44'
    . "\n"
    //. 'BEDANKT VOOR UW BEZOEK EN GRAAG TOT ZIENS!'
    //. "\n"
);
// One final feed before printing
$printer->feed();
        
$printer -> cut();
        
//Open Cashbox
$printer -> pulse(
       0,
       120,
       240
 );
$printer -> close();
```

**Comment by mike42** [comment]
Closing this off as I can't replicate.

Please post a new issue with the extra debugging issue if you believe this can be fixed from `escpos-php`.
