### ISSUE TITLE
bitImage can't justify center

### ISSUE THREAD

**Issue by bp64531** [mike42/escpos-php#260]
Hi,
I've tried your code and it works! (I'm using TaffWare POS-58 printer).
My printer doesn't support graphics() command, so I use bitImage() command. The image shows but it always justify left. Do you know how to make it center?

Thanks!

**Comment by mike42** [comment]
Does `bitImageColumnFormat()` work for you? Images printed like this behave more like text.

We have seen a similar issue before #96 (on a different printer), while Epson printers honour the alignment for both images and text.

**Comment by mike42** [comment]
Closing this off it's known that some printers have this limitation, linked issue has more tips that work around it.

(We've also got TaffWare POS-58 tracked as Zjiang printer, I think it's the same printer sold under a few names)
