### ISSUE TITLE
Zebra ZD420 HostStatus

### ISSUE THREAD

**Issue by MHaendel** [mike42/escpos-php#264]
Hey,

I use this lib on a BIXOLON just fine and I am currently working on getting this to work with my ZD420. I did get it to work with ESCPOS commands and it prints just fine. But right after the printout the printer appends `~HS` two times. I already tried substring the data but this is not the cause. I think this is the command for the HostStatus? How to get rid of it?

**Comment by mike42** [comment]
This driver doesn't append `~HS`, so I'm fairly sure you have another gremlin int he system.

Could you post-

- A description of your platform and interface
- A complete "hello world" snippet showing how you interact with the printer

if I saw this on one of my setups, I would be checking that there isn't a BIXOLON vendor driver lurking somewhere in the print pipeline.
