### ISSUE TITLE
Xprinter ak-234

### ISSUE THREAD

**Issue by uday-pop** [mike42/escpos-php#265]
Does it support for Xprinter ak-234 ?

**Comment by mike42** [comment]
I'd like to know too. Please test it out and get back to us!

The new FAQ entry [I have Printer X. Can I use this driver?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver) contains a bit more detail.
