### ISSUE TITLE
Network Printer - 30 sec timeout to use printer again

### ISSUE THREAD

**Issue by miroslav-cada** [mike42/escpos-php#273]
Hi there,

I have issue with network printing. Everything is fine unless I want to print again in time shorter than 30 sec. I did some quick testing of that with simple script bellow and when i run script 1st time it prints line, if I hit script in 40 seconds interval everything works fine. But when I will run script 1st time, and then let say after 15 seconds, on that try it doesn't print and i get not any error or exception and also it looks like then it resets timer to wait another 30 seconds. Its looks like its opens socket, and doesn't in close it even PHP script ends and 30 seconds is some kind of time out. I did some experiments with max execution time in PHP settings, but its looks like it has no impact on that at all.

So my problem is that I can't use same printer immediately and need to wait 30 seconds.

Printer: BIXOLON SRP 275IIC

Test script:

```
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;

try {

    $connector = new NetworkPrintConnector('192.168.1.20', '9100');

    $printer = new Printer($connector);

    $printer -> text("Hello World!\n");
    $printer -> cut();
    
    $printer -> close();

} catch (Exception $e) {

    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
```

Best Regards
Miroslav

**Comment by JayzeeHuang** [comment]
Try add  usleep(10000) before printer close

**Comment by mike42** [comment]
This is an interesting question. I have not observed the same behaviour on a networked Epson (see, [this code](https://github.com/mike42/Auth/blob/master/lib/misc/ReceiptPrinter.php) has been running for years with no problems), so this may be printer specific.

Aside, note that the connection will not be explicitly closed if an exception is thrown, which is the first thing to look at. A `finally` block would help there.

Next, you might want to jump on the command-line to see if you can observe the connection status with `netstat` or `tcpdump`, or see how your printer responds when `netcat` is used to send a few receipts. I'm open to reviewing any requests that convert [NetworkPrintConnector.php](https://github.com/mike42/escpos-php/blob/c4e2b8ec2f5e83794a118ba430208bccfb49a753/src/Mike42/Escpos/PrintConnectors/NetworkPrintConnector.php) to use PHP's `socket_*` fucntions, if this changes the open/close behavior.
