### ISSUE TITLE
Printer Issue

### ISSUE THREAD

**Issue by wilayats** [mike42/escpos-php#275]
Hi 

I have two printer Citizen which have two different name  share in the local network 

like 
**smb://computer1/printer1**  _are server computer (Where Xampp Install)_
**smb://computer2/printer2** _(Client Computer  when access the server computer  such like this http://computer1/myproject)_

but Computer1 is server 

on computer1 printer worked

but computer2 it will generate error like **failed to copy to printer**

how can i fixed that problem.

**Comment by mike42** [comment]
Most likely, you are either printing to the wrong place, or your setup does not accept print jobs the way you expect.

Please check out [Why do I get this error when I try to print?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#why-do-i-get-this-error-when-i-try-to-print) in the FAQ.
