### ISSUE TITLE
Parallel Port Issue

### ISSUE THREAD

**Issue by Jubi11** [mike42/escpos-php#277]
Hello, I have an strange problem using parallel port connection. My printer (Epson TM-U220) works fine, I have tried, for example, printing from notepad and other software and It works fine. But the problem is when I try to use escpos with parallel port. I get the next error:

       "Warning: file_put_contents() expects parameter 1 to be a valid path"

I don't know why because I tried testing the parallel port with command line and it works perfectly.

         echo "Hello World!!" > LPT1 (this works perfect using command line)

I don't know if the problem is the operative system ( Windows XP Pro SP3) or if there is a problem with the shared printer...

I was thinking the problem is the Windows XP because I can't use command line to connect to a printer that is shared, for example:
                   
             net use \\ComputerName\PrinterName 
Command above sends that I can't access to network location even if the printer is already shared.

But the thing is why if this command works:
      
              echo "Hello World!!" > LPT1

The next code don't work? :

    <?php
    require __DIR__ . '/../../autoload.php';
    use Mike42\Escpos\Printer;
    use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
    $connector = new WindowsPrintConnector("LPT1");
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    /* Close printer */
    $printer -> close();
   ?>

PHP file shows this:

          Warning: file_put_contents() expects parameter 1 to be a valid path

I have already tried the permission thing and a huge of stuff and nothing. 
I have used escpos in the past but using windows 7 and windows 10 and only with usb printers.

Thank you so much.

**Comment by mike42** [comment]
I'll make a note to check the connector code, could be a bug.

Can you try using `new FilePrintConnector("LPT1")`? It's a simpler way of doing the same.

**Comment by Jubi11** [comment]
@mike42 You are awesome.  `FilePrintConnector("LPT1")` resolved the problem.
Thank you for the help and thank you for escpos.

**Comment by karthickyathav** [comment]
@mike42 i am using EPSON TM-T81 model receipt printer i tried your php library for printing when i run the script with the correct port of the printer it returns blank page with no error but i cannot see any receipt coming out of my printer. do u have php library for EPSON TM-T81 receipt printer???
