### ISSUE TITLE
Help: Which PrintConnector to use for my situation

### ISSUE THREAD

**Issue by Mwangangi** [mike42/escpos-php#278]
I was developing a CodeIgniter application within a Linux environment and everything worked perfectly(1 Computer, 1 Application, and  1 Thermal Printer). I am deploying the Web App to an intranet(1 server, 3 client PCs, 3 Thermal printers i.e one for each PC). The Server and all Clients are running on Windows. I have tried to use the NetworkConnector by providing the IP address of the client PC making the request but nothing seems to work. Anyone who's been through this before? Kindly help...

**Comment by JayzeeHuang** [comment]
Firstly, you should know php is server side language. You connot do anything unless the printers at the same network as your server. (server and printers must connect to the same wifi). If you are trying to print from clients at the same wifi, the IP address just simply point to the printer ip address. If trying to print from different wifi, you will need to setup client side socket to the printer ip address not from the server side.

**Comment by Mwangangi** [comment]
@JayzeeHuang thank you! I was able to get a solution around it. I had to buy thermal printers with Ethernet capabilities and then connected them in the same network as the server PC and the rest worked like charm. Thumbs up @mike42 for the awesome library. It works with Codeigniter BTW!
