### ISSUE TITLE
print from html failed

### ISSUE THREAD

**Issue by ihussain1024** [mike42/escpos-php#285]
Hello,
I am trying to use the print-from-html.php example. And I am getting this error.
" Command wkhtmltoimage failed: /usr/local/bin/wkhtmltoimage: 1: /usr/local/bin/wkhtmltoimage: Syntax error: ")" unexpected ".
I am not understanding why this error comming.

Any help will be appreciated
Thanks

**Comment by JayzeeHuang** [comment]
It saids syntax error, just check the grammar, symbols or something else on your code.

**Comment by mike42** [comment]
This error is not coming from PHP, please do a web search for 'wkhtmltoimage Syntax error: ")" unexpected'.

Please direct wkhtmltoimage queries to a more appropriate project, you shod be able to return to this snippet once you have fixed your setup.
