### ISSUE TITLE
Daisy Fiscal Devices Support

### ISSUE THREAD

**Issue by Mendim** [mike42/escpos-php#286]
Hello.i want integration of the Daisy Devices.is this possible
http://en.daisy.bg/products

**Comment by mike42** [comment]
This may be answered already in the FAQ as [I have printed get X. Can I use this driver?](https://github.com/mike42/escpos-php/blob/c4e2b8ec2f5e83794a118ba430208bccfb49a753/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver), please take a look.

**Comment by mike42** [comment]
It's not obvious from a web search whether these printers support ESC/POS, please try it out and let us know.

The 'simple' profile mentioned in the README is best for testing out new printers.
