### ISSUE TITLE
USES FOR NEW USER

### ISSUE THREAD

**Issue by tomatoe45** [mike42/escpos-php#288]
Can anyone here tell me how to  use this great features.. how can we apply this to  production..

**Comment by mike42** [comment]
This is a PHP library which allows developers to write scripts that generate binary ESC/POS code, which is understood by some thermal receipt printers. If you are a PHP developer, and you need to generate binary ESC/POS code in your scripts, then you may be able to use it.

Please read through the README[1], it should give you an idea of whether this driver is suitable for your setup, and what the first steps are to use it.

[1] https://github.com/mike42/escpos-php/blob/development/README.md
