### ISSUE TITLE
Output raw commands at close in debug mode

### ISSUE THREAD

**Issue by nitinsbuzz** [mike42/escpos-php#295]
Would it be the possible to add a debug mode so that all commands are printed on screen instead of sending it to the printer for debugging purposes?

**Comment by mike42** [comment]
The raw output is not human readable, but you could always use a different print connector in your application to achieve this. Eg, `FilePrintConnector("php://output")` goes to the screen/page, so-

```
if($debug) {
    $connector = new FilePrintConnector("php://output");
} else {
    $connector = new NetworkPrintConnector($printerIpAddress, 9100);
}
```

When I need to check which commands are being sent, I currently use a `FilePrintConnector` to write the output to a file, and then read it with either `hexdump` or the ESC/POS parser that I've got on GitHub.
