### ISSUE TITLE
How us FeedForm(). Paper Lenght

### ISSUE THREAD

**Issue by bryandavidt** [mike42/escpos-php#297]
I have a EPSON TMU-220 and y need to set the Paper Lenght and make the cut at the end. Can somebody help me?

**Comment by mike42** [comment]
`feedForm()` releases paper from ticket printers.

If you are looking to activate the auto-cutter, you may want to check out the [cut()](https://github.com/mike42/escpos-php/blob/b03b99ee21b2f772cbde696068726568efb68b1a/README.md#cutmode-lines) command. It can optionally feed a few lines if you need blank space.

**Comment by bryandavidt** [comment]
The problem is that I have a paper with a predefined size. The paper size is: width=7,4cm - lenght=14cm, with ESC-POS is possible to fix the paper size and that the cut is always done at the end of the previously predefined size, Ie all receipts are always cut in 21 cm.

**Comment by mdestafadilah** [comment]
@bryandavidt it's solved?

**Comment by mike42** [comment]
I did some reading on this, you can define a fixed size with page mode, which we don't implement. See #216.

So "can't be done" is the answer for now, and I'll close this off.
