### ISSUE TITLE
Graphical output - Print logo

### ISSUE THREAD

**Issue by sysxlabs** [mike42/escpos-php#3]
Hi Mike, 

I am writing for another enhancement, I have a NV Logo uploaded to the printer memory, now I want to print that logo... If this functionality is already provided then I want to know the syntax for it.

When I send print from windows, the NV Logo is printed, but when I tried to print with this code, the NV Logo is not printing.

Thanks

**Comment by mike42** [comment]
Hi sysxlabs,

This feature is not currently available, but I'll take and see what would be required to add it. So that I can pull up the specs for it, what model printer you're testing this with?

**Comment by sysxlabs** [comment]
I am using EPOS TEP 220M. This printer is compatible with ESC/POS Commands

**Comment by sysxlabs** [comment]
Still Waiting for the update on this enhancement. I used this library on my EPOS TEP 220M and it's working beautifully.... but now stuck in this one issue... I am waiting for this library to get updated ASAP.

**Comment by dudwig** [comment]
Maybe this article helps a bit:
http://nicholas.piasecki.name/blog/2009/12/sending-a-bit-image-to-an-epson-tm-t88iii-receipt-printer-using-c-and-escpos/

**Comment by mike42** [comment]
Hey all, Unfortunately, I don't currently have access to a printer to do an implementation for this, so it's not likely to be done in the next few months.

It's definitely possible/worthwhile/well documented, and I'm happy to accept any pull requests which add the functionality.

**Comment by mike42** [comment]
While I wait for an Epson TM T20 to code proper bitmap uploads with, sysxlabs, could you checkout the testing branch and see if this test function works on your printer?

    $escpos -> image_nv_print_test()

**Comment by mike42** [comment]
Basic image support is now available- you can print a local PNG file from the computer. NV graphics are not quite as straightforward, so I'll leave this feature request open.

You currently need GD to manipulate the images (package php5-gd in Debian).

Documentation:
- https://github.com/mike42/escpos-php#graphicsescposimage-image-size

Usage examples:
- https://github.com/mike42/escpos-php/blob/master/example/graphics.php
- https://github.com/mike42/escpos-php/blob/master/example/receipt-with-logo.php

And if it doesn't work with your printer, the older bitImage() command is also there as a fallback:
- https://github.com/mike42/escpos-php/blob/master/example/bit-image.php

For the NV graphics, there are several ways to upload and print them (older bitImage and newer graphics commands). I've made some progress on saving & printing bit images from NV memory, but the results are not satisfactory. So at the moment, I would suggest a direct print-from-PNG approach.

**Comment by sysxlabs** [comment]
perfecto... this works like a charm

**Comment by mike42** [comment]
Good to hear.

Does the EPOS TEP 220M work with both graphics() and bitImage()?

**Comment by mike42** [comment]
Closing this one. NV graphics still not implemented but original enhancement was added.
