### ISSUE TITLE
Not installed on laravel 5.4

### ISSUE THREAD

**Issue by achalj09** [mike42/escpos-php#300]
can you please upgrade to compatable for laravel 5.4

**Comment by Stenerson** [comment]
Hi @achalj09,
Can you provide some additional details? What's making this library incompatible with Larvel? Are you getting errors? Is there any other information that could help us understand what specific issues you're having?

Thanks!

**Comment by achalj09** [comment]
Hello @Stenerson 

Thank you for quick your reply.

I have installed laravel 5.4 also for token authorisation I have used Laravel Passport so after passport installation if we installed your Plugin it gives error see in screen shot

![untitled](https://cloud.githubusercontent.com/assets/8180139/23330667/84941dd0-fb79-11e6-9a46-47fd5bf8e416.png)
 
Please check it out, it might be guzzle version problem.

Thank You.

**Comment by achalj09** [comment]
Also I installed it new fresh project of laravel, it successfully installed but after that Laravel Passport is not installed for guzzle version problem. See the screen shot

![untitled](https://cloud.githubusercontent.com/assets/8180139/23330707/cb7f66cc-fb7a-11e6-9ab9-8ff4ff23e116.png)

**Comment by Stenerson** [comment]
Hi @achalj09,
Thanks for the additional information. It looks like the version of guzzle that we're dependent on (used in the ApiConnector) is a little out of date which is causing your issue. 

We'll probably need @mike42 to weigh in. I'm not familiar with guzzle so I'm not sure if it can easily be updated or allow multiple versions.

**Comment by achalj09** [comment]
Hello @Stenerson 
Thanks for your comments, my issue is not solve yet, I am eagrly waiting to comment of @mike42 for guidence

**Comment by Stenerson** [comment]
@achalj09, a few ideas...

- Install the library manually instead of using composer. This isn't ideal but if you need it urgently it would work. You could always switch back to use composer when this is addressed. 
- Fork this repo and update the guzzler dependency to 6.6.2. Then you can import your repo from composer. 

These options would at least buy you some time to test, etc. on your project until we hear from @mike42. If you went with the second option you could even test the API connector and submit a PR with the updated composer.json file. Just a thought 😉

**Comment by mike42** [comment]
Marking this as a bug. The guzzle dependency is too strict, and needs to be widened or made optional.

The `ApiConnector` was only added in the most recent release, so `mike42/escpos-php v1.4.2` should avoid the issue if you want to get running immediately.

**Comment by Stenerson** [comment]
> The 'ApiConnector' was only added in the most recent release, so 'mike42/escpos-php v1.4.2' should avoid the issue if you want to get running immediately.

This is a much better suggestion than either of mine! 😂 
Thanks @mike42

**Comment by achalj09** [comment]
Hello @mike42 and @Stenerson thank you for your comments.

And finally its installed and wok fine with v1.4.2

Although current version have same problem.

Thanks once again both of you !!!

**Comment by mike42** [comment]
The fix has now been released as 1.5.1.

I don't use Laravel myself but the dependencies are now much more relaxed. I'll close this off in a few days if there's no reports that it's still broken.
