### ISSUE TITLE
Printer support : EPSON Epson TM-T82 (LAN,Thai)

### ISSUE THREAD

**Issue by polppol** [mike42/escpos-php#301]
EPSON Epson TM-T82 + LAN Model
bought in Thailand
work with this lib.

Also support Thai printout using
example/character-encodings.php

![2017-02-20_10-12-46](https://cloud.githubusercontent.com/assets/1213568/23110601/29133d10-f755-11e6-9fff-bef57cdb2f82.png)

**Comment by sunry2ntkh** [comment]
this your country charator please try this
CS_THAI2 45 【Thai 2】
CS_CP856 46 CP856
CS_CP874 47 CP874

**Comment by polppol** [comment]
Im able to print Thai out-of-box without config anything
just
`
$connector = new NetworkPrintConnector("192.168.1.207", 9100);
$profile = DefaultCapabilityProfile::getInstance();
$printer = new Printer($connector, $profile);
$printer -> initialize();//reset format
$printer -> text("ภาษาไทย and English Text here\n");
$printer -> close();
`

**Comment by sunry2ntkh** [comment]
now you still face that problem?

**Comment by polppol** [comment]
No, I don't have any problem with both Thai and English

**Comment by mike42** [comment]
Thanks for posting this information, this should be useful to future readers.

I don't think there is anything I need to change in the driver or documentation here, so I'll close this off.
