### ISSUE TITLE
Printer support

### ISSUE THREAD

**Issue by imranniaz** [mike42/escpos-php#302]
Hi,

We are using brothers thermal printer, which is not supported in the list, if you add the support for this, it would be great.

Thanks

Imran Niaz

**Comment by mike42** [comment]
Please check with the vendor documentation that your printer understands ESC/POS, and simply try it out. Nobody has tested a Brother ESC/POS printer yet, so there is no way of knowing whether it already works fully, or needs a special profile for the advanced features.

Please see the FAQ entry [I have Printer X. Can I use this driver?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver) for more detail.
