### ISSUE TITLE
Print PDF 

### ISSUE THREAD

**Issue by Tatandiaz13** [mike42/escpos-php#304]
Hi,

How can I avoid printing blanks at the end when printing a PDF, because when this space is wasted paper is wasted:

example:

[ticket.pdf](https://github.com/mike42/escpos-php/files/791508/ticket.pdf)

```php
function printPDF($printName,$fileName){
try {
       $connector = new WindowsPrintConnector($printName);
       $route='\resources';
       $pdf = __DIR__.$route.'\\'.$fileName;
       $printer = new Printer($connector);
    $pages = ImagickEscposImage::loadPdf($pdf,550);
    foreach ($pages as $page) {
    $printer -> graphics($page, 2|0);
           }
    $printer -> cut();

} catch (Exception $e) {
 echo $e -> getMessage() . "\n";}
finally{
    $printer -> close();
}
```

**Comment by mike42** [comment]
The driver is probably behaving correctly by printing the whitespace you've sent it. You need to either create the PDF without unwanted blank space, or remove the whitespace before printing.

Not sure if it's available on your server, but your ticket could be cropped if you ran it through eg. `pdfcrop` first-

```bash
pdfcrop ticket.pdf ticket-cropped.pdf
```

[ticket-cropped.pdf](https://github.com/mike42/escpos-php/files/816205/ticket-cropped.pdf)

Or if you still need a bit of a margin:

```bash
pdfcrop --margin 10 ticket.pdf ticket-cropped-10.pdf
```

[ticket-cropped-10.pdf](https://github.com/mike42/escpos-php/files/816206/ticket-cropped-10.pdf)
