### ISSUE TITLE
Printer support: EPSON TM-T20II

### ISSUE THREAD

**Issue by maserna06** [mike42/escpos-php#306]
Hello,
I am using EPSON TM-T20II, do you currently have support for this printer?
Thank you.

**Comment by Hountez** [comment]
as i see in escpos-php/example/specific/32-german-tm-t20-ii-custom-command.php it should work.
I will test it next time I have the chance to.

**Comment by maserna06** [comment]
Ohh, I can See, 

Thanks.

**Comment by mike42** [comment]
Assuming this is answered.

I use the similar TM-T20 w/ USB from Debian, using a `FilePrintConnector`, and it's a very capable printer. Please post a follow-up issue if you find any bugs!
