### ISSUE TITLE
Help me please.My connection result : Failed to print. Command "smbclient'.... 

### ISSUE THREAD

**Issue by panda211** [mike42/escpos-php#309]
My connection result > Failed to print. Command "smbclient'//computername/printer' -c'print -' -N" failed with exit code -1:

How i resolve its?

**Comment by mike42** [comment]
It appears that you need to troubleshoot your print setup. There is not enough information here about what your setup is, or how you've verified it outside of PHP to point you in the right direction yet.

Please begin by reading through [Why do I get this error when I try to print?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#why-do-i-get-this-error-when-i-try-to-print) in the FAQ. This should guide you through the basics.
