### ISSUE TITLE
Font handling in ImagePrintBuffer

### ISSUE THREAD

**Issue by mike42** [mike42/escpos-php#31]
An error is given if Microsoft fonts are not installed.

Fonts should be configurable, with a public domain, widely available internationalised font being the default

**Comment by haqvsla** [comment]
![image](https://cloud.githubusercontent.com/assets/22507385/18931099/ce2d12e4-85db-11e6-9914-e250de69d25d.png)

How to fix this

**Comment by mike42** [comment]
@haqvsla This issue is closed, and your post is not about missing Microsoft fonts.

Please research how to install Imagick on XAMPP, and file any follow-up questions about escpos-php as a new issue.
