### ISSUE TITLE
58MM Portable MINI Thermal Printer

### ISSUE THREAD

**Issue by meshileya** [mike42/escpos-php#312]
I am trying to make use of this printer, but i am getting this error 

> Warning: copy(\\HP-PC\58MM Portable MINI Thermal Printer): failed to open stream: No such file or directory in C:\xampp\htdocs\escpos\escpos-php-development\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372
> Couldn't print to this printer: Failed to copy file to printer

at my own end...what can i do pls??

**Comment by meshileya** [comment]
NOTE: i also tried using the USB001, still getting same error.

> Warning: copy(\\HP-PC\USB001): failed to open stream: No such file or directory in C:\xampp\htdocs\escpos\escpos-php-development\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372
> Couldn't print to this printer: Failed to copy file to printer

**Comment by meshileya** [comment]
Warning: copy(\\HP-PC\POS-58): failed to open stream: No such file or directory in C:\xampp\htdocs\escpos\escpos-php-development\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372
Couldn't print to this printer: Failed to copy file to printer.

**Comment by meshileya** [comment]
it worked already...had to share the printer

**Comment by mike42** [comment]
Cheers, thanks for sharing the solution.

**Comment by AwadMaharoof** [comment]
Helped me out too! Thank you for sharing the solution

**Comment by makgr** [comment]
it not working for me. mike42. help please
![2](https://user-images.githubusercontent.com/19414854/56787693-25dc9a00-681f-11e9-81fb-7e612d130e40.PNG)
![Capture](https://user-images.githubusercontent.com/19414854/56787694-25dc9a00-681f-11e9-95ae-c0d75afc1088.PNG)

**Comment by thullyrico** [comment]
It works good on my laptop that runs windows 10 but it shows this "Warning: copy(\HP-PC\58MM Portable MINI Thermal Printer): failed to open stream: No such file or directory in C:\xampp\htdocs\escpos\escpos-php-development\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372
Couldn't print to this printer: Failed to copy file to printer" when I'm running it on another desktop that runs on Windows 8. Does this library need some different configurations per Computer or what, I'm confused guys please help

**Comment by yahyanasser** [comment]
> Cheers, thanks for sharing the solution.

what is the solution ? i can't see it

**Comment by InternetFacilito** [comment]
Lo solucioné compartiendo la impresora y copiando exactamente el nombre de la impresora al configurar en el controlador.

```
$nombreImpresora = "EPSON TM-T20II Receipt";
$conector = new WindowsPrintConnector($nombreImpresora);
$impresora = new Printer($conector);
```
