### ISSUE TITLE
Please Help print from PDF

### ISSUE THREAD

**Issue by jhoey7** [mike42/escpos-php#313]
`<?php
    require 'autoload.php';
    use Mike42\Escpos\Printer;
    use Mike42\Escpos\ImagickEscposImage;
    use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
    $connector = new WindowsPrintConnector("Receipt printer");
    $printer = new Printer($connector);
    $pdf = 'resources/document.pdf';
    try {
        $pages = ImagickEscposImage::loadPdf($pdf);
        foreach ($pages as $page) {
            $printer -> graphics($page);
        }
        $printer -> cut();
    } catch (Exception $e) {
        /*
         * loadPdf() throws exceptions if files or not found, or you don't have the
         * imagick extension to read PDF's
         */
        echo $e -> getMessage() . "\n";
    } finally {
        $printer -> close();
    `}``

but i always get retrun loadPdf requires imagick extension.
Thank you before

**Comment by jhoey7** [comment]
``

**Comment by jhoey7** [comment]
problem above has been completed, but i get new problem like this

exception 'ImagickException' with message 'PDFDelegateFailed `The system cannot find the file specified. ' @ error/pdf.c/ReadPDFImage/801' in

**Comment by mike42** [comment]
This is an issue with your ImageMagick setup. Please take a look at the relevant resources for the package that is throwing the error. A web search turns up plenty of information ([eg. this StackOverflow question](http://stackoverflow.com/questions/32466112/imagemagick-convert-pdf-to-jpeg))

Closing this issue off, as this issue tracker is not the correct place to get support for dependencies like ImageMagick.
