### ISSUE TITLE
Connect to printer using URI - determine connection type from scheme

### ISSUE THREAD

**Issue by mike42** [mike42/escpos-php#314]
Idea from #240 - write some new code in `PrintConnector` to accept a URI, then return different implementations based on the scheme used.

```php
$foo = new PrintConnector::get("file:///dev/usb/lp0"); // FilePrintConnector
$foo = new PrintConnector::get("tcp://x.y.z.w:9100/"); // NetworkPrintConnector
$foo = new PrintConnector::get("ipp://foobar/"); // CupsPrintConnector
$foo = new PrintConnector::get("smb://windows/printer"); // creates a WindowsPrintConnector
```

This will facilitate storing a connection string in a database etc.

**Comment by evsar3** [comment]
@mike42 I made a new file called UriPrintConnector.php with it's class that implements exacly this. I'm not so good with git repositories so, I'm attaching the file then you can review and possible merge with the original project. Not tested with all protocols.

[UriPrintConnector.zip](https://github.com/mike42/escpos-php/files/1353488/UriPrintConnector.zip)

**Comment by evsar3** [comment]
Usage:

    $foo = UriPrintConnector::get("file:///dev/usb/lp0");
    $foo = UriPrintConnector::get("file:///home/foo/bar.txt");
    $foo = UriPrintConnector::get("tcp://127.0.0.1");
    $foo = UriPrintConnector::get("tcp://127.0.0.1:8080");
    $foo = UriPrintConnector::get("ipp://foobar");
    $foo = UriPrintConnector::get("smb://windows/printer");
    $foo = UriPrintConnector::get("usb://printer");
    $foo = UriPrintConnector::get("com://COM1");
    $foo = UriPrintConnector::get("ltp://LTP1");

**Comment by alvarobreton** [comment]
I want to handle it on an aws ec2 server, how can I connect a printer?
Ubuntu 20.04
