### ISSUE TITLE
Turkish character output on GP-F80300II

### ISSUE THREAD

**Issue by shenol** [mike42/escpos-php#319]
What should I do to print Turkish characters?

> ş ü ö İ ğ ı ç

```php
<?php
header('Content-Type: text/html; charset=utf-8');
require __DIR__ . '\vendor\autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

try {
    
    $connector = new WindowsPrintConnector("ADS");
    $printer = new Printer($connector);
    $printer -> text("Pijamalı hasta, yağız şoföre çabucak güvendi.\n");
    $printer -> cut();
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
```

**Comment by mike42** [comment]
Could you let me know what type of printer do you have, whether it supports a code page which can encode Turkish characters, and what output you got when you ran this snippet?

The list of code pages can usually  be found in the vendor documentation by printing a self-test page.

**Comment by shenol** [comment]
![whatsapp image 2017-03-17 at 16 42 15](https://cloud.githubusercontent.com/assets/477091/24045692/901e8afa-0b28-11e7-9713-c7596ffbd95e.jpeg)

printer: [](http://gprinter.hk/pos-printers-f80300ii.html)

**Comment by mike42** [comment]
Ok. As a quick check, I don't think printer can print Turkish characters. Your best bet would be one of these these legacy code pages-

- https://en.wikipedia.org/wiki/ISO/IEC_8859-9
- https://en.wikipedia.org/wiki/Code_page_857

But the vendor documentation I found lists these pages:

| # | Page |
|---|---|
| 0 | PC437 [U.S.A.Standard Europe] |
| 1 | Katakana |
| 2 | PC850:Multilingual |
| 3 | PC860:Portuguese |
| 4 | PC863 [Canadian French] |
| 6 | PC865:Nodic |
| 7 | Greek |
| 8 | Hebrew |
| 9 | PC755:East Europe |
| 10 | Iran |
| 16 | WPC1252 |
| 17 | PC866:Cyrillic 2 |
| 18 | PC852:Latin2 |
| 19 | PC858 |
| 20 | IranII |
| 21 | Latvian |

(Source: [GP-80XXX Programmer Manual v6](http://www.gprinter.es/download/program-manual/80mm-thermal-printer-program-manual.pdf))

So to print these characters, you would need to use a work-around that involves generating images with a Unicode font. A user recently had the same problem printing Vietnamese, so you will find some great information on the issue tracker already.

I'll add a link here once that work-around is in the FAQ.

Also, if I post the script to do it, would you be willing to post back the contents of a few of these code pages to help me identify them?

**Comment by shenol** [comment]
Of course I can send it.

**Comment by shenol** [comment]
Sound check :)

**Comment by mike42** [comment]
Going to close this off as there isn't anything much we can do here.

- It's not in the FAQ, but #254 is a good reference for printing characters by by rendering them on the computer and sending them as an image.
- I've posted in the `escpos-printer-db` for a profile for this printer, which will improve encoding if somebody wants to write it.
- [This is how you can print the contents of each code page](https://mike42.me/blog/2018-05-how-to-print-the-characters-in-an-esc-pos-printer-code-page). Using that example, `php escpos-character-tables.php 0 1 2 3 4 6 7 8 9 10 16 17 18 19 20 21 > foo.bin` will generate a printable binary file for these code pages. A picture would be useful at receipt-print-hq/escpos-printer-db#40.
