### ISSUE TITLE
Print in a network printer that shared name contains white spaces

### ISSUE THREAD

**Issue by leolr02** [mike42/escpos-php#320]
Hi, I tryed to print in a local network a receipt, but the shared name of the printer contains white spaces, is possible print a receipt with that name?, the printer is an USB EPSON MT Series and the PC is bassed on windows 7 Professional. Some suggestion please?

**Comment by mike42** [comment]
I have previously used this driver with a printer shared as ["Receipt Printer"](https://mike42.me/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows) on Windows 7, so spaces are no trouble.

Could you outline a bit more information about your setup? Eg,

- some commands to show how you've verified that you can send raw data to your printer from your server
- which OS PHP is running on
- a code snippet of what you're attempting
- what sort of output you get when you attempt to print

**Comment by leolr02** [comment]
Sorry for the late response, I tryed on cmd with this command: 
print /D:"\\CapitanLarry\EPSON TM-T20 BARRA CAPITAN L.ARRY"
but i was unnable to print to that printer, I running this library on PHP 7 in a local server with XAMPP 
my code is something like that: 
```
public function printTestPage ($host, $printer, $type) {
        $response = null;
        try {
            $config = new ControlPanel(NULL);
            $response = $config->getBasicInfo();
            if (trim(mb_strtoupper($type, 'UTF-8')) == "USB") {
                $connector = new WindowsPrintConnector("smb://".$host."/".$printer);
                $printer = new Printer($connector);
                $printer -> setJustification(Printer::JUSTIFY_CENTER);
                $printer ->selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
                $printer -> text('--IMPRESIÓN DE PRUEBA--');
                $printer ->selectPrintMode();
                $printer -> feed();
                $printer -> text("============================================\n");
                $printer -> feed();
                if (count($response) > 0) {

                    $printer->text($response[0]['encabezado']);
                    $printer->feed();
                }
                for ($i = 0; $i < 10; $i++) {
                    $printer
                        -> text("============================================\n");
                }
                if (count($response) > 0) {
                    $printer->text($response[0]['pie']);
                    $printer->feed();
                    $printer -> text("============================================\n");
                }
                $printer -> feed(2);
                $printer -> cut();
                $printer -> close();
                $response = "Success|<span class='fa fa-info-circle cyan-text is-right-5'></span>Se ha impreso un ticket de prueba";
            }
        } catch (Exception $e) {
            $response = "Error|<span class='fa fa-times-circle red-text is-right-5'></span>Ocurrió un error al imprimir la página de prueba, causa: ".$e->getMessage();
        }
        return $response;
    }
```
As you can see the code in very simple, I send my params since another php script that retrieves the database data and call this function,  the snippet runs fine on printers without white spaces like EPSONTM20, regards :)

**Comment by Stenerson** [comment]
Is it `throw`ing when trying to instantiate a new `WindowsPrintConnector` or  `Printer` with the whitespace named printer?

**If yes**: What's the exception that's being thrown (output of `$e->getMessage()`)?
**If no**: What is the experienced behavior/error messages?

**Comment by leolr02** [comment]
I think that error is throwing when I initialize WindowsPrintConnector, because when I run the command on **cmd** shows me this error: `Unnable to initialize device`, and on **PHP**  `shows me failed to copy to printer`, I read that i need to replace the white spaces for %20 but the problem still persist.

**Comment by Stenerson** [comment]
That's where I would have expected to see it throwing.

I don't have any experience working with this driver (or the supplies to test it) but I thought I'd try to get this information in the issue in case anyone has seen it before.

Is there any way to send data to the shared printer outside of this library to ensure that the network itself properly handles the routing of the share name with spaces? (Sorry, I'm grabbing at straws here, just something I'd probably try if possible)

**Comment by Stenerson** [comment]
Actually... in the [link](https://mike42.me/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows) that @mike42 shared above there is an example of how to print without the library.

In `cmd.exe`
```
echo "Hello World" > testfile
print /D:"\\CapitanLarry\EPSON TM-T20 BARRA CAPITAN LARRY" testfile
del testfile
```

If this doesn't work then it's not something within this library. If that does work, we'll need to dig a little deeper here.

**Comment by leolr02** [comment]
Yeah, actually we work with another program (based in Visual Basic) with the same LAN Network, and works well, and I tried to print to this printer in cmd with the same command and throws error. Maybe be a connection error I will try to solve this problem and if I solved i'll post here.
Thanks anyway :)

**Comment by mike42** [comment]
Looks like this wasn't a driver issue, I'll close this off.
