### ISSUE TITLE
EPSON TM-T20II,

### ISSUE THREAD

**Issue by Gerardonv** [mike42/escpos-php#321]
CAN U ADD EPSON TM-T20II  OR ANY MODEL EC-LINE  FOR EXAMPLE EC LINE EC-PM-80320-USB

**Comment by canorioss** [comment]
Yo estoy trabajando con Epson TM-T20II y funciona muy bien. Trabajo con ubuntu server, la impresora la he conectado mediante USB.


I'm working with Epson TM-T20II and it works great. I work with ubuntu server, I connected the printer via USB.

**Comment by sebastianbonilla** [comment]
@canorioss puedes proveer mas informacion acerca de como te pudiste connectar con la impresora? Estoy tratando de usar `$connector = new FilePrintConnector("usb://EPSON/TM-T20III?serial=583741542995820000");` pero  se genera un error.
```
fopen(): Unable to find the wrapper "usb" - did you forget to enable it when you configured PHP?
```
I'm using MacOS 14

Could you please provide more details about how to connect to the printer? I'm using `$connector = new FilePrintConnector("usb://EPSON/TM-T20III?serial=583741542995820000");` but I'm getting an error.
```
fopen(): Unable to find the wrapper "usb" - did you forget to enable it when you configured PHP?
```
Estoy usando MacOS 14

**Comment by InternetFacilito** [comment]
> @canorioss puedes proveer mas informacion acerca de como te pudiste connectar con la impresora? Estoy tratando de usar `$connector = new FilePrintConnector("usb://EPSON/TM-T20III?serial=583741542995820000");` pero se genera un error.
> 
> ```
> fopen(): Unable to find the wrapper "usb" - did you forget to enable it when you configured PHP?
> ```
> 
> I'm using MacOS 14
> 
> Could you please provide more details about how to connect to the printer? I'm using `$connector = new FilePrintConnector("usb://EPSON/TM-T20III?serial=583741542995820000");` but I'm getting an error.
> 
> ```
> fopen(): Unable to find the wrapper "usb" - did you forget to enable it when you configured PHP?
> ```
> 
> Estoy usando MacOS 14

Hola @sebastianbonilla, soy Canorioss pero con otro perfil, este es el que utilizo ahora para todo lo referente a la programación y con las Tecnologías de la Información.

La verdad es que no he tenido la oportunidad de trabajar con servidores en MacOS, de hecho ni en el desarrollo o programación he utilizado Mac.
Mi pregunta es: Utilizarás un servidor MacOS para alojar tu proyecto cuando pase a producción?
Porque es importante saber desde el principio que los conectores son diferentes para cada sistema operativo, al menos es lo que me ha ocurrido a mi trabajando desde Windows y pasando a producción en servidor Ubuntu (LINUX).
Lo digo porque si estas desarrollando ahora en tu laptop (MacOS) y después pasarás a Linux, tendrás el mismo problema que yo, que no funciona el conector.

Como te comentaba, no he configurado para MacOS, pero mirando la documentación veo que en primer lugar no se han realizado pruebas o nadie ha contribuido con ese tipo de conexión. Lo puedes ver aquí [Ver enlace](https://github.com/mike42/escpos-php/blob/master/README.md#compatibility).

Sin embargo esta probada la opción `Ethernet` y `CUPS Hosted`. Esta ultima opción creo es mas parecida a la forma en que tu estas intentando conectar. [Ver enlace](https://github.com/mike42/escpos-php/blob/master/example/interface/windows-usb.php).
Desconozco si en Mac funciona pero creo que deberías probar con este ejemplo [Ver](https://github.com/mike42/escpos-php/blob/master/example/interface/cups.php)

Te comento que, en Windows esta forma de conectar es similar.
En el ejemplo de la documentación se muestra esta linea:
`$connector = new CupsPrintConnector("EPSON_TM-T20");`
En mi caso, desde Windows estoy utilizando `$connector = new CupsPrintConnector("TM-T20II");` porque `TM-T20II` es el nombre real que yo le di a mi impresora cuando la instalé y la configuré. Además es importante mencionar que la impresora debe estar compartida públicamente para poder acceder a ella (verifica si ese es tu problema también).

Ojalá esto te ayude, te repito no he trabajado desde MacOS y no tengo equipo de esa marca. soy pobre :( 

Pdta.. No agrego traducción para no hacer tan extenso el mensaje y evitar problema de cantidad de caracteres en el mensaje... se que puedes traducir con google translate :)  espero saber que lo lograste pronto...

Te adjunto unas capturas
![1](https://github.com/mike42/escpos-php/assets/123510787/bb331237-e624-425c-b61b-18a64939039b)
![2](https://github.com/mike42/escpos-php/assets/123510787/77d194e1-ce8e-4b38-8e3c-c703b1f3b678)
![3](https://github.com/mike42/escpos-php/assets/123510787/0a7bedcf-4ada-4ff7-90f2-4de6fa06ca1c)

**Comment by InternetFacilito** [comment]
> @canorioss puedes proveer mas informacion acerca de como te pudiste connectar con la impresora? Estoy tratando de usar `$connector = new FilePrintConnector("usb://EPSON/TM-T20III?serial=583741542995820000");` pero se genera un error.
> 
> ```
> fopen(): Unable to find the wrapper "usb" - did you forget to enable it when you configured PHP?
> ```
> 
> I'm using MacOS 14
> 
> Could you please provide more details about how to connect to the printer? I'm using `$connector = new FilePrintConnector("usb://EPSON/TM-T20III?serial=583741542995820000");` but I'm getting an error.
> 
> ```
> fopen(): Unable to find the wrapper "usb" - did you forget to enable it when you configured PHP?
> ```
> 
> Estoy usando MacOS 14

@sebastianbonilla, ésta es una segunda respuesta pero es con respecto al uso del conector desde Linux.
Veo que hay mas similitud entre MacOS y Ubuntu (o derivados de lLnux).

En este servidor, cuando se conecta la impresora, se crea un archivo en `/dev/usb/` con un nombre variable pero normalmente si es solo una impresora, el nombre será algo como `lp0` quedando la ruta al archivo así: `/dev/usb/lp0`.
Entonces, cuando necesitas conectar a la impresora con la librería de Mike42, necesitas hacer algo como lo siguiente:
`$connector = new FilePrintConnector("/dev/usb/lp0")`.

Pero si la impresora esta apagada o desconectada, ese archivo no se encontrará y tu sistema explotará haha. Por esta razón debes hacer un par de comprobaciones previas como te muestro en la siguiente captura..

![4](https://github.com/mike42/escpos-php/assets/123510787/b2ceb528-4d18-4ff7-8465-f36ab2cbb5a0)

**Comment by EduardVidalTulsa** [comment]
English translation draft
I was not able to connect directly to my printer across php has http user
so i do some tricks to success
1st i generate just a out.lp file to then concat to /dev/usb/lp(0,1)
In this post i put some code what i developed for find € sing and count how
many chars it can be writed in each line depending on my (for now) 3 types
of  escpos printers
(every time i need to buy other, last model is not available)
i hope it help to someone

Haz desde el terminal file /dev/usb/lp0 a ver que TE da
tiene que ser special character
yo hago algo asi para imprimir
reviso que /dev/usb/lp0 o lp1 sean la impresora antes de enviar el proceso
de impresión
el truco para saber si es vuestra impresora o no lo tenéis en udevadm info
filtrando el product
Tengo una dymo labelwriter también en la misma máquina y alguna vez la
impresora es lp1 o lp0
function ticket_print_command($filename){
       //production mode?
       $tipo_arxiu = shell_exec("udevadm info -a -n /dev/usb/lp0 | grep
product");
       if (preg_match('/Receipt Printer/', $tipo_arxiu))
               exec ("cat {$_SERVER['DOCUMENT_ROOT']}/scale/$filename
>/dev/usb/lp0");
       else {
       $tipo_arxiu = shell_exec("udevadm info -a -n /dev/usb/lp1 | grep
product");
               if (preg_match('/Receipt Printer/', $tipo_arxiu))
                       exec ("cat
{$_SERVER['DOCUMENT_ROOT']}/scale/$filename >/dev/usb/lp1");
        }
}
mi codigo receipt.php
phpgeneral/receipt.php

──(dc.,de febr.28)─┘
<?php
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\EscposImage;

if($receipt_printer_model=="citizen 2000"){
       //citizen
       $euro=213;//a citizen 213
       $taula=2;//a citizen 2
       $fcap=184;//184
       $f2=8;//'41'
       $f3=9;
       $fref=40;//40
       $llpreus=66;//66
       $lldescompte=48;//48
       $llref=25;//25
       $llrecepta=49;
       $llates=49;//49
       $maxespais=64;
       $atencio="ATENCIÓ: Les bosses compostables fan que el\nproducte
torrat perdi el cruixent\n";
}
if($receipt_printer_model=="csi 100"){
//      die;
       //csi 100
       $euro=128;//a citizen 213
       $taula=16;//a citizen 2
       $fcap=177;//184
       $f2=8;//'41'
       $f3=9;
       $fref=8;//40
       $llpreus=58;//66
       $lldescompte=42;//48
       $llref=30;//25
       $llrecepta=49;
       $llates=43;//49
       $maxespais=56;
       $atencio="ATENCIÓ: Les bosses compostables fan que\n el producte
torrat perdi el cruixent\n";

}
if($receipt_printer_model=="NP-350"){
//      die;
       //csi 100
       $euro=128;//a citizen 213
       $taula=16;//a citizen 2
       $fcap=184;//184 font de la capçalera
       $f2=8;//'41'
       $f3=9;
       $fref=8;//40
       $llpreus=66;//66 caracters del que tingui el mateix numero de font
(factura ... preus data)
       $lldescompte=48;//48
       $llrecepta=49;
       $llref=30;//25
       $llates=49;//49 longitut atés per
       $maxespais=64; //aixo si que es llpreus
       $atencio="ATENCIÓ: Les bosses compostables fan que el pro-\nducte
torrat perdi el cruixent\n";

}

if (!extension_loaded('mbstring'))debugtelegram("Aquest servidor no té
mbstring habilitat, pots habilitar-ho a php.ini?",$_SERVER['HTTP_HOST']);

class Printerfestuc extends Printer{
       public function line($v){
               $this -> selectPrintMode('1');
               global $decimalsing,$thousandsing,$euro,$taula,$maxespais;
               $this-> setJustification(Printer::JUSTIFY_LEFT);
               $linea="{$v['urlde']} ";
               if($v['lotnumber']!='')$linea.="Lot: {$v['lotnumber']} ";
               if($v['bulk']==0)$num1=number_format_trim($v['units'],3,$decimalsing,$thousandsing);

               else
$num1=number_format($v['units'],3,$decimalsing,$thousandsing);
               $num1.=$v['u']."
".number_format($v['cost'],2,$decimalsing,$thousandsing).chr($euro)."/{$v['u']}
";
               if($v['discount']>0)$num1.='-'.number_format_trim($v['discount'],2,$decimalsing,$thousandsing).'%
';
               if($v['tax_detall']==1){
                       $num1.='IVA
'.number_format_trim($v['IVA'],2,$decimalsing,$thousandsing).'% ';

if(($v['EQUIVALENCY_CHARGE']>0)&&($_SESSION['Empresa']['sell_wholesale']==1))

                               {$num1.='RE
'.number_format_trim($v['EQUIVALENCY_CHARGE'],2,$decimalsing,$thousandsing).'%
';}

$num1.=number_format($v['Base'],2,$decimalsing,$thousandsing).chr($euro);

               }
               if($v['tax_detall']==0)$num1.=number_format($v['tline'],2,$decimalsing,$thousandsing).chr($euro);

               if (extension_loaded('mbstring')) {
                        $espaisocupats = mb_strlen($linea, 'UTF-8') +
mb_strlen($num1, 'UTF-8');
               }
               else {
                       $espaisocupats = strlen($linea) + strlen($num1);
               }
       //      debugtelegram("$linea \n strlen: " . strlen($linea) +
strlen($num1) . ", mb_strlen: " . mb_strlen($linea, 'UTF-8')+
mb_strlen($num1, 'UTF-8')." espaisocupats=$espaisocupats",
$_SERVER['HTTP_HOST'
]);
       //      $espaisocupats=strlen($linea)+strlen($num1);
               $espaisblancs=$maxespais-$espaisocupats;
               if ($espaisocupats>=$maxespais){
                       $text="$linea\n";
                       $num1=str_pad($num1,$maxespais,' ',STR_PAD_LEFT);
               }
               else $text=str_pad($linea, $maxespais-strlen($num1));
               $this->text($text);
               $this -> selectCharacterTable($taula);
               $this ->textRaw($num1);
               $this -> selectCharacterTable();
               $this -> text("\n");
               /*$this -> selectPrintMode();
               $this->text("{$maxespais}=".strlen($num1));
               $this->text("+".strlen($linea)."+{$espaisblancs}=");
               $this ->text(strlen($text).'+'.strlen($num1)."\n");*/
       }
       public function euro(){
               global $taula;
               $this -> selectCharacterTable($taula);
           $chars = str_repeat(' ', 256);
           for ($i = 0; $i < 255; $i++) {
               $chars[$i] = ($i > 32 && $i != 127) ? chr($i) : ' ';
           }
               //return($chars[$euro]);
               $this->textRaw($chars[$euro]);
               $this -> selectCharacterTable();
       }
}
function customWordWrap($string, $width) {
   $words = explode(' ', $string);
   $output = '';
   $line = '';

   foreach ($words as $word) {
       if ((strlen($line) + strlen($word)) < $width) {
           $line .= $word . ' ';
       } else {
           $output .= trim($line) . "\n";
           $line = $word . ' ';
       }
   }
   $output .= trim($line);
   return $output;
}


Parte del codigo de tiquet.php que genera el archivo que luego hago cat
hacia /dev/usb/lp0
<?php
require_once('login.php');
// imprimeixo tiquet
if($login==false){
echo "nologin";
$link->close();
die;
}
require '../vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\EscposImage;
require_once('phpgeneral/receipt.php');

date_default_timezone_set('Europe/Andorra');
// pre($_REQUEST);die;
if($_REQUEST['uuid']==''){$link->close(); header("$scale_uri");}
if(isset($_REQUEST['ID_Empresa']))$ID_Empresa=$_REQUEST['ID_Empresa'];
if(isset($_REQUEST['year']))$year=$_REQUEST['year'];
else $year=date("Y");
$r=detallrelacio($_REQUEST['uuid'],$ID_Empresa,$year,$link);

$taula_index="{$year}_Empresa_{$ID_Empresa}_index_relacio";
// pre($r);die;
/*ALTER TABLE `2021_Empresa_100_index_relacio`
fADD `print` tinyint NOT NULL DEFAULT '0' AFTER `uuid` COMMENT
current_timestamp()';
 */;
if(!mysql1r("SHOW COLUMNS FROM `{$taula_index}` LIKE 'print'",$link,1)){
$crea="ALTER TABLE  `$taula_index` ADD `print` tinyint NOT NULL DEFAULT '0'
COMMENT '".date("D Y/m/d G:i:s")."';";
//mysqli_query($link,"select print from `$taula` ") or
//echo $crea;
try{
mysqli_query($link,$crea);
}catch (Exception $e){
echo "";//ignore error, means print field already exist
}
}
$recopia=mysql1r("select print from $taula_index where
`uuid`='{$_REQUEST['uuid']}'; ",$link);
mysqli_query($link,"UPDATE $taula_index SET `print` = '1' WHERE
 `uuid`='{$_REQUEST['uuid']}'");
$ticket="out.lp";
//debugtelegram($_SESSION['Empresa']);
if ($_SESSION['Empresa']['bool_ticket_printer']=='1'){
try {
$connector = new FilePrintConnector("out.lp");
$printer = new Printerfestuc($connector);
/* Initialize */
$printer -> initialize();
$printer -> selectCharacterTable($taula);
/* Text */
//head:

$printer -> setJustification(Printer::JUSTIFY_CENTER);
if($recopia>0) $printer->text("Reimpresió de tiquet\n\n");
$printer -> selectPrintMode($fcap);
$printer -> text("{$r['Empresa']['termal_head_1']}\n");
$printer -> feed(1);
$printer -> selectPrintMode($f2);
$printer -> text("{$r['Empresa']['termal_head_2']}\n");
$printer -> text("{$r['Empresa']['termal_head_3']}\n");
$printer -> selectPrintMode($f3);
$idrelacio="{$r['tipus_relacio']['Value']}:{$r['Empresa']['ID']}.{$r['ID']}";
if($r['tax_detall']==1){
$preus="PREUS IVA NO INClÒS";//linees actives
}
else $preus="PREUS IVA INClÒS";
$data=" Data:".latindate($r['data']).' '. date("H:i")."\n";
$preus=str_pad($preus,$llpreus-(strlen($idrelacio)+strlen($data)),'
',STR_PAD_BOTH);
$printer->text($idrelacio.$preus.$data);
$printer->feed(1);
$printer -> selectPrintMode();
$printer -> setJustification(Printer::JUSTIFY_CENTER);
if($r['ID_client']>1)$printer -> text("
Client:".urldecode($r['fiscal_name']));
if($r['NIF']!='')$printer -> text(" NIF:".urldecode($r['NIF']));
if($r['fiscal_address']!='')$printer -> text("\nD.
Fiscal:".urldecode($r['fiscal_address'])."\n");
if($r['comercial_name']!='')$printer -> text(" Nom comercial:
".urldecode($r['comercial_name'])."\n");
if($r['deliver_address']!='')$printer -> text(" Direccio entrega:
".urldecode($r['deliver_address'])."\n");
if($r['phone']!='')$printer -> text(" Telèfon:
".urldecode($r['phone'])."\n");
// $printer->feed(1);
$printer -> setJustification(Printer::JUSTIFY_RIGHT);
foreach ($r['active_lines'] AS $v){
$v['tax_detall']=$r['tax_detall'];
$printer->line($v);
}
$printer -> setJustification(Printer::JUSTIFY_LEFT);
$printer -> selectPrintMode();
// $printer -> selectCharacterTable();
$printer->feed(1);
$printer-> selectCharacterTable();
$descompte="-".$r['discount']."%";
if($r['discount']!='0')
$printer->text(str_pad("Descompte:",$lldescompte-strlen($descompte)).$descompte."\n");
unset($detall);
$printer-> selectCharacterTable($taula);
// if($index_relacio['tax_detall']==1){
$base=number_format($r['Base'],2,$decimalsing,$thousandsing).chr($euro);
$printer ->textRaw(str_pad("Base
imponible:",$lldescompte-strlen($base)).$base);
$printer->text("\n");
// }
//arsort($r['IVA'],SORT_NUMERIC);

foreach ($r['IVA'] AS $iva => $v){
if ($v!=''){
$fiva=number_format_trim($iva,2,$decimalsing,$thousandsing);
$v=number_format_trim($v,2,$decimalsing,$thousandsing);
$detall.=" {$fiva}%: $v".chr($euro);
}
}
$iva=str_pad("IVA :",$lldescompte-strlen($detall));

$printer->textRaw($iva.$detall);

// arsort($r['EC']);
if(($r['Empresa']['sell_wholesale']=='1')&&($r['equivalency_charge']==1)){
$printer->text("\nR.E. ");
foreach ($r['EC'] AS $ec => $v){
$v=number_format_trim($v,2,$decimalsing,$thousandsing);
if ($v!='')$printer -> text(" RE {$ec}%:  $v");$printer->euro();
}
}
$printer->feed(1);
$printer-> selectCharacterTable();
$printer -> selectPrintMode($fref);
$apagar="A
Pagar:".number_format($r['Total'],2,$decimalsing,$thousandsing).chr($euro)."\n";
// $printer -> text(str_pad("Ref.:
{$r['activelines']}",$llref-strlen($apagar)));
$printer -> selectPrintMode('56');
   $printer -> setJustification(Printer::JUSTIFY_RIGHT);
$printer -> selectCharacterTable($taula);
$printer -> textRaw($apagar);
$printer -> setJustification(Printer::JUSTIFY_LEFT);
$printer -> selectPrintMode();
$printer -> text(str_pad("Atés per:
{$r['Nom_Venedor']}",$llates-strlen($r['Empresa']['termal_tail_1'])));

$printer -> selectPrintMode('16');
$printer -> text("{$r['Empresa']['termal_tail_1']}");
$printer -> selectPrintMode();
$printer -> text("\n");
$printer-> selectPrintMode('0');
$printer -> text($atencio);
$printer -> setJustification(Printer::JUSTIFY_CENTER);
$printer -> text("Gràcies per la vostra compra\n");
$r['email']=urldecode($r['email']);
if (correuvalid($r['email'])){
$printer -> text("Us hem enviat copia en pdf de la factura a\n
{$r['email']}\n");
}
//linees borrades
if($r['deletedlines']>0){
//$printer -> cut(66);
$printer -> selectPrintMode();
$printer -> text("Linees borrades \n");
foreach ($r['deleted_lines'] AS $v){
$printer -> line($v);
}
}
$printer -> cut();
$printer -> close();
// pre();print_r($r);tpre();
ticket_print_command($ticket);
//debugtelegram($r,$_SERVER['HOST_NAME']."tiquetrelacio",$Empresa['telegram_relacions']);
`rm $ticket -f`;
//echo `cat out.lp`;
  } catch (Exception $e) {
debugtelegram("tiquet.php" . $e -> getMessage() .
"\n",$_SERVER['HTTP_HOST']);
unset ($r['Empresa']);
$rel="{$r['tipus_relacio']['Value']}: $ID_Empresa.{$r['ID']}";
unset ($r['tipus_relacio']);
debugtelegram($r,"{$_SERVER['HTTP_HOST']} ->
$rel:",$_SESSION['Empresa']['telegram_relacions']);
}
}
else {
//la empresa no té impresora de tiquets
unset ($r['Empresa']);
$rel="{$r['tipus_relacio']['Value']}: $ID_Empresa.{$r['ID']}";
unset ($r['tipus_relacio']);
debugtelegram("La empresa no té assignada impresora de
tiquets",$_SERVER['HTTP_HOST']);
debugtelegram($r,"{$_SERVER['HTTP_HOST']} ->
$rel:",$_SESSION['Empresa']['telegram_relacions']);
}
//todo redirigir a a4.php si es el cas
if ($_REQUEST['close'])echo "<script>window.open('', '_self', '');
window.close();</script>";
else header("Location: $scale_uri");
?>
