### ISSUE TITLE
Js client to communicate with this library

### ISSUE THREAD

**Issue by nitinsbuzz** [mike42/escpos-php#323]
Would it be interesting to build a js client (using service worker) to search local network, find server with this library and open websocket or send data to print?

**Comment by nitinsbuzz** [comment]
I have the js script, just need to improve it and allow it connect to server in one instance through an installation script and listen for data to print (on a raspberry cups linux setup)

**Comment by mike42** [comment]
I'm sure it would be interesting to write, but what problem would this setup solve that i not covered by existing print systems?

**Comment by haithem-rihane** [comment]
I came up with an idea to solve client/server issue, i install wamp server on client machine and when i want to print i send ajax request to 127.0.0.1/escpos-php/print.php  contien json data then i parse it and i send it to local printer it work like a charm

**Comment by nitinsbuzz** [comment]
After going through the ApiConnector and heithem-rihane's setup, the only thing i would add is js scan script but on 2nd thought that might not fit with this library. 

@haithem-rihane i am not completely sure, but there is a possibility that you can use php local server built in php7 + rpi for this task. Unless you need mysql. I will be trying it out in the next few days. 

@mike42 thanks for replying and maintaining this library! 

There is only one problem i face regularly. When is switch views (between only pulse OR full receipt print) during succeeding print jobs, the characters get misplaced on the next print. If i maintain the same initial setup, the print works perfectly. 

ps. any possibility you can a debug mode which if set to true, only valid commands / characters are passed through. The rest is filtered and informed to the user.

**Comment by twf-nikhila** [comment]
@haithem-rihane By local printer do you mean the client's printer? If so How do you do it?

Well, we can get print encoded data from the server using ajax, but then in clients side, it will send to the printer connected?

**Comment by twf-nikhila** [comment]
@nitinsbuzz @haithem-rihane :+1: for yours WebSocket & Ajax solution. I'm trying to build a similar solution as per your suggestions, will it be possible to have your JS code open source? That can be a good separate addon for this package and will eventually get improved by the community.

**Comment by nitinsbuzz** [comment]
Will try to upload tomorrow, tested and it works like charm.

**Comment by twf-nikhila** [comment]
I actually ended you developing the server myself, but it will be interesting to see your approach as well @nitinsbuzz

Do put a comment when you have uploaded it. Thank you :)
