### ISSUE TITLE
Print and reverse feed  n  lines

### ISSUE THREAD

**Issue by asoneji** [mike42/escpos-php#324]
I am not sure what reverse feed does? When I use it I don't see any different in the receipt.

from https://github.com/mike42/escpos-php/blob/5400286144e04474e36440f8703ae7737910ac5b/example/demo.php
`$printer -> text("ABC");
$printer -> feed(7);
$printer -> text("DEF");
$printer -> feedReverse(3);
$printer -> text("GHI");
$printer -> feed();`

When I run the above my output is: 
![output](https://cloud.githubusercontent.com/assets/5489067/24213139/b487b55a-0eee-11e7-8c53-60795ba59e2a.JPG)

now if i remove feed reverse:
`$printer -> text("ABC");
$printer -> feed(7);
$printer -> text("DEF")
$printer -> text("GHI");
$printer -> feed();`

my output stays the same.

I am using EPSON TM-T20ii printer with USB on Mac OS.

**Comment by mike42** [comment]
This feature apparently allows some printers to perform multiple passes, either on the paper, or in memory before the FF command is issued to release the page.

Your model of printer does not appear to support reverse feed, and is happy to ignore the command.

**Comment by asoneji** [comment]
@mike42 Thanks!
