### ISSUE TITLE
Can we send escpos binaray to printer?

### ISSUE THREAD

**Issue by asoneji** [mike42/escpos-php#325]
I have created output.bin following example [235-get-data](https://github.com/mike42/escpos-php/blob/development/example/specific/235-get-data.php)

I wondering is there a way I can send output.bin to printer for printing using the escpos-php?

thanks!

**Comment by mike42** [comment]
Yes, you can [write()](https://github.com/mike42/escpos-php/blob/8f08019b3f8d07b41930e3b0af187a6af9fa4145/src/Mike42/Escpos/PrintConnectors/PrintConnector.php#L46) binary data directly to a `PrintConnector`, which is responsible for transporting binary data to a printer. The connector that was used to instantiate the `Printer` can be retrieved through [getPrintConnector()](https://github.com/mike42/escpos-php/blob/8f08019b3f8d07b41930e3b0af187a6af9fa4145/src/Mike42/Escpos/Printer.php#L572).

The `Printer` class needs to handle bad input without allowing injection attacks, and does not have a similar method.

**Note**: You should only use this to send data that has been generated from `escpos-php`. If you have your own files, you are on your own as far as debugging goes.

**Comment by asoneji** [comment]
@mike42 thanks will try this out. Yes this only for data generated from escpos-php!
