### ISSUE TITLE
Print qr/bar code in TM-U220D

### ISSUE THREAD

**Issue by joivan** [mike42/escpos-php#326]
Hi mike, i have a epson tm-u220d and i try print a qrcode with your example, but print only numbers and letters, do you have any solution?.

Thanks.

**Comment by doublevie** [comment]
use some php qr code generator
<img src="qrcodegenerator.php?code=54646464">

**Comment by mike42** [comment]
@joivan - Your printer does not support QR codes.

See #208, which contains a link to a PHP snippet which I use for rendering QR codes in software. I would be open to reviewing any requests which adds this functionality into the main library.

**Comment by hetiputri** [comment]
Hi mike, i have an epson TM-U220D. I want to print ticket with spesific font size, but all font are printed with small font. do you have any ideas how to solve this?

thanks.
