### ISSUE TITLE
smb printing: not working well  

### ISSUE THREAD

**Issue by shevan** [mike42/escpos-php#330]
Star TSP100 USB printer Is not working well when the printer is not directly connected with the PHP server PC. 

The only function that is working is Text function. but function like Cut, Pulse, setJustification, ... is not working. When i try those function it is printing weird characters.

So i think the printer doesn't accept command over the network.

ps: printer is connect with a client computer in the network and shared. PHP is running on other PC on the same network. Client as server pc are Windows 7 pc. Server pc is running xampp.

**Comment by mike42** [comment]
Sounds like your transport is not passing on raw binary data.

Can you run me through how you installed & shared the printer, and include a code snippet showing how you are calling the code?

**Comment by shevan** [comment]
I downloaded the driver of TSP100 and installed. After installation i went to printer properties and shared it. see screenshots.

i Used following simple code. I went to Spooler folder and opened .SPL file with Notepad++ --> you can see last screenshot.

$connector = new WindowsPrintConnector("smb://KAS-PC/tsp143");
    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    $printer -> close();

and i have also tried FilePrintConnector but i get the same results.


And the following is printing on paper:
**Hello World!
0<x**


![share_printer](https://cloud.githubusercontent.com/assets/5555895/24527097/0f03b87c-15a1-11e7-927e-d7fc234dd655.JPG)

![printer_properties](https://cloud.githubusercontent.com/assets/5555895/24527111/1d3009b4-15a1-11e7-95a8-c7581273523d.JPG)

![notepad_screenshot](https://cloud.githubusercontent.com/assets/5555895/24527136/2fa30434-15a1-11e7-9434-6d1d2fd1d2eb.JPG)


PS: I have also tried to install the printer like you described in your blog as Generic / Text only. But that is not printing anything. Not even a test-page.

**Comment by shevan** [comment]
I have solved the problem. I just had to follow the following tutorial: 

http://help.airpointofsale.com/windows-printer-support/star-tsp100-printer-support-for-windows

**Comment by mike42** [comment]
I'll close this issue off since it's solved.

I usually advise against installing vendor drivers alongside escpos-php to reduce the complexity of debugging. This driver will generate its own ESC/POS, and will only work if the binary is delivered raw to the printer.

This does not appear to be a problem in your case, thanks for sharing the solution.

**Comment by Dinho955** [comment]
Hi, the link to the solution no longer exists, in summary what is the solution?
Thanks
