### ISSUE TITLE
Problem with new printer, the Xpos , XP-TK58.

### ISSUE THREAD

**Issue by hoaianit** [mike42/escpos-php#331]
We are using Epson -t20II, it prints perfectly in Vietnamese.
However, we bought a new thermal printer, the Xpos , XP-TK58(attached picture).
It cannot print Vietnamese properly like the Epson.
Please help us to support the new printer to print in Vietnamse.
Thank you so much.

![xpos](https://cloud.githubusercontent.com/assets/9885836/24523101/ed324484-155f-11e7-81b0-279d14902d37.jpg)

**Comment by hoaianit** [comment]
Epson T200:
![okin](https://cloud.githubusercontent.com/assets/9885836/24533903/9bf58412-1598-11e7-9223-b6e857d74d54.jpg)


Xpos , XP-TK58:
![loiin](https://cloud.githubusercontent.com/assets/9885836/24533909/aaaf951a-1598-11e7-9cef-901252fc0023.jpg)

**Comment by mike42** [comment]
Do you have any vendor documentation for this printer which lists code pages that contain pre-composed Vietnamese characters? The TM-T20 is rendering TCVN-3 there, but the code page lists vary between manufacturers.

If your printer can't support it, or until we get enough info to make it work, then take a look at #254 - this shows a work-around which involves rendering images on the host machine.
