### ISSUE TITLE
Epson TM-T20II printer

### ISSUE THREAD

**Issue by HossamHassan421** [mike42/escpos-php#333]
Hello,
We use Epson TM-T20II printer, i ask for the escpos-php library work with this type or not?
Thanks.

**Comment by kozmoz** [comment]
I'm using the same Epson TM-T20II printer. Works perfect with the default CapabilityProfile. All functions except reverseFeed() are supported. Sharing my printer via USB connected to my router, via printer sharing on port 9100.
