### ISSUE TITLE
Can not print with the website in hosting

### ISSUE THREAD

**Issue by bratlove123** [mike42/escpos-php#334]
Hi Mike,

When I've printed with my ethernet printer in local (http://localhost/), it works well, But if I publish the website on hosting. This error will be appear:  **_Cannot initialise NetworkPrintConnector: Connection timed out_**. I using LAN printer with ip: 198.168.30.30 | port: 9100.

Thanks,
Justin

**Comment by Stenerson** [comment]
For those that might stumble upon this through a Google search in the future. [Check out the FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md#can-i-print-from-my-server-on-the-internet), there are a few options for printing from the Internet listed on there.
