### ISSUE TITLE
New Printer: Citizen CT-S310II

### ISSUE THREAD

**Issue by zone11** [mike42/escpos-php#335]
Successfully using a Citizen CT-S310II with USB using Linux.

The printer identifies itself as USB ID 1d90:2060 an works with the default settings.
Using FilePrintConnector to "/dev/usb/lp0"

Tested functions are EscposImage, different fonts and sizes, feed and cut.

**Comment by mike42** [comment]
Thanks for testing! This will be listed in the README for the next release.
