### ISSUE TITLE
 I can not print from client computer (Windows)

### ISSUE THREAD

**Issue by sistemhenry** [mike42/escpos-php#336]
I need help also I want to print from the client side, Windows operating system, printer is connected by USB. From the server print well; But when I visit the system by means of intenet from another computer I can not print

**Comment by shadowsberg** [comment]
Good morning I have the same problem, I do not speak English but I will try my best, if I run in local, everything is perfect, when I go to the server and access via the internet from another machine, it gives me the following message: Failed to print. Command "smbclient '//Desktop/tsp143' -c 'print -' -N" failed with exit code 1: WARNING: The "syslog" option is deprecatedConnection to Desktop failed (Error NT_STATUS_CONNECTION_REFUSED)

**Comment by sistemhenry** [comment]
I want to know if there is a way that the printer is connected to a client machine from the internet and can be printed. Locally it works very well - I send the client machine name even the IP address but it always throws me that error message.

**Comment by Stenerson** [comment]
@sistemhenry Did you check the [FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) on this? There are a few options for printing over the Internet.
