### ISSUE TITLE
doubt about compatibility with printer

### ISSUE THREAD

**Issue by derkaiser12** [mike42/escpos-php#338]
Hi. 
Do you know if your library can be used with the printer bemantech lr 2000.
I have a new proyect but my client use this model of printers.
thanks!

**Comment by Stenerson** [comment]
Looks like it should work. According to their programming guide the default method is ESC/POS 

http://bematechus.com/wp-content/uploads/2016/01/LR2000-Programming-Manual-v1.2.pdf

**Comment by jonathanoh1** [comment]
sabes si la impresora toshiba tec B-SA4T funciona, he hecho pruebas y la impresora me manda error..

**Comment by jmnyarega** [comment]
how about COMPOS thermal printer?

**Comment by Stenerson** [comment]
Hi, @jmnyarega, can you please open a new issue for this printer and include the specific model number?

I'm going to close this issue for now since it appears that the original question was answered.

Thanks!
