### ISSUE TITLE
Text size not working in TM-U220D

### ISSUE THREAD

**Issue by hetiputri** [mike42/escpos-php#339]
Hi,

I've got problem when printing ticket. I use example escpos-php code. the image's printed well but its all text are still small. Here is my code:

$printer->initialize();
$printer -> setJustification(Printer::JUSTIFY_CENTER);
$img = EscposImage::load("hospital.png");
$printer -> bitImageColumnFormat($img);
$printer -> feed(2);

$printer -> setTextSize(2,4);
$printer -> text($number);
$printer -> feed(2);
$printer -> setTextSize(5,6);
$printer -> text("MC |".$date);
$printer -> feed(3);
$printer -> cut();
$printer -> close();

Can anyone help me to solve this?
 I am using windows 7 and PHP 5.6.15

**Comment by mike42** [comment]
I have a dot matrix TM-U220B, and I don't believe it supported the same sizes as its thermal printer cousins.

Have you tried `selectPrintMode()`? It uses a different command in the background, which supports "double height" and "double width", so you may have different results.

Example usage from `receipt-with-logo.php`-

```php
$printer -> text($tax);
$printer -> selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
$printer -> text($total);
$printer -> selectPrintMode();
```

**Comment by novprayogi** [comment]
this is not solve because can make bigger text
