### ISSUE TITLE
Hello i am having the issue below...

### ISSUE THREAD

**Issue by EdgarVzla** [mike42/escpos-php#34]
Parse error: parse error, expecting `T_STRING' or `T_VARIABLE' or `'$'' in D:\xampp\htdocs\swapv\library\escposphp\src\AbstractCapabilityProfile.php on line 57

what i see in the file is next:

	public static final function getInstance() {
		static $profile = null;
		if ($profile === null) {
			$profile = new static();
		}
		return $profile;
	}

------------------------------------------------
Apache Version  Apache/2.2.11 (Win32) DAV/2 mod_ssl/2.2.11 OpenSSL/0.9.8i mod_autoindex_color PHP/5.2.8  
------------------------------------------------

do you know the reason?

**Comment by mike42** [comment]
Hello,

Thanks for notifying me.

That function is using a feature called late static bindings([link](http://php.net/manual/en/language.oop5.late-static-bindings.php)), which is only available from PHP 5.3+ (released around 6 years ago).

I'll treat this as a bug and remove uses of this feature for the sake of compatibility, but you should upgrade your server if possible, as your PHP version is very out-dated.

**Comment by Ruddyajm** [comment]
Saludos Mike puedo indicas que el problema lo tiene la version de php y que vas  a quitar la funcion para que no genere el error me podrias dar el nuevo archivo AbstractCapabilityProfile.php  debido a que mi version es anterior a la 5.3 y no puedo cambiar de version 

muchas gracias

**Comment by mike42** [comment]
This library now uses namespaces throughout, which are also supported only from PHP 5.3, meaning that there won't be much point removing the use of late static binding.

I can only suggest an upgrade if you wish to use the library. Another alternative could be to fork an [ancient code snippet](https://github.com/mike42/escpos-php/commit/c144eef8e8f40abfffe738f7da6ea0713814da06) from before the library was designed to integrate cleanly into namespaced systems.
