### ISSUE TITLE
Printing from Android localhost

### ISSUE THREAD

**Issue by lkcodk** [mike42/escpos-php#341]
Hi Mike
I am trying to print from my android device to my Epson TM -T20II (USB).
I have downloaded Palapa web server, which is a localhost for android
http://alfanla.com/palapa-web-server/.
I have also connected via USB

When i have to print, i simply make a call from my webserver to my localhost, 
which is running your printer script.

I just wonder what i have to write in the printer-connector-sektion, to make it work.
Here is some of the code:

require 'autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
		
$connector = new WindowsPrintConnector(" [ MY EPSON PRINTER ] ");
$printer = new Printer($connector);
.....

Thank you
Kasper

**Comment by mike42** [comment]
We don't currently have any code snippets that take Android USB into account, so you're chartering new territory I'm afraid.

If you can figure out how to get raw data to your printer with the level of permission PHP is running at, then we can attempt to do the same from PHP. However, I have no idea how the USB device may be available, or whet sort of hoops you might need to jump through to access it.

You might have an easier time if you can get a networked printer connected to the same WiFi network as the printer (`NetworkPrintConnector` can just connect over a socket if nothing blocks it), or using the Android device to hit a PHP server running on a Raspberry Pi instead, where USB is easy to write to.
