### ISSUE TITLE
Print Preview on escpos

### ISSUE THREAD

**Issue by gagantous** [mike42/escpos-php#342]
how can i print preview before i want to print the whole receipt ? 
thanks in advance

**Comment by Stenerson** [comment]
There is no built-in preview functionality. Your best bet would probably be to create a "virtual" receipt using the techniques discussed in #280.

**Comment by gagantous** [comment]
Thanks for your kind answer (y)

**Comment by Stenerson** [comment]
Anytime @gagantous! 

I'm going to close this for now. You can reopen if you run into specific questions relating to this.
