### ISSUE TITLE
Table format and wordwrap 

### ISSUE THREAD

**Issue by gagantous** [mike42/escpos-php#345]
can i do like a wordwrap table content using escpos ?
for example.

```
NO       Name     some1      some2
1    ahjhjhjh    34          hjs
    something
2    kjakjsdkj   78         asd
```

any library for using format like that ?
regards

**Comment by Stenerson** [comment]
Check out the discussion on #159. I think it should be helpful for what you're trying to do.

**Comment by gagantous** [comment]
Many thanks for your answer
(y)

**Comment by Stenerson** [comment]
You're welcome! Does this help you with #343 as well?

**Comment by gagantous** [comment]
yup, that what i was looking for ( some thing like that )
many thanks (y)
