### ISSUE TITLE
printer TOSHIBA TEC B-SA4T doesnt work

### ISSUE THREAD

**Issue by jonathanoh1** [mike42/escpos-php#346]
do you know if the library can be used with the printer TOSHIBA TEC B-SA4T? I'm doing tests and it doesn't work.
thanks!

**Comment by Stenerson** [comment]
Can you provide some more information? How are you trying to connect? What errors are you getting? Thanks!

**Comment by jonathanoh1** [comment]
This is my code

<?php
require __DIR__ . '/escpos-php/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;

    $connector = new NetworkPrintConnector("192.168.20.180",8000);    
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer -> text("prueba de escpos PHP");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();



I want to print labels on the printer that is on the network, apparently it does not work with this printer because it sends me an error or it only flashes the focus when I turn the page, but it does not show me error in PHP, only in the machine with the focus of Error, this machine must be installed with the port 8000 and add it in the line and also try to modify the file of NetworkPrintConnector and also not work. Use another conventional HP LaserJet printer that is also in network and with it I had no problem, just change the IP and ready,

**Comment by mike42** [comment]
This is an ESC/POS library, so if your printer understands ESC/POS and you can get raw data to it, you will usually get some sort of output.

Toshiba only advertises EP-series printers as having ESC/POS based a quick webs search, so I think that your transport is fine, but your printer does not understand the page description language that this library generates.

Aside, your HP LaserJet is also not an ESC/POS printer, maybe check your vendor manuals for any more printers you try (to avoid [breaking anything](https://en.wikipedia.org/wiki/Lp0_on_fire) ;) )
