### ISSUE TITLE
EscposImage::load() error

### ISSUE THREAD

**Issue by Mwangangi** [mike42/escpos-php#347]
Hello, my web app has been printing receipts seamlessly without issues until I did a clean install of the operating system and apache2 web server. Ever since, images/logo cannot print due to this error "No suitable EscposImage implementation found".. is there a library or software package that I might have missed that is required to load graphics for printing? Kindly advise.Thank you

**Comment by Stenerson** [comment]
@Mwangangi, Can you verify that you have installed either `imagick` or `gd` as specified in the [requirements](https://github.com/mike42/escpos-php#requirements)?

The error message you're getting is thrown when neither can be found. See code [here](https://github.com/mike42/escpos-php/blob/5400286144e04474e36440f8703ae7737910ac5b/src/Mike42/Escpos/EscposImage.php#L457).

**Comment by Mwangangi** [comment]
@Stenerson thank you I believe this must be what I'm looking for... do I need to add a ppa or a new software source to be able to install the package?

**Comment by Stenerson** [comment]
I'm not sure which distro you're using but it's pretty easy to install either with your package manager of choice. I'd recommend some Googling for a complete list of steps but it may be as simple as `apt-get install php5-gd` **or** ` apt-get install php5-imagick`then to restarting apache.

**Comment by Mwangangi** [comment]
```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.0-gd
```
This worked for me. Here's a link to the detailed solution http://stackoverflow.com/questions/34367917/install-php70-gd-on-ubuntu/

Thanks a lot @Stenerson for your guidance

**Comment by Mwangangi** [comment]
`sudo apt-get install php-imagick` might also be useful for those who still have this problem
