### ISSUE TITLE
Please add driver TM-U220

### ISSUE THREAD

**Issue by barayuda** [mike42/escpos-php#35]
Please add this driver :)

**Comment by mike42** [comment]
Hello,

I don't think there's any action to take here. This is an Epson-branded thermal printer, so it should understand commands which are generated by escpos-php.

It will be added to [this list](https://github.com/mike42/escpos-php#printers) once somebody who has this printer confirms that it works - If you have a TM-U220, please follow the examples and let me know what works.

**Comment by barayuda** [comment]
Hello thanks for reply.
But it said "fialed to write file to printer at LPT1"
I using windows 7 64 bit

**Comment by barayuda** [comment]
Hello :) 
Sorry this was worked fine, finally with smb://pc-name/printer_name

Thanks for easy library.

**Comment by mike42** [comment]
Thanks barayuda, glad to hear it's working for you!

Feel free to file any questions, bugs, feature requests etc on this bug tracker.

**Comment by severinolorillajr** [comment]
Found the same issue, bitImage() and graphics() both prints garled texts. 
Overall, with texts it's working great. Thank you!

**Comment by barayuda** [comment]
Hope, next update, all is well :)

**Comment by mike42** [comment]
@barayuda  @severinolorillajr - I think TM-U220 support has improved lately. I ended up implementing an extra image format for #83 (not yet merged to master).

My printer doesn't quite keep up with long images, but you can `git checkout 83-columnformat` and-

```php
    $tux = new EscposImage("resources/tux.png")
    $printer -> bitImageColumnFormat($tux, Escpos::IMG_DOUBLE_WIDTH | Escpos::IMG_DOUBLE_HEIGHT);
```

If you have a red/black ribbon, two-color text has also been added in #68.

**Comment by severinolorillajr** [comment]
Wow... Thanks a lot for the updates mike..
Greatly appreciate it.. Cheers!

**Comment by barayuda** [comment]
Thanks update @mike42, thats was amazing.
I hope merging soon to master :)
To try the improve in printer TM-U220
