### ISSUE TITLE
Bluetooth connection

### ISSUE THREAD

**Issue by lkcodk** [mike42/escpos-php#351]
Hi
Is it possible to connect to a bluetooth printer with your script?
How can I do it? Do i need a speciel model or vesion of the printer?

Kasper

**Comment by mike42** [comment]
It's not currently supported, but the [issue tracker](https://github.com/mike42/escpos-php/issues?q=bluetooth) suggests that somebody has got this library working with a bluetooth printer and Raspberry Pi.

Ultimately, you' need to figure out how to transport raw data to your printer from the command line. If you can, then please file a feature request for a bluetooth print connector and we'll get one made!
