### ISSUE TITLE
Set Baud rate and Handshake

### ISSUE THREAD

**Issue by nitinsbuzz** [mike42/escpos-php#352]
I have spent many hours to diagnose a printing problem with some printers.  These printers (Metapace T-1 and Epson TM-T20 (Usb/serial)) were printing (special/error) characters like question marks and c's even though the code is valid and the libraries are valid. I tried different capability profiles and network connectors. The problem turned out to be the settings of the printer itself. Keep feed btn pressed on starting the printer to print the printer's settings page. Copy the baud rate and other settings according to these settings. Restart the printer (with 10sec between shutting down and starting). The printer should work perfect now (in case it did not before).

My setup:
Epson TM-T20 USB/serial connection
CapabilityProfile: simple
Linux Ubuntu (14.04)
CupsConnector

**Comment by mike42** [comment]
Thanks for sharing. I'll close this off since there's nothing more to be done here.

We probably need a dedicated serial connector for this type of situation, see #365.
