### ISSUE TITLE
i want to print with unicode but it show charater ????

### ISSUE THREAD

**Issue by sunry2ntkh** [mike42/escpos-php#354]
<?php 
require 'escpos/autoload.php';
require_once(dirname(__FILE__) . "/../src/RTLBuffer.php");

use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

try {
    // Enter the share name for your USB printer here
 
    $connector = new WindowsPrintConnector("smb://PC-01/80mm");
	
    $printer = new Printer($connector);
  
    $printer -> text("Hellow world​ ខ្មែរ = កម្ូចា\n");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

?>

**Comment by sunry2ntkh** [comment]
can you help me how to mapping UTF-8

**Comment by mike42** [comment]
Please go to receipt-print-hq/escpos-printer-db#28, and post some information about how to encode this script on your printer (such as a link to the vendor's programming guide, or a test print showing the supported code pages and their numbers).

Closing this off as redundant.
