### ISSUE TITLE
unknow unicode??

### ISSUE THREAD

**Issue by sunry2ntkh** [mike42/escpos-php#356]
![18378800_772233969608454_1860775692_o](https://cloud.githubusercontent.com/assets/19813663/25771170/23d3c1d0-3274-11e7-8f75-cd246f35c4d4.jpg)

**Comment by sunry2ntkh** [comment]
<?php
/**
 * This is a demo script for the functions of the PHP ESC/POS print driver,
 * Escpos.php.
 *
 * Most printers implement only a subset of the functionality of the driver, so
 * will not render this output correctly in all cases.
 *
 * @author Michael Billington <michael.billington@gmail.com>
 */
header('Content-Type: text/html; charset=utf-8');
//mb_internal_encoding();

// // Lengths seem to be different on your computer
// $str = "សសាសដថាdsfsd232";
// echo mb_strlen($str) . "\n";
// echo mb_strlen($str, 'UTF-8') . "\n";
// exit();
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
//use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\EscposImage;

$connector = new WindowsPrintConnector("smb://PC-01/80mm");
$printer = new Printer($connector);
$str = base64_decode("  sdfasdf dafdដដដ");

// Epson character tables
//$try = array(
//  37 => 'CP864',
//  50 => 'CP1256');

// E-pos TEP 200M character tables
$try = array(
    // 28 => 'CP864',
    // 29 => 'CPW1001',
    33 => 'CP720',
    34 => 'CP1256' ,
    // 63 => 'CP864',
    34 => 'CP1256',
    // 7 => '0bbbbbbb',
    82 => 'CP1001'
    );

foreach($try as $targetNumber => $targetEncoding) {
    $map = makeMap($targetEncoding);
    $outp = convert($str, $map);

    /* Print test output */
    $printer -> selectCharacterTable($targetNumber);
    $printer -> text($targetNumber." : ".$targetEncoding. "\n");
    if(count($map) == 0) {
        $printer -> text("Can't make $targetEncoding output with iconv.\n");
    } else {
         $printer -> textRaw(strrev($outp) . "\n");
    }
    compactCharTable($printer, 8);
}

$printer -> feed(2);
$printer -> cut();
$printer -> close();

function convert($str, $map) {
    // Convert UTF8 to the target encoding
    $len = mb_strlen($str);
    $outp = str_repeat("?", $len); 
    for($i = 0; $i < $len; $i++) {
        $utf8 = mb_substr($str, $i, 1);
        if(isset($map[$utf8])) {
            $outp[$i] = $map[$utf8];
        }
    }
    return $outp;
}

function makeMap($targetEncoding) {
    // Make map of target encoding v UTF-8
    $map = array();
    for($i = 0; $i < 255; $i++) {
        $native = chr($i);
        $utf8 = @iconv($targetEncoding, 'UTF-8', $native);
        if($utf8 == '') {
            continue;
        }
        $map[$utf8] = $native;
    }
    return $map;
}

function compactCharTable($printer, $start = 2) {
    // Output a table of characters for a code
    $chars = str_repeat(' ', 256);
    for($i = 0; $i < 255; $i++) {
        $chars[$i] = ($i > 32 && $i != 127) ? chr($i) : ' ';
    }

    $printer -> setEmphasis(true);
    $printer -> textRaw("  0123456789ABCDEF\n");
    $printer -> setEmphasis(false);
    for($y = $start; $y < 16; $y++) {
        $printer -> setEmphasis(true);
        $printer -> textRaw(strtoupper(dechex($y)) . " ");
        $printer -> setEmphasis(false);
        $printer -> textRaw(substr($chars,$y * 16, 16) . "\n");
    }
}

**Comment by mdestafadilah** [comment]
What printer type?

**Comment by sunry2ntkh** [comment]
SPRT printer

**Comment by sunry2ntkh** [comment]
![20170516_101959](https://cloud.githubusercontent.com/assets/19813663/26088424/5ffa0e58-3a21-11e7-825e-68d6a34a8b9f.jpg)

**Comment by mike42** [comment]
I'll close this off as the character encodings for this printer wont allow it to print this natively until there is a profile for your printer. receipt-print-hq/escpos-printer-db#28 lists some things that you will need to know to make one.
