### ISSUE TITLE
i want to add the local laguage code table?? for khmer laguage of cambdia

### ISSUE THREAD

**Issue by sunry2ntkh** [mike42/escpos-php#357]
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'There is no code table 63 allowed by this printer's capability profile.' in D:\wamp\www\test\escpos\Escpos.php on line 417

**Comment by mike42** [comment]
Could you include your make/model of printer, some example text in the script you are trying to use, and a snippet showing what PHP code you are running to get that error?

Our printer code pages listings come from the [Receipt Printing HQ database](https://github.com/receipt-
print-hq/escpos-printer-db), and are shared between several projects.

**Comment by mike42** [comment]
Assuming you've decided to try to make a printer profile based on receipt-print-hq/escpos-printer-db#28, so I'll close this off as redundant.
