### ISSUE TITLE
i got message You require xvfb-run but it could not be found

### ISSUE THREAD

**Issue by sunry2ntkh** [mike42/escpos-php#358]
i have install wkhtmltopdf ready ??
and then run for test it show message like this  You require xvfb-run but it could not be found

**Comment by OskarStark** [comment]
this has nothing todo with this lib IMO, wkhtmltopdf itself needs xvfb

**Comment by mike42** [comment]
I'm assuming that you are reading `print-from-html.php`. This file demonstrates that HTML is not understood by the library, and shows how I work around it using `wkhtmltoimage`. `xvfb-run`is a tool that is required to run `wkhtmltoimage` from scripts on linux.

You either need to install the dependencies, or dive in and find your own way to pass images to the library if the example doesn't apply to your setup.
