### ISSUE TITLE
SP700 in Star Command Mode

### ISSUE THREAD

**Issue by temp1029** [mike42/escpos-php#359]
Just curious if there was a way to substitute one set of commands (ESC/POS) for another (STAR) for printers which support both?  I am trying to print to an SP700, but it has the command DIP switch set to STAR command mode and there is other hardware which needs it to be in this mode.

I really like the way this code is structured and wouldn't mind doing the extra work to translate it (assuming it hasn't already been done and I missed it), but I'm not sure if it would be welcome or not.

Stephen

**Comment by mike42** [comment]
Your contributions to the main repository would be most welcome. In general, I'm open to reviewing pull requests which improve support for other command sets, as long as we don't change the output for ESC/POS printers.

We have an existing compatibility flag for Star printers, which I use to choose the character encoding command (a simple [`if ($this -> profile -> getSupportsStarCommands())`](https://github.com/mike42/escpos-php/blob/07313e57c692edf85ddbe4a9ac4da36116d1fb42/src/Mike42/Escpos/Printer.php#L729) block)-  This is intended for Star printers that are in ESC/POS mode, but we can add more flags to the profiles as needed.

Don't worry about adding too many compatibility-related `if` statements to `Printer.php`, I have a plan to move all of the implementations into separate files later anyway.
