### ISSUE TITLE
I change yourcode for Codeigniter

### ISSUE THREAD

**Issue by mdestafadilah** [mike42/escpos-php#360]
Hi, I just change little yourcode to work for my Apps, with Codeigniter..
https://github.com/RSUP/ESC-POS

Bighug for your library! Thanks.

**Comment by mike42** [comment]
Thanks for letting us know, and I'm glad to hear the library has been useful to you.

I am not a CodeIgniter user, so if there is anything you would like to suggest we fix up for compatibility reasons, then I suggestions.

I'll close this issue off as there's no action needed.

**Comment by WilsonicX** [comment]
Hi, I need this for Windows, I add the Mike42 to 3rd Party folder and add too Libraries the EscPos.php and config this in $autoload['libraries'] = array('database','session','form_validation','backend_lib','escpos'); and say a  Message: Class 'Mike42\Escpos\PrintConnectors\WindowsPrintConnector' not found could yo help me please

**Comment by WilsonicX** [comment]
I use composer to install mike42 dependency, but how use this in my project. You can help me please?
