### ISSUE TITLE
not support encode charactor ????? i want to get the code for support language

### ISSUE THREAD

**Issue by sunry2ntkh** [mike42/escpos-php#361]
![20170515_112208](https://cloud.githubusercontent.com/assets/19813663/26042606/08b42874-3961-11e7-9c44-54d13138b4d3.jpg)
![20170515_112216](https://cloud.githubusercontent.com/assets/19813663/26042610/0f72c670-3961-11e7-8087-407160f84d92.jpg)

**Comment by mike42** [comment]
Closing as duplicate.

receipt-print-hq/escpos-printer-db#28 lists some things that you will need to know to make a profile for this printer.
