### ISSUE TITLE
 Filename cannot be empty issue in print from mac machine

### ISSUE THREAD

**Issue by anavgire4** [mike42/escpos-php#362]
```php
<?php
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\CupsPrintConnector;
try {
    $connector = new CupsPrintConnector("EPSON_TM-T20");

    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
?>
```

when i run above code on linux PC it's working fine but in mac it gives below error.
i think it might be an permission error.
please help me.

file_put_contents(): Filename cannot be empty

**Comment by mike42** [comment]
The usage of `file_put_contents` in CupsPrintConnector is-

```
// Build command to work on data
$tmpfname = tempnam(sys_get_temp_dir(), 'print-');
file_put_contents($tmpfname, $data);
```

Can you share your PHP version so that I can try to replicate? I don't have access to a web stack on Mac, but that this method for creating temp files is the likely culprit.

**Comment by anavgire4** [comment]
Thanks for such an early response.
We have used PHP 5.6.30 Version.

**Comment by mike42** [comment]
It appears to be a permissions issue- There are some common stacks that are setting up PHP without a write-able temp space, and a [web search](https://www.google.com/search?q=php+temp+file+permission+mac) turns up plenty of people who have seen it. You can `echo sys_get_temp_dir();` to find out which directory to adjust permissions on.

It is a bug that we don't return an error here that indicates temp files cannot be created, so I'll leave this open until that has been patched.
