### ISSUE TITLE
Fill Buffer or template before sending to printer

### ISSUE THREAD

**Issue by nitinsbuzz** [mike42/escpos-php#364]
Hi Mike,

Would it be possible to allow the text and formatting in a seperate class or allow the user to buffer the esc pos commands before sending to printer? I would like to setup the text and formatting on host a and send only the formatted text to host b to print.

**Comment by nitinsbuzz** [comment]
Possibly something like exportOutput($base64encode = false) {}
 And importOutput($escposCommands);

**Comment by nitinsbuzz** [comment]
Including cut, pulse and close. So on host b you would only have to state printer->printRaw($escposCommands);

**Comment by mike42** [comment]
@nitinsbuzz - Have you checked out the `DummyPrintConnector` interface? I added it for testing, but it should allow you to do something like this.

The `Printer` class is responsible for generating the ESC/POS code, and intentionally does not allow you to send raw data to the printer. For re-using the output, send it to a `DummyPrintConnector`, then retrieve it.

Separately, you can just instantiate any connector, and call `write()` with the raw data.

**Comment by nitinsbuzz** [comment]
Perfect! The dummy connector will do.
