### ISSUE TITLE
Provide arguments in FileConnector

### ISSUE THREAD

**Issue by nitinsbuzz** [mike42/escpos-php#365]
How can I pass arguments to the file connector? I keep getting an error when I add arguments.

    $connector = new FileConnector('/dev/ttyUSB0?baud=19200+bits=8+parity=none+flow=dtrdsrd');

System: Linux Debian RPI
Printer: Epson TM-T20 USB Serial

**Comment by mike42** [comment]
Not currently. `FilePrintConnector` is just going to call `fopen()` in the background, so it's literally looking for a file with the name `/dev/ttyUSB0?baud=19200+bits=8+parity=none+flow=dtrdsrd` there.

You probably need to call `stty` separately.

```php
$device = "/dev/ttyUSB0"
$baud = 19200;
$cmd = sprintf("stty -F %s %s", escapeshellarg($device), escapeshellarg($baud));
exec($cmd)
$connector = new FilePrintConnector($device);
```

Check `man stty` for more options.

I'm not sure how this interacts with USB serial devices, but the rpi has regular serial as well if you can't set the options on your USB adapter.

I'm open to pull requests and/or suggestions for new features, if you have a good idea of what you would expect a `SerialPrintConector` to do.

**Comment by nitinsbuzz** [comment]
@mike42 i also believe your answer is right. The adres used by cups is serial:/... And in the php man i found a similar solution as yours using stty: http://php.net/manual/en/function.dio-tcsetattr.php 

A serialconnector is an option but it would be for very old thermal printers only. What is your opinion on a socketconnector?

**Comment by nitinsbuzz** [comment]
@mike42 On second thought, networkconnector only needs option for persistent connection or auto spawn for permanent connection.

You can definitely add serialconnector. It should allow more access to other serial devices like displays.

**Comment by nitinsbuzz** [comment]
I will look further into stty and contribute where i can.

**Comment by nitinsbuzz** [comment]
Setting baud rate could eliminate most problems with gibberish chars:

https://learn.adafruit.com/networked-thermal-printer-using-cups-and-raspberry-pi/connect-and-configure-printer

**Comment by nitinsbuzz** [comment]
@mike42 all you need is an extra fn $printer->setBaudRate() (stty -F /dev/ttyUSB0 19200) and perhaps document it in readme under problems with serial printer. I am going to test this and check if system-config-printer is required.

**Comment by nitinsbuzz** [comment]
@mike42 Your solution works perfect and it solved the problem i was facing with another printer TM-T88 iii with serial connection where after so many lines, the printer prints gibberish characters and it would not close or cut. All other options of the printer seem irrelevant. All that is required is to set the correct baud rate. 

Even after setting the baud rate in cups, it did not solve the problem with all the printers. It has to be set explicitly as in your example (above) for it work. Could be a bug with cups!!

**Comment by mike42** [comment]
Closing this off since it is all working for you now.

Again, open to suggestions if you think we are doing anything incorrectly in this library.

**Comment by HackCieux** [comment]
Hi @mike42, I have used your library for USB, Serial & Parallel thermal printer. Everything is working as expected and kudos for this project. But I am facing the issue for the Serial-USB printer as It's printing gibberish characters [Note: I am using USB to RS232 Converter [Sample].](https://www.amazon.in/Serial-Adapter-USB-RS232-Standard/dp/B07C1QDB1H?source=ps-sl-shoppingads-lpcontext&psc=1) Please find the below details. Any help or suggestion would be a great help.

> dmesg | grep tty

```
[    1.461673] 00:05: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[   87.363269] usb 2-2.2: ch341-uart converter now attached to ttyUSB0
```
> lsusb
```
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 005: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
Bus 002 Device 004: ID 0e0f:0008 VMware, Inc. 
Bus 002 Device 003: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 002 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```
> ls -lart /dev/ttyUSB0
```
crwxrwxrwx 1 root lp 188, 0 Dec  6 20:32 /dev/ttyUSB0
```
> id
```
uid=1000(printuser) gid=1000(printuser) groups=1000(printuser),4(adm),7(lp),20(dialout),24(cdrom),27(sudo),30(dip),46(plugdev),109(netdev),114(lpadmin),115(sambashare)
```

> cat print.php
```
<?php
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
$device = "/dev/ttyUSB0";
$baud = 19200;
#$baud = 9600;
$cmd = sprintf("stty -F %s %s", escapeshellarg($device), escapeshellarg($baud));
exec($cmd);
$connector = new FilePrintConnector($device);
$printer = new Printer($connector);
$printer -> setLineSpacing(16);
$margin = 32;
$printer -> setPrintLeftMargin($margin);
$printer -> setTextSize(1, 1);
$printer->setFont(Printer::FONT_A);
$printer -> setJustification(Printer::JUSTIFY_CENTER);
$printer -> setEmphasis(true);
$printer -> text("-: Test Print ttyUSB0 :-\n");
$line = 2;
$printer -> feed($line);
$printer -> cut();
$printer -> close();
?>
```
> php print.php
