### ISSUE TITLE
EPSON TM-T88iv printer won't print from live server

### ISSUE THREAD

**Issue by usmanzee** [mike42/escpos-php#366]
Hello,
I connected EPSON TM-T88iv thermal printer to my windows device using USB cable and use WindowsPrintConnector and passed shared name of printer in smb:// url format like this, 
`$connector = new WindowsPrintConnector("smb://server host name/shared printer name");`
Code works perfectly on my local machine just by using shared name of printer as argument.
When I put the code on live server `It does not gives any error` code just executes.
As I have installed SAMBA client on my live (Linux) server but printer does not print receipt.
Any Help, Do I need to configure `smb.config` file more ? if yes then please guide how can i do this ?

**Comment by usmanzee** [comment]
@mike42 any help regarding this ?

**Comment by mike42** [comment]
Hi @usmanzee - this library will throw exceptions when it has issues, and should not silently fail. Can you check your error logging configuration in php.ini and ensure that errors can be seen before continuing?

```php
<?php
throw new Exception('aaaaa');
```

Next up, jump on the server, and try to print "hello world" to your printer from the terminal. This is the best way to confirm that your server can get data to your printer - I think we use `smbclient` to send a text file in this driver.

Lastly, are you printing over a LAN or over the Internet? If the Internet is involved, then we have an FAQ section on the options available.

**Comment by usmanzee** [comment]
@mike42 thank you for your response, I used this command on live server (Linux) with no authentication,
echo "Hello World" | smbclient "//server host name/locally connected printer shared name to windows via USB cable  r" -c "print -" -N
It gives anonymous login successful nothing else.

**Comment by mike42** [comment]
Excellent, that's the problem there. The WindowsPrintConnector is not magic, it just runs smbclient on Linux.

It's always up to the developer to have a setup which is capable of conveying raw data to the printer, so I'm going to close this as out-of-scope for the issue tracker.
