### ISSUE TITLE
i want to print with pdf file but it error

### ISSUE THREAD

**Issue by sunry2ntkh** [mike42/escpos-php#368]
'loadPdf requires imagick extension.' in D:\wamp\www\LibraryPrinter\escpos-php-master\src\Mike42\Escpos\ImagickEscposImage.php on line 217

i use php 5.4.16

$connector =  new WindowsPrintConnector("smb://PC-01/80mm");
$printer = new Printer($connector);
$pdf = 'resources/document.pdf';
$pages = ImagickEscposImage::loadPdf($pdf, 260);
foreach ($pages as $page) {
    $printer -> graphics($page, Printer::IMG_DOUBLE_HEIGHT | Printer::IMG_DOUBLE_WIDTH);
}
$printer -> cut();
$printer -> close();

**Comment by mike42** [comment]
Please do a web search for how to add Imagick to your setup- it's a requirement for working with PDF's.
