### ISSUE TITLE
i want to print with the pdf after i install and config my pc ready it still error with convert

### ISSUE THREAD

**Issue by sunry2ntkh** [mike42/escpos-php#371]
![2017-05-22_115507](https://cloud.githubusercontent.com/assets/19813663/26293149/b5ac662a-3ee5-11e7-9382-d5f19b348e11.png)
![2017-05-22_115442](https://cloud.githubusercontent.com/assets/19813663/26293151/b8bcee7a-3ee5-11e7-987a-6b3906f507ac.png)
![2017-05-22_115720](https://cloud.githubusercontent.com/assets/19813663/26293291/d96c6cb8-3ee5-11e7-8c4b-560b34654a59.png)

**Comment by mike42** [comment]
"UnableToOpenBlob resources/document.pdf: no such file or directory" ... 

This relative path is not in the current directory. Please check out the `__DIR__` keyword in the PHP manual if you would like to make a path relative to the script.
