### ISSUE TITLE
i have a proble like image show below 

### ISSUE THREAD

**Issue by sunry2ntkh** [mike42/escpos-php#372]
![2017-05-27_094604](https://cloud.githubusercontent.com/assets/19813663/26517400/ca93ba5e-42c1-11e7-9f2c-dcb669b7d503.png)

here is the code
============================
$pdf = __DIR__.'/resources/document.pdf';
$connector = new WindowsPrintConnector("smb://PC-01/80mmSeries");
$printer = new Printer($connector);

    $pages = ImagickEscposImage::loadPdf($pdf,300);
    foreach ($pages as $page) {
        $printer -> graphics($page);
    }
    $printer -> cut();
    $printer -> close();

**Comment by mike42** [comment]
The stack trace identifies this as an ImageMagick issue.

As I wrote in #370, please do not post issues here unless they are specific to the `escpos-php` project. I would like to respect the time of our contributors by keeping the issue tracker on-topic.
