### ISSUE TITLE
Please Add Hp Laser Jet

### ISSUE THREAD

**Issue by zobirov** [mike42/escpos-php#374]
hello brother i noticed that the library works for hp laser jet printers please add it to the list and also i noticed that it adds two arrows VA and  black heart in the end of the page can you please tell me how to delete it

**Comment by mike42** [comment]
The HP LaserJet series does not speak ESC/POS, so it is not in the scope of this project to fix this. Generally, sending the wrong language to a printer will just waste time and paper, but it could do some damage if you are unlucky.

Your printer seems to understand plaintext, so you might have some luck using the connectors directly if that's all you need.

```php
$connector = new NetworkPrintConnector("10.x.y.z", "9100");
$connector -> write("Hello World\n");
$connector -> close();
```

Check your printer vendor documentation for supported page description languages that you might be able to generate on your platform - PCL and PostScript are common.

**Comment by mohamedhassan1** [comment]
Can you share your code please and how you make it @zobirov 
the queue handle the document to be printed but the printing action not done!
