### ISSUE TITLE
connect 3 epson TM-T20II with usb

### ISSUE THREAD

**Issue by sinclaireric** [mike42/escpos-php#375]
hellon i want to know if it's possible to connect in same time 3 usb printer and use it . thank

**Comment by mike42** [comment]
Not currently. I think you are describing print multiplexing- A shop will send a receipt to a printer in the kitchen or warehouse to complete the order, and give the same receipt to the customer to take as proof of payment.

Are your printers the same brand?

**Comment by sinclaireric** [comment]
yes i use epson TM T20II , and want to connect 3 printers to my software , i when an order is take , the soft  will send a receipt to a printer in the kitchen and a receipt to a printer in a bar . what can i do please.

**Comment by ianfebriyanto** [comment]
hello, I currently facing same problem, can you share me your solution ?

**Comment by sinclaireric** [comment]
describe your issue please

**Comment by ianfebriyanto** [comment]
same like yours

**Comment by sinclaireric** [comment]
just manage printer permission ! i have make printer available over network

**Comment by mike42** [comment]
I'm assuming this is solved.

There is no built-in way to send output to multiple places, but you would want make a `function` that accepts a `Printer`, and call it 3 times, with 3 different printers.
