### ISSUE TITLE
get paper weight

### ISSUE THREAD

**Issue by lowshint** [mike42/escpos-php#376]
This Tools is very helpfull. anyway can i get paper weight / paper size???,

cz when this setJustification(Printer::JUSTIFY_CENTER) implement to different printer have different result, that function can detect my paper weight.

**Comment by mike42** [comment]
Hi, not sure I understand- [paper weight](https://en.wikipedia.org/wiki/Grammage) is not used at all on ESC/POS printers, but you also talk about alignment and paper size.

Could you expand this into a self-contained bug report with all of the information about your use case?

- Code snippet showing how you're using the library.
- Description of what you were expecting to happen
- A picture of what prints (include a make/model of the printer being used!)

**Comment by lowshint** [comment]
actually i use Printer::JUSTIFY_CENTER, but i have different result in LX-310, TM-T81, and TM-U220. 
sorry about paper weight :D, i mean paper width.

FYI : in LX-310 with TM-T81 same paper dimension  which have 145mm (W) x 195mm (D) x 148mm (H) paper dimension. in TM-T81 we have best result but in LX-310 detected 210mm.

**Comment by mike42** [comment]
Still unsure of what you mean, or whether this could be a bug.

As above, could you please expand this with information such as a complete code snippet, a description of what you were expecting to happen, and a picture of what prints?

( Also, the LX-310 is not an ESC/POS printer, your mileage may vary :) )
