### ISSUE TITLE
failed to open stream: Permission denied on windows 7 client

### ISSUE THREAD

**Issue by r4llproject** [mike42/escpos-php#377]
Hi all,
Im try to print from laravel 5.4 through LAN from server (XAMPP) to client (Connected USB and already shared printer).
I also already set the permission on PRINTERS folder that to full modify.
But it wont works.
In my case PC client use Windows 7.
(It was succesfull when print from server through usb that directly connected to PC server)
Anyone can give me solution? Thanks before..

**Comment by r4llproject** [comment]
as additional info, it was **successfull** tested with cmd: 
echo "Hello World" > testfile
print /D:"\\EROL-VAIO\epsonlx310" testfile
del testfile

**Comment by Stenerson** [comment]
Can you provide some code that shows how you're connecting and the error messages that you're receiving?

**Comment by r4llproject** [comment]
try {
                     // Enter the share name for your USB printer here
                     //$connector = new WindowsPrintConnector("Receipt Printer");
                     $profile = CapabilityProfile::load("simple");
                    //192.168.1.100 is clients ip t
                     $connector = new WindowsPrintConnector("smb://192.168.1.100/Receipt");
                     $printer = new Printer($connector);

                     /* Print some bold text */
                     /* Line feeds */
                     $printer -> setJustification(Printer::JUSTIFY_CENTER);
                     $img = EscposImage::load("images/logom2k.png");
                     $printer -> graphics($img);
                     $printer -> selectPrintMode(Printer::MODE_DOUBLE_HEIGHT);

                     $printer -> text("TIKET MASUK\n");
                     $printer -> selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
                     $printer -> text("No. Ticket : ".$tiketlast->id."\n");
                     $printer -> barcode($tiketlast->id);
                     $printer -> text("\n");
                     $printer -> selectPrintMode(Printer::MODE_FONT_A);
                     $printer -> text("Tambang Tujuan :\n");
                     $printer -> selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
                     $printer -> text($tiketlast->namatambang."\n");
                     $printer -> text("\n");
                     $printer -> selectPrintMode(Printer::MODE_FONT_A);
                     $printer -> text("No. SO : ".$tiketlast->id_salesorder."\n");
                     $printer -> selectPrintMode(Printer::MODE_FONT_A);
                     $printer -> text("Nama Customer : ".$so->namacustomer."\n");
                     //$printer -> text($so->namacustomer."\n");
                     $printer -> text("\n");
                     $printer -> text("Tanggal Cetak : ".$tiketlast->createddate."\n");
                     $printer -> text("Dicetak Oleh : ".$tiketlast->createdby."\n");
                     $printer -> text("\n");

                     $printer -> selectPrintMode(Printer::MODE_UNDERLINE);
                     $printer -> text("Ticket harap dibawa saat memasuki area tambang\n");
                     $printer -> feed();

                     $printer -> cut();
                     /* Close printer */
                     $printer -> close();
                   } catch(Exception $e) {
                     echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
                   }
Sorry, i forget to give the code.. 
Thank you for your response btw..

**Comment by Stenerson** [comment]
Sorry @r4llproject, the `WindowsPrintConnector` is beyond my personal "expertise" and I don't have the equipment to troubleshoot.

I do think the code you posted may help others point you in the right direction.

In the meantime, have you checked out other (closed) issues on this project related to printing with the `WindowsPrintConnector` and USB over the network? If you haven't, there might be a similar issue/question that's been answered that can help. For example, #65 seems to be the same type of issue.

Also, again, if you haven't already - be sure to check out the [FAQ](https://github.com/mike42/escpos-php/blob/cdcffa67843a1e9bdaa3e548f6a0486c2d286af1/doc/FAQ.md#why-do-i-get-this-error-when-i-try-to-print) there's a lot of good information in there.

**Comment by r4llproject** [comment]
I change my code : 
 $profile = CapabilityProfile::load("simple");
                     $connector = new WindowsPrintConnector("smb://**Guest@**192.168.1.101/epsonlx310");
                     $printer = new Printer($connector);

and error change to : 
Exception in WindowsPrintConnector.php line 283:
Failed to print. Command "net use "\\192.168.1.101\epsonlx310" "/user:guest"" failed with exit code 2: System error 53 has occurred.

The network path was not found.

I also already open my firewall on client side.
what i missing??

**Comment by mike42** [comment]
Good debugging. It's not obvious to me what's missing, but there are a few XAMPP users who have had permission issues and posted to this issue tracker.

Could you try executing your script on the command-line (as in run `php.exe foo.php`) to see if the behaviour changes? This could show whether the XAMPP service account has different access to your local user.

**Comment by bob0044** [comment]
Hi! You have to give write permission to a guest users group in the path C://Windows/system32/spool/printer, cause you are connecting as guest user.
