### ISSUE TITLE
Support for PertoPrinter

### ISSUE THREAD

**Issue by welkervinicius** [mike42/escpos-php#381]
Hi!
Any compatible printer on the list can support PertoPrinter?

**Comment by mike42** [comment]
A quick search of this issue tracker suggests that we don't have any PertoPrinter users yet. A good start for any new printer is to check with your vendor for ESC/POS support, which is what this driver sends.

See also the FAQ entry [I have Printer X. Can I use this driver?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver).
