### ISSUE TITLE
 sticky labels - somebody tested?

### ISSUE THREAD

**Issue by pfloriginale** [mike42/escpos-php#384]
Hi everybody... somebody have tested with sticky labels?

Which printer may I use?

Thanks a lot and my compliment to Mike!

**Comment by mike42** [comment]
I don't think anybody has tested sticky lables, but to quote my answer at #514

> If you're looking for compatibility with this library, then it's got to be ESC/POS. We don't have support for the FS ( L "feed to next label" command, but if you source an TM-L90 or the TM-P20/60/P80 Series of printers and are prepared to do some testing, then please come back to file a feature request.
