### ISSUE TITLE
Printer is locked / Impresora se atora

### ISSUE THREAD

**Issue by ezquivel** [mike42/escpos-php#386]
Printer is locked only when I command to print from PHP from the escPos library. You could help me not to is locked, I have to restart it and change the printer and it's only when I print from the escPos library

**Comment by mike42** [comment]
Hi, could you please share your make/model of printer, and a [minimal working example](https://en.m.wikipedia.org/wiki/Minimal_Working_Example) (code snippet) that shows what you're running that freezes this model of printer?

**Comment by ezquivel** [comment]
Printer model: OKI407II

**Comment by ezquivel** [comment]
I forgot the code for the first few times, but then the atmosphere is just the print queue and I have to delete the print queue to reprint it

**Comment by mike42** [comment]
Please still share a PHP code snippet that produces the issue for you, so that I can see how you are using the library.

Marked this issue 'needs info'.
