### ISSUE TITLE
How to use "$connector = new FilePrintConnector("/dev/usb/lp0");"

### ISSUE THREAD

**Issue by LorenzoLa** [mike42/escpos-php#387]
How to use "$connector = new FilePrintConnector("/dev/usb/lp0");"?

**Comment by Stenerson** [comment]
Hi @LorenzoLa, could you provide a little more information with what you’re having issues with? 

If you’re just looking how to use the `$connector` once created, all of the [examples](https://github.com/mike42/escpos-php/tree/development/example) create a new connector (not all are USB but it’s the same idea) and use it.

For example (from the main README):
```php
$connector = new FilePrintConnector(“/dev/usb/lp0”);
$printer = new Printer($connector);
$printer -> text("Hello World!\n");
$printer -> cut();
$printer -> close();
```

**Comment by LorenzoLa** [comment]
Hi, thx for your reply.
From what I have understood is that: “/dev/usb/lp0” is for Linux environments and not for windows, I have tried to connect to LPT1,... but couldn't connect to it. I only print using the basic method explained in connecting a windows USB printer: "https://mike42.me/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows" it works fine for the moment
