### ISSUE TITLE
setTextSize(2,2); too big

### ISSUE THREAD

**Issue by Cynically** [mike42/escpos-php#388]
I find the default font size on a Epson TM-T88V a little bit small for older people to read but if I set the font size to 2x then it is a way too big. What would be the best way to have a size inbetween?

**Comment by Stenerson** [comment]
Have you tried `setTextSize(1, 2)` or `setTextSize(2, 1)`? I find that the double height OR double width alone is some times enough.

**Comment by Cynically** [comment]
I have tried. Double height of way too tall to list all of the items. The perfect would really be half point.
