### ISSUE TITLE
Euro Symbol €

### ISSUE THREAD

**Issue by dumshi** [mike42/escpos-php#39]
Hi,
How do I get euro symbol to work?
Whenever I modify your full-receipt-with-logo template and insert € instead of $, it prints some funny character.

How to get € symbol print?

Thanks

**Comment by dumshi** [comment]
There is EURO symbol on PC858. 
But even when i change printer to PC858, i don't get euro symbol.

Please help

**Comment by mike42** [comment]
Hi dumshi,

Sounds like a bug.

- What model printer are you using?
- Can you snap upload a photo of what character prints in place of the Euro on your printer?

This should tell me whats going on here. Hopefully an easy fix, and yes, there should be an example which includes yen, euro and pounds at a minimum.

**Comment by dumshi** [comment]
Hi again,
- It's unbranded (but their sdk is of Brother).
- https://drive.google.com/folderview?id=0Bw2bSwFt40szY0xoVXRKS2ZjWGM&usp=sharing

Thanks

**Comment by mike42** [comment]
Good use of the receipt-with-logo example!

There is an "International character set" command which I haven't implemented, which changes the currency symbols only. I think I'll need to add it for your use case, as regular encoding issues are per-printer.

I've added a demo 39-currency-symbols.php for testing this issue. You can use ImagePrintBuffer as a workaround (this is the catch-all workaround to open up UTF-8 on any printer by rasterising everything).

The proper solution with the current code is a custom CapabilityProfile which lists supported code pages and what *number they are in the printer*. To put one of these together, we ideally need some specific documentation. Brother [is a bit light](http://download.brother.com/welcome/docp000584/cv_pt9700_eng_escp_103.pdf) on code pages in the first thing I found on Google, so I don't think we'll go down this path (it may not even match up with your printer).

**Comment by mike42** [comment]
Hi,

So I confirmed that on an Epson-branded printer, the currency symbols print correctly using a variety of code pages, and that ImagePrintBuffer produces the same output:

````php
$profile = DefaultCapabilityProfile::getInstance();
// This is a quick demo of currency symbol issues in #39.

/* Option 1: Native ESC/POS characters, depends on printer and is buggy. */
$connector = new FilePrintConnector("php://stdout");
$printer = new Escpos($connector, $profile);
$printer -> text("€ 9,95\n");
$printer -> text("£ 9.95\n");
$printer -> text("$ 9.95\n");
$printer -> text("¥ 9.95\n");
$printer -> cut();
$printer -> close();

/* Option 2: Image-based output (formatting not available using this output). */
$buffer = new ImagePrintBuffer();
$connector = new FilePrintConnector("php://stdout");
$printer = new Escpos($connector, $profile);
$printer -> setPrintBuffer($buffer);
$printer -> text("€ 9,95\n");
$printer -> text("£ 9.95\n");
$printer -> text("$ 9.95\n");
$printer -> text("¥ 9.95\n");
$printer -> cut();
$printer -> close();
````

Please try setting PC858 output and then using this snippet to tell the printer how to output in that code page only:

````php
/*
 Option 3: If the printer is configured to print in a specific code
 page, you can set up a CapabilityProfile which either references its
 iconv encoding name, or includes all of the available characters.

 Here, we make use of CP858 for its inclusion of currency symbols which
 are not available in CP437. CP858 has good printer support, but is not
 included in all iconv builds.
*/
class CustomCapabilityProfile extends SimpleCapabilityProfile {
	function getCustomCodePages() {
		/*
		 * Example to print in a specific, user-defined character set
		 * on a printer which has been configured to use i
		 */
		return array(
		'CP858' => "ÇüéâäàåçêëèïîìÄÅ" .
				"ÉæÆôöòûùÿÖÜø£Ø×ƒ" .
				"áíóúñÑªº¿®¬½¼¡«»" .
				"░▒▓│┤ÁÂÀ©╣║╗╝¢¥┐" .
				"└┴┬├─┼ãÃ╚╔╩╦╠═╬¤" .
				"ðÐÊËÈ€ÍÎÏ┘┌█▄¦Ì▀" .
				"ÓßÔÒõÕµþÞÚÛÙýÝ¯´" .
				" ±‗¾¶§÷¸°¨·¹³²■ ");
	}
	
	function getSupportedCodePages() {
		return array(
				0 => 'custom:CP858');
	}
}

$connector = new FilePrintConnector("php://stdout");
$profile = CustomCapabilityProfile::getInstance();
$printer = new Escpos($connector, $profile);
$printer -> text("€ 9,95\n");
$printer -> text("£ 9.95\n");
$printer -> text("$ 9.95\n");
$printer -> text("¥ 9.95\n");

$printer -> cut();
$printer -> close();
````

These are located in the repository under `examples/specific` for other users to reference. Let me know how it goes!

**Comment by dumshi** [comment]
I echo'ed "EUR " in a foreach loop for each item as a quick workaround.
Will try above soon and let you know.

**Comment by sKY02644** [comment]
@mike42 @dumshi 

hello sorry to bring you back to this but i have to set of XPRINTERS one with the model: XP-V320L i tried to print the ¢ currency but it shows ?

i have tried the image format but it doesnt fit my use case as i am using sprintf() to design a three column table

i also tried to extend the CapabilityProfile and use like you have in your example but even your example for customProfile has bugs in it hence i am not able to use it 

can you please assist me
