### ISSUE TITLE
Asem sr-80 - Asem tool configuration RECEIVE BUFFER SIZE

### ISSUE THREAD

**Issue by pfloriginale** [mike42/escpos-php#391]
I try to use this model
http://www.asem.it/prodotti/point-of-sale-automation/stampanti-termiche/sr-80/

Work's only if I change "RECEIVE BUFFER SIZE" with the asem tool that allow to configure the printer settings... works once and stop working... i change other times in different value and... works!

I don't undersand... some idea?

![cattura](https://user-images.githubusercontent.com/16399563/28084599-58b9917a-6679-11e7-82b3-bea4e50a1eee.PNG)

**Comment by mike42** [comment]
Could you share the PHP code you are using to print? It is not currently clear if/how this issue might relate to `escpos-php`.

**Comment by pfloriginale** [comment]
The same code with another kind of printer (bixolon or asem smsr 85 works

**Comment by mike42** [comment]
I'm not sure if you intended to come back and post a minimal code example that demonstrates the problem, but there is still no information here that would indicate if it's a printer, usage or driver issue, so I'm going to close this off as abandoned.
