### ISSUE TITLE
Unable to open further sockets to Epson TP-T20ii

### ISSUE THREAD

**Issue by srcurtis** [mike42/escpos-php#394]
Hi

I'm not sure if this is a library problem or something with the hardware but as I can't find anything online I thought I would ask.

I use the escpos-php library to communicate with a number of Epson TP-T20ii printers via a RAW IP connection on port 9100.

We have started to experience problems with some printers refusing to open a socket as the day goes on. To be clear, everything works fine for so long and then no further connections are possible.

I can prove that this is the problem with some simple test code:

$ip = "192.168.91.22";
$port = "9100";
$fp = fsockopen($ip, $port, $errno, $errstr);

var_dump($fp);
var_dump($errno);
var_dump($errstr);

This simply times out, as does escpos-php. The output is as follows:

boolean false
int 110
string 'Connection timed out' (length=20)

I can still ping the device and also access the web interface but further printing will require a reboot of the printer.

Below is the print function that uses the library:

```php
try {
	$connector = new Mike42\Escpos\PrintConnectors\NetworkPrintConnector($printer_ip, $printer_port);
	$printer = new Mike42\Escpos\Printer($connector);
	$img = NULL;
	if (!is_null($ship_sender_logo)) {
		$img = Mike42\Escpos\EscposImage::load(dirname(__FILE__) . $ship_sender_logo);
	}

	$now = date("D d M Y h:i");
	$printer->feedReverse(2);
	foreach ($items_by_box as $box) {
		// Print header
		$printer->setJustification(Mike42\Escpos\Printer::JUSTIFY_RIGHT);
		$printer -> setPrintWidth($width);
		//
		$seq = str_pad($box[0]['box_seq'], 3, "0", STR_PAD_LEFT);
		$printer->setTextSize(1, 1);
		$printer->setJustification(Mike42\Escpos\Printer::JUSTIFY_CENTER);
		if (!is_null($img)) {
			$printer->graphics($img);
		}
		if (!is_null($ship_sender_name)) {
			$printer->text("{$ship_sender_name}\n\n");
		}
		$printer->setEmphasis(true);
		$printer->text("{$now}      Delivery: {$delivery_number}\n\n");
		if (!is_null($cust_ref)) {
			$printer->text("Cust Ref: {$cust_ref}\n");
		}
		$printer->setTextSize(2, 2);
		$printer->text("Box {$box[0]['box_seq']} of {$qty_boxes}  ");
		$printer->setReverseColors(true);
		$printer->text(" {$box[0]['box_ref']}-{$seq} \n\n");
		$printer->setTextSize(1, 1);
		$printer->setReverseColors(false);
		$printer->setEmphasis(true);
		$printer->setJustification(Mike42\Escpos\Printer::JUSTIFY_LEFT);
		$printer->text("Items in this box:\n");
		$printer->setEmphasis(false);
		$printer->setJustification(Mike42\Escpos\Printer::JUSTIFY_LEFT);
		$printer->text("Qty   Stock Code       Desc\n");
		// Printe items in box
		foreach ($box as $i) {
			$line = '';
			$tmp = str_pad($i['qty_in_box'], 5);
			$line.= $tmp;
			$tmp = str_pad($i['stock_code'], 16);
			$line.= " " . $tmp;
			$tmp = str_pad($i['description'], 50);
			$line.= " " . $tmp;
			$line = trim(substr($line, 0, $max));
			$printer->text("{$line}\n");
		}
		//
		$printer->text("\n");
		$printer->setJustification(Mike42\Escpos\Printer::JUSTIFY_CENTER);
		$printer->setBarcodeHeight(40);
		$printer->barcode("BXABC{$seq}", Mike42\Escpos\Printer::BARCODE_CODE39);
		$printer->text("\n");
		if ($t == $qty_boxes) {
			$printer->cut(Mike42\Escpos\Printer::CUT_FULL);
		}
		else {
			$printer->cut(Mike42\Escpos\Printer::CUT_PARTIAL);
		}
	}
	$printer->close();
}
catch (Exception $e) {
	$m = "Error returned from Thermal Delivery Note printer";
	$mm = "Error communicating with Thermal Receipt Printer on {$printer_ip}\n\n" . $e -> getMessage();
	$error = "{$m}: {$mm}";
	$this->log_debug(0, "stock_despatch_print_box_content_thermal_delivery()", "{$m} - {$mm}");
	$this->email_admin($m, $mm);
}
```

The two printers that had the problem today are running:

Hardware Version: 17.00
Software Version: 1.01
ROM Version: 1

Has anyone else experienced anything like this?

Thanks

Steve

**Comment by Stenerson** [comment]
This is almost certainly a printer or network issue since, as in your example above, the library simply uses `fsockopen()`& `fclose()` to communicate directly to the printer(s). I do experience similar symptoms at customer sites from time to time with TM-U220Bs using the `NetworkPrintConnector`. Does a restart of the printer resolve the issue for you? Are you noticing any specific patterns as to when the printers start timing out?

I always figured the printer just fell off the network from time to time. Not sure if we've ever tried to ping it before simply restarting. If someone knows what else it could be, I'd be interested in hearing ideas as well.

---

**Side note**: You may want to reduce the timeout in the `NetworkPrintConnector`. I've found that if it doesn't connect in a reasonably short amount of time, it's not going to connect. I've shorted the timeout to somewhere between 5-10 seconds to improve user experience (i.e. they see an error message sooner that it didn't print).

```php
// Timeout after 10 seconds
$connector = new NetworkPrintConnector($printer_ip, $printer_port, 10)
```

**Comment by mike42** [comment]
It is also possible that a client is not disconnecting cleanly, or that the embedded print server has crashed. I am not sure which print server the T20II has, but they often serve a web interface, so you might be able to get a status from `http://192.168.91.22`.

If the issue persists, you could try introducing a more advanced print server to queue the jobs for the printer. In your shoes, I would print to a Raspberry Pi that is running CUPS, and configure it to relay jobs to the TM-T20 printer by adding it as a raw / text only device.
