### ISSUE TITLE
Failed to open stream : permission denied

### ISSUE THREAD

**Issue by sinclaireric** [mike42/escpos-php#395]
hi guy , i have issue with smb connector . i share a printer on a windows 7 computer in local network , but when i launch a  print task in windows 8.1 on the same network, i have this error :  Failed to open stream : permission denied

my code : 

use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
	$cuisine = new WindowsPrintConnector("smb://WARREN-PC/EPSON TM-T20II Receipt Cuisine");

....

**Comment by sinclaireric** [comment]
i hve the same issue but how to fixed access https://github.com/mike42/escpos-php/issues/75

**Comment by sinclaireric** [comment]
Fixed !!!! . just add Guest permission on computer where the usb is connected.

**Comment by mike42** [comment]
Cheers glad to hear it's solved!

**Comment by erwinjnefer** [comment]
i use linux mint, 
i got this error : 
fopen(/dev/usb/lp0): failed to open stream: Permission denied

i have zjiang printer installed in my computer

**Comment by mike42** [comment]
@erwinjnefer - Please open a new issue, this one is closed, and is for a Windows setup.
