### ISSUE TITLE
Issue Communicating with Device using usblp

### ISSUE THREAD

**Issue by tombonan** [mike42/escpos-php#397]
When I run dmesg on my command line, the device gets recognized but it looks like it isn't communicating with usblp and the device is not showing up in the /dev/usb/ folder.

dmesg output:
[   56.117074] usb 1-1.5: new full-speed USB device number 6 using dwc_otg
[   56.263079] usb 1-1.5: New USB device found, idVendor=0483, idProduct=a000
[   56.263092] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   56.263100] usb 1-1.5: Product: ICT GP-58 III
[   56.263108] usb 1-1.5: Manufacturer: STMicroelectronics
[   56.263116] usb 1-1.5: SerialNumber: 00000000050C
[   56.306361] cdc_acm 1-1.5:1.0: ttyACM0: USB ACM device
[   56.308642] usbcore: registered new interface driver cdc_acm
[   56.308653] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters

I saw in [this post](https://mike42.me/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux) that you mentioned making sure that usblp isn't blacklisted and that other drivers aren't claiming the interface. In my case it looks like cdc_acm is the driver that is currently taking priority, how do I switch it so that usblp is the primary method of communication? I haven't seen any direct workarounds online.

Thanks

**Comment by nochecksum** [comment]
Hi @tombonan , it looks like your issue isn't related to mike42's escpos-php library. I agree with your diagnosis. It seems your printer uses a generic USB-serial interface which many devices share, and your OS happens to load the `cdc_acm` driver on detection.

You can blacklist the driver in `/etc/modprobe.d/` but the specific format of the blacklist depends on your linux distribution. That's also the directory to check if `usblp` isn't blacklisted. I'd recommend starting a thread on a forum specific to your linux distribution. A quick search suggests you're using CentOS or Debian or a variant but they have different ways of approaching blacklists.

**Comment by mike42** [comment]
I'm going to close this as I don't believe this can be solved from the PHP side- you need to solve communication on the command-line before this driver comes into play.

In this case, if your adapter is USB/Serial, it may even show up as `/dev/ttyS0` or similar.
