### ISSUE TITLE
Bill is not prinitng

### ISSUE THREAD

**Issue by corpcode** [mike42/escpos-php#399]
I am using Epson TM-T82 and code is not working

**Comment by Stenerson** [comment]
Hi @corpcode, 
Have you checked out the [FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md) and [examples](https://github.com/mike42/escpos-php/tree/development/example)? There are a lot of good answers in there to help get you started. If that doesn't help, can you please post your code and any error messages that you're receiving?  Thanks!
