### ISSUE TITLE
Testeado en FX-890

### ISSUE THREAD

**Issue by zcastle** [mike42/escpos-php#40]
Lo he testeado en una FX-890 y el único problema es que no liberaba el papel luego determinar la impresión, para lo cual añadí la siguiente función:

```<?php

class Escpos {
    const FF = "\x0c";

    function feed_form() {
        $this -> connector -> write(self::FF);
    }
```

Buen trabajo, Saludos.

**Comment by mike42** [comment]
Gracias zcastle, 

I'll add FX-890 to the list of supported printers along with this code, and a note that you need to call this function to release the paper.
