### ISSUE TITLE
mike42/escpos-php

### ISSUE THREAD

**Issue by johnli67** [mike42/escpos-php#402]
Hello please can you tell me how to print using the Mike42 libraries if I have my site in a hosting and it gives me errors.
I have to indicate that locally with the xampp it works very well,
Thanks

**Comment by Stenerson** [comment]
Hi @johnli67, this has been covered many times in previous issues (some examples:  #238, #76, #91, #100, #38). It's also a [topic in the FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md#can-i-print-from-my-server-on-the-internet).

If none of these resources help, can you please provide more details, such as example code, the error that you're seeing and what you've tried so far to resolve the issue? Thanks!

**Comment by johnli67** [comment]
Hola   Gracias por su ayuda

El problema que tengo es el siguiente
Este es el código de impresión que esta en un HOSTING
y al correr me da el siguiente error:

"EN MODO LOCALHOST CON XAMPP FUNCIONA MUY BIEN Y LA CONEXIÓN LA REALIZO CON
WindowsPrintConnector)


[30-Jul-2017 16:59:20 America/New_York] PHP Fatal error:  Class
'Mike42\escpos\PrintConnectors\NetworkPrintConnector' not found in
/home/jolyf986/public_html/eltizon/ticket.php on line 44

tiket.php
<?php
require __DIR__.'/autoload.php';

use Mike42\escpos\printer;

use Mike42\escpos\PrintConnectors\FilePrintConnector;
use Mike42\escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\escpos\PrintConnectors\NetworkPrintConnector;

include "core/controller/Core.php";
include "core/controller/Model.php";

include "core/app/model/OperationData.php";
include "core/app/model/PersonData.php";
include "core/app/model/ProductData.php";
include "core/app/model/ConfigurationData.php";

$iva_val = ConfigurationData::getByPreffix("imp-val")->val;
$title  = ConfigurationData::getByPreffix("ticket_title")->val;
$head1  = ConfigurationData::getByPreffix("ticket_head1")->val;
$head2  = ConfigurationData::getByPreffix("ticket_head2")->val;
$total =0;
$sxtotal=0;


// paametros de impresion

//   aqui da el error     LINE 44
$connector = new NetworkPrintConnector("\\LIMA-S-PC",9100);

$printer = new Printer($connector);
//$printer->selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
$printer->setJustification(Printer::JUSTIFY_LEFT);
/*initialize printer */

$printer -> initialize();
$printer->setTextSize(6,6);
/*for ($i = 1; $i <= 45; $i++) {
    $printer->text($i."\n",40," ",STR_PAD_BOTH);
}*/

$printer->feed(6);
//DATOS GENERALES DEL CLIENTE
$printer->text("CLIENTE: ".$Namclient." ".$Lastclient."\n");
$printer->text("Ci/RUC : ".$Idenclient."\n");
$printer->text("DIREC  : ".$direclient."\n\n");
$printer->text('CNT.       ARTICULO          Pre-U   TOT.'."\n");


2017-07-30 14:33 GMT-05:00 Matt Stenerson <notifications@github.com>:

**Comment by karthick1793** [comment]
star TSP 700 II is not working on server but working in local

hi I am using this code:

require DIR . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\EscposImage;
$connector = new WindowsPrintConnector("smb://Computer Name/Printer name");
$printer = new Printer($connector);
$printer -> initialize();
$printer -> text("\n");
$printer -> text(" FOO CORP Ltd.\n");
$printer -> cut();
$printer -> pulse();
$printer -> close();
This is my error:
Couldn't print to this printer: Failed to print. Command "smbclient '//PCNAME/PRINTERNAME' -c 'print -' -N" failed with exit code 1: Connection to Jerome failed (Error NT_STATUS_UNSUCCESSFUL)
How Can i fix this issue?

**Comment by mike42** [comment]
@karthick1793- Please don't hijack the thread, you are not necessarily working with the same hardware as OP. If you have checked the FAQ and still have questions, then please file a new issue, including information about how you have verified that your setup works.

@johnli67 - The "Class not found" is a class loading error, not to do with this library, so I'll skip past that.

For Internet printing, you need to step back from the PHP code and ensure that you understand the limitations of server-side printing. The best way to do this is to SSH to the server and try to print on the command-line: It wont work, because your printer is behind a firewall.

You can then focus on making a setup where you can convey raw print job securely to your printer. The answer provided by @Stenerson provides the best resources to get started.

I'll close this off since the existing tips & tricks are already in the FAQ.

**Comment by djdang3r** [comment]
I want to install this library in laravel 5.3. What instructions should I follow for the correct installation? Is there a step-by-step guide for the installation in laravel 5.3?

**Comment by mike42** [comment]
Deleted a cross-posted comment, one topic per issue please.
