### ISSUE TITLE
Problem with accented words

### ISSUE THREAD

**Issue by ezquivel** [mike42/escpos-php#406]
Problem with accented words, 
Accents are not printed. 
Print rare characters
How do I solve that?

**Comment by mike42** [comment]
This depends on both the printer and `espos-php` support.

We have a system of "profiles" to print available characters for each printer, compiled at the upstream [receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db) project. The README of that repo has instructions on the type of information that you can collect to request that a profile is added.

If your printer already has a profile, then check the `espos-php` README and ensure that you load it. As a workaround, check the bug tracker for `ImagePrintBuffer` usage, which will use native system fonts.
