### ISSUE TITLE
escpos2text doesn't seem to work with my print driver

### ISSUE THREAD

**Issue by nsatech** [mike42/escpos-php#407]
Gday Mike,

I am trying to get escpos2text.php to convert properly.

I am using the official windows print driver for it (http://www.seiko-instruments.de/fileadmin/Editors/TPS/Drivers/DPU-D_Drivers/IF-D_WinDrv_Ver.2.60.zip)

I have set the printer to "FILE:" port - which creates a .prn file, is this an acceptable way to obtain the binary?

If it is - php escpos2text.php <file.bin> - doesn't successfully convert to text.

Much appreciated.

**Comment by mike42** [comment]
This is probably correct. I will assume that this issue is related to receipt-print-hq/escpos-tools#38, which I've left some info on.
