### ISSUE TITLE
Epson TM-T82II Thai language support

### ISSUE THREAD

**Issue by chiltunder** [mike42/escpos-php#409]
The sentence you want to print out.

> ทดสอบการพิมพ์ภาษาไทย เลขที่บิล วันที่ ชื่อผู้ขาย

But what was printed out.

[https://i.stack.imgur.com/YmtZc.jpg](url)

code

```
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;

$profile = CapabilityProfile::load('default');
$connector = new WindowsPrintConnector("EPSON TM-T82II Receipt");
$printer = new Printer($connector, $profile);

$printer -> selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
$printer -> text("ทดสอบการพิมพ์ภาษาไทย\n");
$printer -> selectPrintMode();
$printer -> text("เลขที่บิล วันที่ เวลา ชื่อผู้ขาย.\n");
```

Help me fix it.

**Comment by andrewsducloux** [comment]
Am also having a Same issue, But for Tamil Language printing issue, Help Me to Fix this.

**Comment by mike42** [comment]
Hi, can you run a self-test and confirm that your printer has a Thai print mode? My model of Epson cannot print Thai, but the Epson manuals say that this is specific to South-East Asia models of printer, and we've had some positive results @ #301 #51.

@andrewsducloux - Character encoding is specific to your model of printer. Please raise a separate issue including make/model of your printer and a sample string that uses the Tamil script.
