### ISSUE TITLE
Brother QL-1060

### ISSUE THREAD

**Issue by mdestafadilah** [mike42/escpos-php#412]
Does work for brother laber printer?

**Comment by mdestafadilah** [comment]
Just try Esc Support in here:
http://download.brother.com/welcome/docp000678/cv_qlseries_eng_raster_600.pdf
https://www.brother.com.au/pdf/support/controlcodes/ESCP_Tech_Manual.pdf

Nothing work, just bipbip light ..

**Comment by mdestafadilah** [comment]
Is working, if i'm test this code:
`$fp = fopen("/dev/usb/lp0", "wb+"); //print_r($fp);
fwrite ( $fp, "\x1B\x40" ); // ESC @

// Select font by pitch and point
$m = 0; // No change in pitch
$nL = 48; // Assuming these point options are what you intend?
$nH = 128;
fwrite ( $fp, "\x1B\x58" . chr($m) . chr($nL) . chr($nH)); // ESC X m nL nH

// Print text
$stringToPrint = "Hello\n";
fwrite ( $fp, $stringToPrint );

// Form feed
fwrite ( $fp, "\x0C" ); // FF`

but with this library, just add few line:
`		$this->load->library('EscPos');

		try {
		    // Tested From Ubuntu Linux
		    $connector = new Escpos\PrintConnectors\FilePrintConnector("/dev/usb/lp0"); //print_r($connector);


		    /* SETTING PRINTER */
		    $printer = new Escpos\Printer($connector); //print_r($printer);

			$printer -> text("Hello World!\n");
   			$printer -> cut();	    
		    
		    /* Close printer */
		    $printer -> close();
		} catch (Exception $e) {
		    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
		}`
my printer, show the bip-bip-bip light.

any idea what wrong?

thanks

**Comment by mike42** [comment]
That printer speaks ESC/P, so this driver is not likely to work well for it.

Some of the software on this list may be more useful: https://github.com/pklaus/brother_ql/blob/master/SIMILAR_SOFTWARE.md
