### ISSUE TITLE
NT_STATUS_UNSUCCESSFUL

### ISSUE THREAD

**Issue by josanu** [mike42/escpos-php#414]
try {
    // Enter the share name for your USB printer here
    $connector = null;
    //$connector = new WindowsPrintConnector("Tickets");
	$connector = new WindowsPrintConnector("smb://LAPTOP-0J27B75G/Tickets");
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

Throws the following error.  

Couldn't print to this printer: Failed to print. Command "smbclient '//LAPTOP-0J27B75G/Tickets' -c 'print -' -N" failed with exit code 1: WARNING: The "syslog" option is deprecatedConnection to LAPTOP-0J27B75G failed (Error NT_STATUS_UNSUCCESSFUL)

Any Suggestions ?

**Comment by younas-bangash** [comment]
Did you solve this problem or not ?

**Comment by mike42** [comment]
Please check out the FAQ entry: [Why do I get this error when I try to print?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#why-do-i-get-this-error-when-i-try-to-print).
