### ISSUE TITLE
Query About Printer Model

### ISSUE THREAD

**Issue by akhyar016** [mike42/escpos-php#416]
Is CRS- "BTP 2002NP" supported for this code ?
If yes, then which interface ??
Thanks in advance :)

**Comment by mike42** [comment]
The FAQ entry ["I have Printer X. Can I use this driver?"](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver) with some basic things to check.

This appears to be an ESC/POS printer, so it will probably work.

It would be great if you can test it out and post back with which features work. The transport has more to do with your operating system than the printer. If you get a choice, Ethernet is the easiest interface to use (same code for any platform), followed by USB if you are on Linux.
