### ISSUE TITLE
TVS Bar Code Printer T-9650 Plus

### ISSUE THREAD

**Issue by andrewsducloux** [mike42/escpos-php#418]
Am using Bar Code Printer T-9650 Plus
for Barcode Generator, this printer is not working with your helper. May i know someother source to use this.

And Printing in Tamil Language is not working, please suggest me for printing bill in tamil for Epson Printer

**Comment by mike42** [comment]
@andrewsducloux - I can't find any documentation on the web for this printer that would suggest that it supports ESC/POS, so this driver may not work for anything but plain ASCII.

If there is a public ESC/POS programming guide for this printer that is available online, please drop in a link and we can look over the difference in barcode or language commands.

**Comment by twf-nikhila** [comment]
@andrewsducloux : Did you got any solution to this? Does TVS barcode priter accept ESC/POS commands or simple printing works with it? 

Thank you in advance.
