### ISSUE TITLE
Citizen

### ISSUE THREAD

**Issue by FulleringerAgency** [mike42/escpos-php#42]
This app work with Citizen printer ?
http://www.citizen-systems.com/us/printer/pos/ct-s601

**Comment by mike42** [comment]
I'm yet to hear any reports (positive or negative) about compatibility with Citizen printers. This driver outputs fairly standard ESC/POS, which the printer manual claims to support, so it should work to some degree.

For most non-Epson printers, it's best to stick with the SimpleCapabilityProfile, then file a request here if with some example text if you want non-Western characters included in a new CitizenCapabilityProfile.
