### ISSUE TITLE
Can't able to print tamil character instead it printing question marks?

### ISSUE THREAD

**Issue by cheralathann** [mike42/escpos-php#420]
@mike42 I would like to print receipt in tamil language but it printing question mark instead of given tamil character. Is there any possibilities to fix the issue. Here is my code. Please help needed.. 

```
      require __DIR__ . '/vendor/mike42/escpos-php/autoload.php';
      use Mike42\Escpos\Printer;
      use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
      use Mike42\Escpos\CapabilityProfile;
      try {
         $connector = new WindowsPrintConnector("VENDOR THERMAL PRINTER");
         $profile = CapabilityProfile::load('default');
         $printer = new Printer($connector, $profile); 
         $printer -> initialize();//reset format
         $printer -> text("------------------!\n"); 
         $printer -> text("வணக்கம்\n");  
         $printer -> text("தமிழ் மொழி\n");  
         $printer -> text("நன்றி\n");  
         $printer -> text("------------------!\n");    
         $printer -> cut();
    
         /* Close printer */
         $printer -> close();
         } catch (Exception $e) {
            echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
        }

```
Ouput now Print
?????
?????
?????

Expected to Print
வணக்கம்
தமிழ் மொழி
நன்றி

**Comment by mike42** [comment]
@cheralathann Can you comment back with the make/model of printer being used for this test, and a link to the programming guide if it's available online?

We need to determine first whether the driver can be extended with a profile to send Tamil characters to this printer, or whether we need to use send images of Tamil characters as a work-aroun.d

**Comment by cheralathann** [comment]
@mike42 Printer model is TVS RP 3200

**Comment by mike42** [comment]
Based on what's here, I don't know if it's possible to render Tamil on this printer, or which commands you would send. At this stage, it's probably best to make an image out of the text, and send that instead.

I think the work-around at #790 is worth a look. It's for the Sinhala language, but with a different font you could do something similar to render Tamil text on the TVS RP 3200.
