### ISSUE TITLE
aclas pp7x thermal printer

### ISSUE THREAD

**Issue by ajayladdha4** [mike42/escpos-php#424]
Will this printer work with your code.

**Comment by mike42** [comment]
Yes, but there is no profile for a similar printer, so output will be quite simple. I have raised an issue at receipt-print-hq/escpos-printer-db#31 to add a profile.

Please consider contributing a profile if you are interested in printing more advanced output on this printer.

**Comment by saavedragusman** [comment]
Hi @mike42 how are you? the printer: Aclas pp9 https://www.aclas.tw/products/pp9x/  is compatible with your library?
