### ISSUE TITLE
Excelvan HOP-E58 QR not working

### ISSUE THREAD

**Issue by Pablo849** [mike42/escpos-php#426]
Hello.
When I try to print a QR code in Excelvan HOP-E58, it only prints multiple lines that starts with: "k1A2k1Ck....."
Maybe a compatibility issue? In printer self test, QR Code have the number 10 in "CODE BAR" list, but I have never can print a QR neither with direct ESC/POS raw data.

**Comment by mike42** [comment]
Yes, appears to be a compatibility issue, QR codes work very well if the printer supports it- see [Howto: QR Codes on receipts with escpos-php](https://mike42.me/blog/2015-04-howto-qrcodes-on-receipts-with-escpos-php). You can also use `phpqrcode` t generate a PNG and send that, if you can get images working.

Try all three methods for images: `graphics`, `bitImage`, and `bitImageColumnFormat`.

We are tracking known compatibility issues with this type of printer at receipt-print-hq/escpos-printer-db#20, and could use your input.
