### ISSUE TITLE
Demo doesn't print stdout

### ISSUE THREAD

**Issue by bedengler** [mike42/escpos-php#429]
Hi,

I've downloaded the most actual version and ran the demo.php. But it doesn't output anything (on the screen). Neither on my localhost testmachine nor online.

See for yourself:
http://dev.web-kasse.at/ESC-POS-2017/example/demo.php

This is an older version of ESC-POS-PHP (I think from 2015 - using the Escpos.php) which works fine:
http://dev.web-kasse.at/ESC-POS-Demo/example/demo.php

I've tried to change "php://stdout" to "php://output" but this also doesn't work.

The script outputs no error, there's just no output...

What could be the problem?

**Comment by sherybhatti1** [comment]
i am also facing the same issue.please anyone help my printer model is "POS-80 11.3.0.0" and printer name is "POS-80"

**Comment by bedengler** [comment]
Output to a text file works, so there's something wrong with the stream...

**Comment by mike42** [comment]
Interesting. I'll treat this as a bug. The expected behavior for running a command-line demo via the web should be an error, but your link gives blank, `200 OK` output.

```
$ curl -vvv http://dev.web-kasse.at/ESC-POS-2017/example/demo.php
*   Trying 77.244.243.55...
* TCP_NODELAY set
* Connected to dev.web-kasse.at (77.244.243.55) port 80 (#0)
> GET /ESC-POS-2017/example/demo.php HTTP/1.1
> Host: dev.web-kasse.at
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sun, 22 Oct 2017 06:36:10 GMT
< Server: Apache
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< Age: 14
< Accept-Ranges: bytes
< Connection: keep-alive
< 
* Curl_http_done: called premature == 0
* Connection #0 to host dev.web-kasse.at left intact
```

You may have a version before [this change](https://github.com/mike42/escpos-php/commit/763ed768a030db1937cc9a69e336b6dff113d17c)- People were uploading the library to their webroot and reporting the demo output as a bug, when it was meant to be redirected to a file or device.

**Comment by bedengler** [comment]
Hi, thanks for getting back. As it works by writing to a file, we have found a workaround for now. 
For your debugging I attached both folders that are on our server, so you can test yourself what's the difference. In the 2016 version the file structure is completely different so I assume it's very old...
[esc-pos-php.zip](https://github.com/mike42/escpos-php/files/1404721/esc-pos-php.zip)

**Comment by mike42** [comment]
Thanks, closed as solved.
