### ISSUE TITLE
Can't print using printer Godex G500?

### ISSUE THREAD

**Issue by buzerbeat** [mike42/escpos-php#432]
Hi,

I use sample script:

$connector = new Escpos\PrintConnectors\WindowsPrintConnector("Receipt Printer");

$printer = new Escpos\Printer($connector);
/* Barcodes */
$a = "{A012323392982";
$b = "{B012323392982";
$c = "{C" . chr(01) . chr(23) . chr(23) . chr(39) . chr(29) . chr(82);

$printer -> setJustification(Escpos\Printer::JUSTIFY_CENTER);
$printer -> setBarcodeHeight(48);
$printer->setBarcodeTextPosition(Escpos\Printer::BARCODE_TEXT_BELOW);
foreach(array($a, $b, $c) as $item)  {
    $printer -> barcode($item, Escpos\Printer::BARCODE_CODE128);
    $printer -> feed(1);
}
$printer -> cut();
$printer -> close();

can't connect or print, but when i using printer NCR 7197 Thermal successful connect and print. Whether this library didn't support printer Godex G500 Label?

Thank you

**Comment by mike42** [comment]
You are correct.

This library is compatible with ESC/POS printers, but the Godex G500 speaks [EZPL](http://www.godexintl.com/upload/media/Downloads/Manuals/en/EZPL_EN_201605_version_J.pdf), which is not the same.

**Comment by xanotoz** [comment]
anything kwow a code for work with this printer (G500)?
