### ISSUE TITLE
POS 5890-C

### ISSUE THREAD

**Issue by Aaronyny** [mike42/escpos-php#435]
I wanted to know if this driver works correctly with the POS 5890-C printer, and if this would be possible. Thank you, excellent work!

**Comment by Aaronyny** [comment]
![printer-pos 5890-c](https://user-images.githubusercontent.com/24752495/31124772-e208e030-a813-11e7-87c6-3f4f108098e5.png)

**Comment by evsar3** [comment]
I just got one of this and I'll be able to tell you in a couple of days. It's predict to arrival oct, 8th.

**Comment by evsar3** [comment]
I just received my printer and yes, it does support.
In my initial tests I can't be able to print images or bar codes.

**Comment by mike42** [comment]
This is a very common printer- I've put some time into making it work well with this driver, so most of its features are implemented.

Just so you are aware, I have looked into the barcode issue previously and concluded that it [is not implemented on the printer](https://mike42.me/blog/2017-06-the-5890-printer-does-not-support-barcodes).
 
Make sure to use the 'POS-5890' `CapabilityProfile` (see the README if you haven't heard about profiles yet) for non-ASCII character support, and one of `bitImage` or `bitImageColumnFormat` will work for images.
