### ISSUE TITLE
Load image from URL via HTTPS

### ISSUE THREAD

**Issue by JacquesLG** [mike42/escpos-php#436]
Hello,
I am trying to print an image from twitter. 
But I get an image not found error. 

Thank you very much have a good day :)

**Comment by younas-bangash** [comment]
Did you face NT_STATUS_UNSUCCESSFUL issue if yes then can you please share how you solved it?

**Comment by mike42** [comment]
This is the current behaviour- you will get a "Not Found" error if you try to print an image by URL. I'll track this as a feature request.

There is a security issue with ImageMagick which allows an attacker execute code on an unpatched system, so this feature is not completely trivial to implement.

If a URL is provided to EscposImage, I would expect a correct implementation to download the image to a tempfile, verify the magic number, then pass the tempfile to the GD or ImageMagick implementation.

See also #195.

**Comment by ShriramNarkhede** [comment]
Hi! I'd like to work on this. Can you confirm if loading via file_get_contents() is acceptable?
