### ISSUE TITLE
Works just the first time

### ISSUE THREAD

**Issue by alexleandrom** [mike42/escpos-php#438]
I am using this example in MAC with CupsPrinterConnector

```
$connector = new CupsPrintConnector("STMicroelectronics_USB_Portable_Printer");
$printer = new Printer($connector);

$printer->feed(4);
$printer->setJustification(Printer::JUSTIFY_CENTER);
$printer->setFont(Printer::FONT_A);
$printer->text("Senha C34\n");
$printer->text("Mesa 02\n");
$printer->feed(4);
$printer->cut();
$printer->close();
```
When I execute this, the printer printing correct, but when I try to execute again, nothing do.
Is there more things which I need todo? Like close or reconnect the printer?

I am using a simple thermal printer (http://www.dx.com/pt/p/portable-58mm-thermo-sensitive-bluetooth-receipt-printer-black-428536?tc=BRL&gclid=CjwKCAjw3_HOBRBaEiwAvLBbotJCvOahNXicn-A7QkALgbXdsaa05wBiXF4CsxMjZ8DGqeFyraan6RoC9-cQAvD_BwE#.Wd0HohNSyRs)

**Comment by younas-bangash** [comment]
Before printing, first time did you face or having any idea of the following error `NT_STATUS_UNSUCCESSFUL`

**Comment by alexleandrom** [comment]
How can I get this error?

**Comment by mike42** [comment]
I think your usage is correct from the PHP side. If "nothing" happens the second time, you either need to check the PHP error log, or the CUPS print queue.

Not sure if relevant, but [this](https://mike42.me/blog/2015-10-how-to-connect-a-usb-receipt-printer-up-on-mac-os-x) is a USB setup that I used on Mac/CUPS previously with success.
