### ISSUE TITLE
Please add driver: Seiko RP-D10

### ISSUE THREAD

**Issue by ratiratiani** [mike42/escpos-php#439]
Thanks for support

**Comment by mike42** [comment]
That printer is not yet tested, we rely on you checking for ESC/POS compatibility and reporting back with any bugs.

See also FAQ entry: [Can you add support for Printer X?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-you-add-support-for-printer-x).
