### ISSUE TITLE
Ability to print Peso sign ₱ on ZJ-5890K

### ISSUE THREAD

**Issue by raigeiki55** [mike42/escpos-php#443]
Hi I would ask how can is this sign(₱) in printing receipt? When I try using printing, it  displays "?".

**Comment by mike42** [comment]
To send it natively, we need a bit more info.

Can you share the make/model of your printer?

**Comment by raigeiki55** [comment]
ZJ-5890K

**Comment by tushark12345** [comment]
Same issue, on ZJIANG ZJ-5890K everything works seamlessly, but the peso symbol is not recognized.

**Comment by mike42** [comment]
So we have a complete ZJ-5890K profile called `POS-5890`. I don't think that this printer can encode a Peso sign natively, and PDF files are a bit of a heavyweight solution.

I think that the encoding of a currency symbol is something that the driver should do, so I've flagged this as an enhancement, I'm hoping that we can solve this with a custom font or small inline bitmap.

**Comment by mike42** [comment]
I wrote up some information about extending the library to print individual bitmaps inline. If you can get your symbol as an image, then you can use [this guide](https://mike42.me/blog/2018-03-how-to-print-custom-currency-symbols-on-a-receipt-printer) to print it.

We are hoping to bundle a bitmap font to use as a fallback for these situations, but it will not be available for some time.

I think the "How to I print ₱ when my printer doesn't know the symbol" part of this question is answered, so I'll close this off.
