### ISSUE TITLE
Can not print SMB from windows server but works from win10

### ISSUE THREAD

**Issue by ERESU** [mike42/escpos-php#445]
Hi @mike42

I code to print to remote printer from win 7 using SMB. But the same code can not print from windows server 2012.
Is it a bug or I do something wrong?
Please advice

Thanks

**Comment by mike42** [comment]
I have only tested Windows 7, so it's hard to be sure. Things to consider are

- Are the setups identical except for the OS? (running on the same network, firewall rules similar, etc)
- What is the OS that is sharing the printer?
- What does "can not print" mean? Is there an error? Does it give you any clues?

First thing I would try is copying a text file to the printer on the command-line. You need that to work before attempting to use PHP. Check out the comments in `example/interface/smb.php`-

```
...
 * Windows: (use an appropriate "net use" command if you need authentication)
 *  echo "Hello World" > testfile
 *  ## If you need authentication, use "net use" to hook up the printer:
 *  # net use "\\computername\Receipt Printer" /user:Guest
 *  # net use "\\computername\Receipt Printer" /user:Bob secret
 *  # net use "\\computername\Receipt Printer" /user:workgroup\Bob secret
 *  copy testfile "\\computername\Receipt Printer"
 *  del testfile
...
```

If it doesn't work, debug it. If it does, then it's likely a permissions issue.

**Comment by ERESU** [comment]
Can not print in my case, it can not to be copied to printer from php winserver, but it can be copied to printer from php win7.
