### ISSUE TITLE
NetworkPrintConnector: Connection refused - Ethernet Printer

### ISSUE THREAD

**Issue by juanxodj** [mike42/escpos-php#447]
I have an EPSON TM-U220 printer that works perfectly locally. My PC has IP (192.168.1.30) and the printer has IP (192.168.1.20). My problem arises when I upload my application to a server or hosting www.mywebpage.com .... When I want to print I throw this error: NetworkPrintConnector: Connection refused.

My autoload.php file looks like this:

```
<?php
defined('PRINTER_IP') or define('PRINTER_IP', "192.168.1.20");
defined('PRINTER_PORT') or define('PRINTER_PORT', 9100);
spl_autoload_register ( function ($class) {
	
	$prefix = "Mike42\\";
	$base_dir = __DIR__ . "/src/Mike42/";
	
	/* Only continue for classes in this namespace */
	$len = strlen ( $prefix );
	if (strncmp ( $prefix, $class, $len ) !== 0) {
		return;
	}
	
	/* Require the file if it exists */
	$relative_class = substr ( $class, $len );
	$file = $base_dir . str_replace ( '\\', '/', $relative_class ) . '.php';
	if (file_exists ( $file )) {
		require $file;
	}
} );
```

What could be the problem? As I say, locally it works perfectly.

**Comment by mike42** [comment]
PHP is running server-side, so most likely the server at your hosting provider can't see your printer at 192.168.1.20. See FAQ entry: [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/9bbc67365261af11a0ab6340e88e25cd4d8bd087/doc/FAQ.md#can-i-print-from-my-server-on-the-internet).

I am also a maintainer at [receipt-print-hq/chrome-raw-print](https://github.com/receipt-print-hq/chrome-raw-print), which solves the same issue for USB printers, and could be be improved for this use case. If you are interested in contributing, please take a look at receipt-print-hq/chrome-raw-print#3.
