### ISSUE TITLE
Set font height and width

### ISSUE THREAD

**Issue by defacto133** [mike42/escpos-php#45]
I'm using the TM-T20II and I use this function to set the font height and width

```
/* $w is in [1, 8].
 * $w = 1: same size
 * $w = 2: double width
 * $w = 3: triple width and so on ...
 * The same for $h but for height.
 */
function setSize($w, $h) {
    $res = "\x1D\x21";
    $w -= 1;
    $h -= 1;
    if ($w == 0 && $h == 0)
        return;

    return $res . chr((pow(2,4) * $w) + $h);
}
```

**Comment by mike42** [comment]
Good example.

This might not be supported by other vendors, so I'll leave `setDoubleHeight` and `setDoubleWidth` in the code as well.

**Comment by mike42** [comment]
This is now implemented, see [README.md#setTextSize($widthmultiplier, $heightmultiplier)](https://github.com/mike42/escpos-php#settextsizewidthmultiplier-heightmultiplier).

The new `example/text-size.php` shows how it works.

![2015-08-receipt](https://cloud.githubusercontent.com/assets/2080552/9025866/f4218f44-395a-11e5-8079-25472c5ad340.jpg)

**Comment by kiloamp** [comment]
hi guys super late and not sure if the right place, but i have some bootleg alibaba express printer and the setFontSize thing (in the website with the screenshot and 8, 8 as parameters) didnt work, for me the biggest size comes at 2, 2 and 8, 8 defaults to normal size --- also the lines eat into each other if they overflow so i added another $printer text line with just \n
