### ISSUE TITLE
 methods are not working

### ISSUE THREAD

**Issue by codepunkrock** [mike42/escpos-php#450]
Hello, I have managed to connect to the "Star TSP100 FuturePRNT" and I can print without any problem, I do it in the following way ...

`
require_once('../../../vendor/autoload.php');
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;
`

but the methods like setTextSize, setUnderline, barcode or bitImage do not work, my code is as follows,
`
function printTkt_1(){

    $connector = new WindowsPrintConnector("smb://192.168.1.19/BODEGA");
    $profile = CapabilityProfile::load("TSP600");
    $printer = new Printer($connector,$profile);

    $printer -> initialize();

    $tkt = $_POST['idtkt'];
    $dts = printTKTshop($tkt);

    $printer -> selectPrintMode(Printer::MODE_FONT_A);
    $printer -> text("My App\r\n");
    $printer -> selectPrintMode(Printer::MODE_FONT_B);
    $printer -> text("My App\r\n");
    $printer -> selectPrintMode(Printer::MODE_FONT_A);
    $printer -> text("My App\r\n");
    $printer -> setEmphasis(true);
    $printer -> setTextSize(8,8);
    $printer -> barcode("2541369852475",BARCODE_JAN13);
    $printer->feed(2);
    $printer->close();

    return true;
}
`
I am doing something wrong?

**Comment by mike42** [comment]
This usage is correct. STAR printers in ESC/POS emulation mode usually have fairly good compatibility- is there a programming guide online for your model of printer that you could link to so that the current output can be compared to what the printer expects?
