### ISSUE TITLE
printer working on localhost but not working in server using star TSP II

### ISSUE THREAD

**Issue by karthick1793** [mike42/escpos-php#451]
hi I am using  this code,
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\EscposImage;
 $connector = new WindowsPrintConnector("smb://Computer Name/Printer name");
$printer = new Printer($connector);
$printer -> initialize();
$printer -> text("\n");
$printer -> text("         FOO CORP Ltd.\n");
$printer -> cut();
$printer -> pulse();
$printer -> close();

**Comment by mike42** [comment]
Hi, this is a frequently asked question: [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/61dc270de7b78ce9be0d49e69163db5500f22cc9/doc/FAQ.md#can-i-print-from-my-server-on-the-internet).

PHP is server-side, so it cannot see printers on your LAN. In my experience, running PHP on a server inside your LAN is the best way to avoid this (use `smbclient` on the command-line to make sure you can print).

If you must run the printer on the Internet, then I think the [chrome-raw-print](https://github.com/receipt-print-hq/chrome-raw-print) aims to solve this permanently, but it is not yet compatible with Samba-based printing.

The linked FAQ entry lists more background and possible ways to architect around this problem.
