### ISSUE TITLE
TM T88V character encoding not correct for æ, ø, å

### ISSUE THREAD

**Issue by lkcodk** [mike42/escpos-php#456]
Hi Mike

When i print special characters like: æ + ø + å 
It prints strange symbols.

I am printing from my windows from a epson TM T88V.
I am using one of your newst packages.

Kasper

**Comment by mike42** [comment]
Interesting one. I would have expected TM T88V to work well, giving either "?" or the correct symbol.

I'll tag this as a bug.

**Comment by lkcodk** [comment]
Did you fix this error?

**Comment by mike42** [comment]
There's been no change related to this bug yet. I don't have a TM-T88V, so I can't replicate this, but quite a lot can be done without a printer in this case.

The first step is actually to verify that the `default` printer profile and modifying it for the `TM T88V`, and possibly making a new profile.

If you're interested in progressing this, then take a look at the https://github.com/receipt-print-hq/escpos-printer-db project, which we get all our data from.

**Comment by mike42** [comment]
I'll close this off, I've made an issue in the upstream `escpos-printer-db` repo, which is where this would need to be fixed.

- receipt-print-hq/escpos-printer-db#41
