### ISSUE TITLE
star TSP 700 II is not working on server but working in local ?

### ISSUE THREAD

**Issue by karthick1793** [mike42/escpos-php#457]
Couldn't print to this printer: Failed to print. Command "smbclient '//PCNAME/PRINTERNAME' -c 'print -' -N" failed with exit code 1: Connection to Jerome failed (Error NT_STATUS_UNSUCCESSFUL)

How Can i fix this issue?

**Comment by mike42** [comment]
Duplicate #451

**Comment by karthick1793** [comment]
star TSP 700 II is not working on server but working in local
hi I am using this code,
require DIR . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\EscposImage;
$connector = new WindowsPrintConnector("smb://Computer Name/Printer name");
$printer = new Printer($connector);
$printer -> initialize();
$printer -> text("\n");
$printer -> text(" FOO CORP Ltd.\n");
$printer -> cut();
$printer -> pulse();
$printer -> close();
This is my erro:
Couldn't print to this printer: Failed to print. Command "smbclient '//PCNAME/PRINTERNAME' -c 'print -' -N" failed with exit code 1: Connection to Jerome failed (Error NT_STATUS_UNSUCCESSFUL)
How Can i fix this issue?
