### ISSUE TITLE
Star TSP143

### ISSUE THREAD

**Issue by ujhgj** [mike42/escpos-php#46]
Trying to print with no luck on Star TSP143 via Ethernet, I have faced no error messages, nor anything that could give my understanding, what could be wrong.
I can print plain text via CUPS. And I can print on another printer Posiflex PP9000W via your library.
I will be very appreciated, if you could give me any clue at how I can debug this issue.

**Comment by mike42** [comment]
Can you verify whether ESC/POS emulation is enabled?

You're the first to try this particular model of printer, but other Star Micronics devices are known to work. Star has its own printer language, and their devices generally need to switched to ESC/POS mode before they will accept the commands that this driver churns out.

To quote [this manual](http://www.starasia.com/dl/manual/TSP100_SoftwareManual_En.pdf) -- p20:

    The TSP100 futurePRNT provides ESC/POS mode emulation, which can be configured in
    “TSP100 Configuration Utility”. Thus, even if your current software is designed for the
    ESC/POS mode, you will be able to use it as is, without making changes.

**Comment by ujhgj** [comment]
I got the answer from support of Star:

"Hi Alex,

The TSP100 printer is a raster only printer, this means it prints raster graphics data.

So the drivers convert data on the computer into raster format and then send it to the printer.

Because of this the printer does not have any command modes, the esc/pos command mode on the TSP100 is through emulation through the drivers. So the esc/pos commands are converted into commands the printer can understand when the print data is rasterised.

So unfortunately, there are no esc/pos emulators for the linux operating system for the TSP100 printer range.

So the printer can’t switch into esc/pos mode in Linux."

If I get it right, there's no way to use ESC/POS sequences with native drivers. 
So, the options are: 
1) to make my own driver, that will generate raster based on ESC/POS sequence,
2) or to print raster images, that look like reciepts, right away.

**Comment by mike42** [comment]
Thanks for investigating. As this driver can only print ESC/POS, I'll close this report.

A utility called `wkhtmltoimage` can convert HTML to raster images programmatically using an embedded WebKit, which might work well with your setup.

**Comment by tjunussovbee** [comment]
@mike42 ! As you became more expert :+1:  in "Thermal Printing" subject, could you give advice? 

I have also **TSP 100 model**, and found **it supports only raster data**, 
But reading their [manual](http://www.starmicronics.com/support/download.aspx?path=../support/Mannualfolder/star_graphic_cm_en.pdf), i dont understand exactly, what they mean by "raster data", is it BMP like black and white or what ?

Do you think, we could use your [print-from-html.php example](https://github.com/mike42/escpos-php/blob/master/example/print-from-html.php) + EscposImage.php ( with slight modification of ESCPOS like command `b n1 n2 ....`  according to manual it is : 
**Function  b n1 n2...**
> Transfer of raster data (automatic line feed)
> Raster data is send at (n1 + n2 x 256) bytes binary data.
> Raster data beyond the print area that is currently set is cut off.
> The deployed position of the image buffer, after deploying the data to one dot column image buffer by
> this command, will one dot column automatic line feed, and move to the left margin of the next line
> position.
> If it goes over page due to automatic line feed
> ・ Page length settings are in continuous print mode, if it exceeds the maximum page length
> (see ESC * r P n NUL command)
> ・ Page length set in the specified page length mode, and if it exceeds the specified page length, and
> print the data up to the end page, to process as the first line of data for the next page.
> In addition, data expansion is performed by overwriting processing (OR processing) the current image
> buffer data.
> For the set raster print color, the deployment image buffer is described below

p.s As i understand, Star TSP100, if i send prepared binary data to USB ( /dev/usb/lp1 ) some commands (  they look like almost ESCPOS ), with one exception after all istead of regular ASCI string, i need send RASTERIZED image of my Characters ?

Thank you in advance for your help in this matter

**Comment by ujhgj** [comment]
We end up with generating PDF and printing it using CUPS.
