### ISSUE TITLE
TM T70II Bluetooth

### ISSUE THREAD

**Issue by cuisineje** [mike42/escpos-php#461]
Do you have a sample to talk to TM T70II thermal epson printer over bluetooth?

**Comment by mike42** [comment]
There's currently [no bluetooth examples](https://github.com/mike42/escpos-php/blob/61dc270de7b78ce9be0d49e69163db5500f22cc9/README.md#interfaces-and-operating-systems) in the repository.

I don't have a Bluetooth printer, but I've heard that you can get them to appear as file on Linux (`FilePrintConnector`). I would first try CUPS (`CupsPrintConnector`) for the superior google-ability of the problem, but if you have Windows-only, I've got no suggestions.

If you get it working, I would be most happy to review any code or notes and get it into the repo, as this question has been asked [before](https://github.com/mike42/escpos-php/issues?q=bluetooth).

**Comment by JefferyHus** [comment]
I am struggling in this too, couldn't make it work, and the problem is that the printer detected doesn't even have a folder on windows.

**Comment by cuisineje** [comment]
I have replaced the TM-T70II with TM-m30 wifi printer and its a breeze and I had wasted weeks of my time to get the Bluetooth printer work for me with ESC commands

**Comment by JefferyHus** [comment]
Im using currently a TM-T20II, the printer does print if I use the driver software or even click the "test the printer" button, I used the commands and got no errors yet it isn't priting, even `copy` command returns true then when I go to the pending list I couldn't find any. I work under windows 10

**Comment by JefferyHus** [comment]
I have come to make it work, the command I used was "type foo.txt > LPT1" and it has printed the file

**Comment by mike42** [comment]
@JefferyHus - In `escpos-php`, I think you can achieve the same with this connector setup-

```php
$connector = new WindowsPrintConnector("LPT1");
```

**Comment by JefferyHus** [comment]
@mike42 I have come to fix it and yes I used ```php$connector = new WindowsPrintConnector("LPT1");```, thanks for your reply :)
