### ISSUE TITLE
Printer DYMO450 LabelWriter

### ISSUE THREAD

**Issue by jecorrales3** [mike42/escpos-php#462]
Hi, 
I've read your repository and I found this "**If you use any other printer with this code, please let us know so that it can be added to the list.**". 

I'm here because I've developed my project on base of this printer, and I get it a little problem with the use, because I've developed printing from the client(AngularJS) a section of HTML, so, when I'm going to print my Label, "I can press the button "cancel" on the preview print of my navigator that in this case is Chrome" And I need that always the label will be printed, and not like one register and nothing else!

So, I need find how can I print directly on my printer(after that I've registered) without use an intermediator as Chrome.

Thanks! I hope that you can help me!

**Comment by jecorrales3** [comment]
@mike42 

Hi, I'm here again,

I've prove on four different printers:

- HP LaserJetP1102w (USB and WIFI)
- EPSON455Series (Only Wifi, I coudn't prove with USB)
- Dymo Label Writer 450 Turbo (Usb)
- Dymo Label Writer 450 (Usb)
- Brother Ql-700 (Usb)

With the printers in WIFI it works, but, when I use the printers with USB it doesn't work, this is my code, please Help Me:
```

`
<?php
require __DIR__ . '/ticket/autoload.php'; 
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

$nombre_impresora = "smb://JOHAN-ROTUMARK/DYMOLabelWriter450Turbo";
echo "Impresora: " . $nombre_impresora;

$connector = new WindowsPrintConnector($nombre_impresora);
$printer   = new Printer($connector);

if ($connector == true && $printer == true)
{
  echo "<br>It's ok for printer!";

  $printer->text("
  Hi world yte.m
  ");
  
  $printer->feed();
  $printer->cut();
  $printer->pulse();
  $printer->close();
}
else {
  echo "It coudn't print from your Server";
}

?>
`


```

**Comment by jecorrales3** [comment]
Hey @mike42 Can you help me please, with that printer, what is the cause of that can't print from CMD?

**Comment by mike42** [comment]
I'm not sure you're going to get a good answer to this.

It's always up to the developer to build a setup which is capable of conveying raw data to the printer. We print server-side, and you've done the right thing to try to run some commands manually to deliver a raw print.

You've found that you can't reliably deliver a raw print from the command-line. The issues would be between the printer & the OS, so it's not a library issue, and thus doesn't belong `escpos-php` issue tracker.

Lastly, I don't think the DYMO450 is an ESC/POS printer, so I don't expect that the output of this library will work.
