### ISSUE TITLE
Printer tested: Xprinter XP-90 / Xprinter XP-58 Series

### ISSUE THREAD

**Issue by KaitoJM** [mike42/escpos-php#463]
hi can you add a device Xprinter XP-90 or XP-58  series on availability please :)

**Comment by jlnxMX** [comment]
Did you Make it work with Xprinter XP-90 or XP-58 series ???? @KaitoJM 
I want to implement this project and I'm buying printers but I want to know XP-80 or XP-58 are compatible

**Comment by marlexladag** [comment]
This one already works. Thanks @mike42 !

**Comment by mike42** [comment]
Updated title based on the info from @marlexladag - this will appear on the list of known working printers for the next release.

We don't have a specific profile for this printer, so output of images and special characters will be limited. If you want to help improve the output, then please follow the instructions on this page to get this printer includes in `escpos-printer-db`!

- https://github.com/receipt-print-hq/escpos-printer-db/blob/master/doc/add-your-printer.md
