### ISSUE TITLE
 RETAIL POS 100 is not working on cloud base

### ISSUE THREAD

**Issue by karthick1793** [mike42/escpos-php#464]
I am using retail pos 100  printer

error log:
Couldn’t print to this printer: Failed to print. Command “smbclient ‘//macappstudio5/RETAIL-POS-100’ -c ‘print -’ -N” failed with exit code 1: Connection to macappstudio5 failed (Error NT_STATUS_UNSUCCESSFUL)

**Comment by mike42** [comment]
I'm assuming this is the same issue as #451, so I'll close this off. If you have extra info to add, you can update or comment there.
