### ISSUE TITLE
Question: Is it possible to setup mobile devices to print directly over wifi?

### ISSUE THREAD

**Issue by ajcastro** [mike42/escpos-php#465]

**Comment by mike42** [comment]
You need a PHP server somewhere, so it depends on what type of printer, mobile device and server hardware you have available.

If you had something like iPad -> Raspberry Pi as WiFi AP + PHP web app -> Epson Printer, then this driver will work a charm, but if you are writing a native app and have a WiFi printer, then a PHP library will not be much help.
