### ISSUE TITLE
Problem number of characters per line

### ISSUE THREAD

**Issue by Julio1961** [mike42/escpos-php#466]
Hello!
Im having a curious bug that I have to fix it but can’t find a way
On same settings and php file:

_$printer -> setFont(Printer::FONT_B);
$printer -> text("********************************\n");
$printer -> text("12345678901234567890123456789012\n");
$printer -> text("--------------------------------\n");
$printer -> setTextSize(2, 2);
$printer -> text("Total: 40.00 EUR\n");_

My chinese zj5890 manages to put the 32 characters as normal but on my EPSON T20ii it doesnt…
On the first it fits the 32 characters on per line but on the epson only 31 -.-‘
If I switch to the other font A, the 5890 and the EPSON both fits 42 characters as normal! So weird why it happends only in the font B...

Heres the receipts with 58mm paper https://ibb.co/ngOeoR

I know this is a "not relevant" issue, but I really need to put that font working with 32 characters per line
Theres no other way for me! Mike suggested that maybe there's a command esc pos to adjust The left margin...I'll see on the manual if there's any code
Can someone test this code with their T20II(on 58mm paper) to see if it happends the same? Or what code should I use to adjust margin
Any other idea will be very apreciated!
Thank you very much ;)

**Comment by Julio1961** [comment]
With solutions from #130 issue continues to fail...
https://imgur.com/a/K2rtP
I'm running out of ideas...
If somebody solve me this problem I'll give a bounty $

**Comment by Julio1961** [comment]
Ok its solved
Bought another model of EPSON that prints the 32 characters per line

**Comment by mike42** [comment]
Glad to hear this is solved.

It could be a limitation of the printer if `ESC W`, `GS L` did not expand the print area. These are available in `escpos-php` as `setPrintLeftMargin($margin)` and `setPrintWidth($width)`.
