### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by awarak** [mike42/escpos-php#467]
![image-0-02-04-771e21e5af09105c198c59782112271fe0f709f2c422fd285e06dc6bb93e981d-v](https://user-images.githubusercontent.com/33783316/32980577-155c3718-cc7a-11e7-964c-91e2b37bcf44.jpg)
dears i use this printer the name write over it is custom can i use it with your codes please help what need to print to this printer
![image-0-02-04-5e647b3664fd1a69c6f38089acb2307d08863e1d0e3003bb31feb2ff214cc54c-v](https://user-images.githubusercontent.com/33783316/32980576-0b6ce234-cc7a-11e7-9f98-b2a8373d512d.jpg)

**Comment by mike42** [comment]
Assuming this is part of #468, closing as duplicate.
