### ISSUE TITLE
online hosted escpos-php library. not working

### ISSUE THREAD

**Issue by javacomtech1** [mike42/escpos-php#469]
escpos-php library is working locally  but i hosted by dydns(port fowarding) with local server. i got error like this :

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: connector

Filename: views/print_pharm.php

Line Number: 21
A PHP Error was encountered

Severity: 4096

Message: Argument 1 passed to Mike42\Escpos\Printer::__construct() must be an instance of Mike42\Escpos\PrintConnectors\PrintConnector, null given, called in C:\xampp\htdocs\jctmart\application\views\print_pharm.php on line 21 and defined

Filename: Escpos/Printer.php

Line Number: 352

Fatal error: Call to a member function write() on a non-object in C:\xampp\htdocs\jctmart\escpos\src\Mike42\Escpos\Printer.php on line 698

**Comment by mike42** [comment]
You have an undefined variable in your PHP code. `Message: Undefined variable: connector`. This is not appear to be happening in the driver or examples, so I would encourage you to check that you are using the driver correctly.

First confirm that you have tested printing on the command-line from your server, and then step through the README to use the appropriate connector to transport the data to your printer, based on the host computer and interface.

If you have tried debugging this with the available resources and don't believe they are sufficient, please post a [minimum working example](https://stackoverflow.com/help/mcve) that shows the problem and I'll re-open this issue.

**Comment by sychowaves** [comment]
cat try it [how install in XAMPP](https://github.com/mike42/escpos-php/issues/869)
