### ISSUE TITLE
Codeigniter issue.

### ISSUE THREAD

**Issue by Subhasish10** [mike42/escpos-php#470]
Escpos work properly .. But when i put this into my Codeigniter framework problem start .....

after load autoload.php steel it show this error massage.."
**Class 'Mike42\Escpos\PrintConnectors\WindowsPrintConnector' not found"**

I am new in codeigniter ...
so please help me out.. please

**Comment by mike42** [comment]
Sounds like you aren't auto-loading correctly. This package is pulled in with composer- a quick web search for "codeigniter composer dependency" suggests that auto-loading composer packages is supported by CodeIgniter.

I think we're packaged correctly, so I would encourage you to check out the CodeIgniter docs or follow up with their support channels, and I'll close this issue off as not specific to escpos-php.
