### ISSUE TITLE
Printer tested: Bematech-4200-TH

### ISSUE THREAD

**Issue by ebnerdeath** [mike42/escpos-php#472]
Testei hoje e funcionou esse driver na impressora Bematech-4200-TH utilizando somente as impressões modo texto (sem imagens ou outras funcionalidades).

**Comment by mike42** [comment]
This printer appears to have an ESC/POS emulation mode, I'll add it to the list.

**Comment by gcardozo2809** [comment]
Hi @ebnerdeath - I am trying to setup a Bematech MP-4000 TH and I keep on getting random characters instead of actual text. Would you please share how you set it up and the profile/ connector you used? Thank you!

**Comment by ebnerdeath** [comment]
Hi @gcardozo2809  of course yes ... I'm using the ethernet example for this
follow the code used in my application

        $connector = new NetworkPrintConnector("192.168.25.8", 9100);
        $printer = new Printer($connector);
        $tux = EscposImage::load(__DIR__ ."\logo_os.png", false);
    
        $printer->setJustification(Printer::JUSTIFY_CENTER);
        $printer->setPrintLeftMargin(0);
        $printer -> text("NÃO É DOCUMENTO FISCAL\n");
        $printer -> text("DOCUMENTO AUXILIAR DE VENDA-ORDEM DE SERVIÇO\n");
        $printer -> selectPrintMode(Printer::MODE_FONT_A);
        $printer -> text("\n");
        $printer -> setTextSize(1,2);
        $printer -> text("NÚMERO DO DOCUMENTO: ".$id."\n");
        $printer -> text("\n");
        $printer -> setTextSize(1,1);
        $printer->setJustification(Printer::JUSTIFY_LEFT);
        $printer -> text("\n");
        $printer -> text("IDENTIFICAÇÃO DO ESTABELECIMENTO EMITENTE\n");
        $printer -> text("------------------------------------------\n");
        $printer -> bitImage($tux, Printer::IMG_DOUBLE_WIDTH | Printer::IMG_DOUBLE_HEIGHT);
        $printer -> text("AGNEL HELENA DA SILVA ROCHA - EIRELI - E\n");
        $printer -> text("CNPJ: 07.360.405/0001-80 - IE: 90337586-82\n");
        $printer -> text("FONE: (41) 3642 4236\n");
        $printer -> text("ATENDENTE: ".$atendente."\n");
        $printer -> text("\n");
        $printer -> text("INFORMAÇÕES DO CLIENTE\n");
        $printer -> text("------------------------------------------\n");
        $printer -> text("NOME:".$nomeCliente."\n");
        $printer -> text("CNPJ/CPF: ".$cnpjcpf."\n");
        $printer -> text("CIDADE/UF: ".$cidade."/".$uf."\n");
        $printer -> text("FONE: ".$fixo." - CELULAR: ".$celular."\n");
        $printer -> text("\n");
        $printer -> text("INFORMAÇÕES DO EQUIPAMENTO\n");
        $printer -> text("------------------------------------------\n");
        $printer -> text("NOME: ".$nome_equipamento."\n");
        $printer -> text("MARCA: ".$marca_equipamento."\n");
        $printer -> text("MODELO: ".$modelo_equipamento."\n");
        $printer -> text("CARACTE/ACESSORIOS: ".$acessorios."\n");
        $printer -> text("NÚMERO DE SÉRIE: ".$num_serie."\n");
        $printer -> text("SENHA: ".$senha."\n");
        $printer -> text("DEFEITO: ".$defeito."\n");
        $printer -> text("\n");
        $printer -> text("RELAÇÃO DE ITENS\n");
        $printer -> text("------------------------------------------\n");
        $printer -> text("Código   Descrição\n");
        $printer -> text("Qtde  Unid  Unitário  Desconto Tot.Item\n");
        $printer -> text("------------------------------------------\n");
        $printer->setJustification(Printer::JUSTIFY_LEFT);
        $printer -> text("\n");
        $printer -> text("Assinatura________________________________\n");
        $printer -> text("##########################################\n");
        $printer -> text("##        NÃO É DOCUMENTO FISCAL        ##\n");
        $printer -> text("##  NÃO É VÁLIDO COMO RECIBO E COMO     ##\n");
        $printer -> text("##        GARANTIA DE MERCADORIA        ##\n");
        $printer -> text("##        NÃO COMPROVA PAGAMENTO        ##\n");
        $printer -> text("##     EXIJA A NOTA FISCAL NA COMPRA    ##\n");
        $printer -> text("##########################################\n");
        $printer->setJustification(Printer::JUSTIFY_CENTER);
        $printer -> text("JEBSoftware - Todos os direitos reservados\n");
    
        $printer -> cut();
        
        /* Close printer */
        $printer -> close();
