### ISSUE TITLE
star TSP100 futurePRINT

### ISSUE THREAD

**Issue by jotechjoab** [mike42/escpos-php#476]
The Library Is not working for this printer star TSP100 futurePRINT

**Comment by mike42** [comment]
We've had success reported, can you confirm that your STAR printer is set to ESC/POS emulation mode,and share the steps you took to try to get this working, including for example:

- Some information about your platform and setup
- A command that transports the "Hello World" to your printer
- The PHP snippet that you were using
- A description of what happened when you ran it (error? bad output?

**Comment by peterkuo02** [comment]
@mike42 
Thanks for the wonderful project.
I've tried to run the example/text-size.php, the printer did trigger the drawer but the data is not printing.
I also ran demo.php with the correct printer setting and it was not printing as well.
The printer is Star TSP100III futurePRNT.(LAN)
