### ISSUE TITLE
can not print image.

### ISSUE THREAD

**Issue by chaiwatt** [mike42/escpos-php#477]
Dear sir, I would like to print image with sample code. I tried several method but getting different ressult as below code, really no luck. Appreciated advise what I'm doing wrong, Thank you.

Attached 
Garbled: https://i.imgur.com/G8B8V1L.jpg
UnableToOpenBlob: https://i.imgur.com/jP8hGvA.png

```
<?php
require __DIR__ . '/../../autoload.php';
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\PrintBuffers\ImagePrintBuffer;
use Mike42\Escpos\GdEscposImage;

try {
    $connector = null;
    $connector = new WindowsPrintConnector("ThermalPrinter");
    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");

    //====not working===> return Couldn't print to this printer: UnableToOpenBlob `logo.png': No such file or directory 
    /*
    $logo = EscposImage::load("logo.png");
    $printer -> graphics($logo);
    */

    //======not working===> return Cannot instantiate abstract class Mike42\Escpos\EscposImage
    /*
     $logo = new EscposImage("logo.png");
     $printer -> bitImage($logo);
    */
    //======not working===>  Printable with garbled instead image.
    /*
    
    $ticketim = imagecreatefrompng("logo.png");
    $logo = new GdEscposImage();
    $logo -> readImageFromGdResource($ticketim);
    $printer -> graphics($logo);
   */

    //======not working===> return Couldn't print to this printer: UnableToOpenBlob `logo.png': No such file or directory 
    /*
    $logo = EscposImage::load("logo.png", false);
    $printer -> bitImageColumnFormat($logo);
    */

    //======not working===> return Couldn't print to this printer: UnableToOpenBlob `logo.png': No such file or directory 
    /* 
    $logo = EscposImage::load("logo.png", false);
    $printer -> bitImage($logo);
    */

    $printer -> feed(7);
    $printer -> cut();
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}


```

**Comment by chaiwatt** [comment]
Problem fixed, just use command:
    $logo = EscposImage::load(dirname(__FILE__) . "/logo.png", false);
    $printer -> bitImage($logo);

**Comment by Stenerson** [comment]
Glad you were able to solve this. Thanks for updating the issue for posterity! 🥂

**Comment by mdestafadilah** [comment]
what bold mean dirname(FILE) ??

**Comment by siamitai** [comment]
Buenas tardes tengo el mismo problema. Podrían ayudarme?? todo imprime bien hasta que intento colocar el logo. Saludos

Fatal error: Uncaught Error: Cannot instantiate abstract class Mike42\Escpos\EscposImage in C:\Program Files\NetMake\v922\wwwroot\sc

Codigo utilizado:

require_once($this->Ini->path_third. '/Mike42/autoload.php');
$connector = null;
$var 	   = "EPSONTMT20II";  // nombre impresora

$connector = new Mike42\Escpos\PrintConnectors\WindowsPrintConnector($var);
$printer   = new Mike42\Escpos\Printer($connector);

$conectorimagen=new Mike42\Escpos\EscposImage;
$logo = EscposImage::load(Mike42\src\Mike42\Escpos\resources. "/logo.png", false);
$printer -> setJustification(Printer::JUSTIFY_CENTER);
$printer -> bitImage($logo);
	


/* Cortar Papel  */
$printer -> cut();
/* Close printer */
$printer -> close();

**Comment by frod809** [comment]
> Problem fixed, just use command: $logo = EscposImage::load(dirname(**FILE**) . "/logo.png", false); $printer -> bitImage($logo);

Hi, I'm having the same issue, I don't understarnt the (dirname(FILE) directive, thanks.

**Comment by mdestafadilah** [comment]
> > Problem fixed, just use command: $logo = EscposImage::load(dirname(**FILE**) . "/logo.png", false); $printer -> bitImage($logo);
> 
> Hi, I'm having the same issue, I don't understarnt the (dirname(FILE) directive, thanks.

dirname is php builtin function , FILE is PATH your file.

**Comment by frod809** [comment]
> > > Problem fixed, just use command: $logo = EscposImage::load(dirname(**FILE**) . "/logo.png", false); $printer -> bitImage($logo);
> > 
> > 
> > Hi, I'm having the same issue, I don't understarnt the (dirname(FILE) directive, thanks.
> 
> dirname is php builtin function , FILE is PATH your file.

Thank you very much my friend.
