### ISSUE TITLE
Add support for the printer Omniprint 9500II

### ISSUE THREAD

**Issue by dhanasekarperiaswamy** [mike42/escpos-php#486]
Hi Mike, 

I have an issue with escpos, below language characters are not printed.

Languages | Not Printed Characters
-- | --
Romanian | Ș | ș |   |   |   |  
Vietnamese | í | ị |   |   |   |  
Slovak | Ĉ | ĉ | Ľ |   |   |  
Russian | Ѣ | ѣ |   |   |   |  
Hungarian | Ĉ | ĉ | Ľ | ľ |   |  
Czech | Ľ |   |   |   |   |  
Bulgarian | Ѣ | ѣ |   |   |   |  
Greek | κ |   |   |   |   |  
Chinese | ™ | ® | ° |   |   |  

Apart from the capital letters mentioned above, corresponding small letters also were not printed. I'm using the printer Omniprint 9500II and escpos-php version 1.6. Could you help me to solve this issue.
Thanks!

**Comment by mike42** [comment]
This issue is very specific. Would you mind sharing which language/script you are mainly interested in printing?

I would also like to see a minimal code snippet that shows how you are using the driver, and a link to the programming guide if it is published online by the vendor.

**Comment by mike42** [comment]
Closing this off as inactive. To get really good language support for an ESC/POS printer, it needs an accurate profile in our upstream project [receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db). Check there for details on what information you need to submit a profile.

New profiles from that project are included in `escpos-php` with each minor release.
