### ISSUE TITLE
How to draw line?

### ISSUE THREAD

**Issue by cloe2291** [mike42/escpos-php#489]
how to print straight line?

FirstLine                           100.00
bmer                               1000.00
--------------------------------    <= like this 

without breaking anything.

**Comment by Stenerson** [comment]
I’m printing lines like this on my receipts by simply printing dashes.

`$printer -> text("-------------------------\n");`

If you want to go across the whole width of the page you’ll need to check how many characters your specific printer supports. I think my printer is 34 wide for FONT_A and 40 for FONT_B.

I’m going to close this for now but if you’re having issue with this, please add some more specifics/code and reopen. Thanks!

**Comment by fosfozol** [comment]
$printer->textRaw(str_repeat(chr(196), 40).PHP_EOL);
