### ISSUE TITLE
Print in times without margins

### ISSUE THREAD

**Issue by Stenfrank** [mike42/escpos-php#492]
It's the same code but at the moment the margins and the aligned ones fail

Attached code:

public function printDocument($id, $printer = '/dev/usb/lp0') {
        $headerDocument = HeaderDocument::find($id);
        
        try {
            $connector = new FilePrintConnector($printer);
            $printer = new Printer($connector);
            
            $printer->selectPrintMode(Printer::MODE_EMPHASIZED);
            $printer->setJustification(Printer::JUSTIFY_CENTER);
            $printer->text(config('app.name')." v".env('APP_VERSION')." \n");
            $printer->text("Documento de ".strtolower($headerDocument->typeDocument->name)." #{$headerDocument->id}\n");
            
            $printer->text("Productos\n");
                
            $printer->selectPrintMode(Printer::MODE_FONT_A);
            $printer->setJustification(Printer::JUSTIFY_LEFT);
            $printer->text($this->textTwoPrint(['Producto', 'Cantidad'], 42));
            
            $printer->selectPrintMode(Printer::MODE_FONT_B);
            
            foreach (DetailDocument::where('header_document_id', $headerDocument->id)->get() as $key => $detailDocument) {
                $printer->text($this->textTwoPrint([$detailDocument->product->name, $detailDocument->quantity], 56, '.'));
            }
            
            $printer->feed();
            $printer->setJustification(Printer::JUSTIFY_CENTER);
            $printer->text("Registrado por: {$headerDocument->user->name}\n");
            $printer->text("Fecha y hora: {$headerDocument->created_at}\n");
            
            $printer->selectPrintMode();
            $printer->cut();
            $printer->close();
        }
        catch (\Exception $e) {
            Alert::info(
                "El documento #{$headerDocument->id} no se pudo imprimir ".$e->getMessage(),
                'Registro documento'
            )->persistent("Close");
        }
    }

[Attached image](https://drive.google.com/open?id=1BnOVKXf46-6mGexKUpbubdLjWawwfWhvQw)

**Comment by mike42** [comment]
Link to image is a 404.

- Which model of printer are you using?
- Can you produce a minimal, self-contained example that demonstrates the problem? I can't run your example easily because it it calling out to your own database which could be returning anything.

**Comment by Stenfrank** [comment]
Sorry for the delay, I leave here the photo of the error and the model of the printer  [error](https://ibb.co/eJZvY7) printer EPSON model M147C, It is the following example [Example](https://github.com/mike42/escpos-php/blob/development/example/qr-code.php)

**Comment by mike42** [comment]
So I'm guessing your M147C doesn't support QR codes using the command that this library uses. You should consider gathering information and making a profile upstream for future users.

We have a deducted project for collecting printer compatibility information:

- https://github.com/receipt-print-hq/escpos-printer-db

Alternativey, try deploying `phpqrcode` and printing images instead. I've blogged about this, but haven't written code to make it available as a fallback.

- https://mike42.me/blog/2015-04-howto-qrcodes-on-receipts-with-escpos-php
