### ISSUE TITLE
Thermal Printer 80mm - XP-370B 

### ISSUE THREAD

**Issue by zacka32** [mike42/escpos-php#493]
hi can you add a device Xprinter XP-370B  series on availability please :)

**Comment by mike42** [comment]
I'm not sure whether you are reporting that your printer works with this driver or not.

If so, could you please briefly explain which features worked, and which didn't? The main things to check are barcodes, images, and formatting.

If you haven't tested it, then check with the vendor documentation for ESC/POS support, and then step through the README. You begin by trying to send it some text on the command-line, then move up to sending a Hello World receipt.

If your printer doesn't support ESC/POS, then it won't work with this library.

**Comment by Axliyor** [comment]
hi, I have monitored the commands sent to the 370b via rs232 via serial, they are as follows

![2022-07-01_130220](https://user-images.githubusercontent.com/35271442/176852118-f9bbe77a-f5ac-4f76-99b3-3e900036a214.png)
they are compatible with TSPL, I thought someone would need this info

[TSPL_TSPL2_Programming_Jan_2017.pdf](https://github.com/mike42/escpos-php/files/9027228/TSPL_TSPL2_Programming_Jan_2017.pdf)
