### ISSUE TITLE
Cannot Print to Local Printer setup as Network printer

### ISSUE THREAD

**Issue by cbonifacio** [mike42/escpos-php#496]
Hi Mike,

I have setup an EPSON Tm T82 Printer in my Windlows 10 Machine as a Local Printer and shared it. Locally on my XAMMP i can print using the SMB.php example but when i upload it to my website and run the same file i get an error "Couldn't print to this printer: Failed to Print. Command "smbclient" //****/EPSON -c 'print'"

    $connector = new WindowsPrintConnector("EPSON");
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();

can you help me out? 

Thanks in Advance

**Comment by mike42** [comment]
The printing is done server-side, so I don't expect that your server can see your printer.  This is a common question, and is addressed in the FAQ- [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-from-my-server-on-the-internet).

Personally, I deploy to a webserver on the LAN to make sure that the server can see the printer. I just wrote some information about Linux/SMB printing at #503 which contains some test commands which would be relevant to your setup if you moved the server into the LAN.
