### ISSUE TITLE
Printer tested: Nyear NP100 printer thermal

### ISSUE THREAD

**Issue by juliopaulo** [mike42/escpos-php#499]
I tested this code with Nyear NP100 printer thermal 

the drive can be downloaded from https://www.posnewland.com/file-category/?catid=1135

**Comment by mike42** [comment]
Thanks, noted. Have you tried printing anything like barcodes or images?

**Comment by juliopaulo** [comment]
yes, barcodes yes, images not yet, i'm trying it
