### ISSUE TITLE
Greek character printing

### ISSUE THREAD

**Issue by stadem** [mike42/escpos-php#50]
Hello, I am using P-822D Thermal printer and everything is working great except from printing Greek characters (the are displayed as chinese)

Is there any settings i can do?

Thank you

**Comment by mike42** [comment]
Hi, I think you're the first person to try getting this printer working (definitely the first to try it in Greek anyway).

We most likely need to assemble a `CapabilityProfile` including the correct way to access a Greek **code page** on your printer. The driver is probably using the [`DefaultCapabilityProfile`](https://github.com/mike42/escpos-php/blob/master/src/DefaultCapabilityProfile.php) (for Epson-branded printers) at the moment, which would explain the strange output.

Do you have any documentation available which contains a list of supported code pages for the P-822D? A quick Google search doesn't turn up much.

**Comment by stadem** [comment]
Hello, thank you for your answer.

The code page of P-822D is :
![p-822d](https://cloud.githubusercontent.com/assets/6703135/9337280/226e6604-45e7-11e5-980b-cf0a2c115d1d.png)

**Comment by mike42** [comment]
Perfect,

I'll post the CapabilityProfile and a test receipt when ready. Hopefully we can get this model of printer working.

**Comment by stadem** [comment]
Great, thank you.

**Comment by mike42** [comment]
Ok, I've added a profile matching this list of code pages. Can you pull and  let me know what the output of the example `example/specific$ cat 50-P-822D-greek.php` is?

(If it doesn't render correctly yet, then I'll get you to run some code snippets for debugging)

````php
<?php
/* Example of Greek text on the P-822D */
require_once(dirname(__FILE__) . "/../../Escpos.php");

// Setup the printer
$connector = new FilePrintConnector("php://stdout");
$profile = P822DCapabilityProfile::getInstance();
$printer = new Escpos($connector, $profile);

// Print a Greek pangram
$text = "Ξεσκεπάζω την ψυχοφθόρα βδελυγμία";
$printer -> text($text . "\n");
$printer -> cut();

// Close the connection
$printer -> close();
````

**Comment by stadem** [comment]
I think that the problem is on device code page. 
Only capital letters works fine.

After some tests...
![001](https://cloud.githubusercontent.com/assets/6703135/9417277/897e9346-4853-11e5-8100-7be481dbd59c.png)

**Comment by mike42** [comment]
Hmm. It's not at all obvious to me why Chinese text appears when your printer tries to work with these code pages.

From what I can find about related models on Google, DIP switches are something we may need to tweak here.

Two things-
- What platform & interface are you printing from?
- Can you flip the SW-4 DIP switch ('two character code pages') and re-print the tables of Greek code pages?

**Comment by mike42** [comment]
I'm closing this issue off, as it's likely to relate to the reporter's printer config. You may need to contact the vendor for advice about how to disable this Chinese text output.

For others, the general way to print most European languages with this driver is to simply send in UTF-8-

```php
<?php
require __DIR__ . '/../../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\CapabilityProfiles\DefaultCapabilityProfile;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

// Setup the printer
$connector = new FilePrintConnector("php://stdout");
$profile = DefaultCapabilityProfile::getInstance();
$printer = new Printer($connector, $profile);

// Print a Greek pangram
$text = "Ξεσκεπάζω την ψυχοφθόρα βδελυγμία";
$printer -> text($text . "\n");
$printer -> cut();

// Close the connection
$printer -> close();
```

Result (TM-T20II):

![greek-text-snippet](https://cloud.githubusercontent.com/assets/2080552/14759843/b65bf6dc-0974-11e6-8faa-ac33c3f9a2f2.png)

In the case of the P-822D, `DefaultCapabilityProfile` is swapped with `P822DCapabilityProfile`.

See also #62

**Comment by kapsampelis** [comment]
Worked for me with NetworkPrintConnector

  $text = iconv('UTF-8', 'ISO-8859-7', "ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΧΩ");
  $printer -> textRaw($text ."\n");
