### ISSUE TITLE
TM-U220D Cannot Print Image? 

### ISSUE THREAD

**Issue by mdestafadilah** [mike42/escpos-php#501]
Hi, Mike, i'm impresive with your library.. 

this library cannot support for "D" series image printing?

Thanks.

**Comment by mike42** [comment]
Have you tried `bitImageColumnFormat()`? I use a TM-U220B and found that it was the only graphics mode which I could use[1] (It wasn't very reliable, but that could be the parallel cable)

[1] http://mike42.me/escpos-printer-db/#profiles/TM-U220

**Comment by mdestafadilah** [comment]
Not yet... i'm using `bitImage()` `bitImageColumnFormat()` .. the result is same...

**Couldn't print to this printer: File 'http://localhost/simrs/assets/img/logo_etiket.png' does not exist, or is not readable.** 

am i missing something??

**Comment by mike42** [comment]
Yes, nothing to do with printers actually. `EscposImage` uses accepts a local filename, not a web URL.

See `examples/receipt-with-logo.php` for correct usage. It starts like this:

```php
$tux = EscposImage::load("resources/tux.png", false);
```

And this would work too:

```php
$tux = EscposImage::load(__DIR__ . "/resources/tux.png", false);
```

**Comment by mdestafadilah** [comment]
Not yet succefull... the result of print like this.. the 'alien character' ... any idea?
![whatsapp image 2018-01-16 at 13 09 40](https://user-images.githubusercontent.com/5575882/34974298-da33c7dc-fabe-11e7-88ff-59472d8f9485.jpeg)

**Comment by mdestafadilah** [comment]
still finding what wrong with this printer, Epson TM-U220D ...

**Comment by mdestafadilah** [comment]
Yes Finding it, from here: [https://github.com/mike42/escpos-php/issues/125](https://github.com/mike42/escpos-php/issues/125)

```
      $path = dirname(__FILE__).'/tux.png'; //exit($path);
      $img_logo = EscposImage::load( $path, false); //exit(var_dump($img_logo));

      $this->check_connection();
      $this->printer->setJustification(Printer::JUSTIFY_CENTER);
      $this->printer->selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
      $this->printer->bitImageColumnFormat($img_logo, Printer::IMG_DOUBLE_WIDTH | Printer::IMG_DOUBLE_HEIGHT);
```
Thanks Mike, you are my hero!!
