### ISSUE TITLE
WindowsPrintConnector Buggy with Star TSP100 Eco

### ISSUE THREAD

**Issue by RickyYoder** [mike42/escpos-php#504]
I just got this receipt printer, and was shocked that it works with this software. However, every time I try to print a message, the letters "VA" print out on a line above the text I wanted to print. Not to mention I need to add a TON of new lines after the text I want to print in order for it to actually become visible when it feeds. I'm using Windows 10 x64 with a WindowsPrintConnector.

Is there anything I may be doing wrong?

Update: It also doesn't output any graphics. I copied the tux example verbatim and all I get are a bunch of ASCII characters instead of the actual image. :(

Update 2: Also don't think the cut() function is working..

**Comment by hamza-younas94** [comment]
Same problem with me on Windows 7
Model: TSP 100 Future

**Comment by mike42** [comment]
`VA` has been mentioned before. I believe that is the cut command being ignored and treated as text.

Can you post a full snippet that shows how you are initializing the printer, and also confirm that you are in ESC/POS emulation mode and not STAR command mode?

**Comment by RickyYoder** [comment]
Contacted Star support and they told me how to put it in ESC/POS mode. The USB version I have works great now. I'm also having issues with a LAN version of a Star printer now, however. I will post a new issue if I can't figure it out. Thanks Mike!
