### ISSUE TITLE
StarTSP100 Barcode / QR Code - Windows

### ISSUE THREAD

**Issue by hamza-younas94** [mike42/escpos-php#505]
i am trying to  print barcode unfortunately its not printing and cut function also not working 

From printer application i have tried to print the barcode successfully

`$printer->barcode("ABC", Printer::BARCODE_CODE39);`

its printing on receipt: KEABC i tried with number dont know KE printing instead of barcode

**Comment by mike42** [comment]
Two things-

- Confirm your Star printer is in ESC/POS emulation mode and not STAR command mode
- Please post a full PHP snippet which shows how you are initializing the printer. I need to see which printer profile you are using.

**Comment by hamza-younas94** [comment]
i have changed the Printer now everything working fine, Epson TM-T88V
