### ISSUE TITLE
How to install Star tsp100 Bluetooth, lan and usb?

### ISSUE THREAD

**Issue by lkcodk** [mike42/escpos-php#506]
Hi Mike

I am trying to find out how to print to a 

* Star tsp100 Bluetooth 
* TSP143III LAN
* TSP143U USB
 
with your script.

Is it possible to print from a android device and a iphone?

Should i use smb or maybe cups to make it work?
If yes, how do i add a printer to smb or cups from a iphone and android?

Kasper

**Comment by mike42** [comment]
Many things are possible, but your setup does not really sound like it has the prerequisites for this library. Where is PHP running? Where is CUPS running?

We generally target web-based point of sale apps, which require a webserver. So, most iPhone and Android clients that print with `escpos-php` are accessing a web page to print. The printing from PHP is server-side, so you need to be nearby or be able to relay print jobs of a CUPS or Windows print server which is in range.

I can't really comment on how printing works on Android and iPhone, this library does not normally interact with those.
