### ISSUE TITLE
Printer zj-5802

### ISSUE THREAD

**Issue by setiawanrestuaji** [mike42/escpos-php#507]
Hi mike

I'm a beginner.
what about the printer zj-5802, does it work??

Thank

**Comment by mike42** [comment]
Probaby, yes. I would suggest stepping through the README and trying to send text like "Hello World" to your printer.

I use a ZJ5890-K via USB on Linux, and after I set it up, I can access it like this:

```php
echo "Hello World" > /dev/usb/lp0
```

And I start my PHP like this:

```php
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;
$profile = CapabilityProfile::load("POS-5890");
$connector = new WindowsPrintConnector("/dev/usb/lp0");
$printer = new Printer($connector, $profile);
```

Use `bitImage` to print images on this printer, and as a bit of a warning, some users have reported trouble with barcodes on ZJ printers.

See also:

- [Getting a USB receipt printer working on Linux](https://mike42.me/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux)
- [POS Printer Database: POS5890 Series](http://mike42.me/escpos-printer-db/#profiles/POS-5890)
