### ISSUE TITLE
Problem with UTF-8 Cyrillic - Macedonian

### ISSUE THREAD

**Issue by brankotasevski** [mike42/escpos-php#510]
hi i like to print Cyrillic on my XPRINTER XP-58 pos printer but no like to prinr pleas for help.

```php
public function index()
{
    $data = "";
    $data["test"] = array(["А Б В Г Д Ѓ Е Ж З Ѕ И Ј К Л Љ М Н Њ О П Р С Т Ќ У Ф Х Ц Ч Џ Ш"]);
    $this->load->library("EscPos.php");
    try {
        $connector = new Escpos\PrintConnectors\WindowsPrintConnector("XP-58");
        $profile = Escpos\CapabilityProfiles\DefaultCapabilityProfile::getInstance();

        $printer = new Escpos\Printer($connector,$profile);
        foreach ($data['test'] as $artikli){
            $printer -> text(iconv("UTF-8","GBK//IGNORE", "$artikli[0]") . "\n");
        }
        $printer -> text("\n\n\n");
        $printer -> cut();

   
        $printer -> close();
    } catch (Exception $e) {
        echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
    }
    $this->load->view('welcome_message');
}
```

I tried this code but do not print all the letters and badly print them if there is any experience please help me thank you all This is what I got as a result of this code, but not all letters are missing
 ---- Ѕ Ј К Љ Њ Ќ Ѓ --------- this LETTERS

**Comment by mike42** [comment]
You don't have the correct profile loaded to print outside of ASCII.

Your printer looks similar to one that is sold under many names, which claims to support three Cyrillic code pages. Can you try the [POS-5890](https://mike42.me/escpos-printer-db/#profiles/POS-5890) profile and see how it goes?

Minimal example might be-

```
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;
$profile = CapabilityProfile::load("POS-5890");
$connector = new WindowsPrintConnector("XP-58");
$printer = new Printer($connector, $profile);
$printer -> text("АБВГДЃЕЖЗЅИЈКЛЉМНЊОПРСТЌУФХЦЧЏШ\n");
```

If this doesn't get you some results, then you will moist likely need to go through the process to [research and add a profile](https://github.com/receipt-print-hq/escpos-printer-db/blob/master/doc/add-your-printer.md) to the printer database, which is specific to the XP-58.

**Comment by brankotasevski** [comment]
I tried using this code did not work, I also made a new printer profile, and I added it but with that profile I came across problems,"Xprinter": {
            "codePages": {
                "0": "PC437",
                "1": "Katakana",
                "2": "PC580",
                "3": "CP860",
                "4": "CP863",
                "5": "CP865",
                "6": "West Europe",
                "7": "Greek",
                "8": "Hebrew",
                "9": "East Europe",
                "10": "Iran",
                "16": "WCP1252",
                "17": "PC866",
                "18": "PC852",
                "19": "PC858",
                "20": "IranII",
                "21": "Latvia",
                "22": "Arabic",
                "23": "PT1511251",
                "24": "PC747",
                "25": "WPC1257",
                "27": "Vietnam",
                "28": "PC864",
                "29": "PC1001",
                "30": "Uigru",
                "31": "Hebrew",
                "32": "WPC1255",
                "255": "Thai"
            },
            "colors": {
                "0": "black"
            },
            "features": {
                "barcodeB": false,
                "bitImageColumn": false,
                "bitImageRaster": true,
                "graphics": false,
                "highDensity": true,
                "pdf417Code": false,
                "pulseBel": false,
                "pulseStandard": true,
                "qrCode": false,
                "starCommands": false
            },
            "fonts": {
                "0": {
                    "columns": 42,
                    "name": "Font A"
                },
                "1": {
                    "columns": 56,
                    "name": "Font B"
                }
            },
            "media": {
                "width": {
                    "mm": "Unknown",
                    "pixels": "Unknown"
                }
            },
            "name": "XP-58",
            "notes": "POS-XP58 thermal printer series, also marketed under various other names.\n",
            "vendor": "Xprinter"
        }
this is my new printer profile and give me this error
A PHP Error was encountered
Severity: 4096

Message: Argument 2 passed to Escpos\CodePage::__construct() must be of the type array, null given, called in C:\wamp64\www\victorianpub\application\third_party\Mike42\Escpos\CapabilityProfile.php on line 132 and defined

Filename: Escpos/CodePage.php

Line Number: 68

Backtrace:

File: \application\third_party\Mike42\Escpos\CodePage.php
Line: 68
Function: _error_handler

File: \application\third_party\Mike42\Escpos\CapabilityProfile.php
Line: 132
Function: __construct

File:\application\third_party\Mike42\Escpos\CapabilityProfile.php
Line: 292
Function: __construct

File: \application\controllers\Welcome.php
Line: 34
Function: load

File: \index.php
Line: 315
Function: require_once

**Comment by mike42** [comment]
This is quite tricky, something is incorrect but I can't be sure what it is. I don't write `capabilities.json` by hand, it's generated.

You need to add a profile to the YML source in https://github.com/receipt-print-hq/escpos-printer-db/ - it includes the source data and a python script to generate a new `capabilities.json` for use with `escpos-php`.

For extra karma, send it in as a pull request when you are done, it should help out future users of the same printer.
