### ISSUE TITLE
Add support Custom VKP 80 II

### ISSUE THREAD

**Issue by mazurva** [mike42/escpos-php#511]
Add support Custom VKP 80 II

**Comment by mike42** [comment]
More info please.

Has this printer been tested and verified to accept ESC/POS, or are you reporting that it doesn't work and asking for it to be fixed?

**Comment by mike42** [comment]
Closing this off, we can't list printers without a clearer report of whether they are accepting ESC/POS commands from this driver.

**Comment by DonTisto** [comment]
Hello, i have tryed these printer yesterday . It's printing, but seems to be with incorrect character table. Plus doesn't feed paper to exit. Storing it in self. Next print task force to feed out previous paper.  I've tried to print character-encoding and character maps, but it's stuck when jammed paper(seems to be after reversefeed command). Too many papers where printed. I've found manual for these printer. And print character table. And phone-scan what printed. All these files i've attach to these message. 
Is it possible to print correct sumbols? And how to force give it paper after print? feedForm doesn't work. I've tried with profiles: simple,default.

[Новый документ 48.pdf](https://github.com/mike42/escpos-php/files/3021341/48.pdf)

[772000000016_1.30.pdf](https://github.com/mike42/escpos-php/files/3021337/772000000016_1.30.pdf)

**Comment by PietroGranati** [comment]
Up!

**Comment by usahmad** [comment]
up

**Comment by radu-bethub** [comment]
up

**Comment by Zaifat** [comment]
up

**Comment by Zaifat** [comment]
does not throw out

**Comment by barryvdh** [comment]
Same request voor VKP90-III 
Did any solve this? We send raw cut command like this:
https://github.com/landg16/Custom-Printer/blob/master/command-list.js#L471C1-L480C2

But it always leaves a big whitespace before the cut.
