### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by arifwebdotcom** [mike42/escpos-php#512]
Hi, i tried to use this code but i found error
No connection could be made because the target machine actively refused it
even though the firewall already turn off
please help 

```php
<?php
/* Change to the correct path if you copy this example! */
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;

/* Most printers are open on port 9100, so you just need to know the IP 
 * address of your receipt printer, and then fsockopen() it on that port.
 */
try {
    $connector = new NetworkPrintConnector("10.x.x.x", 9001);
    
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
```

**Comment by mike42** [comment]
Hello,

I notice that you haven't shared any information about how you would normally send raw data to your printer, so I think you are skipping a step.

Start on the command-line, and try to send the text "Hello World" to your printer without using PHP at all. It's quite difficult for me to point you in the right direction without knowing your setup, but you will need to understand your data transport before attempting to use this library either way.
