### ISSUE TITLE
Can I calculate printer Roler After Finish

### ISSUE THREAD

**Issue by mdestafadilah** [mike42/escpos-php#516]
I'm still not finding near length of roller after finishing printing... i'm  using TM-U220D ?

Thanks.

**Comment by mike42** [comment]
This library has no documented features that will read from the printer, only write.

Can you share the `PrintConnector` you are using, I have a similar printer, if they are connected the same way then I can turn this into a feature request.

**Comment by mdestafadilah** [comment]
`  
// Call Print connect here
function connect($via,$address=null,$port=null)
  {

    // source: https://github.com/RSUP/ESC-POS/tree/EscPOS-Via-Libraries

    switch ($via) {

      /* Your IP In same Network where the printer has connected */
      case 'Network':
        $this->connector = new NetworkPrintConnector($address, $port);
        $this->printer = new Printer($this->connector);
        break;

      /* Name of your printer whichis Recognize by CUPS Printer */
      case 'Cups':
        $this->connector = new CupsPrintConnector($address);
        $this->printer = new Printer($this->connector);
        break;

      /* We Use Samba For Printing Sharing */
      case 'Windows':
        $this->connector = new WindowsPrintConnector("smb://{$address}");
        $this->printer = new Printer($this->connector);
        break;

      /* We Use Port In PC Self, Linux */
      case 'File':
        $this->connector = new FilePrintConnector($address);
        $this->printer = new Printer($this->connector);
        break;
      
      default:
        exit('Not Selected');
        break;
    }
  }`

`
// This is design of ticket
public function etiket_farmasi_rawatjalan($data=[])
  {
    $this->check_connection();
    $this->printer -> setEmphasis(false);
    $this->printer -> setPrintLeftMargin(32);
    $this->printer -> setTextSize(3,3);
    $this->printer -> text("INSTALASI FARMASI\n RSUP PERSAHABATAN \n");
    $this->printer -> selectPrintMode(); // Reset
    
    $this->printer -> setColor(Printer::COLOR_2);
    $this->printer -> setEmphasis(true);
    $this->printer -> setPrintLeftMargin(32);
    $this->printer -> setTextSize(1,3);
    $this->printer -> text("No Resep: ".$data['no_resep']." \n");
    $this->printer -> setUnderline(Printer::UNDERLINE_DOUBLE);
    $this->printer -> text("                                \n");
    $this->printer -> selectPrintMode(); // Reset

    $this->printer -> setColor(Printer::COLOR_1);
    $this->printer -> setEmphasis(false);
    $this->printer -> setPrintLeftMargin(32);
    $this->printer -> setTextSize(1,3);
    $this->printer -> text("Nama: ".$data['nama_pasien']." \n");
    $this->printer -> selectPrintMode(); // Reset

    $this->printer -> setEmphasis(true);
    $this->printer -> setPrintLeftMargin(32);
    $this->printer -> setTextSize(1,2);
    $this->printer -> text("Tgl Lahir: ".$data['tgl_lahir']." \n");
    $this->printer -> setUnderline(Printer::UNDERLINE_DOUBLE);
    $this->printer -> text("                                \n");
    $this->printer -> selectPrintMode(); // Reset

    $this->printer -> setEmphasis(true);
    $this->printer -> setJustification(Printer::JUSTIFY_CENTER);
    $this->printer -> setPrintLeftMargin(32);
    $this->printer -> setTextSize(1,4);
    $this->printer -> selectPrintMode(Printer::MODE_FONT_B);
    $this->printer -> text($data['nama_obat']." \n");
    $this->printer -> selectPrintMode(); // Reset

    $this->printer -> setEmphasis(false);
    $this->printer -> setJustification(Printer::JUSTIFY_CENTER);
    $this->printer -> setPrintLeftMargin(16);
    $this->printer -> setTextSize(1,3);
    $this->printer -> selectPrintMode(Printer::MODE_UNDERLINE);
    $this->printer -> text("Jumlah: ".$data['jumlah']." \n");
    // $this->printer -> setUnderline(Printer::UNDERLINE_DOUBLE);
    // $this->printer -> text("                                \n");
    $this->printer -> setPrintWidth(64);
    $this->printer -> selectPrintMode(); // Reset

    $this->printer -> setEmphasis(true);
    $this->printer -> setJustification(Printer::JUSTIFY_CENTER);
    $this->printer -> setPrintLeftMargin(32);
    $this->printer -> setTextSize(1,4);
    $this->printer -> text("Jam: 06.00; 14.00; 22.00\n SETELAH /SEBELUM MAKAN \n");
    $this->printer -> text("______________________________\n");
    $this->printer -> selectPrintMode(); // Reset

    $this->printer -> setEmphasis(true);
    $this->printer -> setJustification(Printer::JUSTIFY_RIGHT);
    $this->printer -> setPrintLeftMargin(32);
    $this->printer -> setTextSize(1,2);
    $this->printer -> text("ANTIKOKSIDAN - HABISKAN (ED:     ) \n");
    $this->printer -> setLineSpacing(64);
    $this->printer -> selectPrintMode(); // Reset

    $this->printer -> cut();
    $this->printer -> close();
  }`

`		
// I call here ... 
try {
                    // $jumlah as looping, my example has 3 times loop
			for ($i = 1; $i <= $jumlah; $i++) {

                           // $dataObat is onlydata
				foreach($dataObat as $obat){

					$data = array(
						'no_resep' => $no_resep,
						'nama_obat' => $obat['nama_barang'],
						'nama_pasien' => $obat['nama_pelanggan'],
						'tgl_lahir' => indonesian_date($obat['tanggal_lahir']),
						'jumlah' => $obat['qty']

					);

					$this->receiptprint->connect('File','/dev/usb/lp0'); // via Port
					$this->receiptprint->etiket_farmasi_rawatjalan($data);

				}

			}

			echo json_encode(array('berhasil'=>true));


		} catch (Exception $e) {
		  echo "error", "Error: Could not print. Message ".$e->getMessage() ;
		  $this->receiptprint->close_after_exception();
		}`
![img161](https://user-images.githubusercontent.com/5575882/36184206-f2924530-1164-11e8-9ada-1caeab10f15b.jpg)

I'm not sure why if i'm looping more twice... 'some text' running to down...

**Comment by mdestafadilah** [comment]
It's done mike!
``public function etiket_farmasi_rawatjalan($data=[])
  {
    $spasing2 = str_repeat("\\n",$data['looping2']); // looping obat
    $spasing1 = str_repeat("\\n",$data['looping']); // looping cetakan

    $this->check_connection();
    $this->printer -> setColor(Printer::COLOR_1);
    $this->printer -> setEmphasis(false);
    $this->printer -> setJustification(Printer::JUSTIFY_CENTER);
    $this->printer -> setPrintLeftMargin(32);
    $this->printer -> setTextSize(2,3);

    // Success, Obat 1, Cetak 1
    if ($data['looping'] == 1 && $data['looping2'] == 1) {
      $this->printer -> text("INSTALASI FARMASI\n RSUP PERSAHABATAN \n No Resep: ".$data['no_resep']." \n _____________________ \n Nama: ".$data['nama_pasien']." \n Tgl Lahir: ".$data['tgl_lahir']." \n ".$data['nama_obat']." \n Jumlah: ".$data['jumlah_obat']." \n Jam: 06.00; 14.00; 22.00\n SETELAH /SEBELUM MAKAN \n ______________________ \nANTIKOKSIDAN - HABISKAN (ED:     ) \n \n");
      $this->printer -> setLineSpacing(8);
      $this->printer -> selectPrintMode(); // Reset

    // Success, Obat 1, Cetak Lebih Dari 1
    }elseif($data['looping'] > 1 && $data['looping2'] == 1){
      $this->printer -> text("INSTALASI FARMASI\n RSUP PERSAHABATAN \n No Resep: ".$data['no_resep']." \n _____________________ \n Nama: ".$data['nama_pasien']." \n Tgl Lahir: ".$data['tgl_lahir']." \n ".$data['nama_obat']." \n Jumlah: ".$data['jumlah_obat']." \n Jam: 06.00; 14.00; 22.00\n SETELAH /SEBELUM MAKAN \n ______________________ \nANTIKOKSIDAN - HABISKAN (ED:     )\n\n");
      $this->printer -> setLineSpacing(8);
      $this->printer -> selectPrintMode(); // Reset
    
    // Success, Obat lebih dari 1, Cetah hny 1
    }elseif($data['looping'] == 1 && $data['looping2'] > 1){
      $this->printer -> text("INSTALASI FARMASI\n RSUP PERSAHABATAN \n No Resep: ".$data['no_resep']." \n _____________________ \n Nama: ".$data['nama_pasien']." \n Tgl Lahir: ".$data['tgl_lahir']." \n ".$data['nama_obat']." \n Jumlah: ".$data['jumlah_obat']." \n Jam: 06.00; 14.00; 22.00\n SETELAH /SEBELUM MAKAN \n ______________________ \nANTIKOKSIDAN - HABISKAN (ED:     )\n\n");
      $this->printer -> setLineSpacing(8);
      $this->printer -> selectPrintMode(); // Reset

    // Success, Obat lebih dari 1, Cetak lebih dari 1
    }elseif( $data['looping'] > 1 && $data['looping2'] > 1 ){
      $this->printer -> text("INSTALASI FARMASI\n RSUP PERSAHABATAN \n No Resep: ".$data['no_resep']." \n _____________________ \n Nama: ".$data['nama_pasien']." \n Tgl Lahir: ".$data['tgl_lahir']." \n ".$data['nama_obat']." \n Jumlah: ".$data['jumlah_obat']." \n Jam: 06.00; 14.00; 22.00\n SETELAH /SEBELUM MAKAN \n ______________________ \nANTIKOKSIDAN - HABISKAN (ED:     )\n\n");
      $this->printer -> setLineSpacing(8);
      $this->printer -> selectPrintMode(); // Reset
    }

    else{
      exit('Down!');
    }

    $this->printer -> cut();
    $this->printer -> close();
  }

Thanks Mike...
