### ISSUE TITLE
Web application is on online server and printer is connected with laptop via usb.

### ISSUE THREAD

**Issue by LeonScot** [mike42/escpos-php#518]
How can I print when my Web application is on online server and printer is connected locally with laptop via USB. Please help

**Comment by mike42** [comment]
Hello! This is a very frequently asked question, you can read [all about it in the FAQ](https://github.com/mike42/escpos-php/blob/61dc270de7b78ce9be0d49e69163db5500f22cc9/doc/FAQ.md#can-i-print-from-my-server-on-the-internet).

You would generally use a `WindowsPrintConnector` to deliver a raw print job to a USB-shared printer on a Windows laptop. That uses Windows shared printers, an interface that should not be exposed to the open Internet. If you can make a secure tunnel though (eg. VPN the two onto the same network), then there is no difference to LAN printing.

In any case, I suggest verifying on the command-line that you can move raw print jobs through your chosen network topology and print system before attempting to use this library.
