### ISSUE TITLE
print from txt file

### ISSUE THREAD

**Issue by Linus-007** [mike42/escpos-php#52]
I looked at the documentation that I can find. I cannot seem to find a way to print from a text file. I see that printing from html is possible. Is there a similar method for text files?

**Comment by CroModder** [comment]
As this is PHP library you can just read the txt file with fread() - (http://www.w3schools.com/php/php_file_open.asp)
And then pass that it to a printer.

**Comment by Linus-007** [comment]
Thanks!

**Comment by mike42** [comment]
To elaborate a bit, you could modify the "Hello World" PHP example:

````php
<?php
$printer = new Escpos();
$printer -> text("Hello World!\n");
$printer -> cut();
$printer -> close();
````
And add a line like so:
````php
<?php
$printer = new Escpos();
$txt = file_get_contents("foo.txt");
$printer -> text($txt . "\n");
$printer -> cut();
$printer -> close();
````
(or use `fread()` as @CroModder suggests)

A few notes:
-  You should word wrap your text youself to avoid line-breaks mid-word. 48 and 32 are common widths, but it varies per printer and font.
- The `text()` function accepts UTF-8 and filters out ESC/POS commands, so it's safe to send it user input of limited length.
 - To render non-English characters correctly on your printer, you load in a CapabilityProfile, fire up another issue with details about the language and printer if you want some pointers. 
- End the `text()` call with a line break, which is necessary to print the last line.

**Comment by macolmenero** [comment]
Hello,
I try to print a Cyrillic label, but does the printer print "????"  instead and no "ГАЙКА СТУПИЦЫ"
The printer is a Zebra ZT220
I use this code:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
<?php
$texto="CT~~CD,~CC^~CT~^XA~TA000~JSN^LT0^MNW^MTT^PON^PMN^LH0,0^JMA^PR5,5~SD15^JUS^LRN^CI0^XZ~DG000.GRF,03072,024,,:::::::gI02AA,,gI0IA80,gJ0H4,gI0IA80,,gH0A0I08,gG040J04,g0IAI02AA0,,Y0JA800AIA80,g0I4I0J4,Y0KA02AIA80,,X02APA80,Y0I4K0404,X02AHAK02AHA0,,X02AA8008080AHA0,Y0H4H0J404H40,X02AA00AIA02AA0,,X02AA00AHA802AA0,Y0H4H0J4H04,X02AA00AHA802AA0,,X02AA00AHA802AA0,X0I4I0I4H0H40,X02AA00AHA802AA0,,X02AA00AHA802AA0,Y0H4H0I4I04,X02AA00AHA802AA0,,X02AA00AHA802AA0,Y0H4H0I4H0I40,X02AA00AHA80AHA0,,X02AA80AHA80AHA0,Y0I4K0404,X02AIAI02AHA80,,Y0JA800AIA80,Y0J4I0J4,Y02AHA800AIA,gL010,g0IA800AHA8,gG040J04,gH0280022,,:::::::O01,O0HEC008002C2800EHEC002EHEH0JEH0E,N015H5H040014140145540015H5H0J5014,N03ABB80A00383A0383BA003BAB80ABHB80A,N05405405001414050014001405405005014,N0E802E0E80280E0E806A002800E0E00280E,M014001405401405050055001400405001414,M03A0H0A0BA038038A00BA003800A0A00280A,M0140H0505501401540055001400505001014,M02C0H0E0EE82C02EE00A2802800E2EAAE80E,M0140H0505141401540141401401415I5014,M0380H028B0A3800A802A2802803A3BHBA00A,M010I0505051400500141415I5415I5014,M0280H0E8A0EAC00E00280E0EEFE80E002C0E,M0140H0505015400500501415H54005001414,M03A001A0A00B800B002BAA03A2A00A0H0A0A,M0140014050054005005I501415005001414,N0E802E0E00EC00E80EIE8280E80E802E0E,N05405405001400500400501405005005414,N03BHB80B002800A00A0028280380ABBA80A,N015H5H05001400501400141401405I5014,O0HEA00A800800E02C00282802E0EIE80E,O0140,,::M010M040O040J04,V020O080J02,V040K010H040010J010H010,P02E800A80082006A00E00E006002A002A,M010011001040040H040H040040040041,P0208020200820020H0800800200820028,M010H01001040040H0140040040040H010015,N080208020E00CA0H0E00800C00200828002,M010H01001040044004400400400400410H01,P020800AA002A002A002008002002A002A,,::::::::::::::::::::::::::~DG001.GRF,01536,012,,::::::::::::::::::::::O01FKF803FIF0I0JFC01FKF803FIF0:::::I0JFC01FF00FF803FIF0:I0HF80H01FF00FF803FIF0I0HF80H01FF00FF803FE0,::::::::::::::::::::I0JFC01FKF803FE0,::::::I0HF80H01FF00FF803FE0,::::::::::::::::::::I0HF80H01FF00FF803FEAA0I0JFC01FF00FF803FIF0:::::::O01FF00FF803FIF0,:::::::::::::::::::::::::::::::::::^XA^MMT^PW511^LL0408^LS4^FT160,128^XG000.GRF,1,1^FS^FT384,128^XG001.GRF,1,1^FS^FT122,156^A@N,51,51,TT0003M_^FH\^CI17^F8^FD90.19.63^FS^CI0^FT501,310^A@B,17,13,TT0003M_^FH\^CI17^F8^FD39^FS^CI0^FT499,364^A@B,17,13,TT0003M_^FH\^CI17^F8^FD19^FS^CI0^FT47,262^A@N,23,22,TT0003M_^FH\^CI17^F8^FD^FS^CI0^FT469,180^A@N,13,13,TT0003M_^FH\^CI17^F8^FDB^FS^CI0^FT420,153^A@N,23,22,TT0003M_^FH\^CI17^F8^FDx^FS^CI0^FT435,153^A@N,23,22,TT0003M_^FH\^CI17^F8^FD2^FS^CI0^FT47,221^A@N,23,22,TT0003M_^FH\^CI17^F8^FDГАЙКА СТУПИЦЫ ^FS^CI0^FO29,189^GB469,89,1^FS^BY3,3,65^FT42,346^BCN,,Y,N^FD>:90.19.63^FS^PQ1@,0,1,Y^XZ^XA^ID000.GRF^FS^XZ^XA^ID001.GRF^FS^XZ");
echo $texto."<br/>";
//I tried with utf8_decode and utf8_encode, but not gone
//$texto=utf8_decode($texto);
$printer_name = '192.168.1.11';
echo $printer_name;
require __DIR__ . '/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
try {
$connector = new NetworkPrintConnector($printer_name,9100);
	$printer = new Printer($connector);
	$printer -> text($texto);
	$printer -> cut();
	$printer -> close();
} catch(Exception $e) {
	echo "No puedo conectar con la impresora: " . $e -> getMessage() . "\n";
}
?>
</body>
</html>
