### ISSUE TITLE
Print via USB printer under Windows II

### ISSUE THREAD

**Issue by vincentckk** [mike42/escpos-php#521]
![image](https://user-images.githubusercontent.com/26475848/36670887-b8caaaac-1b34-11e8-97a9-ec22e88738f2.png)

Warning: file_put_contents(LPT1): failed to open stream: No such file or directory in C:\inetpub\escpos-php-master\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 384
Couldn't print to this printer: Failed to write file to printer at LPT1

I got the above problem if change to LPT1 with net use...
Please advise if someone resolved it already. Thanks

**Comment by mike42** [comment]
#520
