### ISSUE TITLE
Printer not working on hosting site but works on localhost

### ISSUE THREAD

**Issue by edrsn27** [mike42/escpos-php#523]
Hi! This error appears when I tried uploading our project online to our web hosting site. Is there any solution to this or how can it be solved? I tried searching the internet but to no avail. Need answers or inputs as soon as possible. Thank you in advance.

Couldn't print to this printer: Failed to print. Command "smbclient '//DESKTOP-PVCTR0Q/EPSON TM-T88IV Receipt' -c 'print -' -N" failed with exit code 127: sh: smbclient: command not found

**Comment by mike42** [comment]
Hello! To be clear, this library is maintained by volunteers. You are definitely in the wrong place if you are expecting commercial-grade support.

Having said that, this is a very frequently asked question. You may be interested to check out the list of suggestions [about Internet printing in the FAQ](https://github.com/mike42/escpos-php/blob/61dc270de7b78ce9be0d49e69163db5500f22cc9/doc/FAQ.md#can-i-print-from-my-server-on-the-internet), collected from the user base, plus the answer on #518 that I wrote earlier today.
