### ISSUE TITLE
Printer tested: Senor TP-100

### ISSUE THREAD

**Issue by manuchan** [mike42/escpos-php#528]
Firstly, thanks for this amazing library. Run the demo.php from example. All methods work great except graphics (which I believe the printer do not support it).

And for method bitImage, the image is pushed to the right, i.e. indented and not align to left. Any ideas?

**Comment by manuchan** [comment]
bitImageColumnFormat works fine, work with justification too :+1:

**Comment by mike42** [comment]
Cheers thanks for the report. I'll include this on the printer list for the next minor release.

It is known that the alignment of `bitImage()` outputs varies between printers, looks like you will just need to use `bitImageColumnFormat()`.
