### ISSUE TITLE
Can't print image use Mini Pos Printer thermal Model :MP-RP58A on windows

### ISSUE THREAD

**Issue by risqiaris4** [mike42/escpos-php#531]
hi,, i can't printing images with this code, any solution for me? thanks,

```php
<?php
require __DIR__ . '/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\CapabilityProfile;
$vasis = explode("~",$_GET['contentstruk']);
try {
    // Enter the share name for your USB printer here
    $profile = CapabilityProfile::load("simple");
    $connector = new WindowsPrintConnector("smb://127.0.0.1/miniposmdt");
    $printer = new Printer($connector,$profile);

    $img = EscposImage::load("gambar/logojenong.png", false);
    $printer -> graphics($img,Printer::IMG_DOUBLE_WIDTH);

    //$printer -> bitImage($img);

    /* Print a "Hello world" receipt" */
    foreach($vasis as $isi){

        $printer -> text($isi."\n");
    }
    $printer -> cut();

    /* Close printer */
    $printer -> close();
} catch(Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}


?>
```

![whatsapp image 2018-03-12 at 22 10 30](https://user-images.githubusercontent.com/7911008/37291916-4d43e604-2642-11e8-80e6-c5a2cdabe428.jpeg)

**Comment by mike42** [comment]
One more fallback, `bitImageColumnFormat`, is listed in the README that you can try.

> graphics()
> ...
> The function bitImage() takes the same parameters, and can be used if your printer doesn't support the newer graphics commands. As an additional fallback, the bitImageColumnFormat() function is also provided.

You might also like to try `POS-5890` profile to get access to some better text encoding. If that doesn't work.

Best of luck!
