### ISSUE TITLE
barcode printer not printing

### ISSUE THREAD

**Issue by Egyptionl** [mike42/escpos-php#543]
im trp to print from cmd as example . my printer Xprinter USB connected
and my printer driver ok i had print test. everything good. my printer sharename is Xprinter PC name is Afifi-PC. i have created test file as example
i try this code in cmd.exe
c:\>       print /D:"\\Afifi-PC\Xprinter" testfile
do nothing and printer don't even peep
i use this code printer print normally
c:\>        start /min notepad /P testfile
when i try with php also nothing page don't give any erorr. if i use wrong name for pc or printer it throw error.
what is problem ??? why printer not print in

**Comment by mike42** [comment]
Focus on getting a text file to print as a raw print job on the command-line.

If even this doesn't work, then it's not a library issue, and you need to contact your printer tech support or read the MS documentation to find out how deliver raw data to the printer.

I've tried this with an Epson printer on Windows 7 before, and had to use the "Generic/Text only" driver.

- https://mike42.me/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows

Closing as out of scope.
