### ISSUE TITLE
str_pad will result in a new line

### ISSUE THREAD

**Issue by dpayet** [mike42/escpos-php#544]
Hello,

I've tried the receipt-with-logo example and the lines are not aligned on right. It does a new line below the first. I have the item on the left and its price below the item (it should be on the right).

My printer is a Epson TM-T88IV. Is there any config to do to adjust the paper width or the print size (or something else ?) :)
Thanks (and sorry for my english).
![29261500_10208750308873721_2964178959303966720_o](https://user-images.githubusercontent.com/6755302/37468377-2d12364c-2863-11e8-8ac6-b4c975aa585e.jpg)

**Comment by mike42** [comment]
You might just need to change some numbers. I wrote that example for a printer with 48 characters per line and your printer looks like it's narrower, maybe 42.

Look for `$leftCols` and `$rightCols` in the example.

```php
class item
{
...
    public function __toString()
    {
        $rightCols = 10;
        $leftCols = 38;

        if ($this -> dollarSign) {
            $leftCols = $leftCols / 2 - $rightCols / 2;
        }
        $left = str_pad($this -> name, $leftCols) ;
        
        $sign = ($this -> dollarSign ? '$ ' : '');
        $right = str_pad($sign . $this -> price, $rightCols, ' ', STR_PAD_LEFT);
        return "$left$right\n";
    }
}

It is currently `38 + 10` (48 columns total), you need to make these numbers smaller, maybe start with `34 + 8` and decrease from there if the lines still wrap,

**Comment by mike42** [comment]
I also notice that you have an "ñ" sign on your receipt. Since you are writing in French, I'm guessing you are trying to print a Euro.

If you upgrade to 2.0.1, you can use the `CapabilityProfile` called `TM-T88IV` which should correct this for your specific printer.

A sort of minimal example would be-

```php
use Mike42\Escpos\CapabilityProfile;
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$profile = CapabilityProfile::load("TM-T88IV");
$connector = new FilePrintConnector("/dev/usb/lp0");
$printer = new Printer($connector, $profile);

$printer -> text("Article gratuit      € 0,00\n");

$printer -> cut();
$printer -> close();
```

**Comment by dpayet** [comment]
Thanks you so much !

**Comment by umardevid** [comment]
can i use grid
1. for qty
2. for product name (add line break if text to long)
3. for price

20  Indomie Goreng(break if long text)  Rp12.500 IDR
