### ISSUE TITLE
Can't print Lao Characters 'ພາສາລາວ' try with many example but when print still see ??????

### ISSUE THREAD

**Issue by asongkai** [mike42/escpos-php#549]
Hi Mike,

Could please help to add support for Lao Language Characters, as I saw you have implemented for many others language so far. e.g I want to print 'ລະບົບຮ້ານອາຫານໃນພາສາລາວ' but when print all the characters become ???????????????????.

My POS printer model: EPSON TM-T82

Thank you in advance

**Comment by mike42** [comment]
The "?" symbols are being inserted by this library, because it doesn't know how to encode those characters in a way that your printer will understand,

Would you mind sharing the exact M___ model number off the back of your printer (need to see if it is a South Asia Epson printer), and the code you are using to print?

If the printer supports these characters, we can modify the driver to make it work, otherwise we'll need to use a work-around which involves sending images of the text the printer instead.

**Comment by asongkai** [comment]
Hi Mike,

Printer Name: EPSON TM-T82
Printer Model: M325A
--------------------------

The code i tried to print is within the file receipt-with-logo.php:

`<?php
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfiles\DefaultCapabilityProfile;

$connector = new WindowsPrintConnector("EPSON TM-T82 Receipt");
$profile = DefaultCapabilityProfile::getInstance();
/* Information for the receipt */
$items = array(
    new item("Example item #1", "4.00"),
    new item("Another thing", "3.50"),
    new item("Something else", "1.00"),
    new item("A final item", "4.45"),
);
$subtotal = new item('Subtotal', '12.95');
$tax = new item('A local tax', '1.30');
$total = new item('Total', '14.25', true);
/* Date is kept the same for testing */
// $date = date('l jS \of F Y h:i:s A');
$date = "Monday 6th of April 2015 02:56:25 PM";

/* Start the printer */
$logo = EscposImage::load("resources/escpos-php.png", false);

$printer = new Printer($connector, $profile);
//$printer -> selectCharacterTable(3);
/* Print top logo */
$printer -> setJustification(Printer::JUSTIFY_CENTER);
$printer -> graphics($logo);

/* Name of shop */
$printer -> selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
$printer -> text("ລະບົບຮ້ານອາຫານ Asongkai.\n");
$printer -> selectPrintMode();
$printer -> text("ຮ້ານ ອາຫານ. 42.\n");
$printer -> feed();

/* Title of receipt */
$printer -> setEmphasis(true);
$printer -> text("SALES INVOICE\n");
$printer -> setEmphasis(false);

/* Items */
$printer -> setJustification(Printer::JUSTIFY_LEFT);
$printer -> setEmphasis(true);
$printer -> text(new item('', '$'));
$printer -> setEmphasis(false);
foreach ($items as $item) {
    $printer -> text($item);
}
$printer -> setEmphasis(true);
$printer -> text($subtotal);
$printer -> setEmphasis(false);
$printer -> feed();

/* Tax and total */
$printer -> text($tax);
$printer -> selectPrintMode(Printer::MODE_DOUBLE_WIDTH);
$printer -> text($total);
$printer -> selectPrintMode();

/* Footer */
$printer -> feed(2);
$printer -> setJustification(Printer::JUSTIFY_CENTER);
$printer -> text("Thank you for shopping at ExampleMart\n");
$printer -> text("For trading hours, please visit example.com\n");
$printer -> feed(2);
$printer -> text($date . "\n");

/* Cut the receipt and open the cash drawer */
$printer -> cut();
$printer -> pulse();

$printer -> close();

/* A wrapper to do organise item names & prices into columns */
class item
{
    private $name;
    private $price;
    private $dollarSign;

    public function __construct($name = '', $price = '', $dollarSign = false)
    {
        $this -> name = $name;
        $this -> price = $price;
        $this -> dollarSign = $dollarSign;
    }
    
    public function __toString()
    {
        $rightCols = 10;
        $leftCols = 38;
        if ($this -> dollarSign) {
            $leftCols = $leftCols / 2 - $rightCols / 2;
        }
        $left = str_pad($this -> name, $leftCols) ;
        
        $sign = ($this -> dollarSign ? '$ ' : '');
        $right = str_pad($sign . $this -> price, $rightCols, ' ', STR_PAD_LEFT);
        return "$left$right\n";
    }
}
`

I think the printer support these characters because if I try to print from browser print the printer can print these characters correctly.

Thanks in advance.

**Comment by mike42** [comment]
I've done some research on this, and I can't find a Lao code page for your printer, but I've got a work-around.

Because the Lao script composes characters, the work-around I'm going to suggest is the `ImagePrintBuffer`. It generates small images using ImageMagick and a TTF font - I used Phetsarath_OT since it is [included in Debian](https://packages.debian.org/jessie/fonts/fonts-lao), but you might know a better font.

Minimal example:

```php
<?php
require __DIR__ . '/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\CapabilityProfiles\DefaultCapabilityProfile;
use Mike42\Escpos\PrintBuffers\EscposPrintBuffer;
use Mike42\Escpos\PrintBuffers\ImagePrintBuffer;

try {
    // Enter connector and capability profile
    $connector = new FilePrintConnector("php://stdout");
    $profile = CapabilityProfile::load("default");
    $buffer = new ImagePrintBuffer();
    $buffer -> setFont('/usr/share/fonts/truetype/lao/Phetsarath_OT.ttf');

    /* Print a series of receipts containing i18n example strings */
    $printer = new Printer($connector, $profile);
    $printer -> setPrintBuffer($buffer);
    $printer -> text("ລະບົບຮ້ານອາຫານ\n");

    $printer -> cut();

    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
```

Output for me (on a TM-T20 but similar enough for image printing)-

![2018-04-lao-script](https://user-images.githubusercontent.com/2080552/38361794-eedc82be-3911-11e8-9e37-a21b079bcd19.png)

Text formatting is not available through this API, but I'm open to collaborating if you have any improvements that you would like to see.

**Comment by asongkai** [comment]
Hi Mike,

Thank you for your help I really appropriate the result; I will give a try and let you know the result.

Thanks

**Comment by keophilavanh** [comment]
![Untitled](https://user-images.githubusercontent.com/36201795/66544350-1699a080-eb62-11e9-9839-8422f991e1fb.png)
