### ISSUE TITLE
NetworkPrintConnector attempts to rewind a network connected stream

### ISSUE THREAD

**Issue by Syloq** [mike42/escpos-php#55]
I just tried to get a Printer status from a TM-T88V via the NetworkPrintConnector class. However after issuing a  getPrinterStatus(). I got an error stating:

ERR (3): exception 'ErrorException' with message 'rewind(): stream does not support seeking' in /path/to/php/vendor/mike42/escpos-php/src/FilePrintConnector.php:68

I tried to close then reopen the socket and even to comment out the rewind() that was there to no avail. Commenting out the rewind just made the library hang without putting out an error.

I might be missing something, but I'd like to get a status from the printer to find out if its working as expected before printing to it.

**Comment by mike42** [comment]
That stream handling is a bug, well spotted.

The status feature is flaky enough that I've excluded it from the main documentation to avoid tripping people up. As far as I can tell, the command as implemented matches the spec, but it also hangs my TM-T20 USB under some circumstances, and I don't recommend using it if you can avoid it.

Issue #43 includes more background, and a link to an Auto Status Back (ASB) gist, which will work with most networked Epson printers. It throws a UDP packet to the interface card, which is a better way to perform the check.
