### ISSUE TITLE
Printer tested: DR-MP200

### ISSUE THREAD

**Issue by sigautomacao** [mike42/escpos-php#550]
I want to use a printer that is not in my list. a DR-MP200 that uses EPSON (ESC / POS).

**Comment by sigautomacao** [comment]
This printer works correctly with the library!

**Comment by mike42** [comment]
Thanks for testing!

I'll include this on the list of printers in the next minor release.

**Comment by mdestafadilah** [comment]
What's image of DR-MP200 printer?
