### ISSUE TITLE
Can't print Vietnamese Characters

### ISSUE THREAD

**Issue by daund132** [mike42/escpos-php#554]
Hi Mike,
I want to print a Vietnamese document, but I do every way it's still wrong.
Text string ex: "Ta đã từng hứa yêu nhau đến muôn đời sau
Anh vẫn luôn khắc sâu nhưng hôm nay ân tình phai màu
Còn gì nữa đâu và đành buông lơi những câu
Ta phải xa rời nhau như hoa kia dần úa màu. "
Example 1: Use instance P822D in capabilities.json not add TCVN-3-1 & TCVN-3-2.
Example 2: Use instance P822D in capabilities.json add TCVN-3-1 & TCVN-3-2.
Please see the picture.
![30697594_2488478624711306_5873767329497612288_n](https://user-images.githubusercontent.com/38121731/38594649-7b8e9572-3d71-11e8-9700-480f2541ad2a.jpg)
And here is the printer information I use
![30652674_2488483574710811_1845642928509157376_n](https://user-images.githubusercontent.com/38121731/38594751-fbae0d3c-3d71-11e8-8774-4aaec4f85197.jpg)
Please help me!
Thanks so much!

**Comment by mike42** [comment]
Could you share the code you are using to print each of these?

I can basically confirm that this driver's [P822D proile](https://mike42.me/escpos-printer-db/#profiles/P822D) does not identify code pages containing all of those characters, so '?' would be printed in its place. That's expected.

From a previous issue #50, I know that this printer has a code page called "Vietnam", but I don't know if that's one of the TCVN-3 pages or not.

I don't have a printer to test on, but if you swap the connector here, you can print the contents of that code page for us to try to identify:

```
<?php
require_once(__DIR__ . "/vendor/autoload.php");

use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$connector = new FilePrintConnector("php://stdout");

$connector -> write("\x1b@\x1bt" . chr(27));
$chars = str_repeat(' ', 256);
for ($i = 0; $i < 255; $i++) {
    $chars[$i] = ($i > 32 && $i != 127) ? chr($i) : ' ';
}
for ($y = 4; $y < 8; $y++) {
    $connector -> write(substr($chars, $y * 32, 32) . "\n");
}
$connector -> write("\n\x1dV" . chr(65) . chr(3));
$connector -> finalize();
```

Any changes would go in [this file](https://github.com/receipt-print-hq/escpos-printer-db/blob/master/data/profile/P822D.yml) in our upstream database project.

If this is too much effort, we also have a work-around called `ImagePrintBuffer`, which you will find examples for if you do a search on the issue tracker. It involves using a TTF font to generate small images which are used to print.

As for the second receipt, I don't know what you're doing exactly, so I wont comment on why that's garbled.
