### ISSUE TITLE
Please add support to EPSON TM T58

### ISSUE THREAD

**Issue by kevingio** [mike42/escpos-php#558]
I have tried the basics code and it didn't work on this printer. Someone on the internet told that TM 58 was the same version as TM88 but didn't work on me. I saw the list and it was not on the list. Please add support to EPSON TM T58

**Comment by mike42** [comment]
The printer list in the README is very informal. We add printers to it when somebody has tested it out, and says "hey, it works!". Based on your assessment, the printer doesn't work, so I'm not going to write it in the README at this stage.

However, Epson user guide for the TM-58 lists every command that is used for printing the basic "Hello World' receipt, so I think that you are either trying something else, or that you are not cleanly delivering data to your printer.

Could you please talk us through what led you to conclude that 'it didn't work on this printer'? A good start might be-

- Exact OS, printer interface, how you set it up.
- How you confirmed that you can deliver raw data to the printer on the command-line.
- A copy of the exact PHP code you ran, a description of how you executed it, and a picture of the output if it was garbled.

**Comment by kevingio** [comment]
Hi, thank you for quick respond. I did use your library to print on Epson TM82 using CUPS in MacOS and it worked really good. Now, I'm trying to use another type of printer.

I'm using Windows 7 64 bit and I'm trying to print a receipt through Epson T58 printer. I tried to print 'Hello World' using command line and it works. 
Here is my PHP code, it shows Escpos Class Not Found
`$connector = new WindowsPrintConnector("smb://192.168.1.9/PrinterReceipt");
          $printer = new Escpos($connector);
          $printer->setJustification(Printer::JUSTIFY_CENTER);
          // bold
          $printer -> setEmphasis(true);
          // setTextSize (width, height) 1-8
          $printer -> text("BOEDJANK VAPE HOUZ\n");`

**Comment by mike42** [comment]
"Class not found"!

The `Escpos` class was renamed to `Printer` some time ago, so you either need to down-grade your library, or up-grade your code.

Check the README for more detailed usage of the current version of the library, it has a newer "Hello World" snippet.

**Comment by kevingio** [comment]
I tried to rename it and it showed `proc_open()` error. I tried to use it on shared hosting. Does this method can be done using shared hosting?

**Comment by mike42** [comment]
Server-side printing involves a lot of work, but it's certainly possible on a shared host. You need to pass data to the client (you can write to a DummyPrintConnector and `echo` it with a suitable header), then you need an agent running on the client. In JavaScript, you then fetch the binary data and pass it to the agent, which has permission to see the printer.

Products like qz.io, chrome-raw-print, or [this recent blog post](https://mike42.me/blog/2018-04-how-to-communicate-with-usb-and-networked-devices-from-in-browser-javascript) (linux) should give an idea of what I mean. Consider hiring a software architect if this is critical to your application.

If you can run PHP on localhost or even just somewhere on the same LAN, then the printing will be easier. You can test shared printing on the command-line outside of PHP, and then choose a suitable connector from the README to issue prints over the LAN using the same mechanism.

**Comment by kevingio** [comment]
Thank you for a brief explanation and for the idea, really appreciate it. I should learn more about software architecture or maybe just hiring a software architect as you said.
