### ISSUE TITLE
Output to Customer Display Turret

### ISSUE THREAD

**Issue by amused321** [mike42/escpos-php#56]
Is there the ability (or a separate plugin) which would allow output text to a LCD Customer Display as well as the Thermal Printer? In my case they are daisy chained together so ideally output would need to target either the printer or the display.

**Comment by mike42** [comment]
There's no ESC/POS command to pass things on to a display, so unless it's a simple vendor extension to ESC/POS, this driver probably can't do it. Can you give me some info about how this is connected up?

Specifically-
- Make, model, interface of printer (eg. FooCorp Super Print III w/ Serial to the POS computer)
- Make, model, interface of the turret (eg. BarCorp LCD w/ serial to the printer)
- Links to any online docs about programming for the display.

**Comment by amused321** [comment]
Hi Mike

Many Thanks for getting back to me.

The setup is: serial output (COM1) to the display turret. The turret 
then has a pass through serial connection to send signals on to the 
printer. From looking into it is seems that display and printer signals 
are send out via different pins. Display signals comes via one pin and 
the printer signal comes (and passes through) via another. I think! This 
is all well out of my experience at the moment (I'm learning though).

The turrets all look to be made to a universal standard and do support 
ESC/POS. My exact set-up is
Digipos WD-202E(W) Customer Display
Epson TM-T88(II) Thermal Printer
linked via serial cables

I can't find a user manual for my exact model display but the ones I've 
found of other manufactures all look to have the same information. A 
link to a pretty comprehensive pdf can be found at 
http://www.eposintl.com/manual/Magnum%20%28WD%20202%29%20Customer%20Display%20Manual.pdf

and another here:
http://support.j2rs.com/Documents/OldDocs/CD7220_Manual.pdf

I've tested the ESC/POS.php with the printer on it's own and have got it 
working ok. Not yet tried with the customer display connected up as well 
yet but that is next.

Any thoughts or input you have would be greatly appreciated.

Regards

Simon Coombes

**Comment by amused321** [comment]
Hi Michael

Some time ago I contacted you about your PHP esc/pos program and the possibility of using customer pole displays. 

I'm back on experimenting with this and have a list of ESC codes which I've checked work via raw com output from command prompt. I'd like to experiment using your PHP program but am having issues. 

Basically I need to send additional Esc/POS commands to the serial port. To target the display I send ESC=0 and then all future text, commands etc and displayed or executed by the display. To switch to the printer I send ESC=1 and then all text commands etc and routed through to the printer (The printer being connected to the display which is connected to com1). Until an ESC=n command is sent, all inputs are displayed/printed by the last targeted device. In theory!

So to get up and running I need to simply send additional ESC/POS Commands. I've tried adding new functions to escpos.php  for example

Function display() {
  $this -> connector -> write(self::ESC . "=0");
}

But when I try this I get "Call to undefined method Escpos::Thermal()"
So I'm guessing I'm missing something in a class somewhere.

Could you give me a nudge as to how to add the ability to send ESC/POS commands to your code so I can test with the display? 

Many thanks

Simon

**Comment by mike42** [comment]
Hi,

Your code looks like it would work (I'm not sure where the string 'Thermal' could be coming from in the error??). Anyway, I usually use `chr(0)` to get an ASCII `\0x00` rather than `0x30`, but both tend to work.

So if I was to add this to the code, I would do it like this-
````php
	/**
	 * Direct output to a peripheral device on supported printers.
	 *
	 * @param string $enabled
	 *        	True to start directing output to a peripheral device (default), false to undo this change and direct it back to the printer.
	 */
	function selectPeripheral($enabled = true) {
		self::validateBoolean ( $enabled, __FUNCTION__ );
		$this->connector->write ( self::ESC . "=" . chr ( $enabled == true ? 0 : 1 ) );
	}
````

Which I would test on a real printer like this-
````php
	$connector = new FilePrintConnector("/dev/usb/lp0");
	$printer = new Escpos($connector);
	try {
		$printer -> text("Hello world\n");
		$printer -> selectPeripheral(true);
		$printer -> text("Screen\n");
		$printer -> selectPeripheral(false);
		$printer -> text("Printer\n");
		$printer -> cut();
	} finally {
		$printer -> close();
	}
````

**Comment by mike42** [comment]
@amused321 did this end up working for you?

I haven't got a customer display turret to test with, but if it works for you, I'll add this feature to the main driver for others.

**Comment by amused321** [comment]
Hi Mike

I did get it mostly working before I got too busy and had to put the 
project on hold. It's certainly very easy to edit Escpos.php with 
additional functions to target a display . I could target the display 
using a $this - > connector -> write(self::ESC . "="0) and the thermal 
printer using ESC=1.

It was a bit raw. For example I had to pad/cut each line to ensure it 
was 20 characters long and if I wanted to write to the second line only, 
I'd sent a output of 20 spaces first, but it worked. Also with more 
refining I'm sure I could have got carriage returns and justification 
working.

The challenge was switching from one to the other. I had the two daisy 
chained and need to switch from one to the other constantly. Usually 
you'd somehow get locked outputting to the one device. Turning both off 
and on again meant you could freely target (once) before getting locked 
again. I did eventually manage to break this lock and switch between the 
two at will but it was a hack and I never truly understood WHY it worked!

I certainly had to send a "reset" command of ESC=2 (which didn't even 
show up in the ESCPOS code list I got either from Epson or the display 
manufacturer sent me) which seemed to essentially unset both devices. As 
I said I then had to move onto other things and haven't got back to it. 
I'm happy to send you my code but it's got a lot of place holders and 
"Test31" functions at the moment and "Why does this need a Esc=@ at this 
point?" comments! Once I get back to it though and actually work it all 
out and refine it though I'll be able to send you actual useful code.

So in answer to my initial question: YES ESCPOS.php will run a display 
turret but working with a display AND a printer needs work!

Simon
