### ISSUE TITLE
Printer Fargo DTC 1250e

### ISSUE THREAD

**Issue by jamboljack** [mike42/escpos-php#564]
Can this code run for Printer Fargo DTC 1250e ?
Thanks

**Comment by mike42** [comment]
If it understands ESC/POS, then yes, otherwise, no.

Check out [I have Printer X. Can I use this driver?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver) in the FAQ a slightly more detailed version of this answer.

**Comment by jamboljack** [comment]
Ok, thanks Mike...Maybe i will try other way... 👍

**Comment by jamboljack** [comment]
I use : 
try {
    // Enter the share name for your USB printer here
    // $connector = '192.168.137.5\DTC1250e';
    $connector = new WindowsPrintConnector("DTC1250e");
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer->text("Hello World!\n");
    $printer->cut();
    /* Close printer */
    $printer->close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e->getMessage() . "\n";
}

the printer is respond, but stack in pause button red light.
![fargo dtc](https://user-images.githubusercontent.com/6668588/39414088-af5bc65e-4c5d-11e8-94de-09541bf0b23e.jpeg)

I try in EPSON L220 working well...
