### ISSUE TITLE
Turkish character output Problem

### ISSUE THREAD

**Issue by rapcrown** [mike42/escpos-php#565]
Hi, turkish character is problem.
![5f0b5b29-5a44-491e-b6df-af9b69c18415](https://user-images.githubusercontent.com/25549050/39632731-93c38a3a-4fbe-11e8-9fdb-b790d8238525.jpg)

`<?php
header('Content-Type: text/html; charset=utf-8');
/**
 * This is a demo script for the functions of the PHP ESC/POS print driver,
 * Escpos.php.
 *
 * Most printers implement only a subset of the functionality of the driver, so
 * will not render this output correctly in all cases.
 *
 * @author Michael Billington <michael.billington@gmail.com>
 */
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

try {
    // Enter the share name for your USB printer here
mb_internal_encoding("UTF-8");
    $connector = new WindowsPrintConnector("ZJ-80");
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
	
	$yazi = "Pijamalı hasta, yağız şoföre çabucak güvendi\nPijamalı hasta, yağız şoföre çabucak güvendi\nPijamalı hasta, yağız şoföre çabucak güvendi\nPijamalı hasta, yağız şoföre çabucak güvendi\nPijamalı hasta, yağız şoföre çabucak güvendi\n";

 $printer -> text($yazi);

    $printer -> cut();
    
    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
`

**Comment by rapcrown** [comment]
My printer palmx Model : ZJ-8330

**Comment by serkanhursgunel** [comment]
Hi @mike42. I have same issue. How can I include Turkish character set into my project.

**Comment by mike42** [comment]
@serkanhursgunel - If your printer is also a ZJ-8330, then see the answer above. If not, could you please file a separate issue including a code snippet and the model of printer you are using?

The best way to encode Turkish text will depend on your specific make and model of printer.

**Comment by rapcrown** [comment]
@mike42  Thank You mike.
