### ISSUE TITLE
Using class on raspberry pi, to get queued jobs from server (via cronjob) including cut,and, open cash drawer

### ISSUE THREAD

**Issue by welrachid** [mike42/escpos-php#566]
Hi guys.
Im looking for a solution where i can get a raspberry pi to make a print job using cronjobs where the jobs could include html and within a single job both can have muiltiple cuts, and an open cash drawer.
Obviously i would like for it to be as generic as possible (HTML code), so that i can make it print whatever i like (and not being forced to do an remote-update on the PI whenever i want to update the receipt view)
Storing php directly in DB and getting it in the cronjob to do an eval on the device is not an option (security-wise)

Thanks.

**Comment by welrachid** [comment]
sorry i dont know how to label this as a question.

**Comment by mike42** [comment]
It sounds like you are designing an entire system. Things like display, scheduling, or database interaction are application responsibilities. I'm not designing your system, so I'll leave it to you to solve those.

This project generates binary output that is understood by ESC/POS compatible thermal receipt printers. You specify the commands to send from PHP, so I try to limit the examples on the bug tracker to self-contained PHP snippets.

In any case, cut, cash drawer and text output are all available. Once you have confirmed that you have an ESC/POS printer and stepped through the "Hello World" example, see the usage in the README for `cut()` and `pulse()`.

Best of luck.

**Comment by welrachid** [comment]
Hi. Sorry if it seemed like i didnt take a look on your code.. i actully did look into it and was hoping someone else had a good solution to it.
Ive come to a solution myself that i think is doable.

i json encode an array with the commands i need to run with the parameters to each command.

anyway.. thanks for response.
