### ISSUE TITLE
Thermal Printer TVS RP 3150 STAR not found

### ISSUE THREAD

**Issue by Aravindan11** [mike42/escpos-php#567]
Thermal Printer TVS RP 3150 STAR not found in the list, kindly add that for plugin.

**Comment by mike42** [comment]
The printer can only be added if it's been tested!

If you've got one, then I would encourage you to confirm that it supports ESC/POS (this will be listed in the vendor's documentation), and to then attempt to send the "Hello World" receipt.

See also "[Can you add support for Printer X?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-you-add-support-for-printer-x)" in the FAQ.

**Comment by sunnykm469** [comment]
Tvs RP3150 STAR not listed in mike42 please add it in list i have urgent need.
