### ISSUE TITLE
PDF to thermal recepit

### ISSUE THREAD

**Issue by termy91it** [mike42/escpos-php#568]
hi,
I try to print a thermal recepit with these code but doesn't work why?

```
<?php
require __DIR__ . '/print/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\ImagickEscposImage;
use Mike42\Escpos\EscposImage;

$numero=sprintf("%03d",$_GET['numero']);
$doc=$_GET['dottore'];
require('fpdf.php');
$pdf =new PDF_Code128('P','mm',array(58,70));
$pdf->AddPage();
$pdf->Image("amdos.png",-2,2);
$pdf->SetFont('Arial','B',50);
$pdf->SetY(25);
$pdf->SetX(0);
$pdf->MultiCell(58,20,$numero."|".$doc);
$pdf->Output('F','stampa.pdf');




try {
    // Enter the share name for your USB printer here
    $connector = null;
    $connector = new WindowsPrintConnector("thermalprint");

    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $pages = ImagickEscposImage::loadPdf($pdf);
    foreach ($pages as $page) {
        $printer -> graphics($page);
    }
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
?>
```
the script give me that message:

**Couldn't print to this printer: loadPdf requires imagick extension.** 

thanks for reply.

**Comment by mike42** [comment]
That is `escpos-php` indicating that you are missing a dependency.

When you try to load a PDF like this, this library uses the `imagick` PHP extension to load a PDF file as an image. In turn, Imagick calls GhostScript to do the rendering. You will need to install these on your platform to use this feature.

The install process varies between platforms- please do your own research on the specifics. You can verify that `imagick` is present on the CLI with `php -m`, or from the web via `phpinfo()`, and `imagick` will raise its own error about a missing "delegate" if GhostScript is not available.
