### ISSUE TITLE
Need installation process

### ISSUE THREAD

**Issue by dipakdkale** [mike42/escpos-php#573]
Hi mike 42,

I have some issue i am not about to figure out which files goes where.. The web application is in core php 5.4. Can you please help me out. I need support on the networked printer.

**Comment by mike42** [comment]
Hello,

A step back. Before you write any code, you have two things to do:

- Check that your printer supports ESC/POS.
- Verify your connectivity by sending some text to your printer on the command-line, from the computer that is going to be running PHP.

We get a lot of questions on this issue tracker from people who jump straight into PHP without understanding their printing setup. I really want to emphasize that this library will generate binary output and wrap (mostly) any transport you like, but that it's the user's responsibility to test that the transport they are selecting is actually going to work.

Your goal is to find out how to do send some plain text to your printer command-line. For a networked (Ethernet) printer that is open on port 9100, you could use `netcat` or similar on Linux:

```
echo "Hello World" | nc 10.2.1.3 9100 
```

And on Windows, well, [you will need to do some Googling on that one.](https://serverfault.com/questions/629682/send-text-string-to-a-socket-in-windows).

Understanding part of your print setup is between you, your OS, and your print vendor, and not to do with this library.

Once you have verified that you can do raw printing, and you're fairly sure that you have an ESC/POS printer (you checked, right?), you are ready to install `escpos-php` and to start making receipts.

So to answer your question, this project is distributed as a composer package for PHP developers to use as part of their own applications. If you haven't used composer before, then a good place to start is [here](https://getcomposer.org/doc/00-intro.md).

The command to install this library is-

```
composer require mike42/escpos-php
```

The usage from there depends on your printer, but a `NetworkPrintConnector` sounds likely in your case.

Best of luck!

**Comment by dipakdkale** [comment]
Thanks for writing back.

I have a Epson TM 82 printer , and their is another POS sftware is using
the same.

My problem is I am not able to understand where I have to copy which PHP
file., like autoload.php , or where i should keep the  Mike42\Escpos\Printer
file.

Sorry mike42 , my developer ran away and I have to finalise the products
and their are many agency whom I contacted doesn't have an idea to do it

Thanks and regards
Dipak Digmabar Kale
09860233854

**Comment by mike42** [comment]
As in my previous response, you use `composer` to add this package to your project, which does not involve moving around individual files.

If you're not at a level where you can step through that post yet, then that's OK, but you do need to understand that this is not some commercial support channel. If you're hitting trouble with PHP basics like `composer`, then do a bit of research on that, and come back when you've completed the verification outlined above.

I wish you the best with your application, over to you now.
