### ISSUE TITLE
compatibility with L42 203 dpi - Elgin‎ ?

### ISSUE THREAD

**Issue by matheusnascgomes** [mike42/escpos-php#574]
I would like to know if this lib may be applicable to label printer L42 - 203 DPI - Elgin. I need to know this so I do not run the risk of buying the hardware in vain

Does anyone know that?

**Comment by mike42** [comment]
No, this library is for ESC/POS-compatible printers. It looks like Elgin printers speak something called BPLA ([link](https://www.elgin.com.br/PortalElginAdm/Upload/DownloadPublico/Automacao/L42/Manual%20BPLA.pdf)), which is totally different.

There are some ESC/POS printers that can be loaded with labels though. A POS retailer in your area could tell you what's available with ESC/POS support.

**Comment by matheusnascgomes** [comment]
I can't find any ESC/POS label printer, can you recommend me some?

**Comment by mike42** [comment]
I don't use labels, so can't offer a recommendation based on experience. [Epson lists three ESC/POS label printers](https://www.epson.com.au/pos/products/POS-Printers/POSLabelPrinters.asp?grouptypeid=41&GroupID=42). Again, check with a POS retailer in your area.
