### ISSUE TITLE
Add my printer Cannon

### ISSUE THREAD

**Issue by hmv** [mike42/escpos-php#578]
Hello my friend, I wached your scripts to print in php, I would like  that you add my printer in the php:
Canon MG3500 Series.

thanks for your help

Best regards from Peru
my email: hmv77@hotmail.com

**Comment by mike42** [comment]
This is a receipt printer library for use with ESC/POS-compatible thermal and impact printers.

The Canon MG3500 is not even remotely in that category, so it wont understand the binary format that this library generates.

See also "[I have a printer that does not understand ESC/POS. Can I use this driver?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-a-printer-that-does-not-understand-escpos-can-i-use-this-driver)" in the FAQ.
