### ISSUE TITLE
Print TMU765

### ISSUE THREAD

**Issue by moraser** [mike42/escpos-php#580]
Hi, can I use this library to print on Epson Tmu 765?

**Comment by mike42** [comment]
This type of question appears very frequently. Please see the FAQ entry: "[I have Printer X. Can I use this driver?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver)".
