### ISSUE TITLE
Set Paper Height

### ISSUE THREAD

**Issue by sidikbilardi** [mike42/escpos-php#582]
Can we set Paper Height in this library ?

**Comment by sidikbilardi** [comment]
At least i try running this library on EPSON LX-310 ,  and need to reprint the header every 20 line
so i need to specify paper height to loop the header

any clue for me ?
thanks before mike

**Comment by mike42** [comment]
This library is for ESC/POS-compatible thermal receipt and impact printers, the type you would usually find in point-of-sale (POS) applications. The EPSON LX-310 uses the ESC/P2 page description language, which is not compatible with ESC/POS.

This means that your printer is not not going to work with this library for much more than "Hello World". You would have to generate and send your own ESC/P2 commands via `$connector -> write()` if you are really determined to use this library to solve this problem.

Additional page description languages are not in scope for this project, but I am open to reviewing code changes which improve compatibility for other printers, as long as ESC/POS printers are unaffected.
