### ISSUE TITLE
Can't print qrcode

### ISSUE THREAD

**Issue by HectorLiu** [mike42/escpos-php#584]
hi, I am using sp-pos88v printer. When I tried to print qrcode, i get text(please see attached image)
![1516402476](https://user-images.githubusercontent.com/9148511/41401780-4c939902-6ff3-11e8-99e7-1333c366ba30.jpg)

**Comment by mike42** [comment]
Two questions

- We are all developers here. Can you share your PHP code?
- Does your printer support QR codes?

**Comment by HectorLiu** [comment]
Thanks for reply, here is my code
```
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\Printer;
....
$connector = new NetworkPrintConnector("10.0.0.205", 9100);
$printer = new Printer($connector);
try {
    ...
    $printer->qrCode($this->order->id);
} finally {
    $printer->cut();
    $printer -> close();
}
```

And when i tried the qr-code.php, i get the following
![16325188](https://user-images.githubusercontent.com/9148511/41444484-ed565190-7075-11e8-9f12-30c605ad6c82.jpg)


here is the [DeveloperGuide](https://avior.ru/files/avior_files/termoprint/DeveloperGuideSPRT-SP-POS88V.PDF) of my printer, it does support QR code.

**Comment by mike42** [comment]
As far as I can see, the commands in the guide appear to match what the `qrCode()` method sends, so I don't know why your printer is not delivering the codes.

In the absence of any clear fix, check out "Option 2: Printing codes as images" [in this blog post that I wrote on the topic](https://mike42.me/blog/2015-04-howto-qrcodes-on-receipts-with-escpos-php).

**Comment by mike42** [comment]
See also #208, I would be very interested in getting software QR code fallback into the library if you would like to help.

I'll close this off as I think that's all we can do here. Feel free to re-open if you can see an error in the ESC/POS output, but as above, I think we are generating exactly as listed in the manual for that printer.
