### ISSUE TITLE
Star TSP100III FuturePRNT LAN  not printing using CUPS

### ISSUE THREAD

**Issue by welrachid** [mike42/escpos-php#585]
Hi guys
We're trying to make this printer work.
On your list of working printers we can see that it should be supported. However we are having trouble making the printer print through php and commandline.
The OS is raspbian (Raspberry PI 3 B+), so we had to install CUPS to make the OS use the TSP100III driver.

Im not sure if this is a related issue:
https://github.com/mike42/escpos-php/issues/476

But since we can print a standard txt file we thought there were no problem.
We use the CupsPrintConnector

Code that we use to make a print
```
<?php
require_once __DIR__ . "/escpos-php-development/autoload.php";
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\CupsPrintConnector;
use Mike42\Escpos\EscposImage;

$connector = new CupsPrintConnector('TSP100');
$printer = new Printer($connector);
$printer->text('Test');
$printer->close();

?>
```
This generates a file with the content:
^[@Test
which is unlinked right after (we made a hack during debugging where we did not delete temp files)

Running this command
pi@raspberrypi:~/testing $ sudo lp -d TSP100 /tmp/print-t0f0Ek
request id is TSP100-76 (1 file(s))
does NOT print out anything

Running this command
pi@raspberrypi:~/testing $ sudo echo 'TEST' | lp -d TSP100
request id is TSP100-77 (0 file(s))
print out correcty

Cups setup is the following:
Description:TSP100
Driver:Star TSP100 Cutter (grayscale)
Connection:socket://192.168.3.129:9100Defaults:job-sheets=none, none media=om_x-72-mmy-200-mm_71.97x199.67mm sides=one-sided

By the way.. we tried to use the normal network connector, but this did not work either. It actually made the printer unresponsive so we had to reboot the printer.

I also tried with simple and SP2000 profile - without any luck.

Hopefully some of you can help us out here
 

Thanks!
/Wel

**Comment by mike42** [comment]
Great post.

I think I that what you are seeing is consistent with a Star printer that is not set to "ESC/POS emulation mode", which you would need to do for it to understand the output of this library.

- With the `NetworkPrintConnector`, the printer hangs because we sending it ESC/POS, which it does not understand.
- With CUPS direct printing, most likely `echo hello` either goes straight to the printer (plain text valid in Star command set), or is picked up by your CUPS driver and is converted to Star. I'm not sure what's in your file, but there could be more to the story as you also run the `lp` commands as different users.

So a few things-

- Configure your printer for ESC/POS emulation.
- Use the `NetworkPrintConnector` and `SP2000` profile. You were on the right track there.
- Use either vendor drivers OR this library, not both. A printer driver generates the printer's page description language (binary), which we already do.

Best of luck!

**Comment by welrachid** [comment]
Awesome. I'll look into it tomorrow morning when i get to the office.
Running a "clean" install is always better. Our reason for installing CUPS was that we couldnt find any drivers that would run on the Raspberry Pi. anyway.. i'll get back to you when i have more.
Thanks again.

**Comment by welrachid** [comment]
Message from my collegue:
Dear Mike

I used the last days of testing, now the printer is printing basic text trough the WindowsPrinterConnector.php

The setup is, that the Star TSP100III is installed on my Windows 10 with the Star driver, the printer is shared.

The printer can cut and print using the following command (It cuts and prints 12):
smbclient //192.168.3.138/star1 PASS -U USER -c 'print buffer.txt' -m SMB2
The content of buffer.txt is in hex: 1B 64 03 31 32
This make sens regarding the star manual: http://www.starasia.com/Download/Manual/dot_star_cm_en.pdf

When I tried to cut and print with the code:

```
require_once "escpos-php-development/autoload.php";
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;
use Mike42\Escpos\EscposImage;

$profile = CapabilityProfile::load("SP2000");
$connector = new WindowsPrintConnector('smb://USER:PASS@192.168.3.138/star1');
$printer = new Printer($connector, $profile);
$printer->cut();
$printer->text('12'."\n");
$printer->close();

```
The printer dosen't cut, but prints: VA12

Debugging on this I found that the content of $data in the function finalizeLinux is in hex: 1B 40 1D 56 41 03 31 32 0A

I see that "1B 40" is some initialization, then the "1D 56 41 03" must be the cut... but the printer dosent understand this.

The result is the same in both star line modus and esc/pos modus.


What to do now?

**Comment by welrachid** [comment]
Could this be related? https://github.com/mike42/escpos-php/issues/390

**Comment by mike42** [comment]
Yes, it's related, in that Star printers don't typically understand ESC/POS unless they have an emulation mode and are configured to use it.

The cut command from your comment matches the Star [ESC/POS documentation](http://www.starmicronics.com/support/mannualfolder/escpos_cm_en.pdf), and your printer is still responding to Star Line commands. I would take this as an indication that your printer is not expecting to receive ESC/POS.

Other users have reported success with this model of printer, so I assume it's possible to set it into ESC/POS mode, but that whatever button you're using is not the correct one. I would suggest contacting your vendor at this point to find out how to set and verify that ESC/POS emulation mode is active for this printer.

To be clear, this project exists to build a library for ESC/POS printers, not to help configure them, so I'll close this thread off here. If you find any information which suggests that this printer it was an error to include this with the other Star printers listed in the README, then please file a pull request and we'll remove it to avoid setting incorrect expectations.

**Comment by GianniCarlo** [comment]
@welrachid I'm in the exact position you were in. I'm also using a raspberry pi 3B+, I'm at the point where the printer is configured with ESC/POS emulation (via windows Star config utility). I have:
- Installed the CUPS Star drivers on the Pi, and have added it as a 'LDP/LDR host or printer' in CUPS. 
- Successfully sent a test page from CUPS, but when trying to send a job with this library, nothing is printed (although the print job is successfully created in CUPS).

Via Windows I can print normally, but there are some stores where they don't have a Windows computer. So I'm wondering if you ever managed to print simple text having only the Pi and the printer, no intermediaries?

ps. I followed [Star's guide](http://www.starmicronics.com/support/MannualFolder/common_tsp_linux_en.pdf)

**Comment by GianniCarlo** [comment]
sure! I'll be happy to, let me know how to find you @welrachid

**Comment by welrachid** [comment]
wel.rachid on skype
