### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Exception' with message 'Cannot initialise FilePrintConnector.'

### ISSUE THREAD

**Issue by fullbackup** [mike42/escpos-php#587]
Hi, I have a problem printing to /dev/usb/lp0 from the browser with FileConnector, but is ok when I print using cat to /dev/usb/lp0 from terminal. Tried CUPS connector but gave me problems with some receipts.

This is my setup:
Ubuntu 16.04 Linux 4.4.0-127-lowlatency #153-Ubuntu SMP PREEMPT i686 athlon i686 GNU/Linux
Cups 2.3.1
Xprinter XP-N160I
PHP 5.6 & 7.1
Apache 2.4.18

**Comment by fullbackup** [comment]
Got this error message now... 

PHP Warning:  fopen(/dev/usb/lp0): failed to open stream: Permission denied in /var/www/vendor/mike42/escpos-php/src/Mike42/Escpos/PrintConnectors/FilePrintConnector.php on line 35

**Comment by fullbackup** [comment]
It seems to be working after creating a symlink from /dev/usb/lp0 to /dev/usblp0

**Comment by mike42** [comment]
Looks solved so I'll close this off. For reference, "Permission denied" means exactly what it says, and is not a library issue.

This is best debugged by logging in as the same user that apache is using, and trying to access the device.

```
sudo -u www-data bash
echo "Hello World" > /dev/usb/lp0
```

For Ubuntu and Debian, you normally need to put the `www-data` user into the `lp` group for this to work.

```
sudo usermod -a -G lp www-data
```
