### ISSUE TITLE
Question for printer Connection

### ISSUE THREAD

**Issue by rizwansultan88** [mike42/escpos-php#589]
Hey Mike hope you fine I have question regarding connectivity
File Printer Connection:
$connector = new FilePrintConnector("php://stdout");
$printer = new Printer($connector);

Network Printer Connection: 
$connector = new NetworkPrintConnector("10.x.x.x", 9100);
$printer = new Printer($connector);

What I actually Searching to use Name of printer for connectivity is that possible here to use connectivity with printer name
Code
/* detect locally shared printer */
echo '<pre>';
var_dump(printer_list(PRINTER_ENUM_LOCAL | PRINTER_ENUM_SHARED));
Result:
array(3) {
  [0]=>
  &array(3) {
    ["NAME"]=>
    string(28) "ZDesigner LP 2824 Plus (ZPL)"
    ["DESCRIPTION"]=>
    string(58) "ZDesigner LP 2824 Plus (ZPL),ZDesigner LP 2824 Plus (ZPL),"
    ["COMMENT"]=>
    string(0) ""
  }
  [1]=>
  &array(3) {
    ["NAME"]=>
    string(13) "POS58 Printer"
    ["DESCRIPTION"]=>
    string(23) "POS58 Printer,POS58ENG,"
    ["COMMENT"]=>
    string(0) ""
  }
  [2]=>
  array(3) {
    ["NAME"]=>
    string(19) "BAr-receipt printer"
    ["DESCRIPTION"]=>
    string(44) "BAr-receipt printer,EPSON TM-T70II Receipt5,"
    ["COMMENT"]=>
    string(0) ""
  }
}

**Comment by mike42** [comment]
Not currently, but we have an existing feature request #474, and I'm open to reviewing any pull requests which add this as a new PrintConnector.

This family of functions (`printer_list` and `printer_open`, `printer_write`, `printer_close`) should be able to do raw printing as an alternative to the current way that we connect via a file in `WindowsPrintConnector`. They exist only on Windows installations that carry the `printer` extension.

The enhancement would be to add a new `PrintConnector` implementation, which we should name in a way that identifies the mechanism being used, something like `WindowsPrinterExtPrintConnector`.
