### ISSUE TITLE
Problem to print PDF on the Printer

### ISSUE THREAD

**Issue by matheusfols** [mike42/escpos-php#590]
Hi Mike, how are you?

Could you help me with a problem. I'm using example / print-from-pdf.php
I made the connectors changes for new NetworkPrintConnector ()

However, I did not print correctly. I printed a bunch of strange characters.

Do I need any other settings to print the PDF directly to the printer?

Thank you.

**Comment by mike42** [comment]
Not specifically for PDFs, but this does suggest that you could be using the defaults with something other than an Epson-branded ESC/POS printer.

In the absence of any detail in your post about the hardware or software in your setup, my suggestion would be to read over the README again, and to look at the sections on printer profiles, plus the alternatives to the `graphics()` command.

**Comment by matheusfols** [comment]
Thanks for the response Mike.

I'm using the Kiosk printer BK-T681 Elgin

**Comment by mike42** [comment]
Just with a web search, it's not clear to me whether the BK-T681 is an ESC/POS-compatible printer. Check your available documentation for the word "ESC/POS". If it's not in there, you are most likely wasting your time trying to get this library to work with it.

**Comment by jaimru-farzan** [comment]
Hi @mike42,
I am facing the same problem. I am using EPSON TM-82III. 
I am able to print raw text perfectly. But while printing pdf it's printing strange characters.
Can you help me in this?

**Comment by s2b-git** [comment]
graphics() somehow works very slowly with PDF files
