### ISSUE TITLE
Getting a random set of characters when trying to print 

### ISSUE THREAD

**Issue by gcardozo2809** [mike42/escpos-php#591]
Hello! 

I have setup a Bematech MP-4000 TH, and made sure it's using ESC/POS in it's settings. 

When trying to print anything, something as simple as "Hello World" or a barcode, or any other text instead of getting the text, barcode, etc. I get a completely random set of characters (E.g. u1<cwEra, stuff like that). In adition, cut() doesn't seem to respond either. 

I have setup xampp, made sure mbstring is enabled. I am running this on localhost. PHP version is 7.2.6. 

Code example: 

```
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;
 
try {
	$connector = new WindowsPrintConnector("Bematech"); /*Bematech is the shared printer name*/
	$profile = CapabilityProfile::load("simple");
	$printer = new Printer($connector, $profile);
	$printer -> text("Estacionamiento 123\n");
	$printer -> barcode("123456", Printer::BARCODE_CODE39);
	$printer -> cut();
	$printer -> close();
} catch(Exception $e) {
	echo "Couldn't print to this printer: " . $e -> getMessage() . '\n';
}

?> 
```

With the very same code shown above, sometimes it prints the random characters, and sometimes it doesn't do anything. 

Any help will be greatly appreciated!

**Comment by gcardozo2809** [comment]
Hi Mike,

Thank you for your reply! 

The following works properly.

```
 * Windows: (use an appropriate "net use" command if you need authentication)
 *  echo "Hello World" > testfile
 *  ## If you need authentication, use "net use" to hook up the printer:
 *  # net use "\\computername\Receipt Printer" /user:Guest
 *  # net use "\\computername\Receipt Printer" /user:Bob secret
 *  # net use "\\computername\Receipt Printer" /user:workgroup\Bob secret
 *  copy testfile "\\computername\Receipt Printer"
 *  del testfile
 *
```

Printer understands ESC/POS, and it is set to receive the ESC/POS commands (Bematech printers have 2 modes, ESC/Bem and ESC/POS)

However, I've tried replicating the examples for FilePrintConnector and WindowsPrintConnector and no luck so far, sometimes it doesn't even respond, but when it does, all I get is the random characters. 

If for example, I go to http://127.0.0.1/vendor/example/receipt-with-logo.php, and change it to use WindowsPrintConector("Bematech") it responds, but again, I get a 30cm long receipt with nothing but random characters in it.

**Comment by mike42** [comment]
Good validation. It does not currently look like this is an `escpos-php` issue.

I am not a Windows user, but my last Windows raw printing setup [looked like this](https://mike42.me/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows).

I don't believe we have any Bematech profiles, so once you are sure that raw printing is working, I would suggest using the `simple` profile, it avoids more complex commands that are not understood by non-Epson printers.

**Comment by gcardozo2809** [comment]
Mike, 

Based on this manual: https://www.bematech.com.br/administrador/files/equipamento/suporte/27/1394309158-Impressora%20Fiscal_MP-4000TH%20FI_Manual_01_Manual_do_Usuario_MP-4000_TH_FI[1].pdf (Page 59)

Maybe we could add a driver that should look something like this

---
MP4000:
  name: MP4000
  vendor: Bematech
  notes: >
     Bematech MP-4000 TH
  features:
    barcodeA: true
    barcodeB: true
    bitImageRaster: true
    bitImageColumn: true
    graphics: true
    paperFullCut: true
    paperPartCut: true
  colors:
    0: black
  fonts:
    0:
      name: Font A
      columns: 42
    1:
      name: Font B
      columns: 56
  media:
    width:
      mm: Unknown
      pixels: Unknown
  codePages:
    0: CP850
    1: CP437
    2: CP858
    3: CP860


Not adding myself as I'm not entirely sure about the way to do it.

**Comment by mike42** [comment]
Not quite. You are not yet experiencing an issue that a profile will fix. You can always test the "Hello World" receipt using the `simple` profile, which disables most features. If this doesn't work, then simply your printer does not understand ESC/POS, is faulty, or is not receiving the raw data you are sending it.

So, to debug further, I think you should question your assumptions.

- How have you validated that your device is in ESC/POS mode? It does not currently understand a basic ESC/POS receipt, which is the most reliable test for this.
- How do you know you have a raw printing setup? If the printer crashes when you say "Hello World\n", then the text is not getting to the printer.

Also, is the picture on this guide the same as your printer? It has some more detailed technical information:

- http://www.ekka.com.ua/files/MANUALS/ma501_4421_00_rev14.pdf

**Comment by gcardozo2809** [comment]
Device in ESC/POS > Yes, done through the Bematech Software
Raw Printing SEtup > Maybe I'm missing something here, as far as I know, setting up the printer following the instructions you provided, using Generic/ Text Only drivers, should allow raw printing - Couldnt find anything about that in the manual either. 

The printer is the one in the picture, yes

**Comment by gcardozo2809** [comment]
After hours and hours of testing, trying different drivers, different configurations, etc. I can pretty much say we can confirm that Bematech MP-4000 is simply NOT suitable for this. 

I've repeated all the same steps with an Epson TM-T20II and it works perfectly.

**Comment by mike42** [comment]
Glad to see this is worked-around. I use a Epson TM-T20II as well.

If you're still interested, the programming guide for the MP-4000 shows how to switch the printer to ESC/POS mode, which you can put in your test receipt, something like this:

```php
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;
use Mike42\Escpos\Printer;
$profile = CapabilityProfile::load("simple")
$connector = new WindowsPrintConnector("Bematech");
$connector -> write(Printer::GS . "\xF9\x20\x31");
$printer = new Printer($connector, $profile);
$printer -> text("Hello world\n");
$printer -> close();
```

As above, this should be set up raw, with no vendor drivers (exception would be a `Virtual Port Driver` if absolutely necessary for data transport). It can only cause trouble having vendor drivers on the box while you debug, because we don't ever intentionally interact with them from this code.
