### ISSUE TITLE
Barcode Issue

### ISSUE THREAD

**Issue by sakibrahmancuet** [mike42/escpos-php#593]
I am printing a barcode with the barcode() method, the printed barcode cannot be scanned in any devices.

```
if($counter->printer_connection_type && $counter->printer_connection_type==\App\Enumaration\PrinterConnectionType::USB_CONNECTION) {
                $connector = new WindowsPrintConnector($counter->name);
            }
            else {
                $ip_address = $counter->printer_ip;
                $port = $counter->printer_port;

                $connector = new NetworkPrintConnector($ip_address, $port);
            }

            $printer = new Printer($connector);
$printer->barcode($sale->id."", Printer::BARCODE_CODE39);
```

**Comment by mike42** [comment]
Hi-

This issue needs three pieces of info:

- Which model of printer?
- Can you write a self-contained example so that I can run it on my own printer? I don't have or want the rest of your code.
- Please include a picture of the output, so that it can be compared with what other users see.

**Comment by sakibrahmancuet** [comment]
Hey,

Sorry for the inconvenience. I had problem with the  scanner device. Now it is working fully. You can close this issue now. Thanks.
