### ISSUE TITLE
Printer tested: Zjiang ZJ-8220

### ISSUE THREAD

**Issue by ilgala** [mike42/escpos-php#594]
I've tested this package today with this thermal printer model.

I've tried it both on Ubuntu 18.04 LTS with PHP 7.2 and on Rasbian Stretch. I'm writing a lumen application in order to create a microservice that listens for a print queue and interact with multiple thermal printers.

**Comment by mike42** [comment]
Thanks for reporting!

This printer is now listed in the README,

**Comment by cotiga** [comment]
> I've tested this package today with this thermal printer model.
> 
> I've tried it both on Ubuntu 18.04 LTS with PHP 7.2 and on Rasbian Stretch. I'm writing a lumen application in order to create a microservice that listens for a print queue and interact with multiple thermal printers.

Hi ilgala,
Excuse my intrusion for an off-topic question, but I'm desperately stuck.
I have this printer and want to use it on Ubuntu 18.04, but I can't install it with the driver provided on the Zjiang website.
Can you tell me how you could install it?
Thank you

**Comment by mephjl** [comment]
Excuse me, but I have changed the printer HOB-E801 with ZJ-8220, only the printer, the same cables, but there is an error in

`$connector = new NetworkPrintConnector($ip, $port);`

the script excecution stop at this line.
This is the video : http://www.joomeph.com/20190121_083414.mp4
