### ISSUE TITLE
Fatal error printing to Windows shared printer

### ISSUE THREAD

**Issue by gcardozo2809** [mike42/escpos-php#599]
Hi Mike! 

I keep getting the following: 

Fatal error: in C:\xampp\htdocs\vendor\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 283

This only happens when trying to connect to a shared printer with smb protocol, if I run the website on the computer I´m using as server, without SMB (Specifying only the printer name) it works perfectly. 

Printer is shared in it's settings. 

CODE:

```
require __DIR__ . '/vendor/autoload.php';

use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\CapabilityProfile;
use Mike42\Escpos\EscposImage;

$connector = new WindowsPrintConnector("smb://Gonzalo:password@GONZALO-PC/EPSONTMT20II");
	//$connector = new WindowsPrintConnector($_SESSION["printer"]); THIS WORKS IF USED IN LOCAL PC
	$printer = new Printer($connector);
	$head = EscposImage::load(__DIR__ ."\ingresoHeader.png", false);
	$foot = EscposImage::load(__DIR__ ."\ingresoFooter.png", false);
	$printer->setJustification(Printer::JUSTIFY_CENTER);
	$printer -> bitImage($head);
	$printer -> selectPrintMode(Printer::MODE_FONT_B);
	$printer -> setTextSize(2,2);
	$printer -> text("\nINGRESO: ".$Hora."   ".$Clase."TX".$Matricula."_".$newID."\n\n");
	$printer -> text($DiaYFecha."  USO INTERNO\n\n");
	$printer -> selectPrintMode(Printer::MODE_FONT_B);
	$printer->barcode($newID);
	$printer -> text("\n");
	$printer -> setTextSize(1,1);
	$printer -> bitImage($foot);
	$printer -> cut();
	$printer -> close();

```

Every variable is defined, I just didn't include all the code defining them. 

Any help is much appreciated!

**Comment by mike42** [comment]
Hello,

Would you mind mentioning what the fatal error is, and how you've verified that your sever can connect to your printer?

This currently sounds like a variation of "[Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-from-my-server-on-the-internet)", which we're often asked when people are discovering the limitations of server-side printing.

**Comment by gcardozo2809** [comment]
Hi! Actually the error message I get is the one I posted, I get no other information about it. 

The server is not hosted on the internet, I have a server setup locally connected via WLAN. I can even print a test page using the printer connected to my PC from the server, this is how I know I can communicate with the printer, but when trying to print from the PHP code, I get the error message I posted above.

**Comment by mike42** [comment]
Good initial debugging. I think there are two things you need to follow up here:

- First, find your error logs, or find out how to switch them on. There's an exception being thrown from [line 283 of WindowsPrintConnector](https://github.com/mike42/escpos-php/blob/ed626c2b298f62a44f927f6626b7d79d1bbf7c4f/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php#L283), which contains the command which is being executed, and its output. This is essential debugging info!
- Do some raw printing on the command-line, see if you can get the text "Hello World" to your printer. Test pages and PHP are not the right places to find out whether your  (the `WindowsPrintConnector` in your usage will be wrapping `net use` to authenticate and `copy` to send a text file).

**Comment by Dinho955** [comment]
> CIAO! In realtà il messaggio di errore che ricevo è quello che ho pubblicato, non ricevo altre informazioni a riguardo.
> 
> Il server non è ospitato su Internet, ho una configurazione del server collegata localmente tramite WLAN. Posso anche stampare una pagina di prova utilizzando la stampante collegata al mio PC dal server, in questo modo so che posso comunicare con la stampante, ma quando provo a stampare dal codice PHP, ricevo il messaggio di errore che ho pubblicato sopra.

you solved? I have the same problem
