### ISSUE TITLE
How to connect to Epson TMU220D

### ISSUE THREAD

**Issue by dadinugroho** [mike42/escpos-php#60]
Hi, I have linux server with Epson TMU220D connect to the server using USB. I used this driver from epson tmx-cups-2.0.1.2.tar.gz. My linux server is ubuntu 14.04 lts.

My application is written in Yii! framework. For testing, I put the Escpos.php+src folder in components folder. I am thinking of putting this as extension if working.

The thing is should I use File or Network connector? when checking my linux server, I cannot find /dev/usb. When using Network connector, I got this error message: 

<h1>Exception</h1>
<p>Cannot initialise NetworkPrintConnector: Connection refused (/home/dadinugroho/projects/myshop-app
/protected/components/src/NetworkPrintConnector.php:36)</p><pre>#0 /home/dadinugroho/projects/myshop-app
/protected/controllers/TransactionController.php(516): NetworkPrintConnector->__construct('localhost'
, 9100)

Can someone help me with some guidance?

TIA,

Daniel

**Comment by mike42** [comment]
Hi,

Yep, the error indicates that you're trying to use the `NetworkPrintConnector`, which is for connecting to networked (Ethernet interface) printers.

- Use a FilePrintConnector. The example linked from the main README for Linux/USB is here: https://github.com/mike42/escpos-php/blob/master/example/interface/linux-usb.php
- This PHP driver operates independently of CUPS. I highly suggest uninstalling any system printing driver and ensuring that `usblp` is working correctly instead. `usblp` gives you a device that you can send text to. Once you get a command like `echo "Hello world" > /dev/usb/lp1` working, you'll be on the right track.

**Comment by dadinugroho** [comment]
Thanks mike for prompt response. I really appreciate it. I never think you will answer it in just seconds after posting this question.

So, NetworkPrintConnector is used for network printer not shared local cups printer. What if I am using TP-Link PS110U print server? Can I use NetworkPrintConnector?

If I am to attach the printer directly to the server, I should unsinstall tmx-cups driver and try to get usblp works correctly.

Thank you for your support.

**Comment by mike42** [comment]
Correct. `NetworkPrintConnector` is used for printers with an ethernet port on the back of them, which the driver usually hits on port 9100.

Hm, there might be three setups you can choose from.

### Without print server
![img1](https://cloud.githubusercontent.com/assets/2080552/10410047/18b57ea4-6f81-11e5-87cf-86e2f5695520.png)

This is the easiest to get working, and even if you chose a different solution, start with just the USB printer and computer to make sure that the driver will do what you want.

- Follow [this blog post](http://mike.bitrevision.com/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux), and use a [FilePrintConnector](https://github.com/mike42/escpos-php/blob/master/example/interface/linux-usb.php) - I think you will need to remove the CUPS driver to for `usblp` to be able to claim the printer's USB interface.

### With this print server
![img2](https://cloud.githubusercontent.com/assets/2080552/10410049/3011187e-6f81-11e5-9aa4-2fb687467f27.png)

There are a few things you could do. The tricky bit is that the print server [appears to support](http://www.tp-link.us/faq-239.html) LPR and SMB, but not the raw (port 9100) interface that `escpos-php` uses to talk directly to printers.

So you could:
- Configure the print server to share via SMB, and use a [WindowsPrintConnector](https://github.com/mike42/escpos-php/blob/master/example/interface/smb.php)
- Request LPR support and wait a while to see if it gets added.

### Make your own print server
In case the server has to be in a different place to the printer, dropping in a small embedded computer with a few scripts to is very effective.

- Follow [this blog post](http://mike.bitrevision.com/blog/2015-04-how-to-use-a-raspberry-pi-as-a-print-server) and use a [NetworkPrintConnector](https://github.com/mike42/escpos-php/blob/master/example/interface/ethernet.php).

**Comment by dadinugroho** [comment]
Hi Mike,

Sorry for the delay. I am testing the first scenario without print server by stopping the cups service. usblp pickup my printer and run. It works great.

I do aplogise for being stubborn but I see in cups webadmin that we can change the connection to the printer from local connection to network connection and beside LPR or IPP there is one option HP Jet Direct that should use port 9100. Why we cannot use this with NetworkPrintConnector?

My problem is that in my environment, the server is in second floor and the front desk who need to print will have separate pc and the printer will be attached to the front desk's pc. My current option is probably the front desk pc should be using windows and the printer should be shared using smb. But, I prefer the front desk to use ubuntu linux. 

Thank you for your continuous support.

Daniel

**Comment by dadinugroho** [comment]
Hi Mike, 

After browsing from Internet, I gave up for tp-link print server since some of them reporting that delay is expected during the printing.

I follow your third scenario, How to use a Raspberry Pi as a print server, but I got this error message:

$nohup nc -klp 9100 > /dev/usb/lp0 2> /dev/null&
[1] 929
$ -bash: /dev/usb/lp0: Permission denied

Adding sudo into it and adding user pi, root and www-data to the lp group have been done but still the permission denied is shown.

Can you help on this?

TIA

Daniel

**Comment by mike42** [comment]
Hi,

For your last question, I can't make any guarantees about CUPS because I haven't tested whether it passes through the binary data unmodified, but best of luck if you go that way, and please do let me know if it works!

This permission problem is a general linux thing and not an escpos-php thing, but a good start is to [get USB printing working](http://mike.bitrevision.com/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux) before you try to network it. The detail is in the blog post, but in short:

- Check usblp setup and remove or blacklist any vendor drivers that have claimed the USB interface.
- Check that you are accessing the right device name

Aside from this one, do remove nohup and the hiding of stderr while you debug- the longer command might be supressing some useful output.

    nc -klp 9100 > /dev/usb/lp0

**Comment by mike42** [comment]
Closing, the addition of a CUPS print connector is being tracked in #85 (as it is required to print using USB on Mac OS).

**Comment by yioMtz** [comment]
If it still relevant, I am using TP-Link PS110U print server and I was getting also the permission denied error.
The problem: SELINUX
The fix: :  run a shell console as root or sudo user, and add the following
# /usr/sbin/setsebool http_can_network_connect=1

That's it!

Further reading : http://rkrishardy.com/2009/12/permission-denied-13-when-opening-socket-in-php-apache
