### ISSUE TITLE
Styling Problem

### ISSUE THREAD

**Issue by fiq265** [mike42/escpos-php#601]
Hi Mike,

I have a question but I'm not sure this is the right place or not. I'm sorry about that.

I have design my receipt and it turned great but not sure how to align properly
I just use space to give a space between word.

Do you have idea or way to do this?
I attached here two pictures, first one (above) , how it supposed to be and second (below) was the problem about alignment.

![whatsapp image 2018-07-01 at 12 48 52 pm](https://user-images.githubusercontent.com/26799387/42131125-2852a046-7d2d-11e8-8c65-1674de2a59ca.jpeg)

![whatsapp image 2018-07-01 at 12 43 58 pm](https://user-images.githubusercontent.com/26799387/42131118-f4c8c610-7d2c-11e8-9433-3a63eb5c9598.jpeg)

Thanks again.

**Comment by mike42** [comment]
Hello,

It's not clear from your question that you are actually using `escpos-php` to generate this receipt. If you are, please share your PHP code and some information such as the model of printer.

`sprintf` or `str_pad()` are the normal ways to left-pad text with spaces up to a certain length in PHP.

**Comment by fiq265** [comment]
Hello,

Sorry for lack of info, currently using `escpos-php` to generate the receipt and thanks for the info and tips for the `sprintf` and `sprintf`, I successfully design the receipt as I want. It was a awesome package.
btw Im using printer Epson TM-T82.

Thanks again for the info.

**Comment by mike42** [comment]
Cheers this seems to be solved, so I'll close this off.
