### ISSUE TITLE
Always print space before start printing

### ISSUE THREAD

**Issue by PietroGranati** [mike42/escpos-php#603]
Hi everyone, I simply love using this library, but after 3 days of try I cannon remove the space above the ticket.
I mean, it start printing the ticket after 2cm(about) and cannon resolve this :(

`$tux = EscposImage::load("resources/logo_def2.png", false);

    $printer -> setJustification(Printer::JUSTIFY_CENTER);
    $printer -> bitImage($tux);
    $printer -> feed();
    $printer -> feed();
    $printer -> selectPrintMode(Printer::MODE_DOUBLE_HEIGHT | Printer::MODE_DOUBLE_WIDTH);
    $printer -> text("Visitatore\n");
    $printer -> feed();
    //$printer -> setFont(Printer::FONT_B);
    $printer -> selectPrintMode(Printer::MODE_DOUBLE_HEIGHT | Printer::MODE_EMPHASIZED | Printer::MODE_DOUBLE_WIDTH);
    $printer -> text($cognome . " " . $nome . "\n");
    $printer -> selectPrintMode(Printer::MODE_DOUBLE_HEIGHT | Printer::MODE_DOUBLE_WIDTH);
    //$printer -> setFont(Printer::FONT_A);
    $printer -> feed();
    $printer -> text("- - - - - - - - - - - -");
    $printer -> feed();
    $printer -> qrCode($codice, Printer::QR_ECLEVEL_L, 7, Printer::QR_MODEL_2);
    $printer -> feed();
    $printer -> selectPrintMode();
    $printer -> text("Mostra questo QR Code all'uscita.\n");
    $printer -> text("Il tuo codice è: " . $codice . "\n");
    $printer -> setJustification();
$printer -> cut();
$data = $connector -> getData();
header('Content-type: application/octet-stream');
header('Content-Length: '.strlen($data));
echo $data;
$printer -> close();`

**Comment by mike42** [comment]
Some spacing is expected around cuts (cutting feeds the paper 3 lines by default). 

It's difficult to say much more than that without a fully self-contained example. The code in your question is missing the initialization of a connector and printer, and there could be something else along your transport which is adding line breaks based on the fact you `echo` the data for something else to read.

Does this show spaces between the two prints?

```
echo $data . $data;
```

**Comment by PietroGranati** [comment]
Yeah I echo the data to print on a file, save that file and than send it to the printer from an apple/android device.

Thank you for the answer bur it seems that if I remove the "cut()" command at the end the spacing are fine.

So basically it's the physical space between the "Printer head" and the Printer cutter

**Comment by mike42** [comment]
There may be a good physical reason for the spacing, but one more thing to try-

Your current usage of cut is equivalent to `$printer -> cut(Printer::CUT_FULL, 3)`. Try `$printer -> cut(Printer::CUT_FULL, 2)`, and then `1` and `0`.

It makes no difference on my hardware, but if your printer doesn't need to make the space, then this would be the way to eliminate it.

To quite the docs-

> ### cut($mode, $lines)
>
> Cut the paper.
>
> Parameters:
>
>   - int $mode: Cut mode, either Printer::CUT_FULL or Printer::CUT_PARTIAL. If not specified, Printer::CUT_FULL will be used.
>   - int $lines: Number of lines to feed before cutting. If not specified, 3 will be used.

You can also try `$printer -> cut(); $printer -> reverseFeed(1)`, which on some printers will feed the paper backwards one line after cutting (on my hardware it makes no difference, but worth a shot).
