### ISSUE TITLE
PDFCreator

### ISSUE THREAD

**Issue by iTheLyon** [mike42/escpos-php#604]
You have experience testing with one printer pdfcreator? i try but have error of ghostscript 29100

**Comment by mike42** [comment]
This library does not output PDF files. See also [this FAQ entry](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-i-print-to-file-format-x-with-this).

Please seek an answer elsewhere if you have any questions about these other products.
