### ISSUE TITLE
Support for a EPSON M328A

### ISSUE THREAD

**Issue by HoracioEspinosa** [mike42/escpos-php#605]
Do you have support for this printer? :( thanks

**Comment by mike42** [comment]
I think this is the printer commonly known as the Epson TM-P20.

We haven't had any users who have tested whether the TM-P20 printer understands the code generated by this library yet, but it seems to be an ESC/POS printer, so you should try it out.

Issues with image printing, text encoding, or other more advanced features generally need to be submitted as [a printer profile for escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db/blob/master/doc/add-your-printer.md).
