### ISSUE TITLE
 I need to print through the web specifically on google chrome with a dot matrix printer epson TM-U950 

### ISSUE THREAD

**Issue by krodo93** [mike42/escpos-php#606]
Hello, I need to print through the web specifically on google chrome with a dot matrix printer epson TM-U950 has ESC / POS support, but I printed receipts and slip, is this plugin supported?

**Comment by mike42** [comment]
This is a server-side print library for PHP, not a Chrome plugin.

If your sever (where PHP runs) can connect to a printer which understands ESC/POS, then this library is a good way to generate and send ESC/POS binary data as part of your application.

**Comment by krodo93** [comment]
I understand, the PHP code is in a VPS. Can I send binary data to the printer?

**Comment by mike42** [comment]
I can't answer that for you! This library has connectors which wrap several common transport mechanisms for the raw data, as shown in the README.

If you have a working command which prints from the server, I can show you which connector to use, but if you are trying to figure out raw printing with NAT traversal for the first time, please understand that you're not asking a library usage question, and it should be taken somewhere other than this project's issue tracker.
