### ISSUE TITLE
Multiple recipients /only one printed

### ISSUE THREAD

**Issue by mihaiola** [mike42/escpos-php#607]
We are using this to print some thermal recipients from a web app, recently we are trying to generate multiple recipients at once, so the printer print only the first one, and the rest are ignored. If we try without printer (local), all the files are generate corect. I'm wondering if is any way to fix this ? We are using direct print to network printers.
Best regards,

**Comment by mihaiola** [comment]
Hello, so we are using a php build app to generate diferent food recipient.  There is a thermal printer with is using the NetworkPrintConector to comunicate with the printer.  In the app i have something like a slot with is fill with food orders. When the slot is full i want to print all the recipient from the orders in the slot. When i hit the ok button with is also send the print commands the printer take only the first one, rest of them are ignored.  I assume we use wrong PrintConector and maby we should use CUPS.

**Comment by mike42** [comment]
There's still no code to refer to here, so I'll speak generally.

You can print multiple receipts on the same `Printer` instance as long as you only `close()` it once at the end.

As some background, your printer can only do one physical print at a time. If you are sending the requests in parallel (more than one NetworkPrintConnector open at a time), then the printer might queue, ignore or even interleave later prints, but exact behaviour is quite printer-specific. 

I would generally suggest either refactoring the PHP to print everything as one large receipt, or introduce something to queue the jobs and send them one at a time.

CUPS will queue raw prints, but introduces a delay in printing.
