### ISSUE TITLE
Godex Printer

### ISSUE THREAD

**Issue by mdestafadilah** [mike42/escpos-php#608]
Godex by default support EZPL ... based this information [http://www.godexintl.com/us/download/downloads/list/manuals](Link)

cause, in my organization will switch from Epson to Godex Printer ... (i'm success with Eposn)..

have you try it?

Thanks..

**Comment by mike42** [comment]
EZPL is not the same as ESC/POS, which is what this library generates. If your printer does not understand ESC/POS, then this library will not be useful to you.

Godex printers have been mentioned once before at #432.
