### ISSUE TITLE
Print images with Star SM-T300

### ISSUE THREAD

**Issue by cdinarte** [mike42/escpos-php#609]
Hello, has anyone been able to print images with this printer? I was able to print text but not images nor qrcodes.
Btw, I'm using a different approach by generating a bin file that is then downloaded to an android device and finally printed using the Star SDK.

**Comment by mike42** [comment]
Hello! Reading your question, it is not clear how you are using the `escpos-php` library in your project. Could you post a code snippet showing which CapabilityProfile and print functions you are using?

A web search shows that the Star SM-T300 may have an ESC/POS emulation mode. Generally, `escpos-php` can print to Star printers in this mode (including images, using `bitImage()`).

**Comment by cdinarte** [comment]
Based on one of the samples:

```
<?php

include '../vendor/autoload.php';

use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\CapabilityProfiles\StarCapabilityProfile;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\Printer;

$file = tempnam(sys_get_temp_dir(), 'receipt');

$profile = StarCapabilityProfile::getInstance();
$connector = new FilePrintConnector($file);
$printer   = new Printer($connector, $profile);

$printer->initialize();

$printer -> text("\nHeight 32\n");
$printer->setBarcodeHeight(32);
$printer->barcode("ABC", Printer::BARCODE_CODE39);

try {
    $tux = EscposImage::load('resources/tux.png', false);
    $printer->bitImage($tux);
} catch (Exception $e) {
    /* Images not supported on your PHP, or image file not found */
    $printer->text($e -> getMessage() . "\n");
}

$printer->cut();
$printer->close();

header("Content-Description: File Transfer");
header("Content-disposition: attachment; filename=ipreceipt.bin");
header('Content-Length: '. strlen($file));
header("Pragma: no-cache");
header("Expires: 0");
readfile($file);

```


This starts the download of a bin file. This file is then printed using an android app with the Star SDK. The main goal is to be able to change the receipt on the server as needed.

**Comment by mike42** [comment]
We support three different types of image printing, looks like `bitImageColumnFormat()` might be the one for this printer, since `ESC *` is available on this printer (Source: [Star Mobile Printer Command Manual](http://www.starmicronics.com/support/Mannualfolder/mobile_pm_en15.pdf)).

**Comment by cdinarte** [comment]
Yes, `bitImageColumnFormat()` works! Thanks
