### ISSUE TITLE
Printer tested: 3nStar RPT-008

### ISSUE THREAD

**Issue by germanllop** [mike42/escpos-php#610]
Hello, I've just finished testing with a 3nStar RPT-008 Thermal Printer that I just got and looks good so far.
The only issues that I got is that when I use Double Height the images distorts and I cannot use graphics(), It just prints random characters, but with bitImage() everything is nice.

Thanks for the amazing work!

**Comment by mike42** [comment]
Thanks for reporting! I'll list this printer in the README with the next minor release.

We partly expect that result with `graphics()`, since only Epson printers seem to implement these newer commands.

**Comment by mike42** [comment]
There is a buffer size limit which varies between printers, up to around 4k (at 1 bit per pixel). We track the "large images cause garbled output" problem as issue #206 

It's my view that this driver should detect that a large image is being used and either automatically slice up (segment) the file, or just defer to `bitImageColumnFormat()`, which has no such limitation. Thin horizontal lines appear on the print with any segmentation method, but that's still an improvement on the current output.

**Comment by germanllop** [comment]
Yes, it was that indeed, I just croped the image in four parts manually to fix the issue, but I think I will implement automatic cropping with even parts based on the printer buffer size later.

**Comment by rkgarcia** [comment]
I test this with de 3nstar RPT001 with the same graphics issue, do yo know if it's possible to change the font size?
