### ISSUE TITLE
WiFi printer in weak internet environment

### ISSUE THREAD

**Issue by 8kiwi8** [mike42/escpos-php#614]
Hi,
I have a web base pos using laravel as backend.
All the printing is through network connector and sending image file using bitImageColumnFormat() function.
I implemented queue to send the print job one by one.

As below is the printing job
```
$connector = PrinterHelper::getPrinterConnector($this->_printerInfo);
        if($connector) {
            try {
                $printerID = $this->_printerInfo->id;
                $uuid = Uuid::generate()->string;
                Log::debug('start snapping image');
                $image = SnappyImage::loadView($this->_view, $this->_data)
                    ->setOptions(['width' => 550, 'quality' => 50]);
                Log::debug('done snapping image');
                Log::debug('start saving image');
                $imgPath = storage_path('toprint/printerID_' . $printerID . '_' . $uuid . '.jpg');
                $image->save($imgPath, true);
                Log::debug('done saving image');
                Log::debug('start loading image');
                $img = EscposImage::load($imgPath);
                Log::debug('done loading image');
                Log::debug('start creating printer');
                $printer = new Printer($connector);
                $printer->setPrintLeftMargin(0);
                $printer->setJustification(Printer::JUSTIFY_CENTER);
                Log::debug('done creating printer');
                Log::debug('start sending image');
                $printer->bitImageColumnFormat($img);
                Log::debug('done sending image');
                $printer->cut();
                if(isset($imgPath)) {
                    if(File::exists($imgPath)) {
                        File::delete($imgPath);
                    }
                }
            } catch (\Exception $ex) {
                throw $ex;
           } finally {
                if(isset($printer)) {
                    Log::debug('start close printer');
                    $printer->close();
                    Log::debug('done close printer');
                }
            }
        }
```

I had this error where when the second job comes in before the printer finish printing (even though the first job is done, the printer still printing physically)
```
fwrite(): send of 1832 bytes failed with errno=32 Broken pipe {"exception":"[object] (ErrorException(code: 0): fwrite(): send of 1832 bytes failed with errno=32 Broken pipe at /var/www/vendor/mike42/escpos-php/src/Mike42/Escpos/PrintConnectors/FilePrintConnector.php:72)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'fwrite(): send ...', '/var/www/vendor...', 72, Array)
#1 /var/www/vendor/mike42/escpos-php/src/Mike42/Escpos/PrintConnectors/FilePrintConnector.php(72): fwrite(Resource id #673, '\\e*!a\\x02\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00...')
#2 /var/www/vendor/mike42/escpos-php/src/Mike42/Escpos/Printer.php(490): Mike42\\Escpos\\PrintConnectors\\FilePrintConnector->write('\\e*!a\\x02\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00...')
#3 /var/www/app/Core/Printer/PrintViewJob.php(77): Mike42\\Escpos\\Printer->bitImageColumnFormat(Object(Mike42\\Escpos\\ImagickEscposImage))
#4 /var/www/app/Jobs/ProcessViewPrinting.php(49): App\\Core\\Printer\\PrintViewJob->print()
#5 /var/www/vendor/laravel/framework/src/Illuminate/Redis/Limiters/ConcurrencyLimiter.php(75): App\\Jobs\\ProcessViewPrinting->App\\Jobs\\{closure}()
```
I can avoid this by implement sleep after the first job. But it's hard to estimate the sleep duration as the image size can be vary.

Please advice how can I overcome this issue.

Update:
After some troubleshooting. This error only occur when I'm using NetworkConnector to connect to my Wifi printer (no issue when using USB for same printer). It seem like there's delay for the web socket to be fully closed until the next job can use.  

Printer Model: zywell zy906 wifi printer

**Comment by 8kiwi8** [comment]
Some update

This issue happens after our printer supplier run a specific configuration on the printer
1f 1b 1f b5 41 54 2B 4D 41 58 53 4B 3D 31 0d 0a 0d 0a 00
Which I had no idea what it does (will consult them on coming Monday).

After I reset the printer configuration. This issue has gone.

Now I switch the implementation by chunking the image into small size (550 x 350)px and use bitImage() function to print the image.

This implementation lead me to another issue where garbled text appears in random occurrences.
From the physical view, the garbled text appears after the first chunk as below:

![38284410_10215300737324113_8044255788702629888_n 1](https://user-images.githubusercontent.com/10398988/43643830-191765fc-975f-11e8-9b8f-10ea606da806.jpg)

After study the source code, and bitImage() function.
```
public function bitImage(EscposImage $img, $size = Printer::IMG_DEFAULT)
    {
        self::validateInteger($size, 0, 3, __FUNCTION__);
        $rasterData = $img -> toRasterFormat();
        $header = Printer::dataHeader([$img -> getWidthBytes(), $img -> getHeight()], true);
        $this -> connector -> write(self::GS . "v0" . chr($size) . $header);
        $this -> connector -> write($rasterData);
    }
```
I suspect the packet from this line `$this -> connector -> write(self::GS . "v0" . chr($size) . $header);` has dropped or delayed after `$this -> connector -> write($rasterData);`. due to unstable connection (It's a **WiFi printer**). This cause the printer unable to decode the $rasterData properly.
Printer Model: zywell zy906 (**WiFi Printer**)

However. I not sure whether fwrite() operation will execute in sequence or not.

If it doesn't, my suspicion is correct, then you'll need handler when `$this -> connector -> write($rasterData);` is not successful
If it does, what is the possible problem.

**Comment by 8kiwi8** [comment]
Update: 

after digging into log files, it's really because of `$this -> connector -> write(self::GS . "v0" . chr($size) . $header);` not succuessful.

Is there any walkaround to handle this exception?

```
fwrite(): send of 8 bytes failed with errno=104 Connection reset by peer {"exception":"[object] (ErrorException(code: 0): fwrite(): send of 8 bytes failed with errno=104 Connection reset by peer at /var/www/vendor/mike42/escpos-php/src/Mike42/Escpos/PrintConnectors/FilePrintConnector.php:72)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'fwrite(): send ...', '/var/www/vendor...', 72, Array)
#1 /var/www/vendor/mike42/escpos-php/src/Mike42/Escpos/PrintConnectors/FilePrintConnector.php(72): fwrite(Resource id #827, '\\x1Dv0\\x00A\\x00(\\x00')
#2 /var/www/vendor/mike42/escpos-php/src/Mike42/Escpos/Printer.php(462): Mike42\\Escpos\\PrintConnectors\\FilePrintConnector->write('\\x1Dv0\\x00A\\x00(\\x00')
#3 /var/www/app/Core/Printer/PrintViewJob.php(61): Mike42\\Escpos\\Printer->bitImage(Object(Mike42\\Escpos\\ImagickEscposImage))
```

**Comment by mike42** [comment]
I'm not sure what quality of reply you will get with this information, because you have either network/printer reliability issues plus that unknown configuration setting.

If fewer `write()` calls is what you're after, then you can print to a `DummyPrintConnector`, so that you can send the whole print with one `write()`:

```
// Generate the data
$connector = new DummyPrintConnector();
$profile = CapabilityProfile::load('.....');
$printer = new Printer($connector, $profile);
$printer -> text("Hello world");
$printer -> close();

// Get your data
$myPrintData = $connector -> getData();

// Send the data: use a NetworkPrintConnector or make your own socket calls, your choice!
$realConnector = new NetworkPrintConnector("10.x.y.z", 9100);
$realConnector -> write($myPrintData);
$realConnector -> close();
```

However, I'd lean toward debugging this as a transport or printer issue first, since there are no issues with the correctness of the `bitImage()` output which would affect images of this size.

It sounds like some parts of your setup are worth re-visiting:

- **Fix your WiFi.** Move it, extend it, get a second one, just make it work reliably.
- **Use USB**. This worked, right? Deploy a raspberry PI with CUPS to do the final transport, or roll your own by sending print jobs by performing a HTTP POST to something written in PHP running on the PI.
- **Swap the printer for another one** Epson printers are awesome. Use USB or Ethernet if you can.
- **Get rid of images** Text uses less data, and on an unreliable network, less data means less problems. Text also prints faster, so you're not waiting.
- **Configuration** What does that option do, and why? Is it actually helping? Can it be reversed?

But none of this has much to do with this library, so I'll close this off while you debug. If you can identify something that this code is doing incorrectly, please feel free to re-open.
