### ISSUE TITLE
How to set TextPosition inline?

### ISSUE THREAD

**Issue by jnryu87** [mike42/escpos-php#616]
Hey Mike,
Thanks to your great effort, I decided to use your amazing Library instead JS SDK from Epson.
JS version allows to call Printer only by TCP/IP and it has caused a lot of connection failure with printer.
So I am very happy with your lib and I am almost done !
The only method I need is
'addTextPosition'
I have read github readme and your blog, but all I can find to control position seems to be 
'setPrintLeftMargin'.
I have tried this but it seems it doesn't work properly between two text().
According to my experience, I cannot change align from left to right in a line from the original SDK, right?
Can anyone help me out?

**Comment by mike42** [comment]
Hello,

I want to make sure I'm understanding this correctly. Can you draw a picture or type out a receipt in notepad which shows the layout you are trying to achieve?

**Comment by jnryu87** [comment]
![bills](https://user-images.githubusercontent.com/18186479/43631252-fbf329e0-9702-11e8-80fc-294346fa1cac.jpg)

I put a new bill over old one(dirty one).
New one with your lib, I controlled the position with whitespace like this.
![image](https://user-images.githubusercontent.com/18186479/43631333-3853a6e4-9703-11e8-82ef-6473d8f8f26b.png)

but old one which I used javascript SDK, and used 'addTextPosition' this method with custom method for calculating pos(space) between words. Please take a look below
![image](https://user-images.githubusercontent.com/18186479/43631578-db642106-9703-11e8-8a51-0b4fab7e5386.png)


I hope it's much clear now :))
What will be the best way to align word efficiently with your library??
Oh and I should appreciate you again for this great job USB work with PHP <8

**Comment by jnryu87** [comment]
Never mind... I solved this with this.
Basically it fills 'whitespace' between strings by calculating dots(42 chars max).
`   function textPos($leftStr, $rightStr, $fontSize = 1) {
    $maxChar = (int)(42 / $fontSize);
    $emptySpace = $maxChar - strlen($leftStr) - strlen($rightStr);
    return str_repeat(' ', $emptySpace);
  }`
Hope it's helpful for someone needs 'textPos' left<-> Right :*)
