### ISSUE TITLE
fopen(/dev/usb/lp0): failed to open stream: Permission denied

### ISSUE THREAD

**Issue by erwinjnefer** [mike42/escpos-php#617]
hi mike ..
i got this error log when i use linux usb for printer connection

fopen(/dev/usb/lp0): failed to open stream: Permission denied

thanks..

**Comment by mike42** [comment]
"Permission denied" means exactly what is says!

What are the permissions on `/dev/usb/lp0`, and which user is PHP running as?

It is sometimes more complex, but for me, the `lp` group has write access to `/dev/usb/lp0`, and apache runs PHP as `www-data`. I run `usermod -a -G lp www-data`, restart a few things, and I can then open the printer from PHP.

**Comment by Ahirlabs** [comment]
"Permission denied" on /dev/usb/lp0

Im Try `usermod -a -G lp www-data` , `usermod -a -G lp pcname` its Not Works on My PC 

Then im Try With This Command  `sudo chmod +777 /dev/usb/lp0` its Works Better. 
But After restart a printer Its Again "Permission denied" on /dev/usb/lp0 from PHP.

**Comment by BaiMaoLi** [comment]
Yes, Ahirlabs is right.
I tried sudo chmod +777 /dev/usb/lp0.
and it worked. 
thanks

**Comment by 0l1v3r5** [comment]
thanks dearies

**Comment by blutme** [comment]
Hice esto y me funcionó / I do that and Works for me:

ejemplo para imprimir /print example: pos.php

```
<?php
require __DIR__ .'/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

try{
        $connector = new FilePrintConnector("/dev/usb/lp0");
}

catch(Exception $e){
        exec("python openlp.py");
        try{
                $connector = new FilePrintConnector("/dev/usb/lp0");
        }
        catch(Exception $e){
        exit;
        }
}

$printer = new Printer($connector);


/* Print any text */
$printer -> setEmphasis(true);
$printer -> text("BLUTME TECH .\n");
$printer -> setEmphasis(false);
$printer -> feed();
$printer -> text("Hola care monda! \n");
$printer -> feed(4);


/*Enviar pasos/feeds white line*/
$printer->feed(3);
/*
        Cortar Papel/Cut paper
*/
$printer->cut();
/*
        Abrir cajon/open cashdrw
*/
$printer->pulse();
/*
        Cerrar la conexion con la impresora / close conect pos
*/
$printer->close();
?>

```

y  este otro script sirve para darle permisos chmod: /and make another chmod script called: openlp.py (python 2.7)
```
import os

os.system("sudo chmod +777 /dev/usb/lp0")

```
y disfruten agilados entroilados... /and enjoy good guys...
