### ISSUE TITLE
export esc/pos command as hex string to use by another app to print ?

### ISSUE THREAD

**Issue by erlangp** [mike42/escpos-php#618]

**Comment by erlangp** [comment]
@mike42

**Comment by mike42** [comment]
This library outputs binary ESC/POS.

If you wanted to wire up your own transport or do some downstream conversions, you can implement a new `PrintConnector`, or print to a `DummyPrintConnector`, which has this `getData` method, which we use extensively in our test suite.

**Comment by erlangp** [comment]
@mike42 ow thanks sir :)
