### ISSUE TITLE
I need to print through the web with epson TM-T88V connected with USB PORT

### ISSUE THREAD

**Issue by IKLAMALKI** [mike42/escpos-php#620]
I need to print through a web page using PHP code with an epson TM-T88V connected with a USB PORT.
I've tried to use this code
require 'autoload.php';
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\Printer;
$connector = new FilePrintConnector("php://stdout");
$printer = new Printer($connector);
$printer -> text("Hello World!\n");
$printer -> cut();
$printer -> close();
but I get no answer.

**Comment by fghoekstra** [comment]
You're trying to print to php://stdout
I'm thinking you need to print to the USB port (https://mike42.me/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux)
So $connector = new FilePrintConnector("dev/usb/lp1"); for example

**Comment by tdusmoha** [comment]
> You're trying to print to php://stdout
> I'm thinking you need to print to the USB port (https://mike42.me/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux)
> So $connector = new FilePrintConnector("dev/usb/lp1"); for example

Correct. I have the exact same setup, and it works like a charm. Be sure to sort out the permissions on "dev/usb/lp1" though.
