### ISSUE TITLE
Set allightment issues 

### ISSUE THREAD

**Issue by busyferdinand** [mike42/escpos-php#621]
![1534503937314160179341](https://user-images.githubusercontent.com/37654920/44263198-8554c580-a20d-11e8-8711-0f7028ad5256.jpg)

how to align the circle A portion to the right ? Any help plz !

**Comment by blackty2** [comment]
check the solution [here](https://github.com/mike42/escpos-php/issues/239) by @sk335577

**Comment by busyferdinand** [comment]
Thank you
