### ISSUE TITLE
Please add support for printer iware

### ISSUE THREAD

**Issue by mmohl** [mike42/escpos-php#622]
the driver actually working but it couldn't output the result, it only stored in memory and the text will show if i manually exec the printer on my machine. 

Thank you,

**Comment by mike42** [comment]
Just doing a web search for iware printers, I only see references to `iware` is a POS software vendor, not as a printer vendor.

Could you share the PHP code you are using and the model of printer? It's not clear to me what hardware/software is involved, and how this library might fit into it.
