### ISSUE TITLE
Star tsp100III Lan version problem

### ISSUE THREAD

**Issue by MarkusKoo1** [mike42/escpos-php#626]
Hi,

FYI

I have been bashing my head against the wall with this printer because it does not print anything even straight from command line echo "foobar" | nc 123.456.78.9 9100  

Looks like this printer needs a special wrapper https://www.starmicronics.com/faq/attachments/118/Print%20Commands%20to%20LAN%20Port_Ubuntu.zip

**Comment by mike42** [comment]
Interesting to know, thank you for sharing.

**Comment by GianniCarlo** [comment]
@MarkusKoo1 the link is dead, would you mind sharing what it contained? what is/was the special wrapper? I'm having trouble with this particular printer as well

**Comment by MarkusKoo1** [comment]
@GianniCarlo 

https://www.starmicronics.com/absolutefm/absolutefm/attachments/118/Print%20Commands%20to%20LAN%20Port_Ubuntu.zip

**Comment by GianniCarlo** [comment]
Thanks @MarkusKoo1 !

**Comment by joshluongo** [comment]
Sorry to reply to this old thread but i'm having the same issue with this printer. The link is now offline, did it solve the issue?
