### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by IsaacMujica** [mike42/escpos-php#629]
Hello, I have the following issue:

Fatal error: Uncaught Error: Class 'Mike42\Escpos\PrintConnectors\WindowsPrintConnector' not found in C:\xampp\htdocs\pedidosvlocalv2\src\class.printv2.php:23

And this is my code:

`require_once __DIR__ . '\autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

try {
    // Enter the share name for your USB printer here
    //$connector = null;
    $connector = new WindowsPrintConnector("BIXOLON SRP-350plus");
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}`

Thanks for any help.

**Comment by rakeshkumar33** [comment]
Fatal error: Uncaught Error: Class 'Mike42\Escpos\PrintConnectors\FilePrintConnector' not found in C:\xampp\htdocs\printer\prnt\src\print.php:5 Stack trace: #0 {main} thrown in C:\xampp\htdocs\printer\prnt\src\print.php on line 5


this is my code

<?php
require  'vendor/autoload.php';
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\Printer;
$connector = new FilePrintConnector("php://stdout");
$printer = new Printer($connector);
$printer -> text("Hello World!\n");
$printer -> cut();
$printer -> close();
?>

**Comment by mike42** [comment]
@IsaacMujica @rakeshkumar33 - If the `escpos-php` classes cannot be seen, then this library is not correctly installed on your project. Please consider re-visiting "Basic Setup" in the README and following the steps to add it via composer.

**Comment by apoorvaHealthians** [comment]
@mike42  hi can you help me I need to print barcode using tsc tpp 244 printer.

**Comment by mbadarp** [comment]
@mike42 
Message: Class 'Mike42\Escpos\PrintConnectors\WindowsPrintConnector' not found

require __DIR__ . '/../../autoload.php';

use Mike42\Escpos\EscposImage;
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

$connector = new WindowsPrintConnector("printer_nazar");
$printer = new Printer($connector);

it works on local, but when hosting it pops up an error like that. I have checked the capital letters and they are correct, what do you think caused the error

**Comment by SalimF** [comment]
Alright I figure it out, I was trying to use windows class on Linux machine the autoloader won't load that class automatically.

```
PHP Fatal error:  Uncaught Error: Class 'WindowsPrintConnector' not found in vendor/arabic.php:24
Stack trace:
#0 {main}
```

```
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\Printer;
use Mike42\Escpos\CapabilityProfile; 
use Mike42\Escpos\PrintBuffers\ImagePrintBuffer; 
require   __DIR__ . '/autoload.php'   ;
```
