### ISSUE TITLE
How to print chinese?

### ISSUE THREAD

**Issue by junezhou** [mike42/escpos-php#63]
How to print chinese?
utf8

**Comment by mike42** [comment]
This is not currently supported, but there is a lot of interest in it over at #37, and somebody has their printer working by replacing my UTF8 wrangler with a one-line UTF-8 to GBK conversion.

Can you let me know-
- Printer manufacturer & model
- Printer interface (USB/Serial/Ethernet).
- Are you trying to print traditional or simplified characters?

**Comment by mike42** [comment]
No extra info here, closing as duplicate of #37
