### ISSUE TITLE
Can't print from PDF

### ISSUE THREAD

**Issue by sbrutin** [mike42/escpos-php#630]
Hi,

I'm trying to print from a pdf generated by fpdf lib and it didn't work as expected.
Did you know what could possibly be wrong ?

Thanks,
![signal-2018-09-14-084300](https://user-images.githubusercontent.com/893148/45534133-6b9da280-b7fa-11e8-8abf-f5c01e3c4128.jpeg)

**Comment by mike42** [comment]
Good question. There is not much to go off here, would you mind sharing your PHP code?

It's not currently clear to me how this library is being used in your setup, if at all.

**Comment by olkotz** [comment]
Hello Mike, thanks for everything you create for the comunity!!

I need to print a pdf file and i have this issue...

Fatal error: Uncaught Exception: loadPdf requires imagick extension. in C:\xampp\htdocs\admin\ticket\Mike42\Escpos\ImagickEscposImage.php:218 Stack trace: #0 C:\xampp\htdocs\admin\pdf.php(25): Mike42\Escpos\ImagickEscposImage::loadPdf('/comandaX.pdf', 260) #1 {main} thrown in C:\xampp\htdocs\admin\ticket\Mike42\Escpos\ImagickEscposImage.php on line 218

If you can help me i really grateful!!!!

**Comment by olkotz** [comment]
this is part of my php code when i invoque the function...

$pdf = 'resources/comandaX.pdf';
$pages = ImagickEscposImage::loadPdf($pdf, 260);

i put the pdf file into the resource folder on escpos proyect folder

**Comment by mike42** [comment]
@olkotz - your issue is not the same as the one in this thread. Please install imagick, and post in a new thread if you have any follow-up questions.

**Comment by ajay2690** [comment]
I install imagick but still i am not able to print from pdf file
I am getting below error
ImagickException: Failed to read the file in C:\xampp\htdocs\ppp\vendor\mike42\escpos-php\src\Mike42\Escpos\ImagickEscposImage.php:228
Stack trace:
#0 C:\xampp\htdocs\ppp\vendor\mike42\escpos-php\src\Mike42\Escpos\ImagickEscposImage.php(228): Imagick->readImage('http://localhos...')
#1 C:\xampp\htdocs\ppp\server.php(202): Mike42\Escpos\ImagickEscposImage::loadPdf('http://localhos...')
#2 [internal function]: {closure}(Object(Hoa\Event\Bucket))
#3 C:\xampp\htdocs\ppp\vendor\hoa\consistency\Xcallable.php(159): call_user_func_array(Object(Closure), Array)
#4 C:\xampp\htdocs\ppp\vendor\hoa\event\Listener.php(179): Hoa\Consistency\Xcallable->__invoke(Object(Hoa\Event\Bucket))
#5 C:\xampp\htdocs\ppp\vendor\hoa\websocket\Connection.php(303): Hoa\Event\Listener->fire('message', Object(Hoa\Event\Bucket))
#6 C:\xampp\htdocs\ppp\vendor\hoa\socket\Connection\Handler.php(195): Hoa\Websocket\Connection->_run(Object(Hoa\Websocket\Node))
#7 C:\xampp\htdocs\ppp\server.php(229): Hoa\Socket\Connection\Handler->run()
#8 {main}

**Comment by vasimevincedev** [comment]
> Good question. There is not much to go off here, would you mind sharing your PHP code?
> 
> It's not currently clear to me how this library is being used in your setup, if at all.

Hey Mike, Can Please share the solution to this issue.

**Comment by wpamn** [comment]
> 

Hey Mike, Can Please share the solution to this issue.

**Comment by amanevdpl** [comment]
> Good question. There is not much to go off here, would you mind sharing your PHP code?
> 
> It's not currently clear to me how this library is being used in your setup, if at all.

Hey Mike, Can Please share the solution to this issue.
