### ISSUE TITLE
How to know if the printer is busy?

### ISSUE THREAD

**Issue by sgiradoa-psl** [mike42/escpos-php#634]
Hello guys,
I would like to know if you already have a way to know if the printer is busy (Printing another job) so I can hold the  next job until the printer finishes.
Someone told me that maybe I can use the buffer (So if the buffer has some data is very likely is printing) but I don't know if that is possible.

Dos someone any information about it? How to know if the printer is busy (Printing another job) ?

**Comment by mike42** [comment]
There is currently no way to check the printer status in this library, and unfortunately printers behave in all different ways when they are already printing and you send them more data.

If you have a scenario where print jobs can come from multiple sources at the same time, then you need a print server which passes them on one at a time.

I would either ensure that I had a printer with a print server built into the Ethernet card, or I would connect the printer to a Raspberry Pi and use CUPS to share it.
