### ISSUE TITLE
Windows/USB: Error Printing Receipt From Epson Printer Using Escpos-php, Please How can I Resolve This. Thank You

### ISSUE THREAD

**Issue by Macwilcy** [mike42/escpos-php#64]
mike42 Thanks so much for your help and time in making this available.

I have tried to implement your codes and I have not seem to find a headway. I would really appreciate your help.

I am using Epson TM-T20

I tried the "hello word" world test script above and it gave this error :

```
"Warning: copy(\\MGC-LTD-PC\ESDPRT001): failed to open stream: No such file or directory in C:\xampp\htdocs\jamiykeboutique\lib\src\WindowsPrintConnector.php on line 339
Couldn't print to this printer: Failed to copy file to printer"
```

Please, how do I resolve this and make the printer to print. The code I used is below

```php
<?php
require_once("lib/Escpos.php");
/**
 * Install the printer using USB printing support, and the "Generic / Text Only" driver,
 * then share it (you can use a firewall so that it can only be seen locally).
 * 
 * Use a WindowsPrintConnector with the share name to print.
 * 
 * Troubleshooting: Fire up a command prompt, and ensure that (if your printer is shared as
 * "Receipt Printer), the following commands work:
 * 
 *      echo "Hello World" > testfile
 *      print /D:"\\%COMPUTERNAME%\Receipt Printer" testfile
 *      del testfile
 */
try {
    // Enter the share name for your USB printer here
    $connector = new WindowsPrintConnector("ESDPRT001");
    /* Print a "Hello world" receipt" */
    $printer = new Escpos($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();

    /* Close printer */
    $printer -> close();
} catch(Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

?>
```

It seems you have change your codes in regarding the WindowsPrintConnector(). The link to the one you gave above and the one in the master folder I downloaded are not looking alike

Please Note : I tried to share the Epson TM-T20 printer as you describe in your blog, but it kept on saying "Another printer shared already have the same name". 

Please, how can I implement your code so It will work for me. Thank so much

**Comment by mike42** [comment]
I'm assuming your printer is USB, as it sounds like you're referring to [this blog post](http://mike.bitrevision.com/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows) and [this example](https://github.com/mike42/escpos-php/tree/master/example/interface/windows-usb.php).

The `WindowsPrintConnector` operates on shared printers, and you've mentioned that sharing the printer failed. You need to fix this before you continue (eg, you could try uninstalling any drivers and printers and attempt to re-share it according to the blog post, or consult Google with the error you mentioned).

Before you attempt into PHP, you _must_ be able to print to the shared printer via the command-line. What `escpos-php` does in the background is mentioned in the 'troubleshooting' section in the example you're using:

````php
/*
 * Troubleshooting: Fire up a command prompt, and ensure that (if your printer is shared as
 * "Receipt Printer), the following commands work:
 * 
 * 	echo "Hello World" > testfile
 * 	copy testfile "\\%COMPUTERNAME%\Receipt Printer"
 * 	del testfile
 */
```

Let me know if this is still an issue once you get your printer working with Windows. It would also help if you include:
- Windows version
- PHP version

**Comment by Macwilcy** [comment]
Hi Mike,

Thanks so much for your response,

I will try and resolve the sharing issue.

1. Windows version : Window 7

2. PHP version : 5.6.12

I will keep you updated

Thanks again.

**Comment by Macwilcy** [comment]
Hi Mike,

I can now see the shared printer \\localhost

2. I was able to execute the command you provided above using command prompt "echo "Hello World" > testfile
 *  copy testfile "\\%COMPUTERNAME%\Receipt Printer""
And I got a response " 1 file(s) copied. "

3. I was also able to print the "Hello World" using the command you provided and I got the response "testfile is currently being printed" and it actually printed "Hello World" I tried it severe times more and it printed 

4. However, When I tried the escpos-php and the example you provided. It printed the following response :
"Couldn't print to this printer: Printer 'pos-receipt printer' is not valid. Use local port (LPT1, COM1, etc) or smb://computer/printer notation."

5. "pos-receipt printer" is the printer name I used for 2 and 3 above

Are my having the right escpos-php code ? I got it from here - github.com

Please, how do I fix this. Thank you

**Comment by mike42** [comment]
You're on the right track. Regexes are used to check printer names for use with the connector, and it is failing because of the "-" character.

I'll post a change in a few moments. If you adjust your printer name to remove the "-" you will be able to work around it.

**Comment by Macwilcy** [comment]
Thanks so much. Let me work on it

**Comment by mike42** [comment]
Updated the regexes to be a bit more forgiving (I don't know the real set of allowed characters, so I've only allowed ascii + spaces & dashes in most places).

Simple printer names may be advisable for historical reasons though- https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/print_choosing_a_printer_name.mspx

**Comment by Macwilcy** [comment]
Hi Mike,

Thanks so much. It is now printing, I changed the printer name and it is now working. 

Thanks a lot.

I will continue to work on the arrangement of the printout.  am so glad it is finally printing from the printer.

Thank again. I really appreciate

**Comment by imran353** [comment]
Hello, I have an Epson TM-T88V connected via USB in port "ESDPRT001" but I cannot print anything to the printer.
I get the following error - "Couldn't print to this printer: Printer 'ESDPRT001' is not a valid printer name. Use local port (LPT1, COM1, etc) or smb://computer/printer notation."
I tried the command line test and it worked successfully.
Can you help me. If you need any other information please do tell.

**Comment by PanJ** [comment]
@mike42 The regex is broken. I recommend `^\w+[\s\w-]*\w+$`

**Comment by imran353** [comment]
Sorry Can you explain it?

**Comment by mike42** [comment]
@imran353 - This is not the same (Mac/USB is currently "Not Tested" per the [compatibility table](https://github.com/mike42/escpos-php#interfaces-and-operating-systems)), please file a [new issue](https://github.com/mike42/escpos-php/issues/new) if you'd like to help pioneer this feature.

@PanJ - Thanks for spotting this, my mistake. I used `/^[\w-]+(\s[\w-]+)*$/`, see [related unit test](https://github.com/mike42/escpos-php/commit/b714062c0b3a727000504d6f9aaed206d9a2d3f4).

Glad to hear this Windows/USB setup is working.

**Comment by Macwilcy** [comment]
Hi Mike42,
It's been working great.

The challenges is that, it is cutting the right column content and shifting the remaining text to a new line. It is leaving too many space between the left and right column. Can we adjust the right column width so it can accommodate more than 10 characters. Thanks

2. Can It read a bar code ? If it cannot, please do you know how I can get PHP bar code reader script working ?

3. Thanks so much

**Comment by mike42** [comment]
This driver doesn't wrap lines, and your printer should get you more columns than that. Are you using 80mm or 56mm paper? Can you post a snippet of what code you're using? I've got a TM-T20 so I run the same print-out and tell you if it's your code or the printer config if you like (check [Epson](http://www.epson.com.au/pos/products/receiptprinters/DisplaySpecs.asp?id=tmt20) for config). 

Re barcode *reading*, this driver will *write* barcodes, but not read them. A usual POS barcode reader registers itself as a USB Human Interface Device and types out numbers as they're scanned, so you should need no special software to integrate barcode scanning into your forms.

**Comment by Macwilcy** [comment]
Mike42 Thanks a lot. I will post the snippet.

Does the escpos work with windows XP ?

I have been trying to us it with windows XP but to no avail. I installed the printer based on the same description you posted which is also what I used for my windows 7 and it worked perfectly. However, it is not working with windows XP - at lease, in my own case as for now.

I did the \\localhost and it did not work either.

Please is there a way to solve this. Thanks

Machine and OS:  jming POS and window XP
I want the jming POS system to run PHP based POS system

Thanks for your help

**Comment by Macwilcy** [comment]
Hi Mike42.

It is now working well with windows XP.

It was my oversight before.

Thanks again.

**Comment by Macwilcy** [comment]
Hi Mike.

Thanks for the good work you are doing.

Please, how can I print two copies of the receipt for one sale ?

I tried and it gave error of previously declared class

Thanks for your help

**Comment by mike42** [comment]
Can you post a code snippet of what you're currently attempting? It sounds like you may have `include()`'d the same file twice.

**Comment by Macwilcy** [comment]
Yes, that's what I did. Is there any other way ?

There are really some stuff I do not know. But am willing to ask and learn. Thanks for your help

**Comment by Macwilcy** [comment]
Hi Mike42, 

Please, I really need your help in printing two copies of each sales. Thanks so much, Mike42

**Comment by mike42** [comment]
Hey as above, can you post a code snippet of what you're doing? You've probably just used `include()` inside a loop, but it's hard to know without seeing it.

**Comment by Macwilcy** [comment]
Hi Mike42

Below is the snippet, 

--- After inserting the sales details ...

if($updateProd){
                                // Select this Customer information so we can update this particular customer's no. of transactions and also assign this particular Discount Voucher Card Code to this Customer
                                $selectCustD = mysql_query("SELECT id,no_of_tranx FROM customer_info WHERE customer_name='$customerName' && status=1");
                                if(mysql_num_rows($selectCustD) > 0){
                                    while($getCustD = mysql_fetch_array($selectCustD)){
                                        $cid = $getCustD['id'];
                                        $cuTranxCount = $getCustD['no_of_tranx'];

                                        $cuTranxCount2 = $cuTranxCount+$i;

                                        //Update the this particular Customer's information and increase his/her transaction count and also assign the Discount Voucher Code to this particular customer
                                        $updateCustomerInfo = mysql_query("UPDATE customer_info SET no_of_tranx='$cuTranxCount2' WHERE id='$cid' && `customer_name`='$customerName' && status=1");
                                    }
                                 }
                                 include("includes/pos-printer-receipt.inc.php");
                                $success = "New sales made successfully. Thank you";
                            }
                            else{
                                $error = "Sorry, the new sales could not be transacted successfully at this moment. Please try again. Thank you";
                            }


I tried the loop and it was printing two copies but with the duplicate class declaration error

Thanks for your help

**Comment by mike42** [comment]
Hi- This example does not appear to contain the issue. What is in `includes/pos-printer-receipt.inc.php`?

My suggested approach is to open the printer, and then send two copies of the data before you close it. If you `include()` `Escpos.php`, then swap it for a `require_once()` to save yourself any trouble.

````php
<?php
/* Print a receipt twice */
require_once("Escpos.php");

// Stuff you would get from the UI and database
$copies = 2;
$receiptData = array(
	"title" => "Bob's Hardware Shop LLC",
	"item" => array(
		array("Brick", "17", "17.00"),
		array("Roof", "1", "1.00"),
		array("Concrete kg", "20", "40.00")
	),
	"total" => "123.40"
);

// Open printer
$conn = new FilePrintConnector("/dev/usb/lp1");
$profile = DefaultCapabilityProfile::getInstance();

// Open printer, print a few times, close printer
$printer = new Escpos($conn, $profile);
try {
	// Print a few copies
	for($i = 1; $i < $copies; $i++) {
		printReceipt($receiptData, $printer, $i, $copies);
	}
} finally {
	// Always close the printer
	$printer -> close();
}

/**
 * Print data to the printer.
 *
 * @param $data receipt data
 * @param $p printer
 * @param $id Copy number
 * @param $count Total copies
 */
function printReceipt(array $data, Escpos $p, $id, $count) {
	// Header
	$p -> text($data['title']);
	foreach($data['item'] as $item) {
		// Print items
		$p -> text($item[0] . " " . $item[1] . " $ " . $item[2]);
	}
	// Print total
	$p -> text($data["total"]);
	// Label copy
	$p -> text("Copy $id of $count");
	$p -> cut();
}
````

**Comment by Macwilcy** [comment]
Mike42, Thanks so much. I really appreciate your help and time

**Comment by Macwilcy** [comment]
Hi Mike42,
I believe you are doing great.

Is ESCPOS-PHP work with PHP .exe files ?

I compiled PHP Sales and Inventory Management System application into a .exe file so it can be installed. But printing of receipt gives the following error:

"Fatal error: Call to undefined function mb_detect_encoding() in C:\Program Files (x86)\Macwilcy Sales and Inventory Management System\www\lib\src\EscposPrintBuffer.php on line 97" 

Please is there a way for this to be resolved ?

Thanks again

**Comment by mike42** [comment]
Hi, this is not escpos-php problem- I'm not sure how you're compiling, but usually this error would mean the `mbstring` extension is missing from your PHP build.

Please direct this query to the support forums for your compiler product, or check their FAQ for how to load extensions.

**Comment by Macwilcy** [comment]
Thanks Mike42.

**Comment by josanu** [comment]
Hello Mike

I tried to read the linux logs but I could not find any clue.

I am running a linux php
The idea is to print in a windows printer

My code is the following 👍 

<?php
/* Call this file 'hello-world.php' */

error_reporting(E_ALL);
ini_set('display_errors','1');

require __DIR__ . '/vendor/mike42/escpos-php/autoload.php';

use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

try {
	// Enter the share name for your USB printer here
	$connector = new WindowsPrintConnector("smb://LAPTOP-0J27B75G/Tickets");
	
	//smb://computer/printer notation
	//$connector = null;
	$printer = new Printer($connector);

	/* Print a "Hello world" receipt" */
	$printer -> text("Hello World!\n");
	$printer -> cut();
	
	/* Close printer */
	$printer -> close();
} catch(Exception $e) {
	echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

I am able to print from windows, but when I run my php code it throws the following message

Couldn't print to this printer: Failed to print. Command "smbclient '//LAPTOP-0J27B75G/Tickets' -c 'print -' -N" failed with exit code 1: WARNING: The "syslog" option is deprecatedConnection to LAPTOP-0J27B75G failed (Error NT_STATUS_UNSUCCESSFUL)

**Comment by proglio** [comment]
Good afternoon will have an example of implementation of the ESC / POS library in a hosting hosting help ...!

**Comment by mike42** [comment]
@josanu @proglio - This issue has been closed for over a year. If you have the same question as OP, then the [README](https://github.com/mike42/escpos-php/blob/development/README.md) and [FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md) should be your first port of call.

If you can send data to your printer on the command-line but not PHP, then please open new issue that explains your setup, and outlines the steps you have taken to debug so far.

If you don't know how to get raw data to your printer, then you need find out: check with your vendor's support documentation, support channels, or hit up Google. This library will generate great raw ESC/POS output, but it's important to research test the connectivity yourself before attempting to use this library.

I'll lock the discussion here so that it does not attract more comments.
