### ISSUE TITLE
open(/dev/usb/lp1): failed to open stream: Permission denied 

### ISSUE THREAD

**Issue by haviansyah** [mike42/escpos-php#644]
Hi Mike i got open(/dev/usb/lp1): failed to open stream: Permission denied 
when i try to print from browser using xampp 
but when i try using command line "php foo.php" it's worked,

i was doing sudo usermod -a -G lp www-data like in #617 but it's still error

im using ubuntu 18.04, XAMPP, panda x58 thermal printer 

thanks in advance

**Comment by mike42** [comment]
Just on permissions, can you restart the box and check these?

```
stat /dev/usb/lp1
id www-data 
```

You should then be able to switch to the www-data user to print with no trouble.

```
sudo -u www-data bash
php foo.php
```

A more complete reference would be [this blog post from a few years back](https://mike42.me/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux), which includes better `usblp` debugging., which may be applicable if `/dev/usb/lp1` is not appearing as a character device.

**Comment by haviansyah** [comment]
thanks for ur answer mike, 
i was uninstall lampp and install apache2,php,and mysql manualy and it's work
i dont know why it's doesn't work in xampp
and it was solved for me now
