### ISSUE TITLE
brother QL700?

### ISSUE THREAD

**Issue by danielst2006** [mike42/escpos-php#648]
brother QL700?

**Comment by mike42** [comment]
Hi, I'm assuming you've got one of these printers.

I found the manual "Brother QL Series Command Reference (QL-500/550/560/570/580N/650TD/700/1050/1060N)" on the vendor's website, which suggests that the printer understands ESC/P, but does not mention ESC/POS. These protocols are not the same.

So, you can always try, but I don't think your printer will work with `escpos-php`. See also "[I have a printer that does not understand ESC/POS. Can I use this driver?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#i-have-a-printer-that-does-not-understand-escpos-can-i-use-this-driver)" in the FAQ.
