### ISSUE TITLE
Windows Network printing error : Permission denied

### ISSUE THREAD

**Issue by dannygunawan** [mike42/escpos-php#65]
I could print from my USB local connection successfully using smb://localhost/printer1. 

However, when I was trying to print to network shared printer on other computer, I got permission denied error.
    
    Connector :   smb://nano1/lx310

    Warning: copy(\\nano1\lx310): failed to open stream: Permission denied in E:\Projects\escpos-php\src\WindowsPrintConnector.php on line 340

I also tried to add user credential anc changed the connector path to : 

    smb://Guest@nano1/lx310

But I got the same error.
I checked the permission of the printer, there was "Everyone" with Print permission already.

Is there any configuration I missed?

Environment: Windows 7 & PHP 5.4.33

**Comment by dannygunawan** [comment]
OK, I found the solution for my case.
I had to give **Guests group** write permission to folder *C:\windows\system32\spool\printers\*

[Reference](http://serverfault.com/questions/191393/access-is-denied-when-copying-text-file-to-printer-unc-path)

**Comment by akinnega** [comment]
@dannygunawan can you describe it in detail how you short this proplem, bcoz i am also facing the same proplem. Plz help out. am get this errors.
Message:  copy(\\LTENTERPRISE-PC\l220): failed to open stream: Permission denied</p>
<p>Filename: print/WindowsPrintConnector.php</p>
<p>Line Number: 339</p>

</div><br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Failed to copy file to printer' in C:\xampp\htdocs\motel\application\views\print\WindowsPrintConnector.php:262


i have tried as you said. changed permission of C:\windows\system32\spool\printers\ but still same.

**Comment by dannygunawan** [comment]
@akinnega here is what my permission setting:

![screen shot 11-20-15 at 12 29 pm](https://cloud.githubusercontent.com/assets/12872940/11292604/23f6e772-8f83-11e5-885c-640e3393b336.JPG)

In your case, you should apply this permission on the LTENTERPRISE-PC.

**Comment by akinnega** [comment]
Thank you for response and solution. One more favour plz. Do i have to close the firewall in pc with printer attached ?

**Comment by r4llproject** [comment]
I use windows 7, and already set permission setting on PRINTERS as your sample.
But, still got :
 ErrorException in WindowsPrintConnector.php line 372:
copy(\\192.168.1.100\epsonlx310): failed to open stream: Permission denied

Is there anything can do?

**Comment by IsaacMujica** [comment]
Pretty thanks about that <3

**Comment by bob0044** [comment]
> I use windows 7, and already set permission setting on PRINTERS as your sample.
> But, still got :
> ErrorException in WindowsPrintConnector.php line 372:
> copy(\192.168.1.100\epsonlx310): failed to open stream: Permission denied
> 
> Is there anything can do?

Hi! You have to put "smb://guest@hosting/printername" as argument for the connection. It's important to indicate the guest user, because you gave write permission to a guest user in the printer folder.

Hope it helps you!

**Comment by lucaspertuz** [comment]
importante usar la cola de impresion , no escribir directo en la impresora
![Sin título](https://user-images.githubusercontent.com/10199606/109572309-ff42b680-7aba-11eb-96e6-66fa1eb62801.png)

**Comment by rontuku** [comment]
I hope am not late, this will help someone.
I managed to sort this error by setting fastgi.impersonate = 0 and it worked.
