### ISSUE TITLE
 NIPPON printer does not cut paper

### ISSUE THREAD

**Issue by Cundalf** [mike42/escpos-php#667]
Hello everyone,
I have a problem with the cut() function with a particular printer and I do not know how to solve it. The printer does not cut the paper when executing the function.
The printer is: NIPPON PRIMEX NP-KV30 (ver: 2.02).
I tested on an EPSON and it worked.
I am using PHP 5.6 and Codeigniter 3.

My code is similar to this:
```
$connector = new WindowsPrintConnector("smb://pc/printer");
$printer = new Printer($connector);
$printer->initialize();

$printer->text("Example");

$printer->cut();
$printer->close();
```

What I can do?
Thanks a lot

**Comment by Cundalf** [comment]
Hello Mike42. I'm sorry, I have not responded before.
I do not have much experience with these printers and there is not much documentation.
I always work with EPSON and I have not had problems. But this time I had to make an exception.

I solved the problem in the following way:

```
$printer->feed(5);
$connector->write(chr(27).chr(109));
$printer->close();
```

Thanks for your help!

**Comment by hikdul** [comment]
Hi, i resolve this proble in python.. 
i find in the documentation of 'escpos' and the mi print (NP-K304) in the both options the code for cut ist diferent. in the case of pithon i use

`printer._raw("\x1bm663")`

* \x1bm its de option for partial cut...

always you can test this in php...
