### ISSUE TITLE
Error : Couldn't print to this printer: Failed to copy file to printer when I'm trying to print from a shared printer (USB)

### ISSUE THREAD

**Issue by moradrouaguy** [mike42/escpos-php#67]
I'm trying to print from a computer which is not connected to the printer directly but it's connected by the shared printer in the same network of the connected computer (USB).

I have two computers in the same network, the first one is connected by USB to the printer, I shared this printer then I installed it on the second computer I can print a test page It's works fine. But when I'm trying to print from the web page I get this error : "Couldn't print to this printer: Failed to copy file to printer."

My web page : 

```<?php
require_once(dirname(__FILE__) . "/escpos-php/Escpos.php");
try {
	$connector = new WindowsPrintConnector("smb://COMPUTERNAME/epson");
	$printer = new Escpos($connector);
	$printer -> text("Hello World");
	$printer -> cut();
	$printer -> pulse();
	$printer -> close();
} catch(Exception $e) {
	echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
?>

Anyone can help me, please ?

**Comment by mike42** [comment]
Hey,

Sounds like your printer path `smb://COMPUTERNAME/epson` isn't accessible from the webserver. Here's what I'm hearing, guessing the operating systems-

- Computer A, USB printer, shared over SMB as 'epson', Windows
- Computer B, Webserver, Windows.

Your best debugging tool is to attempt a test print on *Computer B*, via the command prompt. See notes in comments [here](https://github.com/mike42/escpos-php/blob/master/example/interface/windows-usb.php).

### Method 1

`````
echo "Hello World" > testfile
copy testfile "\\COMPUTER-A\epson"
del testfile
`````
And once this prints, it would correspond to this connector setup:

`````php
$connector = new WindowsPrintConnector("smb://COMPUTER-A/epson");
`````

### Method 2

Connect up to the printer using `net use` on Computer B:

`````
net use LPT1 \\COMPUTER-A\epson
echo "Hello World" > LPT1
`````

And this can be accessed with either of these:

`````php
$connector = new WindowsPrintConnector("LPT1"); // whole receipt is sent when you close the printer
$connector = new FilePrintConnector("LPT1"); // commands are sent in real-time
`````

**Comment by moradrouaguy** [comment]
Thank you for you reply.

Yes both of computers are Windows (windows 7 and windows server).

Results of Method 1 : 
the first command (echo "Hello World" > testfile works fine)
the second command line shows me an error:

`Access is denied.
        0 file(s) copied.`

Method 2 : 
the first command line shows me this error :
 
`The local device name is already in use.`

**Comment by moradrouaguy** [comment]
For the second method I just delete the mapping and remap it : 
`net use LPT1 /delete`
`net use LPT1 \\COMPUTER-A\epson`

Now I have this error : 
`Access is denied.`

**Comment by moradrouaguy** [comment]
I just managed to print from the command line prompt.

I changed the permissions of the PRINTERS folder : 

>>1) Share Permissions
>>1. On explorer, go to C:\windows\system32\spool\PRINTERS
>>2. Right click, Properties
>>3. Sharing tab
>>4. Advanced Sharing
>>5. Check "Share this folder"
>>6. Permissions
>>7. Grant everyone Full Control
>>
>>2) NTFS Permissions
>>1. On explorer, go to C:\windows\system32\spool\printers
>>2. Right click, Properties
>>3. Security tab
>>4. Edit
>>5. Add
>>6. Advanced
>>7. Find Now
>>8. Choose "NETWORK"
>>9. OK
>>10. Grant NETWORK Full Control


AND THEN we had to install as local printers, using the port trick. . .

1. Go to "Printers"
2. click "Add Printer"
3. "Add a Local Printer"
4. "Create a New Port"
5. use the "Local Port" option
6. at "Enter a Port Name" enter: "\\Computername\Printername"

https://community.spiceworks.com/topic/102569-acces-denied-when-creating-local-port

But I still have this error message from the web page : 

`Couldn't print to this printer: Failed to copy file to printer`

**Comment by mike42** [comment]
Hi, this error is still permission-related.

My suggestion would be to set up the printer with credentials on the server, and then connect to it in the form `new WindowsPrintConnector("smb://bob:secret@computer/workgroup/printer");`. This is somewhat more secure, and gives very clear messages about what was being attempted when things go wrong.

Currently, you appear to be asking to the driver to connect to a network file share in the form `new WindowsPrintConnector("smb://foo/bar");`, which in the background will write to a temp file and then copy it to `\\foo\bar` (this was Method 1 above, and didn't work). The command that did involved setting up `LPT1`. In PHP, this is more like `new WindowsPrintConnector("LPT1");`.

**Comment by mike42** [comment]
Closing this as the code being referenced has has been recently updated. Please refer to the latest code and documentation, and if you have the same issue, file it as a [new issue](https://github.com/mike42/escpos-php/issues/new).

**Comment by younas-bangash** [comment]
I am using Linux server and printer is connected with Windows 7 so is it possible to connect the printer to Linux server?

**Comment by mrpagesolution** [comment]
Saludos Mike, 
Me esta presentando este error y la impresora esta compartida, uso el mismo nombre de la impresora compartida en la libreria, tengo win 7 y la impresora es una EPSON TM-T88III  a que se debe este error 

Warning: copy(\\Michael-PC\EPSON): failed to open stream: No such file or directory in C:\wamp32\www\FACTURA GENERICA\Sistemas\probarticket\ticket\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372

**Comment by vcandela** [comment]
> Saludos Mike,
> Me esta presentando este error y la impresora esta compartida, uso el mismo nombre de la impresora compartida en la libreria, tengo win 7 y la impresora es una EPSON TM-T88III a que se debe este error
> 
> Warning: copy(\Michael-PC\EPSON): failed to open stream: No such file or directory in C:\wamp32\www\FACTURA GENERICA\Sistemas\probarticket\ticket\src\Mike42\Escpos\PrintConnectors\WindowsPrintConnector.php on line 372

Amigo, lo llegaste a solucionar a mi me sale lo mismo
copy(\\DESKTOP-64MLHVD\USB001): failed to open stream: No such file or directory
Cuando imprimo desde mi App en Laravel

**Comment by mrpagesolution** [comment]
Si, me funciono pero solo en el localhost no en el hosting

**Comment by DevsDynamic** [comment]
> net use LPT1 \\COMPUTER-A\epson
> echo "Hello World" > LPT1

Lograste solucionarlo?

**Comment by mrpagesolution** [comment]
Si

**Comment by digutier** [comment]
Hola! @mrpagesolution cómo pudiste solucionarlo? Me podrías explicar? gracias de antemano
