### ISSUE TITLE
How to use the Library

### ISSUE THREAD

**Issue by mountainclimbing** [mike42/escpos-php#678]
I have managed to use the composer for the installation. I now need guidance on how this can be used. 
I tried using the files in the example, and when I open say demo.php, it comes blank on the browser. How is this library used?

 I want to be able to get data from a database and present it in table format and have a print button which should automatically print without the print dialog and selecting the default printer only.

**Comment by mike42** [comment]
Hello,

I think you may have zipped past the ["basic usage"](https://github.com/mike42/escpos-php#basic-usage) section of the README, which is quite comprehensive in my humble opinion (suggestions welcome!) :)

In any case, this library is intended for server-side raw printing to ESC/POS printers, which is very different to the setup you are describing.

Before you use this library, you should be testing your raw print setup outside of PHP by sending text files from your server to your printer on the command-line.

You can then find a mechanism that works for you, and take a look at the available `PrintConnectors` to see how we wrap these same mechanisms to print from PHP. Also, enable error reporting, and print your receipts as a command-line PHP script initially.

All of the examples in this repository start with `$connector = new FilePrintConnector("php://stdout");`, so they wont work from the web unless you change the `PrintConnector` to something else. Again, start from the README and perform raw printing on the command-line first.

**Comment by mountainclimbing** [comment]
Hello,
Thank you for the useful feedback. I want to be able to print by selecting any printer under my computer's  **Devices and Printers**. With my php and windows environment, I have something like below that works using the php_printer functions:

<?php
$handle = printer_open("HP LaserJet 600 M512");
$handle = printer_open($printer_name);
printer_start_doc($handle, "My Document");
printer_start_page($handle);
$font = printer_create_font("Arial", 100, 50, PRINTER_FW_MEDIUM, false, false, false, -50);
printer_select_font($handle, $font);
printer_draw_text($handle, 'We auto \n\r print here!', 100, 400);
printer_delete_font($font);
printer_end_page($handle);
printer_end_doc($handle);
printer_close($handle);
?>

this line: **$handle = printer_open("HP LaserJet 600 M512");** selects and opens that printer.

Now, with your solution, how can I modify **$connector = new FilePrintConnector("php://stdout");** to match the printer above.
