### ISSUE TITLE
Epson TM-U220 - Print in Red Ink

### ISSUE THREAD

**Issue by superlative1** [mike42/escpos-php#68]
Hi.

So happy I came across this. Great work. Really wonderful.
I have managed to get my one to print ot the printer with PHP great. 

The only question I have, is the TM-U220B has a ribbon that is black and red.

You can send a ESC/POS command that will change the printing color from color1 to color2. 

How can I do this with your code?

Here is the relevant part from the manual:

[Name] Select printing color
[Format] ASCII ESC r n
Hex 1B 72 n
Decimal 27 114 n
[Range] n = 0, 1, 48, 49
[Default] n = 0
[Description] Selects the printing color specified by n.
* When n = 0,48, color 1 is selected.
* When n = 1,49, color 2 is selected.

Any help appreciated. Thank you so much.

**Comment by mike42** [comment]
This is not yet implemented, so I'll take this as a feature request.

I'm sourcing a TM-U220 to do some testing, as it supports traditional/simplified Chinese and red/black, both of which are missing from this driver.

**Comment by mike42** [comment]
Hi,

I've just pushed in a new `setColor()` method based on your comment above. Can you give it a shot and let me know if it works for you?

````php

$connector = .... // Set up your PrintConnector
try {
	$printer = new Escpos($connector);
	$printer -> text("Hello World!\n");
	$printer -> setColor(Escpos::COLOR_2);
	$printer -> text("Red?!\n");
	$printer -> setColor(Escpos::COLOR_1);
	$printer -> text("Default color again?!\n");
	$printer -> cut();
} finally {
	/* Always close the printer! */
	$printer -> close();
}
````

**Comment by mike42** [comment]
Closing this request, example above worked on my TM-U220-

![2015-10-colour-receipt-printing-3-300x66](https://cloud.githubusercontent.com/assets/2080552/12008543/35cc772a-ac96-11e5-87a4-27d9e81664c4.jpg)

Blogged [here](http://mike.bitrevision.com/blog/2015-12-red-black-impact-receipt-printing), and documented [in the main README.md](https://github.com/mike42/escpos-php#setcolorcolor).
