### ISSUE TITLE
Printer tested: Elgin i9

### ISSUE THREAD

**Issue by RenanGaleno** [mike42/escpos-php#689]
Reporting that I've tested Elgin i9 printer, and it works perfectly. I think it can be added to compatibility list. Probably Elgin i7 works, also, as it's almost the same printer, just without cutting.

**Comment by etromorte** [comment]
Fala amigo, vi que você conseguiu fazer o modulo funcionar com a impressora elgin i9. poderia me ajudar com isso pois preciso fazer a impressão mais não estou conseguindo fazer a configuração no código.

**Comment by RenanGaleno** [comment]
Veja os exemplos em https://github.com/mike42/escpos-php/tree/development/example/interface e configure como nos exemplos que deve funcionar

Check the examples at https://github.com/mike42/escpos-php/tree/development/example/interface and configure like that, it should work
