### ISSUE TITLE
linux-usb not working

### ISSUE THREAD

**Issue by habibridho** [mike42/escpos-php#70]
I try your example to print receipt via usb from [here] (https://github.com/mike42/escpos-php/tree/master/example/interface/linux-usb.php). However, I get an error saying "Couldn't print to this printer: Cannot initialise FilePrintConnector.". Is there any further configuration that I should make? In addition, I have removed CUPS from my ubuntu.

**Comment by mike42** [comment]
Hey,

I often refer to [this blog post](http://mike.bitrevision.com/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux) when I talk about Linux USB.

Your next debugging steps are along the lines of-
- `sudo usermod -a -G lp habibridho` (Add yourself, and your web user to the `lp` group)
- `lsmod | grep usblp` (confirm that `usblp` is loaded. if not, make it load!)
- `ls /dev/usb/` (find the device)
- `echo "test" >> /dev/usb/ABC" where "ABC" is the name of your printer.

Once you have this working on the command-line, you are ready to use `new FilePrintConector("/dev/usb/ABC")` to start printing with escpos-php.

**Comment by habibridho** [comment]
Hi, thanks for the really fast response!

I did the steps you provide, but I got `bash: /dev/usb/lp0: Permission denied`. According to [this] (http://ubuntuforums.org/showthread.php?t=1437325), it has some something do with /usb/*lp* new installation. I fix the problem using solution provided by the link and I successfully echo "test" and run your usb example.

Thanks!

**Comment by candrairawan78** [comment]
Dear mike,

I also have the same problem when print with linux-usb.
i always got an error
"Couldn't print to this printer: Cannot initialise FilePrintConnector." when tried on esc-php-master/example/linux-usb.php

I have successfuly tried all of your steps:

sudo usermod -a -G lp habibridho (Add yourself, and your web user to the lp group)
lsmod | grep usblp (confirm that usblp is loaded. if not, make it load!)
ls /dev/usb/ (find the device. If not, replug it and debug with dmesg)
echo "test" >> /dev/usb/ABC"

I also can print from esc-php-master/example/cups.php

Can you help me please?

Regards,
Candra

**Comment by mike42** [comment]
Hi @candrairawan78 - This issue has been closed. If you have read through the steps here and it has not worked for you, then please open a [new issue](https://github.com/mike42/escpos-php/issues/new) including details such as a code snippet,  the name of your print device, platform, PHP version and printer make/model.

**Comment by marknelpogi** [comment]
Hi Guys,

I want to share my solution. 
for the ff error accessing via localhost/ip.

`fopen(/dev/usb/lp0): failed to open stream: Permission denied`

The solution is to setenforce selinux is disabled.
`setenforce 0`

Here's the specification of my server.
- CentOS7
- PHP7
- Apache2

Thanks!
