### ISSUE TITLE
Add Printer Panda pos80AT

### ISSUE THREAD

**Issue by zacka32** [mike42/escpos-php#707]
Please we use thermal printer Panda POS80AT,
thanks you very much

**Comment by mike42** [comment]
Hello,

We add printers to the list once they have been tested. Please see [Can you add support for Printer X?](https://github.com/mike42/escpos-php/blob/4fff198b2a5d07f5d2fb8dc00e361935abd36447/doc/FAQ.md#can-you-add-support-for-printer-x) in the FAQ.
