### ISSUE TITLE
Printer tested: SNBC BTP-R880NPIII

### ISSUE THREAD

**Issue by fghoekstra** [mike42/escpos-php#714]
SNBC Receipt Printer BTP-R880NPIII works.

**Comment by mike42** [comment]
Thanks for reporting! This will be included in the README in the next minor release.

**Comment by welrachid** [comment]
Did you test images?

**Comment by fghoekstra** [comment]
No. Only text

Op za 23 mrt. 2019 08:11 schreef Wel Rachid <notifications@github.com>:

**Comment by welrachid** [comment]
Okay maybe check image test, just to make sure that that part has been tested
