### ISSUE TITLE
Print certain PDF fails

### ISSUE THREAD

**Issue by mrbrowni** [mike42/escpos-php#718]
Hi, thanks for the great library!

My use case is to print PDF using an ESC printer (Epson TM20ii for now). Many PDFs work, but there is this PDF I can't make it print using the pdf example code (method 1).

[out2.pdf](https://github.com/mike42/escpos-php/files/2972116/out2.pdf)

Any idea?

Thanks.

**Comment by mike42** [comment]
Hi,

Can you share the PHP code you are using to print this, and perhaps describe what happens when you run that code on with this PDF, as opposed to the other ones that do work?
