### ISSUE TITLE
Cannot print to a Linux fifo

### ISSUE THREAD

**Issue by jonsito** [mike42/escpos-php#72]
While waiting for my printer to come, I'm trying to test code by mean of monitoring a Linux fifo character special device, using this code:

<?php
require_once(__DIR__."/../server/printer/Escpos.php");
/* bash$ sudo mkfifo -m 0666 /tmp/rawprint.fifo */
$connector = new FilePrintConnector("/tmp/rawprint.fifo");
$printer = new Escpos($connector,SimpleCapabilityProfile::getInstance());
if (!$printer) {  echo "Failed"; return; }
$data=json_encode(array("a"=>"Hello","b"=>"World"));
$printer->initialize();
$printer->text($data."\n");
$printer->cut();
$printer->close();
echo "Done";
?>

in the fifo read side I'm listening with this command:
hexdump -C < /tmp/rawprint.fifo

When running this script in console works fine... but when invoke as cgi script, just receive "Done", but no output sent to fifo.
What am I doing wrong?
Thanks in advance

**Comment by jonsito** [comment]
Stupid of me: php safe mode is on.
Problem solved

**Comment by mike42** [comment]
Glad you got this working- using a FIFO as a fake printer is pretty solid way to debug without a printer.

I usually use something like `FilePrintConnector("foo.bin")` and then read the output, which is how some of the tests run.
