### ISSUE TITLE
Khmer Character has Problem

### ISSUE THREAD

**Issue by phearunum** [mike42/escpos-php#727]
![image](https://user-images.githubusercontent.com/35354771/55623519-6ec7a280-57cd-11e9-8ef3-5bb93ba33e42.png)

Please help me. how to do ?

**Comment by mike42** [comment]
The answer to this question will depend on whether Khmer characters are available on your printer.

- Which model of printer is this?
- Can you please include the UTF-8 Khmer text you are trying to print?

**Comment by phearunum** [comment]
Printer Model : TM-T88V
$printer->text(" សូមស្វាគមន៍ សូមអរគុណ ");

**Comment by phearunum** [comment]
<?php
try {
    mb_internal_encoding("UTF-8");
    $connector = new \Escpos\PrintConnectors\NetworkPrintConnector("192.168.5.239",9100);
    $img=new \Escpos\GdEscposImage();
    $profile= \Escpos\CapabilityProfiles\EposTepCapabilityProfile::getInstance();
    //$profile = \Escpos\CapabilityProfiles\DefaultCapabilityProfile::getInstance('MT-T88V');
    $textBuffer = new \Escpos\PrintBuffers\EscposPrintBuffer();
    $printer =new \Escpos\Printer($connector,$profile);
    $printer->setJustification(\Escpos\Printer::JUSTIFY_RIGHT);
    $printer -> text("__________________________________________\n");
    $printer -> setEmphasis(true);
    $total -> text("សាច់គោ);
  $total -> text('សាច់មាន់');
    $printer -> text("__________________________________________\n");
    $printer -> cut();
    $printer -> close();
} catch (Exception $e) {
    $printer -> close();
    throw $e;
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

**Comment by phearunum** [comment]
Please help me @mike42

**Comment by vannak62** [comment]
Hi pearunum! I'm Khmer too. what connector type do you use? do you know how to use NetworkPrintConnector? no matter i use LAN IP or public IP with forwarded port on router, there is no error but also print nothing.

**Comment by phearunum** [comment]
can you give me configuration code

**Comment by phearunum** [comment]
I have use with IP , but I don't know why printer unknown khmer character

**Comment by vannak62** [comment]
Hi Phearum, thank for replying. i just copy and paste the example of networkprintconnector that is writen by this Mike42, by just changing to my own IP address. My IP Address is a public IP. I assigned local IP to my printer 192.168.1.198, and then i did port forwarding to that IP on port 9100 on the router, so any connection that go to my public IP on 9100 it should forward to my printer right? however, no matter i test use local IP or public IP it shows no error and print nothing.
However, i have no composer installed, so i downloaded (not cloned) and store it in my project folder and included as usual the way i call other php file. Here is my code:

<?php
/* Change to the correct path if you copy this example! */
require ("escpos/src/Mike24/Escpos/Pirnter.php");
require ("escpos/src/Mike24/Escpos/PrintConnectors/NetworkPrintConnector.php");

/* Most printers are open on port 9100, so you just need to know the IP 
 * address of your receipt printer, and then fsockopen() it on that port.
 */
try {
    $connector = new NetworkPrintConnector("114.134.184.171", 9100);
    
    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    $printer -> text("Hello World!\n");
    $printer -> cut();
    
    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

**Comment by phearunum** [comment]
this is i have used . But still unknown khmer character.
can you give me full code, and printer model name?
thanks you

**Comment by vannak62** [comment]
are you expecting that I solve your problem or are you helping me with mine?

**Comment by phearunum** [comment]
Please help me ,

**Comment by phearunum** [comment]
> are you expecting that I solve your problem or are you helping me with mine?

can you try to print khmer  language via ip address ?
$printer->text(" សូមស្វាគមន៍ សូមអរគុណ ");

it will be show  ( ??????????????? ) on receipt 
if you have resolution please help me

**Comment by Rothana127** [comment]
Phearun,
I think you should to convert your contents to image first, then you can print it.

**Comment by phearunum** [comment]
> Phearun,
> I think you should to convert your contents to image first, then you can print it.

Do you have code for example to convert, I ready try but still unknow khmer (??????) 
@Rothana127  can you help me ?

**Comment by mike42** [comment]
Closing this off because of #856, which describes the problem better.
