### ISSUE TITLE
Excelvan HOP-E58 success. Some usb tips

### ISSUE THREAD

**Issue by jonsito** [mike42/escpos-php#73]
I can confirm that this code works fine with Excelvan HOP-E58 thermal printer throught USB interface.

Only a detail: depending on the current supplied by USB port sometimes this printer is not properly recognized. If this happens, just connect it through a powered usb hub

Thanks for the job

**Comment by mike42** [comment]
Thanks for reporting- I've added the HOP-E58 to the list of models in README.md.
