### ISSUE TITLE
Code128 Wont Work

### ISSUE THREAD

**Issue by BlakeMadigan** [mike42/escpos-php#732]
So when i catch the exception i get it asking for a range of 65-71 but received a 73(which i understand is 128) and after doing some lurking I figured I should just ask what the issue could be, no point pasting code as I literally copied and pasted your barcode128 examples just to see if I could get it to work, and I am pretty confident that the Bixolon SRP-350III im using supports 128, but my exception handler is telling me that the issue is i'm not within the range I need to be, and your landing page for this project doesn't specify that 128 is supported only 39, is there anything you can tell me that'll help me use 128?

**Comment by mike42** [comment]
Hi,

I don't currently know how you are using the library.

Please include a self-contained snippet of code which exhibits the problem, plus the exception you are seeing, this would ve a great help.
