### ISSUE TITLE
Print on another port other than the 9100

### ISSUE THREAD

**Issue by nmorales1991** [mike42/escpos-php#736]
Hi. Can I print on another port other than the 9100?

**Comment by mike42** [comment]
Certainly. Assuming you are using `NetworkPrintConnector` ([link](https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/PrintConnectors/NetworkPrintConnector.php#L30)) , the port is an optional second argument, eg.

```php
$connector = new NetworkPrintConnector("my-printer-ip-address", 9200);
```

**Comment by nmorales1991** [comment]
> Certainly. Assuming you are using `NetworkPrintConnector` ([link](https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/PrintConnectors/NetworkPrintConnector.php#L30)) , the port is an optional second argument, eg.
> 
> ```
> $connector = new NetworkPrintConnector("my-printer-ip-address", 9200);
> ```

With another port other than 9100 gives me error **Fatal error: Uncaught exception 'Exception' with message 'Cannot initialise NetworkPrintConnector: Connection refused'**
