### ISSUE TITLE
Margin and Cut not working with TVS RP3160 GOLD

### ISSUE THREAD

**Issue by ananth88** [mike42/escpos-php#738]
Using Windows Printer Configuration

`try {
                        // Enter the share name for your USB printer here
                        $connector = new WindowsPrintConnector("rp3160");
                        $printer = new Printer($connector);

                        $printer -> setPrintWidth(512);
                        /* Print some bold text */
                        $printer -> setEmphasis(true);
                        $printer -> text($name);
                        $printer -> setEmphasis(false);
                        $printer -> feed();
                        $printer -> text("Order No :".$oid);
                        $printer -> feed(1);
                        $printer -> text("------------------------------------------");
                        $printer -> feed(1);
                        $printer -> text("Dish");
                        $printer -> setPrintLeftMargin(256);
                        $printer -> text("Quantity");
                        $printer -> setPrintLeftMargin(512);
                        $printer -> text("Price");
                        $printer -> feed(1);
                        $printer -> text("------------------------------------------");
                        $printer -> feed(1);
                        $result = mysqli_query($conn, "SELECT od.price,od.quantity,od.dishid,d.dishname,ot.paymentmode,p.type,ot.discount FROM ordertable ot,orderdetails od,dish d,paymentmode p where ot.id='$oid' and od.orderid=ot.id and od.dishid=d.id and ot.paymentmode=p.id") or die(mysql_error());

                        if (mysqli_num_rows($result) > 0) :
                            while ($row = mysqli_fetch_array($result)) {

                                $price = $row[0];
                                $quantity = $row[1];
                                $dish = $row[3];
                                $paymentmode = $row[5];
                                $discount = $row[6];
                                

                                $printer -> text($dish);
                                $printer -> setPrintLeftMargin(256);
                                $printer -> text($quantity);
                                $printer -> setPrintLeftMargin(512);
                                $printer -> text($price);
                                $printer -> feed(1);                     
                            }

                        endif;

                        $printer -> feed(1);
                        $printer -> text("Amount :".$amount);
                        $printer -> feed(1);
                        $printer -> text("CGST(".$tax."%) :" . $amount * ($tax/100) );
                        $printer -> feed(1);
                        $printer -> text("SGST(".$vattax."%) :" . $amount * ($vattax/100) );
                        $printer -> feed(1);
                        $printer -> text("Discount :".$discount);
                        $printer -> feed(1);
                        $printer -> text("Grand Total :".$grandtot);
                        $printer -> text("------------------------------------------");
                        //$printer -> feed(7);

                        //$printer -> text("Payment Mode :".$paymentmode);

                       
                        //$printer -> setJustification(Printer::JUSTIFY_CENTER);
                        $printer -> text("Thank You");
                        $printer -> cut();
                        //$printer -> getPrintConnector() -> write(chr(27).chr(105));
                        //$printer->text(chr(27)."@".chr(29)."V".chr(1));
                        
                        /* Close printer */
                        $printer -> close();

                    } catch(Exception $e) {
                        $printer -> text("Couldn't print to this printer: " . $e -> getMessage() . "\n");
                    }`

The text Thank you not printing and it wont cut also

**Comment by mike42** [comment]
Hi,

There might also be a real compatibility issue here, but let's try something first.

Some commands (like cut and margin) need an empty print buffer to work, and you still have text in the buffer until it's terminated with a line feed (`$printer -> text("\n");` or `$printer -> feed(1)` will print it).

So this-

```php
$printer -> text("Thank You");
$printer -> cut();
```

Should say-

```php
$printer -> text("Thank You\n");
$printer -> cut();
```

Also, you want tabs or spaces to make space within a line, since the left margin and print width commands move the entire line of text.

Instead, try just using PHP's `sprintf` to align your items. Eg this example could allow 20 characters (left-aligned) for the dish, 7 for a unit price, 7 for a quantity, and 7 for a subtotal (all right-aligned), for 41 total (eg. would fit on a 42-column printer).

```
$ php -r 'echo sprintf("%-20s%7.2f%7d%7.2f\n", "food", 2.5, 3, 7.5);'
food                   2.50      3   7.50
```
