### ISSUE TITLE
print image barcode  with Sanei Electric SK1-21/31/41

### ISSUE THREAD

**Issue by CommandGong** [mike42/escpos-php#739]
For the Printer Sanei Electric SK1-21/31/41, which command system conforms to ESC/POS. It works fine for the  text, however for print the  barcode by executing example/barcode.php, it only prints the text instead the image. 

ps: I tried executed "echo GS."k".chr(4)."987654321".NUL; // Print barcode" from linkc https://mike42.me/blog/2015-03-getting-a-usb-receipt-printer-working-on-linux my printer could print out the barcode

**Comment by mike42** [comment]
Hello,

There are two barcode functions implemented in this library, but it sounds like your printer only supports one of them. We do have code to [switch implementations based on printer support](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/src/Mike42/Escpos/Printer.php#L435), and `escpos-php` release contain a JSON blob from [escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db) detailing printer features.

If you load the `simple` profile, then `barcodeB: false`, and you will get the barcode you want.

```php
<?php
require __DIR__ . '/../autoload.php';
use Mike42\Escpos\CapabilityProfile;
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

$connector = new FilePrintConnector("php://stdout");
$profile = CapabilityProfile::load("simple");
$printer = new Printer($connector, $profile);

$printer->barcode("987654321", Printer::BARCODE_CODE39);

$printer->cut();
$printer->close();
```

However, we don't have a profile for Sanei Electric SK1-21/31/41, so you might have more problems like this. Please consider [adding your printer to the database](https://github.com/receipt-print-hq/escpos-printer-db/blob/master/doc/add-your-printer.md) if you want better compatibility with this software, and other project like it.

**Comment by CommandGong** [comment]
> Hello,
> 
> There are two barcode functions implemented in this library, but it sounds like your printer only supports one of them. We do have code to [switch implementations based on printer support](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/src/Mike42/Escpos/Printer.php#L435), and `escpos-php` release contain a JSON blob from [escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db) detailing printer features.
> 
> If you load the `simple` profile, then `barcodeB: false`, and you will get the barcode you want.
> 
> ```
> <?php
> require __DIR__ . '/../autoload.php';
> use Mike42\Escpos\CapabilityProfile;
> use Mike42\Escpos\Printer;
> use Mike42\Escpos\PrintConnectors\FilePrintConnector;
> 
> $connector = new FilePrintConnector("php://stdout");
> $profile = CapabilityProfile::load("simple");
> $printer = new Printer($connector, $profile);
> 
> $printer->barcode("987654321", Printer::BARCODE_CODE39);
> 
> $printer->cut();
> $printer->close();
> ```
> 
> However, we don't have a profile for Sanei Electric SK1-21/31/41, so you might have more problems like this. Please consider [adding your printer to the database](https://github.com/receipt-print-hq/escpos-printer-db/blob/master/doc/add-your-printer.md) if you want better compatibility with this software, and other project like it.

Load `simple` profile as the code above works, and for sure I will add my printer to the database .
Thanks
