### ISSUE TITLE
Float QR Code to left

### ISSUE THREAD

**Issue by Raikas77** [mike42/escpos-php#744]
Hi,
the git is working great, I got just a problem with floating qr codes.

I am trying to float two qr codes to center or left, but everytime I try to add a qr code it does a new line.
I hope someone can help me.

Example:
`$printer -> setJustification(Printer::JUSTIFY_LEFT);
$printer -> qrCode('qrCode1', Printer::QR_ECLEVEL_H, 6);
$printer -> qrCode('qrCode2', Printer::QR_ECLEVEL_H, 6);`

**Comment by mike42** [comment]
It is not possible to present elements side-by-side in ESC/POS unless "Page mode" is used.

Page mode is not currently implemented in this library. Issue #216 tracks progress on that particular feature (pull requests welcome!)

**Comment by petrojackson5** [comment]
This for me solves the problem
you have to put this line some where you want to be aligned
$this->printer->setJustification(Printer::JUSTIFY_LEFT);

In the following path D:\yourpcfolder\vendor\charlieuki\receiptprinter\src\ReceiptPrinter.php
