### ISSUE TITLE
Printer tested: Sewoo SLK-400 Bluetooth/USB version

### ISSUE THREAD

**Issue by pierrejoye** [mike42/escpos-php#746]
Works out of the box, need to use bitImage() as graphics() fail.

I will update the exact version I use asap but the IDs are:

Bus 001 Device 019: ID 0525:a700 Netchip Technology, Inc.

**Comment by pierrejoye** [comment]
![image](https://user-images.githubusercontent.com/282408/58010176-1c8ed680-7b1a-11e9-9403-0f7e8ff44ae1.png)

For the details.

How can I see the details so I can complete escpos-php capabilities? Like I have the DPI, etc. But it would be nice to have details like chars/line depending on the font size and such things.

Happy to provide it all :)

**Comment by pierrejoye** [comment]
Ah, Found the db submit process. I will do asap.
In the meantime, the doc for this model (dpi, chars/line, etc)
[SLK-TS400EB_MANUAL.pdf](https://github.com/mike42/escpos-php/files/3197199/SLK-TS400EB_MANUAL.pdf)

**Comment by mike42** [comment]
Hi! Thanks for sharing, I'll include this printer on the list in the README for the next minor release.
