### ISSUE TITLE
 xvfb-run wkhtmltoimage windows install

### ISSUE THREAD

**Issue by azerioid** [mike42/escpos-php#748]
hi @mike42  i cannot install  xvfb-run wkhtmltoimage  windows platform for html pdf print file pls help me

**Comment by mike42** [comment]
Hi,

The [example](https://github.com/mike42/escpos-php/blob/development/example/print-from-html.php) shows that HTML input is not part of the API, while image printing is. If you aren't directly creating text/formatting commands with this library, then you can instead use any method you like to create an image, and then print that instead.

I don't use `wkhtmltoimage` on Windows, so I can't tell you how to install that. You can edit out 'xvfb-run' though, that's a Linux/Mac thing.

**Comment by azerioid** [comment]
@mike42  thanks for detaily answer.  Please anyone help me edit 'xvfb-run'  for windows alternative
