### ISSUE TITLE
escpos-php setup in windows

### ISSUE THREAD

**Issue by deep97** [mike42/escpos-php#75]
Hi, want to know how to use escpos-php with windows. What i am doing.
escpos-php is working fine if i am using it on my server computer. as keeping escpos-php folder in same folder. 
But it is not working if I am accessing my php pages from a computer on network with its own printer.  
In this case I put escpos directory in local wamp/www/escpos folder. and try to change 

line require_once(dirname(__FILE__) . "/escpos/Escpos.php"); with require_once(dirname(__FILE__) . "c:/wamp/www/escpos/Escpos.php"); to use local Escpos.php file but no luck.

Any help will be great.
Regards
Deep

**Comment by mike42** [comment]
I'm afraid that I may not understand this issue well enough to provide a proper response here.

It seems that you want the server to print via another machine, and this will generally involve sharing a printer and making use of the `WindowsPrintConnector` in the form `new WindowsPrintConnector("smb://bob:secret@computer/workgroup/printer");`

**Comment by deep97** [comment]
Will it work on windows

**Comment by deep97** [comment]
i am getting below error.

Warning: copy(\\PC-1\Receipt Printer1): failed to open stream: Permission denied in C:\wamp\www\escpos\src\WindowsPrintConnector.php on line 339

**Comment by mike42** [comment]
Hello, I updated the README recently to include advice about things that you need on your system before the driver can print. Please see: https://github.com/mike42/escpos-php#the-hello-world-receipt

In short, you need to know how your machine is going to communicate with the printer, and to test this, you should first send some text from the command-line to the printer.

You can find information in the README link above, the [Windows SMB](https://github.com/mike42/escpos-php/blob/master/example/interface/smb.php) example, or via Google for a good way to do this on your system.

If you can't find a working print command, then others may be able to suggest one if you provide more information about your setup. The basics are things like- (examples included for clarity)

- What sort of printer do you have? (FooCorp SuperPrint 300)
- What is it plugged in to? (Windows ME)
- How is it plugged in? (Parallel port)
- How have you installed it? (Generic text driver, and I can print a test page fine)
- How have you tried printing (Copied a file to LPT1 and it worked, but PHP gives me an error if I try to print to LPT1)
- What is running on the thing it's plugged into? (PHP version 7, Apache, running as "Network Service" user account)

**Comment by deep97** [comment]
I got it just changed permissions.

Mike only thing to test left is. If i am using a computer(client) on LAN with printer and i am accessing or using PHP file from my server(WAMP). I want to get print using escPOS.
I have WAMP on both client and server. Do I need to keep escPOS in WAMP/WWW or somewhere else. 

or If I want to print any online page.

**Comment by deep97** [comment]
What if I want to call escPOS/Escpos.php from online page.

**Comment by deep97** [comment]
•What sort of printer do you have? (FooCorp SuperPrint 300)
Epson TM-T88V

•What is it plugged in to? (Windows ME)
Windows 7

•How is it plugged in? (Parallel port)
USB (ESDPRT001)

•How have you installed it? (Generic text driver, and I can print a test page fine)
Generic text driver , I can add test print from Host Computer.

•How have you tried printing (Copied a file to LPT1 and it worked, but PHP gives me an error if I try to print to LPT1)
working if using to same machine where php is installed

•What is running on the thing it's plugged into? (PHP version 7, Apache, running as "Network Service" user account)
On Network computer -> \\LINE1\LINE1 ADMIN

**Comment by deep97** [comment]
What I have on network
Computer1 with (PHP, Apache) ip 192.168.1.2
Computer2 with printer attached to USB.
I add printer to computer2 as generic/Text Only with name Receipt Printer1. Working
Then shared it.
Added as network printer on computer1. Test page is working.

ESCPOS is also on computer1.

**Comment by mike42** [comment]
I'm hearing that your setup looks like so, can you confirm?

![image](https://cloud.githubusercontent.com/assets/2080552/15499416/7a22847a-21e7-11e6-88e1-5918bcf6580c.png)

Windows strangeness aside, I think the README covers your setup. Can you step through [this section](https://github.com/mike42/escpos-php#the-hello-world-receipt) on Computer 1, and attempt to send text to `\\computer2\Receipt Printer1` or `\\<ip address>\Receipt Printer1` on the command line using `net use` and `copy`?

(as always, escpos-php will only be able to take over once you have a working way to send text to your printer from the computer that PHP is running on, and it sounds like you're on the right track)

**Comment by deep97** [comment]
unsuccessful to use NET USE and COPY.
tried -> net use \\192.168.0.5\Receipt Printer1
some time it says access is denied.

**Comment by deep97** [comment]
fixed access was problem. Now will try to implement

**Comment by mike42** [comment]
It sounds like this has worked, so I'll close this. Please file a [new issue](https://github.com/mike42/escpos-php/issues/new) if you run into any other blockers using the driver.

**Comment by sinclaireric** [comment]
"fixed access was problem. Now will try to implement" explain please
