### ISSUE TITLE
Question: Table format

### ISSUE THREAD

**Issue by onally** [mike42/escpos-php#750]
Please can i create a table ? I've tried so many methods is not just working for me.

**Comment by mike42** [comment]
The `$printer -> text()` method is used to deliver UTF-8 text, which is all you usually need for a table.

For spacing, I suggest just using PHP's `sprintf` ([documentation](https://www.php.net/manual/en/function.sprintf.php)) to align your items, as described [here](https://github.com/mike42/escpos-php/issues/738#issuecomment-489317816)).

For drawing lines, most ESC/POS printers are in CP437 by default, so you may like to attempt to use [box drawing character from that code page](https://en.wikipedia.org/wiki/Code_page_437).

Best of luck!

**Comment by onally** [comment]
Thanks @mike42
