### ISSUE TITLE
Totally confused with ESC/POS?

### ISSUE THREAD

**Issue by binaryCodescape** [mike42/escpos-php#751]
Im sorry to sound lik such a noob, but I was never the best at byte arrays, and these ESC/POS commands are so confusing to me. Can you just explain to me do you have to program in hex, or can you use the commands listed in the command reference on epsons website. I have some code that does everything that I need except it doesn't print code 39 barcodes. The project is in a repo on GitHub under ESC-POS-.NET. basically Im trying to figure out what I need to translate here. The code seems to be mostly hex but theres still some esc commands. In the FAQ it gives info about the hex codes and such but it says FOR, and range of D, and range of K. Im very confused. It lists the ESC command and the hex and ASCII values but a lot of them have a For table like I mentioned. Im assuming it has nothing to do with a FOR loop. Im very confused as to why the programming examples have esc commands but most packages I see encode in hex what situation are hex/ASCII/ESC commands used when. So basically to sum it up can you just give me an overview of how to understand this information or any references or research that will assist me in doing so? Other than the FAQ and Command reference that give sample programs that look absolutely nothing like any of the packages/projects Ive seen around for esc/pos printing; I cant find anything to help me understand this better.

**Comment by hakushakusama** [comment]
Sameiam looking to understand how to use ESC/POS library using WINDOWSUSB because its the only thing  that seems to somehow working :/

**Comment by mike42** [comment]
The `escpos-php` implementation for barcodes is [here](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/src/Mike42/Escpos/Printer.php#L391), and [these are the unit tests](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/test/unit/EscposTest.php#L587) relating to CODE39 barcode command output. Provided that you follow the license, you are welcome to directly port it.

Your more general query does not appear to be related to this project, so I would appreciate it if you could take that elsewhere.
