### ISSUE TITLE
themal print model

### ISSUE THREAD

**Issue by Alqarooni** [mike42/escpos-php#755]
Hi ,
i was wondering if this library supports this 
brand: ISSYZONEPOS
model: IMP013

**Comment by mike42** [comment]
Hi, to quote the FAQ entry "[I have Printer X. Can I use this driver?](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/doc/FAQ.md#i-have-printer-x-can-i-use-this-driver)":

> If the printer understands ESC/POS, and you know how to get raw binary data to it, then yes. Otherwise, no.

You can generally find this information in the manual which comes with your printer. Some printers only support ESC/POS as one of several languages, so just make sure that ESC/POS is enabled before you start sending commands, or the printer will likely print garbage.
