### ISSUE TITLE
How can i print arabic in POS printer?

### ISSUE THREAD

**Issue by degeta10** [mike42/escpos-php#757]
Im trying to print arabic along with these texts. How can i do it?

  ```
        $printer -> text("Address.\n");
        $printer -> text("Contact: 132456789 \n");
        $printer -> text("TRN: 0055005 \n");
        $printer -> text(" فاتورة ضريبية \n");
```

**Comment by mike42** [comment]
Arabic printing is not currently supported in this library.

Unfortunately hardware support for the text layout and characters we need is not common, and nobody has yet found a way to use ImageMagick or GD to render the text correctly in software.

We are tracking this issue under #455, so I'll close this as a duplicate. If you know anything which would set this in the right direction, then your input would be appreciated!
