### ISSUE TITLE
BIXOLON SRP-E302 

### ISSUE THREAD

**Issue by minhtrungs** [mike42/escpos-php#760]
I have some BIXOLON SRP-E302 printer. I want to print image on it. Please add it to this lib. thanks.

**Comment by mike42** [comment]
Hi, which image printing functions have you tried so far?

The [manual for this printer](http://www.bixolon.com/upload/download/manual_srp-e300302_command_english_ver_1_00.pdf) suggests that `ESC *` is used for printing images on this printer, which corresponds to `bitImageColumnFormat()` in this library.

Also remember, we only target ESC/POS printers. This printer does appear to advertise ESC/POS support, so anything beyond plaintext is a bonus. As always, [use the `simple` profile for non-Epson printers](https://github.com/mike42/escpos-php/tree/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f#using-a-capabilityprofile).
