### ISSUE TITLE
Print multiple times on the same line

### ISSUE THREAD

**Issue by MRolandd** [mike42/escpos-php#763]
How could I print multiple times on the same line? 

For example if I print `Hello`  I want the printer to return to it's initial position and print `Hello` again.

**Comment by mike42** [comment]
On most printers, you may use either `setDoubleStrike()`, or `setEmphasis(true)` to achieve this effect.

I don't know a portable way to type over the same line twice with different text, but `setLineSpacing(0)` (see the implementation [here](https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/Printer.php#L875)) does work on the Epson TM-U220B, but no other printers I have tried.
