### ISSUE TITLE
Catching WindowsPrintConnector Error, Prevent to stop

### ISSUE THREAD

**Issue by juanPao** [mike42/escpos-php#765]
I have multiple printers, and all should proceed even if one is turn off (or catches error)

What I have tried:

```
try{
                    $connector = new WindowsPrintConnector("smb://Guest@".$availablePrinter->setup_name);
                    $printer = new Printer($connector);
                }catch(Exception $e){
                    $printer = false;
                }
```

Result: I got exception but the loop just stop.
`copy(\\dining1-pc\TMU-220-DINING): failed to open stream: Invalid argument`

is there any way to solve this?

I'm using TM-U220B

**Comment by mike42** [comment]
The `WindowsPrintConnector` attempts to print only when you call `$printer -> close()`, which is not in your example.

The actually message you are receiving looks like it could be a warning from [here](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php#L372), which is not an exception unless a global error handler makes it one (there is none in your example). In PHP's production configuration, this would simply be logged, and should not affect your output.

If the log messages are also unwanted, then you may be able to cautiously apply the [error control operator](https://www.php.net/manual/en/language.operators.errorcontrol.php) to silence them.
