### ISSUE TITLE
Label support?

### ISSUE THREAD

**Issue by beikeland** [mike42/escpos-php#77]
Would it be feasible to add support for feeding to the next label on printers with black mark support?

**Comment by mike42** [comment]
The command-set I've implemented does lean a bit toward receipt printers (eg, no 'page mode' support). If there is an ESC/POS command to locate the black mark, it may be easy to add this.

Can you reply back with the make and model of printer you're using, and link to any online docs from the vendor which would include the command that should be used to feed labels on your printer?

**Comment by beikeland** [comment]
I will try, but while GS FF (0x1d 0x0c) seems to be the documented command
for feed up to the next black mark it does not appear to work.  Hopefully
the sellers will report back with a the appropriate commands.

But for your comparability matrix I have a "P85A-401", not sure of the
make, its "Chinese". And it seems to support everything but grahphics, QR
codes and reverse feeding.

**Comment by mike42** [comment]
Some Epson printers seem to support `FS ( L` to feed the paper to 'print start', 'peel' & 'cut positions' (three separate variants of the command). This is in-scope to implement in this driver, but I don't have any hardware to test with, nor do I know of any users on one of these printers.

I'll close this issue off, but if the vendor does report back to you with the correct command for your printer, it can be re-visited.
