### ISSUE TITLE
Need jnformation about escpos connectivity with balck copper BC 95AC

### ISSUE THREAD

**Issue by ahsanAsif26** [mike42/escpos-php#772]
Hey
I need some information regarding this escpos library connection with php code.
Is it compatible ?? And what are your recommendation which printer should i use with my php pos system ??
Waiting for the positive response

**Comment by mike42** [comment]
The BC 95AC is [on the list of printers tested by the community](https://github.com/mike42/escpos-php/tree/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f#printers), so it should work to some extent.

I don't offer recommendations on printer purchasing, but mostly this library has been validated against Epson TM-series printers, so those would be the most compatible.
