### ISSUE TITLE
Support for EPSON FP-81II

### ISSUE THREAD

**Issue by itajackass** [mike42/escpos-php#774]
I'm trying to use demo script (PHP - network mode under windows using WAMP SERVER) with an EPSON FP 81II but nothing appened...no errors...no HELLO WORD print.... i'd like to know if it a model incompatibily or I have some config problem.

My client PC use WAMP to emulate the server.

The printer is LAN connected with main router.

IP / PORT are ok... EPSON CONFIG APP GET RESPONSE OK.

**Comment by mike42** [comment]
Hi, sorry for the slow response. It's an incompatibility.

Epson fiscal printers use a different protocol, and do not appear to understand ESC/POS. More information about what it _does_ support can be found on [their documentation for this printer](https://download.epson-biz.com/modules/pos/index.php?page=prod&pcat=51&pid=3318).
