### ISSUE TITLE
Error Printing on Windows Shared Printer connected via USB

### ISSUE THREAD

**Issue by gepraveen** [mike42/escpos-php#775]
I'm trying to Print from a Network Server (LAN) hosted on Linux(Centos) to a Shared Printer, connected via USB to a windows system.

but is giving the following error..

 PHP Fatal error:  Uncaught exception 'Exception' with message 'Failed to print. Command "smbclient '//192.168.113.144/TSC_TA210' -c 'print -' -N -m SMB2" failed with exit code 1: session setup failed: NT_STATUS_ACCESS_DENIED'

This is my code:
$connector = new WindowsPrintConnector("smb://192.168.113.144/TSC_TA210");
$printer = new Printer($connector);
$print_status = $printer->textRaw($prn_data);

Kindly help

**Comment by juanPao** [comment]
I encountered this issue, You need to setup your printer settings to allow "Guest" access. Also manually modify your printer/spool folder in windows to give permission to "Guest" role.

**Comment by sandeepkhehra** [comment]
Hello @juanPao,

I am having the same issue as @gepraveen . 
I am trying to use this library to access my printer (which is not a POS printer) but it works (prints page) when I test it locally, using XAMPP.

But when I try to print the page from a web server, it doesn't work. It is giving me this error:

`Fatal error: Uncaught Exception: Failed to print. Command "smbclient '//192.168.2.102/EPSON L380 Series' -c 'print -' -N -m SMB2" failed with exit code 127: sh: 1: smbclient: not found in /home/admin/web/new.il-bambino.nl/public_html/wp-content/plugins/wp-smart-pos/lib/printer/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php:230 Stack trace: #0 /home/admin/web/new.il-bambino.nl/public_html/wp-content/plugins/wp-smart-pos/lib/printer/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php(175): Mike42\Escpos\PrintConnectors\WindowsPrintConnector->finalizeLinux('\e@Hello World!\n...') #1 /home/admin/web/new.il-bambino.nl/public_html/wp-content/plugins/wp-smart-pos/lib/printer/src/Mike42/Escpos/Printer.php(503): Mike42\Escpos\PrintConnectors\WindowsPrintConnector->finalize() #2 /home/admin/web/new.il-bambino.nl/public_html/wp-content/plugins/wp-smart-pos/lib/printer/dd.php(52): Mike42\Escpos\Printer->close() #3 {main} thrown in /home/admin/web/new.il-bambino.nl/public_html/wp-content/plugins/wp-smart-pos/lib/printer/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php on line 230`

Any help would be appreciated.

**Comment by Leonardus-dot** [comment]
try :

$ip=$_SERVER['REMOTE_ADDR'];
$hostname = gethostbyaddr($_SERVER['REMOTE_ADDR']);
/*if you use ipaddress *
$connector = new WindowsPrintConnector("smb://$ip/EPSON80");
/*if you use hostname *
$connector = new WindowsPrintConnector("smb://$hostname/EPSON80");


Dont forget share your printer .

**Comment by sandeepkhehra** [comment]
@Leonardus-dot I am still having the same problem. Seems like the "smbclient" is missing on the server?
Could this be the reason? If so, how can I install smbclient on my server?
Thanks

**Comment by mike42** [comment]
Closing this off. There are a variety of problems here to do with shared printers.

Provided that you can show how to get text to your printer (eg. on the command-line from the server that runs PHP), please feel free to file separate issue with the details of your individual setup.

If you don't yet have a way to get raw data to your printer from the server that will be running PHP, then you need to solve that first, or this library will not be useful to you.

**Comment by sarojbrt1** [comment]
> try :
> 
> $ip=$_SERVER['REMOTE_ADDR'];
> $hostname = gethostbyaddr($_SERVER['REMOTE_ADDR']);
> /*if you use ipaddress */
> $connector = new WindowsPrintConnector("smb://$ip/EPSON80");
> /*if you use hostname */
> $connector = new WindowsPrintConnector("smb://$hostname/EPSON80");
> 
> Dont forget share your printer .

**Comment by fernandoavalos** [comment]
@sandeepkhehra Did you ever solved this error? I'm having the same issue.

**Comment by fayzasalman** [comment]
@sandeepkhehra Did you solve this issue? I'm having the same problem.
