### ISSUE TITLE
Printers tested: Everycom EC-58, TVS RP45 Shoppe

### ISSUE THREAD

**Issue by lgastmans** [mike42/escpos-php#778]
The following printer works:
Everycom Thermal Receipt Printer
Model EC-58
Print width:58mm
Interface: USB
Esc/Pos

**Comment by mike42** [comment]
Thanks for reporting! This will be included in the README for the next minor release.

**Comment by lgastmans** [comment]
You are most welcome. As I implement different printers I will inform you.

And I thank you very much for offering this class, I have been searching
for this for years!

**Comment by lgastmans** [comment]
Another supported printer model:
TVS RP 45 SHOPPE
Print Method: 9-pin serial impact dot matrix
Printing Speed: 5 lps @ 16 cpi; 40 col
Print Font: 7 X 9
Print width: 2.25" – 3.9"

Draft: 12, 13.3, 15, 16, 17, 20
High speed draft: 12
NLQ: 12
Interface: USB, Parallel, Serial

**Comment by markzaku** [comment]
What about Epson LQ2190, does it work?

**Comment by lgastmans** [comment]
If I come across the Epson LQ2190 I will let you know.
But most likely it will work

**Comment by mike42** [comment]
@markzaku - I don't suggest using this library for Epson LQ-series printers. These printers use ESC/P2 (documentation [here](https://www.epson.com.au/products/dotmatrix/lq2190_Specs.asp)), which is not compatible with ESC/POS. Plain ASCII text is the same on both protocols, but the control commands (eg. text encoding, formatting and images) are not.
