### ISSUE TITLE
can't print to usb port

### ISSUE THREAD

**Issue by fbafaro** [mike42/escpos-php#783]
Hi,

I'm trying to print directly to the USB001 port using this

$connector = new FilePrintConnector("USB001");

but nothing is beeing printed.

I'm on a xampp setup on a local machine with windows 7.

It does work using the share name with WindowsPrintConnector but as soon as the computer has not internet access, it stop working, any idea why?

**Comment by Leonardus-dot** [comment]
why you don't use the command  $connector = new WindowsPrintConnector("PRINTERNAME"); ?

**Comment by mike42** [comment]
You have just asked it to make a file called `USB001` and print to it. You most likely either have an error in a log, or a file called `USB001` somewhere. :)

I don't use Windows nowadays, but I wrote a bit about how to make receipt printers visible in [this blog post](https://mike42.me/blog/2015-04-getting-a-usb-receipt-printer-working-on-windows) a few years ago, which also used Windows 7.

Once you are comfortable that you have a working, command-line accessible raw printing setup, I would suggest starting with [the annotated example for Windows USB printing](https://github.com/mike42/escpos-php/blob/10b1230ba6875ac189f1f79b9e2de91a633c06b3/example/interface/windows-usb.php), which describes a similar setup in the comments.
