### ISSUE TITLE
How to check if the printer connection is failed or success?

### ISSUE THREAD

**Issue by jcbolor** [mike42/escpos-php#785]
Is there a way to know if the printer connection fails? either via WindowsPrintConnector, FilePrintConnector, or NetworkPrintConnector.

**Comment by mike42** [comment]
Hi jcbolor, this code is generally designed to throw exceptions if anything hasn't worked. The `WindowsPrintConnector` [code has many examples](https://github.com/mike42/escpos-php/blob/0659800298f4843d51b5e0413263a8e62727c732/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php).

You can use a `catch` block to handle exceptions gracefully, check the PHP documentation for more information.
