### ISSUE TITLE
zenpert 4t200

### ISSUE THREAD

**Issue by ramkrishna70** [mike42/escpos-php#787]
Hi, zenpert 4t200 printer not supporting the library.

**Comment by mike42** [comment]
Hi @ramkrishna70,

This library is written for printers which are compatible with ESC/POS. I don't think this printer is one of those, just from what I can see on the web about it.

If this is incorrect and printer does understand ESC/POS, then please post some more information and we'll debug from there. In the meantime, I'll close this off as other types of printers are not handled by this project.
