### ISSUE TITLE
Sinhala Language Printing Issue

### ISSUE THREAD

**Issue by gitsampath** [mike42/escpos-php#790]
Hi Mike,

I'm trying to print a bill in Sinhala language. I have added sinhala Unicode list to the Capabilities.php file and created a new CapabilityProfile.php file. However, the test print does not print my expected results. Attached herewith the files I modified.

encodings added to Capabilities.php

"TCSN-3-1": {
            "data": [
                "\u0D82\u0D83\u0D85\u0D86\u0D87\u0D88\u0D89\u0D8A\u0D8B\u0D8C\u0D8D\u0D8E\u0D8F\u0D90\u0D91",
                "\u0D92\u0D93\u0D94\u0D95\u0D96\u0D9A\u0D9B\u0D9C\u0D9D\u0D9E\u0D9F\u0DA0\u0DA1\u0DA2\u0DA3",
                "\u0DA4\u0DA5\u0DA6\u0DA7\u0DA8\u0DA9\u0DAA\u0DAB\u0DAC\u0DAD\u0DAE\u0DAF\u0DB0\u0DB1\u0DB2",
                "\u0DB3\u0DB4\u0DB5\u0DB6\u0DB7\u0DB8\u0DB9\u0DBA\u0DBB\u0DBC\u0DBD\u0DBE\u0DBF\u0DC0\u0DC1",
                "\u0DC2\u0DC3\u0DC4\u0DC5\u0DC6\u0DCA\u0DCF\u0DD0\u0DD1\u0DD2\u0DD3\u0DD4\u0DD5\u0DD6\u0DD7",
                "\u0DD8\u0DD9\u0DDA\u0DDB\u0DDC\u0DDD\u0DDE\u0DDF\u0DE6\u0DE7\u0DE8\u0DE9\u0DEA\u0DEB\u0DEC",
                "\u0DED\u0DEE\u0DEF\u0DF2\u0DF3\u0DF4"
            ],
            "name": "Sinhaleese TCSN-3 1"
        },

[escpos.zip](https://github.com/mike42/escpos-php/files/3634053/escpos.zip)

Sinhala Unicode List : https://jrgraphix.net/r/Unicode/0D80-0DFF
Printer Model : Epson TM-U220  

Thank you
Sam

**Comment by mike42** [comment]
I'm sorry to say that printing Sinhalese to this type of printer is going to be practically impossible. A CapabilityProfile tells the library which glyphs a printer has, but your printer [does not have Sinhalese glyphs](https://www.epson.com.au/products/brochures/TM-U220lr.pdf), so they are not going to help.

We do support adding glyphs through custom fonts (I'm adding this for Chinese/Japanese/Korean). Unfortunately, that work will not help with Sinhalese, which is a more complex script, nor for the TM-U220, which uses a very compact 7x9 font.

## Possible solution

This is easier to solve if you have a higher-density printer, such an Epson TM-series, and know how to render Sinhalese text to an image with the help of other tools.

I'm on Debian GNU/Linux with an Epson TM-T20II, and I was able to hack something together using [wkhtmltoimage](https://wkhtmltopdf.org/), [Noto Sans Sinhala](https://www.google.com/get/noto/) font, and of course escpos-php.

I made a "Hello World" HTML file-

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>

    <style>
      @font-face {
        font-family: 'Noto Sans Sinhala Bold';
        font-style: normal;
        font-weight: 700;
        src: url('fonts/NotoSansSinhala-Bold.ttf') format('truetype');
      }
      body {
        font-size: 24px;
        font-weight: 700;
        font-family: 'Noto Sans Sinhala Bold'
      }
    </style>
  </head>
  <body>හෙලෝ වර්ල්ඩ්</body>
</html>
```

![image](https://user-images.githubusercontent.com/2080552/65423525-95959600-de4c-11e9-88b8-73e8b76278bc.png)

Then rendered it to a small image -- note that 576 is calculated from the printer specifications.

```bash
wkhtmltoimage --width 576 test.html test.pbm
```

![test](https://user-images.githubusercontent.com/2080552/65424070-f40f4400-de4d-11e9-8d4e-1b0a8ac46c5b.png)

And our library here can print images just fine-

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

use Mike42\Escpos\Printer;

$connector = new FilePrintConnector("/dev/usb/lp0");
$printer = new Printer($connector);
$img = EscposImage::load("test.pbm");
$printer -> bitImage($img);
$printer -> cut();
$printer -> close();
```

![2019-09-example](https://user-images.githubusercontent.com/2080552/65423702-15236500-de4d-11e9-925f-de3e1065bbc8.jpg)

The good thing is that this can be easily extended to formatting more complex things-

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>

    <style>
      @font-face {
        font-family: 'Noto Sans Sinhala Bold';
        font-style: normal;
        font-weight: 700;
        src: url('fonts/NotoSansSinhala-Bold.ttf') format('truetype');
      }
      body {
        font-size: 24px;
        font-weight: 700;
        font-family: 'Noto Sans Sinhala Bold'
      }
    </style>
  </head>
  <body>
    <table style="width: 100%">
      <tr>
        <td>හෙලෝ</td>
        <td style="float: right">20.00</td>
      </tr>
      <tr>
        <td>වර්ල්ඩ්</td>
        <td style="float: right">30.00</td>
      </tr>
    </table>
  </body>
</html>
```

![test2](https://user-images.githubusercontent.com/2080552/65424126-1903b700-de4e-11e9-835c-d3b2f741f550.png)

It's not ideal, but hey it works.

Best of luck!

**Comment by gitsampath** [comment]
Hi Mike,

Thank you very much for your reply and that will stop my further works on trying to solve my problem with CapabilityProfile.

However, before your reply, I solved my problem by converting my HTML into a PDF file using mPDF library, print the bill and that works. Only problem I have with my solution is printing an empty area after the bill content.

I'm sure with your suggested solution I will be able to get a complete solution. I will try it out.

Thank you very much again!

Sam.
