### ISSUE TITLE
the library support zj9200 label printer ??

### ISSUE THREAD

**Issue by leonardogitbash8400** [mike42/escpos-php#791]
mike42 the library support zj9200 label printer ?? and witch class of the library i must used to working this printer? please, thanks.

**Comment by mike42** [comment]
It may work to some extent, please try the "Hello World" receipt from the README and see what works from there. The documentation I can find online claims that the printer supports both TSPL and ESC/POS. This library produces ESC/POS only, so make sure you have that enabled on your printer before you start sending it data.

You would be the first person to use it, so I can't offer any tips beyond that. Good luck!
