### ISSUE TITLE
Greek charters not supported 

### ISSUE THREAD

**Issue by alisharafat123** [mike42/escpos-php#796]
This is absolutely great effort by you. I am trying to print in Greek Language but it does not support. Kindly help. the printer I am working with XPOS-85C, Black Copper 85AC etc.

I have set this in Printer.php

` public function textGreek($str = "")
    {
        self::validateString($str, __FUNCTION__);
        //$this -> connector -> write(self::FS . "&");
        $str = iconv("UTF-8", "CP737//IGNORE", $str);
        $this -> buffer -> writeTextRaw((string)$str);
        //$this -> connector -> write(self::FS . ".");
    }`
But Still not working.

**Comment by mike42** [comment]
The short answer is that this is not the correct usage of the library. Once everything is set up, I would expect `$printer -> text("Γειά σου Κόσμε")` to work work just as well as `$printer -> text("Hello World")`.

To actually fix this, you will need some background though.

Every ESC/POS printer has a list of code pages numbered `0-255`. This library will automatically switch between the code pages to print various characters, using the information contained in a `CapabilityProfile`. We bundle a copy of the [ESC/POS printer database](https://github.com/receipt-print-hq/escpos-printer-db) with the library, so you can load any of those profiles at initialization time (see [example from the README](https://github.com/mike42/escpos-php/tree/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f#using-a-capabilityprofile)). The `default` profile matches the features of most Epson-branded printers.

If nobody has created a profile similar enough to your printer, then [you will need to submit one](https://github.com/receipt-print-hq/escpos-printer-db/blob/master/doc/add-your-printer.md). Check the "Information to gather" for things that you will need.

**Comment by alisharafat123** [comment]
and the printer
![pos](https://user-images.githubusercontent.com/12140043/66055806-877ffd80-e54f-11e9-90eb-05719dc97ea9.jpg)

**Comment by mike42** [comment]
I don't see a SAMPOS 80UE profile in the receipt printer database, so I'm not sure what you're running.

You will need some documentation about the supported code pages, and assuming that something Greek (eg. CP737) is supported by the printer, the entry in the database will tell this driver how to access the Greek characters.

There is a link in my previous comment with more information about submitting new printers to the database.
