### ISSUE TITLE
How to save print buffer into image

### ISSUE THREAD

**Issue by ssamnotr** [mike42/escpos-php#797]
Hi Mike,

I am wondering if it is possible to send the print buffer to save it as an image instead of sending it to the printer or the file connector?
Any thoughts on this?

Kind regards,

**Comment by Muraveiko** [comment]
This is called a device emulator. There are applications in google play. Virtual printer. Wirtualna drukarka termiczna

**Comment by ssamnotr** [comment]
@Muraveiko: Thanks for suggesting this.
I searched for virtual ESC POS solutions but unfortunately no luck so far.
It would be great if you can suggest application names or a link.
Thanks in advance.

**Comment by Muraveiko** [comment]
last 3 words is name app in google play. Not ideal. lots support command. 

and see on it
https://github.com/receipt-print-hq/escpos-tools

**Comment by mike42** [comment]
@Muraveiko is correct on all points.

This library outputs ESC/POS, which is a language understood by printers. We do not internally render an image of the receipt along the way, so there is no way to save that.

You can use a `FilePrintConnector` to write to a file, then you can recover the content with [escpos-tools](https://github.com/receipt-print-hq/escpos-tools), which is also open source and produced by myself. The most accurate image-based rendering would be achieved by [esc2html](https://github.com/receipt-print-hq/escpos-tools/blob/master/doc/esc2html.md) followed by `wkhtmltoimage`, which converts HTML to images.

A virtual printer is another option, but I don't know of any well enough to make a suggestion in that area.

Best of luck!
