### ISSUE TITLE
Uneven margin depending on last use of setJustification() ?

### ISSUE THREAD

**Issue by Qwent** [mike42/escpos-php#80]
Hello there !

First of all thank you for this wonderful code ! Really usefull !

I've been playing with it lastly, and I found something that could be an issue and worth reporting.

While working on my receipt I found that it appeared always with a margin larger on the right border than on the left one. It is not really a problem because the difference is small. But recently I put a final item that I wanted to be centered and used setJustification(Escpos::JUSTIFY_CENTER). Just by doing it and not reversing it to JUSTIFY_LEFT until the end of the code, **the whole receipt appeared perfectly centered** !

I didin't test any further this hypotesis but if I'm not the only one having this, I suppose it's a trick worth spreading. Moreover I bet it could be fixed in order to have a centered ticket without having to use this trick.

I hope this could hep,

Keep on the good work,

**Comment by mike42** [comment]
Hey,

This sure does sound strange. Can you share a code snippet and the model of your printer so that I can look into this a bit?

**Comment by mike42** [comment]
Thanks for the tip, hopefully this helps some people out.

I'll close this as there is not enough information to take any further action.
