### ISSUE TITLE
Printer Bak Bk-033

### ISSUE THREAD

**Issue by DevKleber** [mike42/escpos-php#811]
Doesn't work whti BAK Bk-033

**Comment by mike42** [comment]
Good to know, but I'm not sure whether we are expecting it to work.

- Does this printer use the ESC/POS command set?
- When you send it the ["Hello World" receipt](https://github.com/mike42/escpos-php/tree/e10cfb062b39885d1895a7af942b73ea1b7fec31#the-hello-world-receipt) in the README, how are you sending it, and what actually happens?
