### ISSUE TITLE
where is auotload.php file and vendor ?

### ISSUE THREAD

**Issue by 854163615** [mike42/escpos-php#817]
i download the last virsion and i didnt find the autoload file ?!!!

**Comment by Muraveiko** [comment]
It has long been time to learn how to automatically install the necessary libraries into one command.

https://getcomposer.org/
https://packagist.org/packages/mike42/escpos-php

**Comment by mike42** [comment]
This is intentional, and is documented as a breaking change in the [release notes for v3.0](https://github.com/mike42/escpos-php/releases/tag/v3.0):

> [composer](https://getcomposer.org/) is now required to correctly load dependencies, where it was previously optional.
