### ISSUE TITLE
Invalid Argument php_sapi_name() on Mac 

### ISSUE THREAD

**Issue by fheo** [mike42/escpos-php#82]
I am running the demo.php program by connecting Epson Tm82|| to Mac V10.11 and am getting this error:

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Argument passed to Escpos::__construct() must implement interface PrintConnector, null given.' in /Users/Jaynav/mtailer/escpos-php-master/Escpos.php on line 177

**Comment by mike42** [comment]
Hey, I have a USB TM-T20II and a Mac, so I'd like to try to replicate this.

Some of the basics-
- What interface does your printer use? (Ethernet, USB, serial, etc)
- What version of PHP and Mac OS are you running?

Detail if you know it-
- Have you been able to send "Hello World" text to your printer on the command-line, and if so what command worked?
- How are you attempting to print? (eg, command-line and redirecting to the device, command-line, saving to a file and printing, or via Apache after editing the demo file)

**Comment by mike42** [comment]
The optional use of a print connector on the CLI sapi has been removed, see [updated README.md](https://github.com/mike42/escpos-php#using-a-printconnector) for info on choosing a print connector.

In your case, you may need to track the progress of #85 for improved Mac USB support via a CUPS connector.
