### ISSUE TITLE
help me I have Problem Fatal error: Uncaught Error: Class 'CapabilityProfile' not found

### ISSUE THREAD

**Issue by keophilavanh** [mike42/escpos-php#820]
hi tem i'm student from Laos

I create mamimarket system , When I need print Lao Language , i have problem similar is link [https://github.com/mike42/escpos-php/issues/549](url)

[

but i try is not work. help me how can i do ?

is code
`<?php

require __DIR__ . './../vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\CapabilityProfiles\DefaultCapabilityProfile;
use Mike42\Escpos\PrintBuffers\EscposPrintBuffer;
use Mike42\Escpos\PrintBuffers\ImagePrintBuffer;

try {
  
    $connector = new NetworkPrintConnector("192.168.1.10", 9100);
   
    $profile = CapabilityProfile::load("default");
    $buffer = new ImagePrintBuffer();
    $buffer -> setFont('/usr/share/fonts/truetype/lao/Phetsarath_OT.ttf');
    

  
    $printer = new Printer($connector, $profile);
    $printer -> setPrintBuffer($buffer);
    $printer -> text("ລະບົບຮ້ານອາຫານ\n");

    $printer -> cut();

    /* Close printer */
    $printer -> close();
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}`

![Untitled](https://user-images.githubusercontent.com/36201795/67028007-cbb8f380-f134-11e9-8818-530146164b8a.png)
](url)

**Comment by mike42** [comment]
There is an error in the code posted to that issue.

Include the `autoload.php` for your project, and `use` any classes in your code. In this case-

```php
use Mike42\Escpos\CapabilityProfile;
```
