### ISSUE TITLE
Issue in network print using IP  address while using multiple printers PHP application 

### ISSUE THREAD

**Issue by fusionminds** [mike42/escpos-php#823]
Hello Team,

We have an PHP server side application for printing reciepts and we are using 3 network printers configured through IP addresses. 

We have hosted 3 instances of same application in XAMPP sever and each instances uses one printer. and the each client is accessing the same server and prints are taken. But issue which we have encountered is once in a while randomly print from one instance is being printed in the printer which is assigned to different instance. 

eg: instance 1 is assigned to 192.168.1.88
instance 2 is assigned to 192.168.1.89
instance 3 is assigned to 192.168.1.90

some times intance 1 print is printed in instance 3 printer.

Awaiting your response.

**Comment by mike42** [comment]
If you are using `new NetworkPrintConnector($ip, $port)`, then this library directly uses `fsockopen` ([link](https://github.com/mike42/escpos-php/blob/203c53e97e0365b91491bea6fc1996e6629343a7/src/Mike42/Escpos/PrintConnectors/NetworkPrintConnector.php#L36)) to speak to the IP address and port you ask it to, so there isn't much space for the library to mix things up.

The decision for which printer to use is presumably somewhere in your XAMPP configuration or application code, which is not something I can help you with.

I've marked this as `needs info` in case there is something else I'm missing. If you think it's a library issue, please include a small example which shows the problem.
