### ISSUE TITLE
 No such file or directory | autoload.php

### ISSUE THREAD

**Issue by celikyazilim** [mike42/escpos-php#825]
Warning: require(C:\AppServ\www\escpos-php-development\example\interface\..\..\autoload.php): failed to open stream: No such file or directory in C:\AppServ\www\escpos-php-development\example\interface\windows-usb.php on line 3

Fatal error: require(): Failed opening required 'C:\AppServ\www\escpos-php-development\example\interface\..\..\autoload.php' (include_path='.;C:\php\pear') in C:\AppServ\www\escpos-php-development\example\interface\windows-usb.php on line 3

How can i fix this?

**Comment by mike42** [comment]
The example path doesn't exist.

Change it to-

```php
require __DIR__ . '/../../vendor/autoload.php';
```

You need to run `composer install` for this file to exist. If you haven't used composer before, you can read about it at [getcomposer.org](https://getcomposer.org).

For future readers: In most project setups, you will need to change the `require_once` statement to point to the `autoload.php` file for their project before the examples will run. The line above your crash is commented to point this out-

```php
<?php
/* Change to the correct path if you copy this example! */
...
```
