### ISSUE TITLE
Remove Padding Top

### ISSUE THREAD

**Issue by Charlieevox** [mike42/escpos-php#826]
Hi Mike, I have an issue when i printing, i see by the default, it always feed some line before my text print. 

my question, how to remove feed before i print? at the end i just wanna make this no padding on top.

**Comment by mike42** [comment]
Which model of printer do you have?

This seems to affect some printers more than others, but it's likely to have to do with the `cut()` function, which feeds 3 lines by default.

I would suggest first attempting-

```php
$printer -> cut(Printer::CUT_FULL, 0);
```

**Comment by mike42** [comment]
See also #835, which is a similar issue that I've posted a more detailed answer to.
