### ISSUE TITLE
Graphics() and BitImage() Printing Characters and Not Image

### ISSUE THREAD

**Issue by emerns02** [mike42/escpos-php#83]
Hi Mike,

I've recently gotten started using your tool and just about everything seems to be working well!

The only thing - I'm attempting to print a .png logo at the top of my receipt and cannot get it to work. I've tried both graphics() and bitImage(). I'm hoping I'm missing something small...

A few more specifics:
- HP A799 thermal printer
- GD enabled
- Windows environment (followed your tutorial - installed as shared printer with generic text driver, etc...)
- Barcodes, formatting, and all other text seem to print as expected

Thanks so much for the help.

#7

**Comment by mike42** [comment]
I've marked this as a bug. It looks like the graphics commands accepted by your printer don't line up with the ones that this driver can currently generate, so some new implementations could fix it. I've got access to a printer which shows the same limitation, so more graphics commands are certainly on the way.

Can you please also attempt-
- Print a diagnostics page and upload it here ([see page 16 here])(http://h10032.www1.hp.com/ctg/Manual/c04479810)  
- Repeat the test with legacy emulation enabled, which may impact graphics commands ([link](http://h20564.www2.hp.com/hpsc/doc/public/display?docId=mmr_kc-0107093)).

For reference, the programming guide for this printer is at-
- http://www.cognitivetpg.com/assets/downloads/A799-Programmer%20Guide_PG00001_Rev%20D.pdf

**Comment by emerns02** [comment]
Hey Mike,

Sorry for the delay in my response. Here's the diagnostics form:

[a799_thermal_print_config.pdf](https://github.com/mike42/escpos-php/files/140965/a799_thermal_print_config.pdf)

I won't have access to the printer until this afternoon - that's when I'll repeat the testing with legacy emulation enabled.

Thanks and I'll keep you posted!

**Comment by emerns02** [comment]
OK - I did get to repeat the test with legacy emulation enabled. No dice. I tested both the graphics() command and the bitImage() command.

Please keep me posted if you need any additional testing.

**Comment by mike42** [comment]
I've coded an experimental implementation of the column format, which I've tested on the Epson TM-T20 and Epson U220.

````
git pull
git checkout 83-columnformat
````

You might like to try printing `tux.png` on your HP A799, with some code like below (adapted from `example/graphics.php`).

````php
	$tux = new EscposImage("resources/tux.png");
	
	$printer -> bitImageColumnFormat($tux);
	$printer -> text("Regular Tux.\n");
	$printer -> feed();
	
	$printer -> bitImageColumnFormat($tux, Escpos::IMG_DOUBLE_WIDTH);
	$printer -> text("Wide Tux.\n");
	$printer -> feed();
	
	$printer -> bitImageColumnFormat($tux, Escpos::IMG_DOUBLE_HEIGHT);
	$printer -> text("Tall Tux.\n");
	$printer -> feed();
	
	$printer -> bitImageColumnFormat($tux, Escpos::IMG_DOUBLE_WIDTH | Escpos::IMG_DOUBLE_HEIGHT);
	$printer -> text("Large Tux in correct proportion.\n");
	
	$printer -> cut();
````

**Comment by emerns02** [comment]
Hey Mike,

Happy to report that your updates are working! My logo is printing out with the bitImageColumnFormat() command.

I tested it with Legacy Emulation both on and off. It worked both times.

Let me know if I can help out any more! Thanks again for the quick resolution.

**Comment by emerns02** [comment]
Hey Mike,

One other small bug I came across yesterday:

line #284 of your Escpos.php file, there are two '$' signs causing a warning issue on certain image prints. I simply removed one of them, and everything works great!

Here's the variable: '$$highDensityHorizontal'.

Thanks again!

**Comment by pierrejoye** [comment]
For the record here,

model: XPrinter XP-C300H

Using ::graphics fails (print out text with whatever charset is set).

::bitImage and ::bitImageColumnFormat do the job.
