### ISSUE TITLE
error because of missing autoload.php

### ISSUE THREAD

**Issue by LoverBot999** [mike42/escpos-php#830]
Warning: require(G:\Program Files x86\xampp\htdocs\print\example\interface/../../vendor/autoload.php): failed to open stream: No such file or directory in G:\Program Files x86\xampp\htdocs\print\example\interface\smb.php on line 3

**Comment by sychowaves** [comment]
try it [Install XAMPP](https://github.com/mike42/escpos-php/issues/869)

**Comment by medimaru** [comment]
> try it [Install XAMPP](https://github.com/mike42/escpos-php/issues/869)

it still not working
