### ISSUE TITLE
Can We Use Without Composer?

### ISSUE THREAD

**Issue by celikyazilim** [mike42/escpos-php#832]
Hi;

Can we use without composer? (on shared hosting)

**Comment by JuanjoArmellino** [comment]
Hi
im loading it with autoload.php, file attached.. rename it
just require the file and use namespaces

use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\EscposImage;

.. just check paths for location of Mike42 folder

[autoload.php.txt](https://github.com/mike42/escpos-php/files/3816124/autoload.php.txt)

**Comment by mike42** [comment]
If you skip loading PHP dependencies, then you will get mysterious "Class not found" errors on some code paths.

This doesn't mean that you need to install `composer` it on your server - you can instead run it in a build environment, then upload the result.

I think the README is quite clear on this-

> This library is designed for use with the composer PHP dependency manager.

You are of course welcome to do whatever you like on your own server, but at least you now know what to expect.
