### ISSUE TITLE
textChinese function "almost" printing spanish text. need help

### ISSUE THREAD

**Issue by JuanjoArmellino** [mike42/escpos-php#833]
Hi Mike
Excelent job on your library
i have been trying to print spanish on my Xprinter 80mm with no luck, 
in a last desperate try i used the function textChinese
i found out that á é í ó ú get printed, but a blank space is added after each character. 

is there anything i can try to correct this ? 
thanks in advance
Juanjo

**Comment by Muraveiko** [comment]
In chines mode (kanji) all char have 32x32 dots .
I think you need send 2 bytes ( chine mode off ) before ESC t

**Comment by JuanjoArmellino** [comment]
well, i finally found a tool to change the default internal table from chinese to international... now changing codepage works properly.

**Comment by mike42** [comment]
Glad to hear this is solved.

I'm open to suggestions if you think there is some way that this library could handle this situation better, but at this stage I'm assuming it's just something that Xprinter 80mm owners will need to be aware of and configure manually.

**Comment by chinomenares** [comment]
> bueno, finalmente encontré una herramienta para cambiar la tabla interna predeterminada de chino a internacional ... ahora el cambio de página de códigos funciona correctamente.

me puedes decir como solucionaste este problema, yo tengo problemas con los acentos
