### ISSUE TITLE
I host my laravel project on Siteground Server, and Got smbclient error

### ISSUE THREAD

**Issue by owsoultions** [mike42/escpos-php#834]
Please help me with how it will sort out, following is the complete error
Failed to print. Command "smbclient '//sgp76.siteground.asia/BlackCopperBC-85AC' -c 'print -' -N -m SMB2" failed with exit code 127: sh: smbclient: command not found

**Comment by owsoultions** [comment]
It works fine while i use my project on Localhost xampp server, but if i host my whole project on my Siteground hosting account, so it gives me error: Failed to print. Command "smbclient '//sgp76.siteground.asia/BlackCopperBC-85AC' -c 'print -' -N -m SMB2" failed with exit code 127: sh: smbclient: command not found

**Comment by Muraveiko** [comment]
smbclient: command not found
if there is no command on the Unix server, then you need to deliver it. The command depends on the version of the operating system.
Most often it is
apt-get install

**Comment by mike42** [comment]
It sounds like you have moved your app to an Internet-based host, which most likely cannot see your printer anyway.

This type of setup is fine, but you will need to do some extra work to get the data back to your printer, and a shared host may not give you enough control to get it all working. See "[Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/5e904fed73704dcf22c4c4db2f31b329fb7a0b5f/doc/FAQ.md#can-i-print-from-my-server-on-the-internet)" in the FAQ for some ideas.
