### ISSUE TITLE
-m SMB2 not work on WIndows 10

### ISSUE THREAD

**Issue by mean-cj** [mike42/escpos-php#837]
Hello , thnk you for your project

I will found SMB2 parameter not work with windows 10

`# echo "HELLO" | smbclient '//192.168.0.100/GP-8300TC'  -c 'print -' -N `
OS=[Windows 10 Pro 18362] Server=[Windows 10 Pro 6.3]
putting file - as stdin-582 (2.3 kb/s) (average 2.3 kb/s)

`# echo "HELLO" | smbclient '//192.168.0.100/GP-8300TC'  -c 'print -' -N -m SMB2`
NT_STATUS_ACCESS_DENIED opening remote file stdin-584

On Windows
```
`Get-SmbServerConfiguration | Select EnableSMB2Protocol`
EnableSMB2Protocol
------------------
              True
```

Thank you.

Ref: https://github.com/mike42/escpos-php/issues/575

**Comment by mike42** [comment]
Hi @mean-cj, thanks for reporting.

Issue #575 lists the use of this command-line parameter as a bug, since there is no "correct" SMB level for everybody.

Pull requests are welcome- I'm rarely use Windows for printing myself, so I'm not likely to make this change any time soon.
