### ISSUE TITLE
Improve command support for Star Micronics SM-S230i

### ISSUE THREAD

**Issue by bedengler** [mike42/escpos-php#84]
Hi, we've tried to print through ESC-POS-PHP on some printers that support esc-pos.
Basically everything works on 80mm printers so far. But as soon as we try to print an image or qr code on a 58mm printer, it gets totally messed up and no image or qr is printed.
Is there any option to set the paper width? Or should it be auto detected?

**Comment by mike42** [comment]
Hi,

If you get garbage one one printer, it may not support QR codes natively, and will need some help from `phpqrcode` or similar.

Can you have a read of [this](http://mike.bitrevision.com/blog/2015-04-howto-qrcodes-on-receipts-with-escpos-php) and let me know what model printers are involved? (eg, an 80mm FooCorp SuperPrint 7 via USB is working but the 58mm Quux via Parallel is struggling). The programming guides for the printers show which commands they can run.

(Note that the library has just been updated to use namespaces, so the code in the linked post is not current)

**Comment by bedengler** [comment]
Ok, so we've tried a very cheap Rongtatech RPP300 (80mm) which prints everything perfect. And we have a Star Micronics SM-S230i which messes up everything. The star supports ESC/POS and also supports qr code printing.
What's strange is the fact that it doesn't print only qr codes, but also images.
I attached the both printouts...
![img_20160223_155649](https://cloud.githubusercontent.com/assets/17435772/13295568/caf35f6e-db29-11e5-80be-cd7feef3cda8.jpg)

**Comment by mike42** [comment]
Yep, I see what you mean here. Can I get a code snippet of what you're printing? (eg, `bitImage()` looks the same as `graphics()` on paper, but is supported by more printers)

[This guide](http://www.starmicronics.com/support/download.aspx?type=5&tabText=StarPRNTCommand%20Specifications%20for%20Portable%20Printer%20&%20mPOP%20&path=../support/Mannualfolder/StarPRNT_cm_en.pdf&referrer=http://www.starmicronics.com/support/manual.aspx?printerCode=SM-S230i&id=0) shows supported commands for the SM-S230i. The QR code commands in Star printers is not from ESC/POS, but appears to be a mix of proprietary codes which varies between models. Long term, it's intended that the `CapabilityProfile` classes in this driver will deal with these differences, but rendering to an image will get you up and running for now, if we can get the images working of course.

**Comment by bedengler** [comment]
Ok thanks for your reply. Here's the code snippet:
`/* Start the printer */
$logo = new EscposImage("resources/escposphp.png");

/* Print top logo */
$printer -> setJustification(Escpos::JUSTIFY_CENTER);
$printer -> bitImage($logo, Escpos::IMG_DOUBLE_WIDTH | Escpos::IMG_DOUBLE_HEIGHT);`

**Comment by bedengler** [comment]
Ok I talked to our developers again and it seems that these printers aren't able to print the pictures via bitImage() (or conventional ESC/POS) commands. So we're printing it with native commands on Star printers and "normal" bitImage() on everything else.
We need Star-support as our clients are using them...

**Comment by mike42** [comment]
Regarding image support, the new `bitImageColumnFormat()` (ESC *) output from #83 is very similar to commands that your printer supports (ESC K). Can you have a shot at printing with this new command to see if it works on your printer?

**Comment by mike42** [comment]
Since the SM-S230i is not an ESC/POS printer, improving support for it is not currently in-scope for this project. Since there is also no response regarding whether images work with an ESC/POS command, I'm going to close this issue off.

I'm open to pull requests which either add non-ESC/POS features without breaking other printers, or disable standard features for a particular printer so that it can do more basic prints.

**Comment by bedengler** [comment]
Hi Mike, sorry for don't coming back to this issue. I missed your response. We'll try the new bitImageColumnFormat() command within the next 2 weeks! I'll keep you posted. Thanks for your engagement, I appreciate that...

**Comment by bblimke** [comment]
@bedengler have you managed to print somehow qr codes and images in the ESC/POS mode on the SM-S230i printer at the end?

**Comment by bedengler** [comment]
Hi guys,

we got image printing running on the SM-S230i with the bitImageColumnFormat!
Just use it like this:
`$logo = EscposImage::load("/example/resources/escpos-php.png");`
`$printer -> bitImageColumnFormat($logo);`

That's it!
