### ISSUE TITLE
Addressing usb on Mac

### ISSUE THREAD

**Issue by bedengler** [mike42/escpos-php#85]
Is there a possibility to use a usb connected printer on a mac?
I've investigated some "lp" (from cups), but how should I set it up in the php script?

The usb printer isn't showing up in `ls /dev/*`
Something like this? 
`$connector = new FilePrintConnector("lp - p PRINTERNAME");`

I have a USB Epson TM-T20II on a Mac

**Comment by mike42** [comment]
Hi, you're on the right track.

My suggestion is to load the printer in to CUPS using raw output, print to a temp file from escpos-php, and then use `lpr` to print the file to the printer. The guide [here](http://mike.bitrevision.com/blog/2015-10-how-to-connect-a-usb-receipt-printer-up-on-mac-os-x) is written for a TM-T20II on Mac.

In the future, the interface I would really like to see is:

```php
$connector = new CupsPrintConnector("EPSON_TM-T20");
```

But in the meantime, your code would look something like this:

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;

// Temp file
$tmpfname = tempnam(sys_get_temp_dir(), 'print-');
$connector = new FilePrintConnector($tmpfname);

// Generate output
$printer = new Printer($connector);
$printer -> text("Hello World!\n");
$printer -> cut();
$printer -> close();

// Print it out
$cmd = sprintf("lpr -o raw -H localhost -P EPSON_TM-T20 %s 2>&1",
    escapeshellarg($tmpfname));
exec($cmd, $retArr, $retVal);
unlink($tmpfname);
if($retVal != 0) {
	throw new Exception("$cmd: " . implode($retArr));
}
```

**Comment by bedengler** [comment]
thanks for your code snippet! I'll give it a try...
Great to have support from you, I appreciate that a lot.

**Comment by gnanakeethan** [comment]
Hi mike, 
I have been using this library for about an year. I want to print directly to printer on a Mac. Is that even possible with some other aids?

Best Regards,
Gnanakeethan

**Comment by mike42** [comment]
As linked above, you can probably use CUPS for such a setup. The `CupsPrintConnector` uses the `lp` command, please try it out and open a new issue if you have issues on Mac (we can detect and handle OS-specific problems)

I don't know another way to get raw data to a USB printer from PHP on Mac OS X, but I'm open to reviewing pull request for new connectors if available.

**Comment by gnanakeethan** [comment]
As far as i know, my printer prints gibberish PS based script when it is
being setup into the system. So i suppose there must be a way beside cups.

**Comment by bedengler** [comment]
Check this out: https://www.neodynamic.com/products/printing/raw-data/php/

It's a plugin for nearly all popular browsers...

**Comment by gnanakeethan** [comment]
I fear that it works through CUPS.

**Comment by bedengler** [comment]
In my knowledge there's no other way on unix / linux / osx to setup a printer than using cups. If your printer prints weird things, it's not cups' fault, but it's a setup problem...
