### ISSUE TITLE
Autoload missing error

### ISSUE THREAD

**Issue by Alectron5555** [mike42/escpos-php#850]
Hi,
i began to install escpos-php with composer thanks to the following command:  
composer require mike42/escpos-php
but it get: 
Failed opening required 'C:\wamp64\www\print\example\interface/../../vendor/autoload.php'

So i followed this [topic](https://github.com/mike42/escpos-php/issues/847) and did the manipulations you propose but i always get the same message

did i miss something ?

**Comment by mike42** [comment]
Can you include the steps you took, in enough detail that somebody else could follow it and end up getting the same error?

This should make it clear where the files are on your system.

**Comment by Alectron5555** [comment]
I'm beginner so excuse me if it's not very clear in my explanations.

So i'm working on a registration station developed via php and running with WAMP (in file www).
OS is  windows10 and the thermal printer use is Epson TM-T20II.
My goal is to print a ticket generated by php script (thats allow me to use informations from my database)

The process i used is :
- I downloaded the driver of the thermal printer and install it via this topic [here](http://dudnaev.com/php-print-to-printer-example/)

- Then i tested if the communication was ok via those commands in the cmd : 
    cd c:/
    echo "hello world" > testfile
    print /D:"\\%COMPUTERNAME%\TM-T20II" testfile
    del testfile

- On your page i dl composer and install it (via the wizard assistant) , after i dl the zip file escpos-php and extract it in a folder (in www file) and did : composer require mike42/escpos-php in the cmd

- In order to test it, i modified windows-usb.php to recognise my printer (always via the tutorial on the top). and i get this message : Failed opening required 'C:\wamp64\www\print\example\interface/../../vendor/autoload.php'

- So i looked at the Issues section and saw the topic i linked in my first message. Then i installed git hub desk and the command git on my cmd and did : 
    git clone git@github.com:mike42/escpos-php.git
    cd escpos-php
    composer install

But nothing changed, always the same : Failed opening required 'C:\wamp64\www\print\example\interface/../../vendor/autoload.php'

I hope it will help, if you need more informations don't hesitate. 

Thanks for your work by the way 👍 👍 👍

**Comment by Alectron5555** [comment]
I found the answer to my problem, i wasn't in the good directory when i did "composer install" via the cmd.
 
So i did : 
- cd c:/wamp64/www/nameofyourescposfolder/ (for exemple : print)
- composer install

I tested it and everything works !
