### ISSUE TITLE
Autoload missing error 

### ISSUE THREAD

**Issue by FaizanKhan445** [mike42/escpos-php#853]
require __DIR__ . '/vendor/autoload.php';

**Comment by mike42** [comment]
There is not much information to go from here.

I'm assuming that you followed the [Basic Usage](https://github.com/mike42/escpos-php#basic-usage) in the README, and have used `composer` to add `mike42/escpos-php` to your project. If this is incorrect, then please go back and use `composer` - it is the only supported way to use this library.

On any composer project, you will have an `autoload.php` file in a directory called `vendor`. You may need to adjust the path or discard that line entirely, depending on what the rest of your project looks like.
