### ISSUE TITLE
add multiple printers with images Print?

### ISSUE THREAD

**Issue by rehankausar** [mike42/escpos-php#857]
Hello,

it's possible to use two printers to print the each copy of images via Ethernet (IP)?
example
Printer 1 $connector = new NetworkPrintConnector("192.168.1.10", 9100);
Printer 2 $connector2 = new NetworkPrintConnector("192.168.1.12", 9100);
`$connectors = MultiplePrintConnector($connector,$connector2)`
`$priners  = new Printer($connectors);`
`$img = EscposImage::load('../image1.png');`
`$img2 = EscposImage::load('../image2.png');`

i have also implement #789  and its working good with same data. is there any way to send categories wise receipt print to multiple printers at once.
for example:-
`Printer A` has assigned `category A `and `Printer B` has assigned `category B` and i want to print `category A` to `Printer A` and `category B` to `printer B` at once.
how would i do that please suggest.
apologies for bad English hope you can understand what i mean..

Thank you i appreciate your help in advance.

**Comment by mike42** [comment]
The `MultiplePrintConnector` will send **identical print data** to multiple print connectors, which is not what you want.

To print different content to different printers, you will need two separate `Printer` instances, which you can then interact with however you like. Eg.

```php
$blueConnector = new NetworkPrintConnector("192.168.1.10", 9100);
$greenConnector = new NetworkPrintConnector("192.168.1.12", 9100);

$bluePrinter = new Printer($blueConnector);
$greenPrinter = new Printer($greenConnector);

$blueImg = EscposImage::load('../image1.png');
$greenImg = EscposImage::load('../image2.png');

$bluePrinter -> bitImage($blueImg);
$greenPrinter -> bitImage($greenImg);
```

To reduce repetition, you could write a `function` with some `if` statements in it. This is your application code, so the structure is your choice.

**Comment by rehankausar** [comment]
is it also posible with `WindowsPrintConnector(smb://path)`.?
