### ISSUE TITLE
Error Composer (Xampp Windows)

### ISSUE THREAD

**Issue by Askeshine** [mike42/escpos-php#860]
Hi , when i try do composer show me this error command promt

Root package 'mike42/escpos-php' cannot require itself in its composer.json

**Comment by Askeshine** [comment]
Mi bad , solved.

**Comment by sychowaves** [comment]
> Hi , when i try do composer show me this error command promt
> 
> Root package 'mike42/escpos-php' cannot require itself in its composer.json

try it [Install for XAMPP](https://github.com/mike42/escpos-php/issues/869)

**Comment by medimaru** [comment]
> Mi bad , solved.

hey ; please tell me how did you solve it ? ASAP

**Comment by Askeshine** [comment]
Sorry but i dont remember , i dont use more escpos.
