### ISSUE TITLE
failed to open stream: Permission denied in - Windows 

### ISSUE THREAD

**Issue by zeprodriguesKing** [mike42/escpos-php#864]
hello my friend, thanks for developing something wonderful like escpos-php.
friend i'm brazilian so sorry my english.
I would like to have your help working with escpos-php on my project.

My current scenario is as follows.
a local area network with a windows 10 notebook running as php server.
server name = KM-PC
php version 7

and another notebook connected to the same network with windows 7
computer name = JK-PC
conm usb printer connected and shared with name IMP.

I did all the tests
echo "Hello World"> testfile
copy testfile "\\ JK-PC \ IMP"
del testfile

net use LPT1 \\ JK-PC \ IMP
echo "Hello World"> LPT1

I was successful in both cases.

I also gave full permission to all users and to the network at C: \ windows \ system32 \ spool \ PRINTERS

With everything done when trying to run the print for my php project it returns the error:

Warning: copy (\\ JK-PC \ IMP): failed to open stream: Permission denied in C: \ wamp64 \ www \ SS \ vendor \ mike42 \ escpos-php \ src \ Mike42 \ Escpos \ PrintConnectors \ WindowsPrintConnector.php on line 375

Couldn't print to this printer: Failed to copy file to printer
could you help me?
thanks in advance

**Comment by zeprodriguesKing** [comment]
thanks my friend already solved the problem

**Comment by andrewl94** [comment]
Could you elaborate how your friend solved the problem? I'm facing an similar problem.
