### ISSUE TITLE
Printing from file

### ISSUE THREAD

**Issue by Sofianio** [mike42/escpos-php#865]
Hello,
This isn't exactly an issue with the package which is great btw, it's more of a question

I have my api in a server and I don't think I can link the printer to the server
So, I thought of giving the user a file generated by this Package (using Dummy Connector)
Then the user will print the file using some third party software

My question is: is it possible? is there such software that takes the generated code and prints it?
If so, can you give me an example of such tool, I tried searching online but don't know what I'm looking for

Thanks in advance

**Comment by mike42** [comment]
It sounds like you have already decided how you want to solve this, but you might like to read the FAQ anyway:

- [Can I print over the network?](https://github.com/mike42/escpos-php/blob/e920a0f70fd117b83361ddaf4e3fa90d96ccdc96/doc/FAQ.md#can-i-print-over-the-network)
- [Can I print from my server on the Internet?](https://github.com/mike42/escpos-php/blob/e920a0f70fd117b83361ddaf4e3fa90d96ccdc96/doc/FAQ.md#can-i-print-from-my-server-on-the-internet)

What you are looking for is simply called "raw printing from a file on <platform>". You probably don't need any special software for it, but you will need to know how your print system works, and a small custom application could certainly make such a setup more usable.

The specifics depend on your print system and maybe your printer. On Linux, I print a file to a USB printer like this:

```bash
cat foo.bin > /dev/usb/lp0
```
