### ISSUE TITLE
Install mike42/escpos-php in XAMPP by apachefriend issue error [SOLVED]

### ISSUE THREAD

**Issue by sychowaves** [mike42/escpos-php#869]
hi, surely it has given you a headache XAMPP
this was my solution
First you must have the installed version of composer you can download it directly from [https://getcomposer.org/Composer-Setup.exe](https://getcomposer.org/Composer-Setup.exe)  I also recommend seeing the guide in [Composer Guide]([https://getcomposer.org/Composer-Setup.exe](https://getcomposer.org/Composer-Setup.exe) )

we go with XAMPP
in the XAMPP control panel
![apache](https://user-images.githubusercontent.com/3643158/73518924-f7a37080-43d5-11ea-9c9a-52481c2d8ceb.GIF)
we must go to the `apache` configuration and locate the `php.ini` a blog of notes will open select F3 to search for the word `intl`, the extension will appear `;extension = intl`, delete the` ; ` from the beginning we will save it and we will have to restart the xampp server 
![php](https://user-images.githubusercontent.com/3643158/73519138-8a440f80-43d6-11ea-9526-93422bbb899b.GIF)
to continue the configuration go to the `XAMPP` panel control on the right and locate shell button and select it, and the XAMPP `console` will open and type `cd htdocs`
![htdocs](https://user-images.githubusercontent.com/3643158/73519554-cb88ef00-43d7-11ea-920a-1e533fc1517b.GIF)
If all goes well we will continue the indications as they appear in [Basic Usage](https://github.com/mike42/escpos-php/blob/development/README.md#basic-usage) 
Simply add the `mike42/escpos-php` package to get started:

> composer require mike42/escpos-php
it will run and the following will appear
![compose-1](https://user-images.githubusercontent.com/3643158/73520081-1d7e4480-43d9-11ea-9497-9e2c40f6945a.GIF)

in the `code` for the test in my case it is a `POS-58` `USB`, and it worked without problems
![post](https://user-images.githubusercontent.com/3643158/73520651-78646b80-43da-11ea-9362-99285c7ae3b9.GIF)

the example you use to perform the test in `PHP` is found in 

> C:\xampp\htdocs\vendor\mike42\escpos-php\example\interface\windows-usb.php

this could change ..
and make the following modification to my code to reach the autoload.php since the directory is quite extensive and the routes changed

![code](https://user-images.githubusercontent.com/3643158/73521221-d2b1fc00-43db-11ea-9e23-7f0451f5102c.GIF)

Route used:

> require __DIR__ . '/../../../../autoload.php';

shared printer name:

> $connector = new WindowsPrintConnector("POS-58-Series");

run in:

> http://localhost/vendor/mike42/escpos-php/example/interface/windows-usb.php

and enjoy printing everything without problems

If anyone has any recommendations for me I will thank them for completing my grateful project in advance

**Comment by mike42** [comment]
Thank you for posting this, I'm sure it will help a lot of future users.

We added `php-intl` as a dependency in `escpos-php` 3.0. It replaces `php-mbstring`, which was required for earlier versions.

We use it to convert UTF-8 text to various legacy code pages, so that users can access the non-ASCII characters on their printers.

**Comment by InternetFacilito** [comment]
Gracias, me sirvió para poder utilizar la versión mas reciente de esta librería ya que cuando la instalé, no tenía habilitada la extensión initl en php.ini, por esa razón se instaló la versión 2.2 de la librería en un principio.
Yo sabia que la versión mas reciente hoy, es la 4.0, así que me di a la tarea de investigar porqué no se me había instalado la versión actual... y llegue aquí 🙂
Solo con habilitar initl en php.ini y reinstalar la librería de mike42 ya se actualizó a la versión mas reciente.

**Comment by fayzasalman** [comment]
I want to implement printing using pos in my laravel project by using this package
composer require rawilk/laravel-printing

I was facing those errors and your post saved me
```
Problem 1
    - rawilk/laravel-printing[v3.0.2, ..., v3.0.4] require mike42/escpos-php ^4.0 -> satisfiable by mike42/escpos-php[v4.0].
    - rawilk/laravel-printing[v3.0.0, ..., v3.0.1] require illuminate/support ^8.0|^9.0 -> found illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - mike42/escpos-php v4.0 requires ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
    - Root composer.json requires rawilk/laravel-printing ^3.0 -> satisfiable by rawilk/laravel-printing[v3.0.0, ..., v3.0.4].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp8.2.12\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-intl` to temporarily ignore these required extensions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require rawilk/laravel-printing:*" to figure out if any version is installable, or "composer require rawilk/laravel-printing:^2.1" if you know which you need.
```

thank you :)
