### ISSUE TITLE
Connect using ip with smb windows

### ISSUE THREAD

**Issue by acespedes** [mike42/escpos-php#87]
Hello Mike

I'm having an error when connecting to a printer on LAN passing authentication parameters.

`$connector = new WindowsPrintConnector("smb://Esmeralda:wilsonman@ESMERALDA-PC/workgroup/zebralenovo");`

When I execute this on the server as well on the console the error generated says:
"Multiple connections for a server or shared resource supported by the same user, more than using username UN, are not allowed . Disconnect all previous connections to the server or shared resources and try again ."

But, when I do this on console, it works great:
`net use "\\192.168.0.21\zebralenovo" "/user:workgroup\Esmeralda" "wilsonman"`

But on the server, it just doesn't work :/, with error:
"Fatal error: Uncaught exception 'BadMethodCallException' with message 'Printer 'smb://Esmeralda:wilsonman@192.168.0.21/workgroup/zebralenovo' is not a valid printer name. Use local port (LPT1, COM1, etc) or smb://computer/printer notation."

So, how can I use the IP for connecting, or, what else can I do?

Environment: IIS 10 over Windows 10
PHP version: 5.6.16

Thanks Mike

**Comment by barayuda** [comment]
Hai @acespedes , I have same error like this before.
From #35 , have you try to connect with this _smb://pc-name/printer_name_ ?
I have try this in Windows 8.1 and PHP 5.6, and worked

**Comment by acespedes** [comment]
Hi @barayuda , thanks for your reply.

The curious thing is that, I can connect with the printer in both ways with authentication and with no authentication, but this has been possible just on the console, but in PHP running in IIS, it throws errors.

Thanks

**Comment by barayuda** [comment]
Hi @acespedes 
Hmm thats problem on your windows, that access Administrator needed.
Maybe running your server need "run as adminstrator"
Have you checked your firewall? on windows or antivirus maybe?

**Comment by acespedes** [comment]
Hello @barayuda, you are right, that was the problem, thanks a lot.

For the record, I have change the following on the IIS Manager
`Sites > [Your Website]`
In "Features" view under the IIS subsection
`Authentication [Open Feature] > Anonymous Authentication [right-mouse "Edit..."] > Select: Application Pool Identity [OK]`

Regards.

**Comment by barayuda** [comment]
Glad to hear @acespedes :)
happy code

**Comment by mike42** [comment]
Hey, marking this as a bug because the regex is too strict to pick up IP addresses. Well spotted.

As in #35, the field is used to construct and write to a file path, so the validation is to save system admins from mischief and mistakes.

**Comment by barayuda** [comment]
Thanks @mike42 , hope fixed in next update :)
