### ISSUE TITLE
Improve strict type checking

### ISSUE THREAD

**Issue by mike42** [mike42/escpos-php#879]
As PHP improves optional typing, we've been making use of it in this project, since it avoids the need to validate things extensively across the entire API surface.

Strict typing is being introduced here as well, which prevents type coercion, which can act in surprising ways.

```php
declare(strict_types=1);
```

The following classes do not have this feature enabled, since it turns out we depend on type coercion for some reason, and unit tests crash when we attempt to prevent it.

- CodePage
- ImagickEscposImage
- NetworkPrintConnector
- Printer

To close this issue, fix the underlying problem, and declare strict types in these four classes.

**Comment by thicolares** [comment]
Hi @mike42, please comment know if you have any question. Thanks!
