### ISSUE TITLE
Can't Redirect

### ISSUE THREAD

**Issue by jolebo** [mike42/escpos-php#894]
Why the script after  "$printer-> close (); " Can't run?
i can't redirect my page

**Comment by goentursumkid** [comment]
yes I also found the problem

**Comment by mike42** [comment]
@jolebo @goentursumkid - This is not expected. Can you include a bit more detail about your platform, PHP version, and include a minimal example which I can use to replicate the issue?

It's also worth checking your PHP error log for warnings.

**Comment by jolebo** [comment]
problem solved

**Comment by rifqiramdhani** [comment]
@jolebo how to solved this? i hv same problem

**Comment by jolebo** [comment]
> @jolebo how to solved this? i hv same problem 

I removed the redirect
