### ISSUE TITLE
Xprinter XP-237B Cant print

### ISSUE THREAD

**Issue by wulean** [mike42/escpos-php#899]
Hi, I am using Xprinter XP-237B with your code but I am not able to print. could you please guide me?

**Comment by Muraveiko** [comment]
XP-237B isn't receipt printer. it is label printer. Are you sure the printer supports the ESC / POS instruction set?

**Comment by wulean** [comment]
> XP-237B isn't receipt printer. it is label printer. Are you sure the printer supports the ESC / POS instruction set?

Sorry. It’s my mistake,thanks your reply.

**Comment by mike42** [comment]
The first hit on Google for "Xprinter XP-237B command set" suggests that this printer claims to be a receipt and label printer, and to have some kind of ESC/POS support.

From the vendor-

> Q:What are your product command?

> A:Thermal printer compatible with ESC\POS.
> Label printer compatible with TSPL\ EPL\ DPL\ ZPL emulation.

With this in mind, you might be able to configure to use ESC/POS (check with the vendor for how to do this).

Nobody has attempted to use this printer with `escpos-php`, so you will need to check that ESC/POS support is really there. A good test would be to send the text "Hello World" on the command-line, including a simple ESC/POS formatting command.

On Linux this would be:

```
echo -en '\x1b@\x1b\x45\x00Hello \x1b\x45\x00World\x0a' > /dev/usb/lp0
```

Which writes: "Hello **World**".  If this doesn't work, then this library will not be useful to you at all.

Once you've confirmed that you do have an ESC/POS device, it's best to [use the 'simple' CapabilityProfile](https://github.com/mike42/escpos-php/blob/32d6c83dee6bf37c8881978ce9d4d56238a130c1/README.md#using-a-capabilityprofile). We do not have any more specific profile for this printer, so you still won't be able to use more complex features (eg. non-ASCII text), but it's a start.
