### ISSUE TITLE
zebra ZT230

### ISSUE THREAD

**Issue by sanal2net** [mike42/escpos-php#905]
Is this library support zebra ZT230 printer?
If not Please take this printer into account.

Thank you very much for your contributions.

**Comment by mike42** [comment]
Hi @sanal2net,

This library works with printers which understand the ESC/POS command set. Zebra printers use ZPL, which is not covered by this library at all, so we cannot communicate directly with them.

If you want to take a safer approach, then I would suggest finding some ZPL software instead.

However, ESC/POS software can speak to Zebra printers via a translation layer (called a 'Zebra Virtual Device'). I don't know of anybody who has attempted to connect `escpos-php` to a Zebra printer like this, but it would be an interesting thing to try.

**Comment by Asarudheenasr** [comment]
suggest a php framework independent library that can support  ZPL or working with zebra printer . 
also what would be the best option for barcode printing using php .
is there any library that capable of printing barcodes independent of what type type of barcode printer is.
