### ISSUE TITLE
source code for printer 

### ISSUE THREAD

**Issue by sanjiveG** [mike42/escpos-php#913]
i want to use this code with Birch BP-T3 thermal 80mm printer 
 can u share code for this specific printer

**Comment by mike42** [comment]
Based on a quick [search of the issue tracker](https://github.com/mike42/escpos-php/issues?q=BP-T3), nobody has tested whether the BP-T3 is compatible with `escpos-php`, so you may be the first person to use it.

The `README` suggests using `CapabilityProfile::load('simple')` in this case:

> When trying out a new brand of printer, it's a good idea to use the "simple" CapabilityProfile, which instructs the driver to avoid the use of advanced features (generally simpler image handling, ASCII-only text).

It looks like you have another issue open about your library setup (#914), so I'll close this off.
