### ISSUE TITLE
Advice plz label printer (ethernet)

### ISSUE THREAD

**Issue by Kelolot** [mike42/escpos-php#918]
Hi! Advice please  esc/pos ethernet label printer.

**Comment by mike42** [comment]
If you're looking for a printer in general, then please contact a local printer dealer!

If you are looking for a printer to use with this library, then Epson-branded printers advertising ESC/POS support are the way to go. I don't have one myself, but the Epson TM-L90 apparently works with a small code change #284 

The obvious [disclaimer](https://github.com/mike42/escpos-php/blob/development/LICENSE.md) is that this software is developed entirely by volunteers who are solving their own printing problems, and there is no guarantee at all that it will work for you.
