### ISSUE TITLE
Fiscal Model Integration

### ISSUE THREAD

**Issue by Mendim** [mike42/escpos-php#919]
Hello.i need help to add this model 
SYNERGY PF550
Here u can download all drivers
Control Codes
https://www.accent.mk/downloads/Control_codes_PF550_v136_EN.doc
https://www.accent.mk/downloads/PrimeriZa_IN_Datoteka_PF550.rar

https://www.accent.mk/?page_id=1282
Can you help me on this

**Comment by mike42** [comment]
I did a web search for "SYNERGY PF550 ESC/POS", and it doesn't look like this printer advertises ESC/POS support.

This library only prints to ESC/POS-compatible thermal and impact printers, so it won't be much use to you.
