### ISSUE TITLE
Can this be used with a dot matrix printer?

### ISSUE THREAD

**Issue by albertbeck** [mike42/escpos-php#92]
Hi Mike,

I need to print to a dot matrix printer from a web app.  Can you solution be used?

Thank you

**Comment by mike42** [comment]
Hi,

I can't say anything specific without knowing which model printer, OS (Windows, Mac, Linux) and interface (USB, Parallel, etc) you are working with, but you should mainly just check that it supports the ESC/POS protocol.

This driver can be used with any ESC/POS compatible printer: either impact receipt printers or thermal receipt printers. ESC/POS 'Page mode' is not supported at this stage.

Eg, among the [printers known to work](https://github.com/mike42/escpos-php#printers), you will find the Epson TM-U220, which is a dot matrix (impact) two-colour receipt printer.
