### ISSUE TITLE
Is it possible to print from safaris on iPhone browser?

### ISSUE THREAD

**Issue by wilson382** [mike42/escpos-php#921]
Hello, I have a php website using rawbt android app I'm able to print to bluetooth printer.

But this app is not available for iPhone. Is it possible to somehow print to bluetooth printer connected to iPhone?

**Comment by mike42** [comment]
This project really only deals with things which PHP can see. It's not directly possible for a PHP server to access anything on a phone, so you will need to find/develop something outside of this project. This applies equally to Android and iOS.

My standard suggestion is to include a Raspberry Pi in the design somewhere if you need more options to work with.

If you are committed to printing directly from the phone instead, then you will need to find and integrate a substitute app, write your own, or convince the `rawbt` team to make an iOS port. If you need to develop your own transport, then as far as this project goes, you will want to look at the `PrintConnector` interface, which is implemented for each type of transport.

Hopefully obvious disclaimer: This project has no affiliation with `rawbt`, which I understand to be a commercial product. I'm glad to have such products in the ecosystem, but I don't personally use or offer support for it.

Best of luck, sorry we don't have a more straightforward answer!

**Comment by wilson382** [comment]
Thank you so much for the detailed answer.
