### ISSUE TITLE
I cant redirect my page after $print->close()

### ISSUE THREAD

**Issue by rifqiramdhani** [mike42/escpos-php#927]
this my code

https://carbon.now.sh/2zWbweQi4CGfQXTFME9b

**Comment by thullyrico** [comment]
> 
> 
> this my code
> 
> https://carbon.now.sh/2zWbweQi4CGfQXTFME9b

I have archived that by setting redirect status using variable and separate print file and include it when i need to print, for example

<?php
/* Change to the correct path if you copy this example! */
require 'autoloader.php';
use Escpos\Printer;
use Escpos\PrintConnectors\WindowsPrintConnector;

/**
 * Install the printer using USB printing support, and the "Generic / Text Only" driver,
 * then share it (you can use a firewall so that it can only be seen locally).
 *
 * Use a WindowsPrintConnector with the share name to print.
 *
 * Troubleshooting: Fire up a command prompt, and ensure that (if your printer is shared as
 * "Receipt Printer), the following commands work:
 *
 *  echo "Hello World" > testfile
 *  copy testfile "\\%COMPUTERNAME%\Receipt Printer"
 *  del testfile
 */

//echo $contents;
$print_status = "none";
try {
    // Enter the share name for your USB printer here
    //$connector = null;
    $connector = new WindowsPrintConnector($business_printer);

    /* Print a "Hello world" receipt" */
    $printer = new Printer($connector);
    
    $printer -> text("------------------------------------------------\n");
    $printer -> text($busines_name."\n");
    $printer -> text("Address Line one\n");
	$printer -> text("Address Line two\n");
	$printer -> text("Phone +266 ".$business_phone_1."/". $business_phone_2." \n");
	$printer -> text("------------------------------------------------\n");
	$printer -> text("Clerk: ".$user_name." ".$user_surname."\n");
	$printer -> text("Date:  ".$item_sales_date." ".date("h:s:m")."   Slip No:".$item_slip_number."\n\n");
	
	$printer -> text("------------------------------------------------\n");
	$printer -> text( "|".str_pad("ITEM NAME",19, " ")."  |  ".str_pad("PRICE",10," ")." |".str_pad("SUB-TOTAL",10," ",STR_PAD_LEFT)."|\n");
	$printer -> text("------------------------------------------------\n");

	//selecting things to be printed
	if($db === false){

		die("ERROR: Could not connect. " . mysqli_connect_error());

	}
	$today_date_is = date('Y-m-d',strtotime('+0 days'));

	$sql = "select * from shopping_cart where sales_date = '$today_date_is' and ckerck_reference = '$user_user_count'";
	
	$i = 0;
	$total_items_price = 0;

	if($result = mysqli_query($db, $sql)){

		if(mysqli_num_rows($result) > 0){
		
			while($row = mysqli_fetch_array($result)){
				 
				$shopping_card_item_name = $row['item_name'];
				$shopping_card_item_qty = $row['item_qty'];
				$shopping_card_item_price = $row['item_price'];
				$shopping_card_shopping_count = $row['shopping_count'];
				$shopping_item_barcode = $row['item_barcode'];
				
				$total_items_price = $total_items_price + $shopping_card_item_qty * $shopping_card_item_price;
				
				$i = 1 + $i;
				
				//$printer -> text( str_pad($shopping_card_item_name,20, " ")." x".str_pad($shopping_card_item_qty,3," ")." M".str_pad(number_format($shopping_card_item_price,2),7," ",STR_PAD_LEFT)." M".str_pad(number_format($shopping_card_item_price * $shopping_card_item_qty,2),8," ",STR_PAD_LEFT)."\n");
				$printer -> text( str_pad($shopping_card_item_name,30, " ")."\n");
				$printer -> text(" x".str_pad($shopping_card_item_qty,22," ")." M".str_pad(number_format($shopping_card_item_price,2),10," ",STR_PAD_LEFT)." M".str_pad(number_format($shopping_card_item_price * $shopping_card_item_qty,2),10," ",STR_PAD_LEFT)."\n");
				
			}
		}
	}
	$printer -> text("\n\n");
	$printer -> text("Total Cost                           M".str_pad(number_format($total_items_price,2),10," ",STR_PAD_LEFT)."\n");
	$printer -> text("Cash                                 M".str_pad(number_format($_POST['enter_cash'],2),10," ",STR_PAD_LEFT)."\n");
	$printer -> text("Change                               M".str_pad(number_format($_POST['enter_cash'] - $total_items_price,2),10," ",STR_PAD_LEFT)."\n");
	$printer -> text("Tax (15%)                            M".str_pad(number_format($total_items_price * 0.15,2),10," ",STR_PAD_LEFT)."\n\n");
	$printer -> barcode($item_slip_number);
	$printer -> text("------------------------------------------------\n");
	$printer -> text("           ".$business_motto."          \n");
	$printer -> text("------------------------------------------------\n");
	
    $printer -> cut();
    $printer -> pulse();
    
    /* Close printer */
    $printer -> close();
   $print_status = "true";
} catch (Exception $e) {
    echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}

on the other page where you have included the file above just  immediately after that line write this
if($print_status == "true"){
  //directing page using php

 //directing page using javascript
?>
      <meta http-equiv="refresh" content="2; url='new-redirect.php'">
<?php
}

**Comment by thullyrico** [comment]
> I have archived that by setting redirect status using variable and separate print file and include it when i need to print, for example
testfile 

<?php
//echo $contents; 
$print_status = "none"; 
try { 
	// Enter the share name for your USB printer here 
	//$connector = null; $connector = new WindowsPrintConnector($business_printer); 
	/* Print a "Hello world" receipt" */ 
	$printer = new Printer($connector); 
	$printer -> text("------------------------------------------------\n"); 
	$printer -> text($busines_name."\n"); 
	$printer -> text("Address Line one\n"); 
	$printer -> text("Address Line two\n"); 
	$printer -> text("Phone +266 ".$business_phone_1."/". $business_phone_2." \n"); 
	$printer -> text("------------------------------------------------\n"); 
	$printer -> text("Clerk: ".$user_name." ".$user_surname."\n"); 
	$printer -> text("Date: ".$item_sales_date." ".date("h:s:m")." Slip No:".$item_slip_number."\n\n"); 
	$printer -> text("------------------------------------------------\n"); 
	$printer -> text( "|".str_pad("ITEM NAME",19, " ")." | ".str_pad("PRICE",10," ")." |".str_pad("SUB-TOTAL",10," ",STR_PAD_LEFT)."|\n"); 
	$printer -> text("------------------------------------------------\n"); 
	//selecting things to be printed 
	if($db === false){ 
		die("ERROR: Could not connect. " . mysqli_connect_error()); 
	} $today_date_is = date('Y-m-d',strtotime('+0 days')); 
	$sql = "select * from shopping_cart where sales_date = '$today_date_is' and ckerck_reference = '$user_user_count'"; 
	$i = 0; 
	$total_items_price = 0; 
	if($result = mysqli_query($db, $sql)){ 
		if(mysqli_num_rows($result) > 0){ 
			while($row = mysqli_fetch_array($result)){ 
				$shopping_card_item_name = $row['item_name']; 
				$shopping_card_item_qty = $row['item_qty']; 
				$shopping_card_item_price = $row['item_price']; 
				$shopping_card_shopping_count = $row['shopping_count']; 
				$shopping_item_barcode = $row['item_barcode']; 
				$total_items_price = $total_items_price + $shopping_card_item_qty * $shopping_card_item_price; 
				$i = 1 + $i; //$printer -> text( str_pad($shopping_card_item_name,20, " ")." x".str_pad($shopping_card_item_qty,3," ")." M".str_pad(number_format($shopping_card_item_price,2),7," ",STR_PAD_LEFT)." M".str_pad(number_format($shopping_card_item_price * $shopping_card_item_qty,2),8," ",STR_PAD_LEFT)."\n"); 
				$printer -> text( str_pad($shopping_card_item_name,30, " ")."\n"); 
				$printer -> text(" x".str_pad($shopping_card_item_qty,22," ")." M".str_pad(number_format($shopping_card_item_price,2),10," ",STR_PAD_LEFT)." M".str_pad(number_format($shopping_card_item_price * $shopping_card_item_qty,2),10," ",STR_PAD_LEFT)."\n"); 
			} 
		} 
	} 
	$printer -> text("\n\n"); 
	$printer -> text("Total Cost M".str_pad(number_format($total_items_price,2),10," ",STR_PAD_LEFT)."\n"); 
	$printer -> text("Cash M".str_pad(number_format($_POST['enter_cash'],2),10," ",STR_PAD_LEFT)."\n"); 
	$printer -> text("Change M".str_pad(number_format($_POST['enter_cash'] - $total_items_price,2),10," ",STR_PAD_LEFT)."\n"); 
	$printer -> text("Tax (15%) M".str_pad(number_format($total_items_price * 0.15,2),10," ",STR_PAD_LEFT)."\n\n"); $printer -> barcode($item_slip_number); 
	$printer -> text("------------------------------------------------\n"); 
	$printer -> text(" ".$business_motto." \n"); 
	$printer -> text("------------------------------------------------\n"); 
	$printer -> cut(); 
	$printer -> pulse(); 
	/* Close printer */ 
	$printer -> close(); 
	$print_status = "true"; 
	
	} catch (Exception $e) { 
		echo "Couldn't print to this printer: " . $e -> getMessage() . "\n"; 
	} 
	?>
	on the other page where you have included the file above just immediately after that line write this 
	
	<?php
		if($print_status == "true"){ 
			//directing page using php 
			
			//directing page using javascript 
			?>
	  			<meta http-equiv="refresh" content="2; url='new-redirect.php'">
	  		<?php
  		}  		
  	?>

**Comment by drycrushader** [comment]
Just in case someone visit this issue and still can't find how to fix that issue.
In my case, I use "**WindowsPrintConnector**", so I find this line and change the code a bit.
This should works for other **Print Connector**.
```
public function finalize()
{
        $data = implode($this -> buffer);
        $this -> buffer = null;
            $this -> finalizeWin($data);
            die;
```

Just comment that "die;" script. So it will look like:
```
public function finalize()
{
        $data = implode($this -> buffer);
        $this -> buffer = null;
            $this -> finalizeWin($data);
            // die;
```

After that you can redirect after doing `$printer -> close();`

**Comment by mike42** [comment]
Closing this off. Happy to take bug reports if there are steps to reproduce, but I'm not going to debug your code.

@drycrushader - There is no `die;` in our `WindowsPrintConnector` ([link](https://github.com/mike42/escpos-php/blob/f414320fc510afcacd4cbb75902f827399dee429/src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php#L176)). I'm not sure where you are getting your code from, but appears to be different to what I ship from this repo. please file a fresh issue if you're able to replicate this problem using the latest `escpos-php`, installed via `composer`.
