### ISSUE TITLE
Using release 1.0 without composer

### ISSUE THREAD

**Issue by zone11** [mike42/escpos-php#93]
I'm trying to get escpos-php release 1.0 running without the need of composer. 
Following issue #21 this should work including Escpos.php. With this version I replaced this with Printer.php as there is no such file. No luck so far.

I created a simple test.php and copied your sources to the same folder.
```
require_once("Mike42/Escpos/Printer.php");

$printer = new Printer();
```

All I get is this typical missing class error:
`Fatal error: Class 'Printer' not found in /Users/christian/Desktop/pos/demo_my.php on line 13
`
Playing around with namespaces like `use Mike42\Escpos\Printer` helps for Printer class but opens new troubles with PrinterConnector.

Thanks,
Chris

**Comment by mike42** [comment]
To save others from the same trouble, I've packaged in an autoloader and updated the docs. The driver now uses namespaces and auto-loading (#36), which makes it play nicer for dependency managers (composer, symphony).

To use it without composer now, first grab a fresh copy of the master branch:

````
$ git clone https://github.com/mike42/escpos-php vendor/mike42/escpos-php
````

Include the `autoload.php` file and `use` any classes (to save `\Absolute\Class\Names` further down in the code), like so:

````php
<?php
require_once('vendor/mike42/escpos-php/autoload.php');

use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\Printer;

$connector = new FilePrintConnector("/dev/usb/lp0");
$printer = new Printer($connector);
try {
	$printer -> text("Hello world!\n");
	$printer -> cut();
} finally {
	$printer -> close();
}
````

**Comment by zone11** [comment]
Thank you, works perfect now!
