### ISSUE TITLE
Printing Japanese Characters

### ISSUE THREAD

**Issue by amibappy** [mike42/escpos-php#935]
Need Help!

I need to print Japanese texts (kanji, Hiragana, Katakana) on my receipt. I have spent many hours finding a good solution but got nothing. I don't want to print from a file/image. I need to print data from the database. And I will use a network printer.

Here is a code snippet that I tried last.

`
require __DIR__ . '/../../vendor/autoload.php';
use Mike42\Escpos\PrintConnectors\NetworkPrintConnector;
use Mike42\Escpos\Printer;
use Mike42\Escpos\Experimental\Unifont\UnifontPrintBuffer;
try {

	$connector = new NetworkPrintConnector("192.168.1.5", 9100);
	$printer = new Printer($connector);
	
	// Use Unifont to render text
	$unifontBuffer = new UnifontPrintBuffer("unifont-13.0.02.hex");
	$printer -> setPrintBuffer($unifontBuffer);

	// Most simple example
	$printer->text("助けが必要です");
	
	$printer->feed(2);
	$printer->cut();
	$printer->close();
	
    $printer -> cut();
    $printer -> close();
} finally {
    $printer -> close();
}

`

This PHP script and the "unifont-13.0.02.hex" file are in the same folder.

I'm using the MUNBYN ITPP047 printer. The printer supports Japanese texts.
I'm using Windows 10. I have no problem printing English texts. 

Can someone give me a simple solution? 
I was trying to solve by my own but now I badly need some help. 

Thanks in advance.

**Comment by amibappy** [comment]
I have solved this problem by using "wkhtmltoimage". 
Thanks, @mike42 for making such a wonderful library.

**Comment by rapcrown** [comment]
> I have solved this problem by using "wkhtmltoimage".
> Thanks, @mike42 for making such a wonderful library.

Please cod document wkhtmltoimage :)
