### ISSUE TITLE
Star TSP100iii futurePrint - can't print any

### ISSUE THREAD

**Issue by nchankov** [mike42/escpos-php#944]
I have an wifi connected printer Star TSP100iii futurePrint. It prints via their phone app, I can print from the computer if I install it as a network printer. So hardware for me is not a problem.

The problem is when I try to print via terminal or that class.

First when I try to connect via `nc` command like:
`nc 192.168.0.31 9100` it just return a strange symbol like:
#�
and that's it. Then I tried to pipe the test script which was tested with another printer and it's working as:
`php test.php | nc 192.168.0.31 9100` but then i see again that strange symbol

Finally when I try to print using the NetworkPrintConnector() nothing happens (as I think it's related to the above), even though if I print the $connector I see a Resource #123 so for sure it's connected.

I've tried to set a CapabilityProfile::load("SP2000"); and tried with various profiles but nothing changed. The script didn't throw exception as I am catching all of them, so I really out of ideas how to make this printer work.

Here is the printout of the settings. I think there is something to do with those bits at the top, but to change it one by one will eat a lot of paper and I don't have it as I have just one roll which came with the printer.

![IMG_20200714_124042](https://user-images.githubusercontent.com/187725/87422289-46357780-c5d0-11ea-85b4-d2af84c3649f.jpg)

BTW: I've seen some comments saying their printer is ESC/POS enabled, but as I have only Linux, I can't do it.

So any idea how to make this baby print via terminal? :)

**Comment by derayke** [comment]
Can you show your test.php? What the charset you are using?

**Comment by nchankov** [comment]
Unfortunately I returned the printer. And now I don't have it. Strangely enough there were same printers (as model) which print without problem. So I would suggest that either my printer was broken, or the configuration was not correct, but it was opened by me and I haven't changed initially much.

Anyway I can't reproduce and can't give much info, so for now this ticket should be closed.
