### ISSUE TITLE
Is the plugin can use for Epson LQ 310

### ISSUE THREAD

**Issue by Yassa123** [mike42/escpos-php#952]
I need to print a invoice directly to printer ( Without browser print preview ). Is there a possibility to use this plugin for my requirement ? Is the plugin can use for Epson LQ 310 ?

**Comment by mike42** [comment]
No, the Epson LQ-310 is not compatible with this library. It expects ESC/P2 commands, while this library generates ESC/POS. Printers which support ESC/POS tend to be retail receipt printers.
