### ISSUE TITLE
Printing from aws to network printer

### ISSUE THREAD

**Issue by homemix** [mike42/escpos-php#962]
Hello guys am getting this error when printing from aws hosted php system `**Cannot initialise NetworkPrintConnector: Connection refused.**` somebody help. From local machine it's working problem is from aws.

**Comment by vcandela** [comment]
hello, could you solve it

**Comment by homemix** [comment]
Not yet, am still finding a working solution.

**Comment by homemix** [comment]
I found a work round. Host the printing code locally and then fetch my live data using curl and then print to my local or network connected printer.

**Comment by doublevie** [comment]
Did you set the port forwarding (9100) in your local network router

**Comment by homemix** [comment]
Only data am fetching from server (Json format) and the rest of printing code is as defined in the library. If your printer is on network set port to 9100. Example data:  `foreach ($customer_name as $customer):
				$printer->text("Customer:" . $customer['customer_name'] . " \n");
			endforeach;` and so on.

**Comment by Mate20x** [comment]
@homemix 
> I found a work round. Host the printing code locally and then fetch my live data using curl and then print to my local or network connected printer.

I also use this method
feasible
