### ISSUE TITLE
Develop an application to print from the cloud

### ISSUE THREAD

**Issue by javierybar** [mike42/escpos-php#966]
I am a developer and collaborator of the [TakePOS ](http://www.takepos.com)point of sale. One of the printing methods of this software is this mike42 script for printing. I think it would be very interesting to develop a connector for this great mike42 script. With TakePOS we use the [TakePOS connector](http://en.takepos.com/connector/) and I think we could start from the open code of TakePOS connector. I personally can help a lot. I request volunteers to develop, test, invest.

**Comment by mike42** [comment]
I'm not entirely sure what you have in mind, but I'm happy to review any changes to `escpos-php` that are filed as pull requests.

The scope of this library is to allow the user to programmatically generate binary print data and send it along. We have a simple system of print connectors to [get data to printers via common methods](https://github.com/mike42/escpos-php/tree/33864eea993542b5db7191f16a88cdd0a8aeb1a5/src/Mike42/Escpos/PrintConnectors), or we allow the caller to retrieve the print data if they have something more advanced in mind.

PS: My understanding is that TakePOS is part of Dolibarr. They are still using [escpos-php 2.2](https://github.com/Dolibarr/dolibarr/blob/ae4020c9fe35df6d7353a0ea657bef1a8d34ff2d/composer.json#L30), which was the last version to support PHP 5.6. If you can convince them to add PHP7 as a minimum version, then they can benefit from [several improvements](https://github.com/mike42/escpos-php/releases) that I was unable to publish while we still supported older PHP versions.
