### ISSUE TITLE
Color Label Printers

### ISSUE THREAD

**Issue by AttaF1** [mike42/escpos-php#969]
Is there any way we can connect Epson's Color label printer with same code/libraries and print from web

**Comment by mike42** [comment]
Most likely not. This library targets ESC/POS printers, which are typically found in point-of-sale environments. I do not know of any Epson color printers which understand ESC/POS. They instead use languages like ESC/Label, ESC/P, and ESC/P2, all of which sound similar but are not compatible.

I think that the TM-L90 LFC or TM-P60II Label might be more ESC/POS-like, but this is yet to be verified.
