### ISSUE TITLE
EscposImage dithering

### ISSUE THREAD

**Issue by SteampunkProfessor** [mike42/escpos-php#97]
You can add the Citizen CBM1000-II to your list.
Any chance of adding an Atkinson dither to EscposImage.php?
Thans for your worrk, it's fun trying it out.

**Comment by mike42** [comment]
I'll leave this open as a feature request.

Could be done with a few loops-
- https://gist.github.com/lordastley/1342627

Or could use dithering algo's built in to GD & Imagick-

- http://php.net/manual/en/function.imagetruecolortopalette.php
- http://php.net/manual/en/imagick.constants.php
- http://php.net/manual/en/imagick.posterizeimage.php

**Comment by mike42** [comment]
As part of the image handling re-write, the raster data is all generated in ImageMagick in a single call, which dithers as a side-effect-

```php
$im -> setformat('pbm');
$im -> getimageblob();
```

The linked commit contains a challenging public domain [sample image](https://raw.githubusercontent.com/mike42/escpos-php/7029b7bdc5b79dbfc81c2364720187b671e53be7/example/resources/tulips.png), and a [code snippet](https://github.com/mike42/escpos-php/blob/7029b7bdc5b79dbfc81c2364720187b671e53be7/example/specific/97-dithering.php) showing how to fall back on the old, slow implementation which performed a threshold.

The output is-

![2015-04-dither-example](https://cloud.githubusercontent.com/assets/2080552/14765752/4eb49fe2-0a33-11e6-8adf-9b0b7529cb6d.png)

I'll note that the image quality is still not as good as I would like, but this is simply what Imagick gets us. Any pure PHP image manipulation will be very slow, so you should either pre-process your images or use an alternative utility to render them if you have an image-intensive workflow.

Specifically, if you are printing a lot of images, you should also check out-
- The port of these routines that I recently submitted to [python-escpos](https://github.com/python-escpos/python-escpos) produces better quality output than the example above (by using PIL in place of Imagick)
- [png2pos](https://github.com/petrkutalek/png2pos) is a compiled utility which works exclusively with images.

**Comment by SteampunkProfessor** [comment]
Thanks for the update!
