### ISSUE TITLE
iconv() Error

### ISSUE THREAD

**Issue by designcise** [mike42/escpos-php#99]
I've tried just about everything, but I keep getting this error: 

```
iconv(): Detected an illegal character in input string in ..\lib\escpos-php-master\src\Mike42\Escpos\PrintBuffers\EscposPrintBuffer.php on line: 225
```

Any idea how to fix this? Anyone else had the same problem? The code I'm running is:

```
require LIB_DIR . 'escpos-php-master/vendor/autoload.php';

use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

try {
	// tried both these ways:
	$connector = new WindowsPrintConnector("smb://IM-A-PC/BIXOLON");
	//$connector = new WindowsPrintConnector("BIXOLON");

	$printer = new Printer($connector);
	$printer->text("a\n");
	$printer->cut();
	
	$printer->close();
} catch(Exception $e) {
	echo "Couldn't print to this printer: " . $e -> getMessage() . "\n";
}
```

I'm using XAMPP on Windows 7; the printer is shared as "BIXOLON". It is printing fine via cmd.exe and using other software.

**Comment by mike42** [comment]
Labeling as a bug. #36 removed the encoding table cache from git, so escpos-php is attempting to generate tables, and has hit a compatibility problem. The encoding tables should really be cached in pure PHP, removing `iconv()` as a run-time dependency

**Possible workaround:** Use `textRaw()`. You can't print in Spanish or anything, but the error may go away.

**Other possible workaround:** Try hopping to the `SimpleCapabilityProfile`, which restricts you to `CP437` only and may also avoid the incompatible code.

Quoting the README-
````php
use Mike42\Escpos\CapabilityProfiles\SimpleCapabilityProfile;
$connector = new WindowsPrintConnector("smb://computer/printer");
$printer = new Printer($connector, $profile);
````

**Comment by designcise** [comment]
Hi Mike, I appreciate the quick response! I'm not very well-versed in your script, therefore, I would like to bother you once more. Two things I would like to ask:

1. You suggested to use ```textRaw()``` but I'm unsure how to make use of it; I tried doing:

```
$utf8 = $this -> writeTextRaw($characterMap);
// instead of @iconv($characterMap, self::INPUT_ENCODING, chr($char));
```

this gives the following error:

```
file_put_contents(...\lib\escpos-php-master\src\Mike42\Escpos\PrintBuffers/cache/Characters-Mike42-Escpos-CapabilityProfiles-DefaultCapabilityProfile.ser.gz): failed to open stream
```

2. You suggested using ```SimpleCapabilityProfile```, quoting from the readme, you wrote ```$printer = new Printer($connector, $profile);```; in that I'm not quite sure what value to give ```$printer```, tried with ```$profile = SimpleCapabilityProfile::getInstance();;``` but that gives the same error as above, i.e.:

```
file_put_contents(...\lib\escpos-php-master\src\Mike42\Escpos\PrintBuffers/cache/Characters-Mike42-Escpos-CapabilityProfiles-DefaultCapabilityProfile.ser.gz): failed to open stream: No such file or directory
```

**Comment by designcise** [comment]
Nevermind, fixed it. Can't believe I missed it, just had to create "cache" folder inside "...\lib\escpos-php-master\src\Mike42\Escpos\PrintBuffers"

I hope the iconv stuff is fixed in the next version of the script. The script is very useful, thanks!

Thanks for the help!
