### ISSUE TITLE
copy(ELGIN i9): failed to open stream: No such file or direct WindowsPrintConnector.php on line 375  Failed to copy file to printer 

### ISSUE THREAD

**Issue by GuilhermeDischer** [mike42/escpos-php#994]
I am having this problem. Here is my code

`<?php 
	require __DIR__ . '/vendor/autoload.php';

	use Mike42\Escpos\Printer;
	use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;

	try {
		$connector = new WindowsPrintConnector("ELGIN i9");

		$printer = new Printer($connector);
		$printer -> text("Hello World!\n");
		$printer -> text("Test!\n");
    	$printer -> cut();

    	$printer -> close();
	} catch (Exception $e) {
    	echo "Não foi possivel imprimir: " . $e -> getMessage() . "\n";
	}
 ?>
`

**Comment by GuilhermeDischer** [comment]
Resolved

**Comment by romiardisaja** [comment]
How to solve that problem?
thx

**Comment by GuilhermeDischer** [comment]
Hello, Changing the printer driver to Generic / Text Only
________________________________
De: Romi Ardiansya ***@***.***>
Enviado: terça-feira, 23 de março de 2021 15:40
Para: mike42/escpos-php ***@***.***>
Cc: GuilhermeDischer ***@***.***>; State change ***@***.***>
Assunto: Re: [mike42/escpos-php] copy(ELGIN i9): failed to open stream: No such file or direct WindowsPrintConnector.php on line 375 Failed to copy file to printer (#994)


How to solve that problem?
thx

**Comment by Bkoech** [comment]
How did you change the printer driver to printer driver to Generic

**Comment by GuilhermeDischer** [comment]
Printer Properties -> Advanced -> New Driver
